Repository GoogleChrome/lighthouse, pull requests merged in 2018-02, with the labels that each got.

#4518 core(gather-runner): [revert] load a blank data URI, rather than about:blank
  lighthouse-core/gather/blank-page.html
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/gather/logo-page.html
  lighthouse-core/test/gather/fake-driver.js
  lighthouse-core/test/gather/gather-runner-test.js
Labels: rls-blocker, waiting4reviewer

#4523 docs(headless-chrome.md): fix broken link
  docs/headless-chrome.md
Labels: waiting4reviewer

#4394 core(config): add support for audit/gatherer options
  lighthouse-core/config/config.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/runner.js
  lighthouse-core/test/config/config-test.js
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/runner-test.js
Labels: waiting4reviewer

#4475 core(main-resource): adjust main resource identification logic
  lighthouse-core/gather/computed/main-resource.js
  lighthouse-core/test/gather/computed/critical-request-chains-test.js
  lighthouse-core/test/gather/computed/main-resource-test.js
  lighthouse-core/test/gather/fake-driver.js
  lighthouse-core/test/runner-test.js
Labels: waiting4reviewer

#4550 core(font-size): recalibrate the legible font sizes
  lighthouse-cli/test/fixtures/seo/seo-tester.html
  lighthouse-core/audits/seo/font-size.js
  lighthouse-core/gather/gatherers/seo/font-size.js
  lighthouse-core/test/audits/seo/font-size-test.js
Labels: waiting4reviewer

#4592 extension: fix issue where gatherers cannot be found
  lighthouse-extension/gulpfile.js
Labels: waiting4reviewer

#4540 docs(programmatic): add caveat about removing artifacts
  docs/readme.md
Labels: waiting4reviewer

#4566 core(seo): link to "meta description" reference
  lighthouse-core/audits/seo/meta-description.js
Labels: seo, waiting4reviewer

#4278 report(category): enable all categories to show audit groups
  lighthouse-core/report/v2/renderer/category-renderer.js
  lighthouse-core/report/v2/renderer/performance-category-renderer.js
  lighthouse-core/report/v2/renderer/report-renderer.js
  lighthouse-core/report/v2/report-generator.js
  lighthouse-core/report/v2/report-template.html
  lighthouse-core/scripts/compile-against-devtools.sh
  lighthouse-core/test/report/v2/renderer/category-renderer-test.js
  lighthouse-core/test/report/v2/renderer/performance-category-renderer-test.js
  lighthouse-core/test/report/v2/renderer/report-renderer-test.js
  lighthouse-viewer/app/src/lighthouse-report-viewer.js
Labels: waiting4reviewer

#4537 report: add docs link to bootup-time audit
  lighthouse-core/audits/bootup-time.js
Labels: waiting4reviewer

#4552 core(lantern): improve RTT estimates
  lighthouse-core/audits/predictive-perf.js
  lighthouse-core/gather/computed/page-dependency-graph.js
  lighthouse-core/lib/dependency-graph/network-node.js
  lighthouse-core/lib/dependency-graph/simulator/connection-pool.js
  lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js
  lighthouse-core/lib/dependency-graph/simulator/simulator.js
  lighthouse-core/lib/dependency-graph/simulator/tcp-connection.js
  lighthouse-core/test/audits/predictive-perf-test.js
  lighthouse-core/test/lib/dependency-graph/simulator/network-analyzer-test.js
  lighthouse-core/test/lib/dependency-graph/simulator/simulator-test.js
Labels: waiting4committer

#4555 core(render-blocking): handle amp-style stylesheets
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
  lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
  lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js
Labels: waiting4reviewer

#4605 misc(typecheck): add dependency graph to tsc
  lighthouse-core/lib/dependency-graph/cpu-node.js
  lighthouse-core/lib/dependency-graph/network-node.js
  lighthouse-core/lib/dependency-graph/node.js
  lighthouse-core/lib/dependency-graph/simulator/connection-pool.js
  lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js
  lighthouse-core/lib/dependency-graph/simulator/simulator.js
  lighthouse-core/lib/dependency-graph/simulator/tcp-connection.js
  lighthouse-core/lib/errors.js
  tsconfig.json
  typings/externs.d.ts
Labels: waiting4reviewer
