Repository GoogleChrome/lighthouse, pull requests merged in 2018-04, with the labels that each got.

#4914 core(tsc): add type checking to remote protocol commands
  lighthouse-core/gather/connections/connection.js
  lighthouse-core/gather/connections/extension.js
  lighthouse-core/gather/driver.js
  lighthouse-core/lib/emulation.js
  lighthouse-core/lib/errors.js
  lighthouse-core/scripts/extract-crdp-mapping.js
  typings/crdp-mapping.d.ts
  typings/protocol.d.ts
Labels: waiting4reviewer

#4918 core(tsc): add types for DevtoolsLog and NetworkRecorder
  lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
  lighthouse-core/audits/byte-efficiency/unminified-css.js
  lighthouse-core/audits/byte-efficiency/unused-css-rules.js
  lighthouse-core/audits/byte-efficiency/unused-javascript.js
  lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
  lighthouse-core/audits/consistently-interactive.js
  lighthouse-core/gather/computed/critical-request-chains.js
  lighthouse-core/gather/computed/main-resource.js
  lighthouse-core/gather/computed/network-records.js
  lighthouse-core/gather/computed/network-throughput.js
  lighthouse-core/gather/computed/page-dependency-graph.js
  lighthouse-core/gather/computed/pushed-requests.js
  lighthouse-core/gather/devtools-log.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/gather/gatherers/scripts.js
  lighthouse-core/lib/dependency-graph/cpu-node.js
  lighthouse-core/lib/dependency-graph/network-node.js
  lighthouse-core/lib/dependency-graph/simulator/connection-pool.js
  lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js
  lighthouse-core/lib/dependency-graph/simulator/simulator.js
  lighthouse-core/lib/network-recorder.js
  typings/externs.d.ts
  typings/gatherer.d.ts
  typings/web-inspector.d.ts
Labels: waiting4reviewer

#4882 report(helptext): fix typos
  lighthouse-core/audits/accessibility/image-alt.js
  lighthouse-core/audits/byte-efficiency/unused-css-rules.js
  lighthouse-core/audits/dobetterweb/password-inputs-can-be-pasted-into.js
  lighthouse-core/audits/mainthread-work-breakdown.js
  lighthouse-core/audits/uses-rel-preload.js
  lighthouse-core/test/results/sample_v2.json
Labels: waiting4reviewer

#4920 core(noopener-audit): noreferrer implies noopener
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
  lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js
  lighthouse-core/gather/gatherers/dobetterweb/anchors-with-no-rel-noopener.js
Labels: waiting4reviewer

#4926 core(network-recorder): fix typo in once() call on super
  lighthouse-core/lib/network-recorder.js
Labels: waiting4reviewer

#4932 core(fast-config): bring back a11y and SEO categories
  lighthouse-core/config/fast-config.js
Labels: to merge:2.x, waiting4reviewer

#4910 core(lantern): cleanup Simulator construction
  lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
  lighthouse-core/config/constants.js
  lighthouse-core/gather/computed/load-simulator.js
  lighthouse-core/gather/computed/metrics/lantern-metric.js
  lighthouse-core/gather/computed/network-analysis.js
  lighthouse-core/gather/computed/network-throughput.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/lib/dependency-graph/simulator/simulator.js
  lighthouse-core/runner.js
  lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
  lighthouse-core/test/gather/computed/load-simulator-test.js
  lighthouse-core/test/lib/dependency-graph/simulator/simulator-test.js
  lighthouse-core/test/runner-test.js
  typings/audit.d.ts
Labels: waiting4reviewer

#4919 tests: use nyc for coverage, dropping deprecated istanbul
  .travis.yml
  lighthouse-core/scripts/run-mocha.sh
  package.json
  yarn.lock
Labels: waiting4reviewer

#4936 extension: Pass flags from options in runLighthouseForConnection
  lighthouse-extension/app/src/lighthouse-background.js
Labels: waiting4reviewer

#4927 core: add default audit options with scoring
  lighthouse-core/audits/audit.js
  lighthouse-core/audits/bootup-time.js
  lighthouse-core/audits/byte-efficiency/total-byte-weight.js
  lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
  lighthouse-core/audits/consistently-interactive.js
  lighthouse-core/audits/dobetterweb/dom-size.js
  lighthouse-core/audits/estimated-input-latency.js
  lighthouse-core/audits/first-interactive.js
  lighthouse-core/audits/first-meaningful-paint.js
  lighthouse-core/audits/mainthread-work-breakdown.js
  lighthouse-core/audits/speed-index-metric.js
  lighthouse-core/config/config.js
  lighthouse-core/runner.js
  lighthouse-core/test/audits/bootup-time-test.js
  lighthouse-core/test/audits/byte-efficiency/total-byte-weight-test.js
  lighthouse-core/test/audits/byte-efficiency/uses-long-cache-ttl-test.js
  lighthouse-core/test/audits/consistently-interactive-test.js
  lighthouse-core/test/audits/dobetterweb/dom-size-test.js
  lighthouse-core/test/audits/estimated-input-latency-test.js
  lighthouse-core/test/audits/first-meaningful-paint-test.js
  lighthouse-core/test/audits/mainthread-work-breakdown-test.js
  lighthouse-core/test/audits/speed-index-metric-test.js
  lighthouse-core/test/config/config-test.js
  typings/audit.d.ts
Labels: waiting4reviewer

#4912 cli(output): Add ability to export results to CSV
  lighthouse-cli/printer.js
  lighthouse-cli/test/cli/printer-test.js
  package.json
  readme.md
  typings/externs.d.ts
  yarn.lock
Labels: waiting4reviewer

#4933 core(lantern): more flexible graph edge creation
  lighthouse-cli/test/fixtures/byte-efficiency/script.js
  lighthouse-cli/test/fixtures/byte-efficiency/tester.html
  lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js
  lighthouse-cli/test/smokehouse/smokehouse.js
  lighthouse-core/gather/computed/page-dependency-graph.js
  lighthouse-core/test/gather/computed/page-dependency-graph-test.js
Labels: waiting4reviewer

#4944 core(tsc): add type checking to gather-runner
  lighthouse-cli/bin.js
  lighthouse-cli/run.js
  lighthouse-core/gather/computed/metrics/lantern-consistently-interactive.js
  lighthouse-core/gather/computed/metrics/lantern-first-contentful-paint.js
  lighthouse-core/gather/computed/metrics/lantern-first-meaningful-paint.js
  lighthouse-core/gather/computed/metrics/lantern-metric.js
  lighthouse-core/gather/connections/cri.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/index.js
  lighthouse-core/lib/emulation.js
  lighthouse-core/lib/errors.js
  lighthouse-core/runner.js
  lighthouse-core/test/gather/gather-runner-test.js
  typings/artifacts.d.ts
  typings/audit.d.ts
  typings/config.d.ts
  typings/externs.d.ts
  typings/gatherer.d.ts
  typings/web-inspector.d.ts
Labels: waiting4reviewer

#4945 cli(chrome-launcher): remove chrome-launcher forwarding stubs
  chrome-launcher/README.md
  chrome-launcher/chrome-launcher.js
  chrome-launcher/index.js
  lighthouse-core/scripts/manual-chrome-launcher.js
  package.json
Labels: waiting4reviewer

#4943 core(metrics): move TTCI to computed artifact
  lighthouse-core/audits/consistently-interactive.js
  lighthouse-core/closure/typedefs/ComputedArtifacts.js
  lighthouse-core/gather/computed/first-interactive.js
  lighthouse-core/gather/computed/metrics/consistently-interactive.js
  lighthouse-core/gather/computed/metrics/lantern-consistently-interactive.js
  lighthouse-core/gather/computed/metrics/lantern-first-meaningful-paint.js
  lighthouse-core/gather/computed/metrics/lantern-metric.js
  lighthouse-core/gather/computed/metrics/metric.js
  lighthouse-core/gather/computed/page-dependency-graph.js
  lighthouse-core/gather/computed/trace-of-tab.js
  lighthouse-core/lib/errors.js
  lighthouse-core/lib/traces/tracing-processor.js
  lighthouse-core/runner.js
  lighthouse-core/test/audits/consistently-interactive-test.js
  lighthouse-core/test/gather/computed/metrics/consistently-interactive-test.js
  typings/artifacts.d.ts
Labels: I/O-Expedite, waiting4reviewer

#4948 core(metrics): add FCP metric
  lighthouse-core/audits/first-contentful-paint.js
  lighthouse-core/config/default-config.js
  lighthouse-core/gather/computed/metrics/consistently-interactive.js
  lighthouse-core/gather/computed/metrics/first-contentful-paint.js
  lighthouse-core/gather/computed/metrics/metric.js
  lighthouse-core/lib/errors.js
  lighthouse-core/test/audits/first-contentful-paint-test.js
  lighthouse-core/test/gather/computed/metrics/first-contentful-paint-test.js
  typings/artifacts.d.ts
Labels: I/O-Expedite, waiting4reviewer

#4949 core(tsc): add type checking to asset-saver
  .eslintrc.js
  lighthouse-core/gather/devtools-log.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/lib/asset-saver.js
  lighthouse-core/lib/network-recorder.js
  lighthouse-core/lib/traces/pwmetrics-events.js
  package.json
  typings/artifacts.d.ts
  typings/externs.d.ts
  typings/gatherer.d.ts
  yarn.lock
Labels: waiting4reviewer

#4950 core: de-dupe URLs in is-on-http, uses-http2
  lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
  lighthouse-core/audits/dobetterweb/uses-http2.js
  lighthouse-core/audits/is-on-https.js
  lighthouse-core/test/audits/dobetterweb/uses-http2-test.js
  lighthouse-core/test/audits/is-on-https-test.js
Labels: waiting4reviewer

#4954 extension(compilation): add object rest/spread support
  lighthouse-core/lib/asset-saver.js
  lighthouse-extension/gulpfile.js
  lighthouse-extension/package.json
  lighthouse-extension/yarn.lock
  package.json
  yarn.lock
Labels: waiting4reviewer

#4957 docs: "LHR" is "Lighthouse Result"
  docs/understanding-results.md
Labels: waiting4reviewer

#4951 core(metrics): move FMP to computed artifact
  lighthouse-core/audits/first-meaningful-paint.js
  lighthouse-core/audits/metrics.js
  lighthouse-core/audits/screenshot-thumbnails.js
  lighthouse-core/config/default-config.js
  lighthouse-core/gather/computed/metrics/first-meaningful-paint.js
  lighthouse-core/gather/computed/trace-of-tab.js
  lighthouse-core/lib/traces/pwmetrics-events.js
  lighthouse-core/test/audits/first-meaningful-paint-test.js
  lighthouse-core/test/audits/metrics-test.js
  lighthouse-core/test/gather/computed/metrics/first-meaningful-paint-test.js
  lighthouse-core/test/lib/asset-saver-test.js
  lighthouse-core/test/lib/traces/pwmetrics-events-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: I/O-Expedite, waiting4reviewer

#4959 tests: fix run-smoke handoff of testResults
  lighthouse-cli/test/smokehouse/run-smoke.js
Labels: waiting4reviewer

#4956 tests: add CI test to confirm sample_v2.json is up to date
  .travis.yml
  lighthouse-core/scripts/assert-golden-lhr-unchanged.sh
  lighthouse-core/scripts/cleanup-LHR-for-diff.js
  package.json
Labels: waiting4reviewer

#4964 tests: exclude audit helpText from 'yarn diff:sample-json' assertion
  lighthouse-core/scripts/cleanup-LHR-for-diff.js
Labels: waiting4reviewer

#4960 core(config): clean flags for settings
  lighthouse-core/config/config.js
  lighthouse-core/config/constants.js
  lighthouse-core/gather/driver.js
  lighthouse-core/test/config/config-test.js
  typings/config.d.ts
  typings/externs.d.ts
Labels: waiting4reviewer

#4961 core(tsc): add type checking to runner
  lighthouse-core/audits/audit.js
  lighthouse-core/audits/seo/robots-txt.js
  lighthouse-core/config/config.js
  lighthouse-core/lib/asset-saver.js
  lighthouse-core/runner.js
  lighthouse-core/scoring.js
  lighthouse-core/test/lib/asset-saver-test.js
  lighthouse-core/test/runner-test.js
  lighthouse-core/test/scoring-test.js
  package.json
  typings/artifacts.d.ts
  typings/audit.d.ts
  typings/config.d.ts
  typings/lhr.d.ts
  yarn.lock
Labels: waiting4reviewer

#4965 core(screenshots): align filmstrip to observed metrics
  lighthouse-core/audits/screenshot-thumbnails.js
  lighthouse-core/lib/errors.js
  lighthouse-core/test/audits/screenshot-thumbnails-test.js
Labels: I/O-Expedite, waiting4reviewer

#4967 tests(smoke): add smoke test code coverage
  .travis.yml
  lighthouse-core/gather/gatherers/dobetterweb/js-libraries.js
  lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js
  lighthouse-core/gather/gatherers/seo/robots-txt.js
  lighthouse-core/lib/dom-helpers.js
  package.json
Labels: waiting4reviewer

#4966 core(metrics): add first CPU idle lantern metric
  lighthouse-core/audits/predictive-perf.js
  lighthouse-core/gather/computed/first-interactive.js
  lighthouse-core/gather/computed/metrics/lantern-first-cpu-idle.js
  lighthouse-core/test/gather/computed/metrics/lantern-first-cpu-idle-test.js
  typings/artifacts.d.ts
Labels: I/O-Expedite, waiting4reviewer

#4695 core(metrics): add lantern speed index
  lighthouse-core/audits/predictive-perf.js
  lighthouse-core/gather/computed/metrics/lantern-speed-index.js
  lighthouse-core/test/gather/computed/metrics/lantern-speed-index-test.js
Labels: I/O-Expedite, waiting4reviewer

#4975 core(tsc): add type checking to many core gatherers
  lighthouse-core/gather/connections/raw.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gatherers/accessibility.js
  lighthouse-core/gather/gatherers/cache-contents.js
  lighthouse-core/gather/gatherers/chrome-console-messages.js
  lighthouse-core/gather/gatherers/css-usage.js
  lighthouse-core/gather/gatherers/fonts.js
  lighthouse-core/gather/gatherers/html-without-javascript.js
  lighthouse-core/gather/gatherers/http-redirect.js
  lighthouse-core/gather/gatherers/image-usage.js
  lighthouse-core/gather/gatherers/js-usage.js
  lighthouse-core/gather/gatherers/manifest.js
  lighthouse-core/gather/gatherers/mixed-content.js
  lighthouse-core/gather/gatherers/offline.js
  lighthouse-core/gather/gatherers/runtime-exceptions.js
  lighthouse-core/gather/gatherers/scripts.js
  lighthouse-core/gather/gatherers/service-worker.js
  lighthouse-core/gather/gatherers/start-url.js
  lighthouse-core/gather/gatherers/theme-color.js
  lighthouse-core/gather/gatherers/url.js
  lighthouse-core/gather/gatherers/viewport-dimensions.js
  lighthouse-core/gather/gatherers/viewport.js
  lighthouse-core/lib/dom-helpers.js
  lighthouse-core/lib/manifest-parser.js
  lighthouse-core/test/gather/gatherers/mixed-content-test.js
  tsconfig.json
  typings/artifacts.d.ts
  typings/web-inspector.d.ts
Labels: waiting4reviewer

#4986 core(config): remove config.artifacts; always use auditMode
  .gitignore
  docs/readme.md
  lighthouse-core/config/config.js
  lighthouse-core/lib/asset-saver.js
  lighthouse-core/runner.js
  lighthouse-core/test/config/config-test.js
  lighthouse-core/test/fixtures/artifacts/empty-artifacts/artifacts.json
  lighthouse-core/test/fixtures/artifacts/perflog/artifacts.json
  lighthouse-core/test/fixtures/artifacts/perflog/defaultPass.devtoolslog.json
  lighthouse-core/test/fixtures/artifacts/perflog/defaultPass.trace.json
  lighthouse-core/test/gather/fake-driver.js
  lighthouse-core/test/gather/network-recorder-test.js
  lighthouse-core/test/index-test.js
  lighthouse-core/test/runner-test.js
  typings/config.d.ts
  typings/lhr.d.ts
Labels: waiting4reviewer

#4988 tests(smokehouse): split pwa2, perf batches
  lighthouse-cli/test/smokehouse/pwa2-expectations.js
  lighthouse-cli/test/smokehouse/pwa3-expectations.js
  lighthouse-cli/test/smokehouse/run-smoke.js
Labels: waiting4reviewer

#4973 core(canonical): pass when there are multiple identical canonical links
  lighthouse-cli/test/smokehouse/seo/expectations.js
  lighthouse-core/audits/seo/canonical.js
  lighthouse-core/test/audits/seo/canonical-test.js
Labels: waiting4reviewer

#4981 core(load-fast-4-pwa): use computed artifacts
  lighthouse-core/audits/load-fast-enough-for-pwa.js
  lighthouse-core/gather/computed/metrics/metric.js
  lighthouse-core/test/audits/load-fast-enough-for-pwa-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: 3.0, I/O-Expedite, waiting4reviewer

#4982 core(metrics): move first-interactive to first-cpu-idle
  lighthouse-cli/test/smokehouse/perf/expectations.js
  lighthouse-cli/test/smokehouse/tricky-ttci/expectations.js
  lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
  lighthouse-core/audits/byte-efficiency/offscreen-images.js
  lighthouse-core/audits/first-cpu-idle.js
  lighthouse-core/audits/metrics.js
  lighthouse-core/closure/typedefs/ComputedArtifacts.js
  lighthouse-core/config/default-config.js
  lighthouse-core/config/fast-config.js
  lighthouse-core/config/plots-config.js
  lighthouse-core/gather/computed/metrics/first-cpu-idle.js
  lighthouse-core/gather/computed/metrics/lantern-first-cpu-idle.js
  lighthouse-core/lib/traces/pwmetrics-events.js
  lighthouse-core/test/audits/byte-efficiency/offscreen-images-test.js
  lighthouse-core/test/audits/metrics-test.js
  lighthouse-core/test/config/config-test.js
  lighthouse-core/test/gather/computed/metrics/first-cpu-idle-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: 3.0, I/O-Expedite, waiting4reviewer

#4968 core(image-usage): use min of resourceSize/transferSize
  lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js
  lighthouse-core/gather/gatherers/image-usage.js
  lighthouse-core/test/gather/gatherers/dobetterweb/optimized-images-test.js
Labels: waiting4reviewer

#4991 core(tsc): add type checking to seo gatherers
  lighthouse-core/gather/gatherers/seo/canonical.js
  lighthouse-core/gather/gatherers/seo/crawlable-links.js
  lighthouse-core/gather/gatherers/seo/embedded-content.js
  lighthouse-core/gather/gatherers/seo/font-size.js
  lighthouse-core/gather/gatherers/seo/hreflang.js
  lighthouse-core/gather/gatherers/seo/meta-description.js
  lighthouse-core/gather/gatherers/seo/meta-robots.js
  lighthouse-core/gather/gatherers/seo/robots-txt.js
  tsconfig.json
  typings/artifacts.d.ts
Labels: waiting4reviewer

#4990 tests(smokehouse): increase timeout
  lighthouse-cli/test/smokehouse/run-smoke.js
Labels: waiting4reviewer

#5000 cli: update documented throttling flags
  docs/readme.md
  docs/throttling.md
  lighthouse-cli/cli-flags.js
  lighthouse-cli/test/smokehouse/smokehouse.js
  package.json
  plots/README.md
  readme.md
Labels: waiting4reviewer

#4989 core(estimated-input-latency): use a 5s rolling window
  lighthouse-core/audits/estimated-input-latency.js
  lighthouse-core/lib/traces/tracing-processor.js
  lighthouse-core/test/audits/estimated-input-latency-test.js
  lighthouse-core/test/lib/traces/tracing-processor-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: I/O-Expedite, waiting4reviewer

#5006 tests: drop port number from dbw_tester for golden lhr
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
Labels: waiting4reviewer

#5005 core(tsc): add type checking to remaining (dbw) gatherers
  lighthouse-core/gather/gatherers/dobetterweb/all-event-listeners.js
  lighthouse-core/gather/gatherers/dobetterweb/anchors-with-no-rel-noopener.js
  lighthouse-core/gather/gatherers/dobetterweb/appcache.js
  lighthouse-core/gather/gatherers/dobetterweb/domstats.js
  lighthouse-core/gather/gatherers/dobetterweb/js-libraries.js
  lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js
  lighthouse-core/gather/gatherers/dobetterweb/password-inputs-with-prevented-paste.js
  lighthouse-core/gather/gatherers/dobetterweb/response-compression.js
  lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js
  lighthouse-core/gather/gatherers/dobetterweb/websql.js
  lighthouse-core/lib/element.js
  lighthouse-core/test/gather/gatherers/dobetterweb/response-compression-test.js
  lighthouse-core/test/gather/gatherers/dobetterweb/tags-blocking-first-paint-test.js
  tsconfig.json
  typings/artifacts.d.ts
  typings/web-inspector.d.ts
Labels: waiting4reviewer

#5011 core(critical-request-chains): remove preloaded assets from crc
  lighthouse-core/gather/computed/critical-request-chains.js
  lighthouse-core/test/gather/computed/critical-request-chains-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: waiting4reviewer

#4983 core(lhr): lhr-lite type declaration
  typings/lhr-lite.d.ts
Labels: waiting4reviewer

#5018 core(tsc): add type checking to fonts gatherer
  lighthouse-core/gather/gatherers/fonts.js
  package.json
  typings/artifacts.d.ts
  yarn.lock
Labels: waiting4reviewer

#5020 misc: remove timing from golden lhr
  lighthouse-core/scripts/cleanup-LHR-for-diff.js
  lighthouse-core/test/results/sample_v2.json
  package.json
Labels: waiting4reviewer

#5019 core(tsc): gatherer type-checking cleanup
  lighthouse-core/gather/gatherers/dobetterweb/response-compression.js
  lighthouse-core/gather/gatherers/image-usage.js
  lighthouse-core/gather/gatherers/js-usage.js
  lighthouse-core/gather/gatherers/start-url.js
  typings/artifacts.d.ts
  typings/externs.d.ts
  typings/web-inspector.d.ts
Labels: waiting4reviewer

#4999 core(runner): split lhr, artifacts return, respect output type
  docs/hacking-tips.md
  lighthouse-cli/bin.js
  lighthouse-cli/printer.js
  lighthouse-cli/run.js
  lighthouse-cli/test/cli/printer-test.js
  lighthouse-cli/test/cli/run-test.js
  lighthouse-core/closure/typedefs/viewer-externs.js
  lighthouse-core/config/config.js
  lighthouse-core/config/constants.js
  lighthouse-core/index.js
  lighthouse-core/lib/file-namer.js
  lighthouse-core/report/v2/html-report-assets.js
  lighthouse-core/report/v2/report-generator.js
  lighthouse-core/runner.js
  lighthouse-core/test/config/config-test.js
  lighthouse-core/test/index-test.js
  lighthouse-core/test/report/v2/report-generator-test.js
  lighthouse-core/test/runner-test.js
  lighthouse-extension/app/src/lighthouse-ext-background.js
  lighthouse-extension/gulpfile.js
  lighthouse-viewer/app/src/viewer-ui-features.js
  lighthouse-viewer/gulpfile.js
  typings/externs.d.ts
Labels: I/O-Expedite, waiting4reviewer

#5023 report(util): fix formatDuration, add tests
  lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
  lighthouse-core/report/v2/renderer/util.js
  lighthouse-core/test/audits/byte-efficiency/uses-long-cache-ttl-test.js
  lighthouse-core/test/report/v2/renderer/util-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: waiting4reviewer

#5009 report: new score display, metrics display, rich tooltips
  lighthouse-core/report/v2/renderer/category-renderer.js
  lighthouse-core/report/v2/renderer/performance-category-renderer.js
  lighthouse-core/report/v2/renderer/report-renderer.js
  lighthouse-core/report/v2/report-styles.css
  lighthouse-core/report/v2/templates.html
  lighthouse-core/test/report/v2/renderer/category-renderer-test.js
  lighthouse-core/test/report/v2/renderer/performance-category-renderer-test.js
  lighthouse-extension/test/extension-test.js
Labels: waiting4reviewer

#5034 report: move html report from v2/ dir to html/
  docs/hacking-tips.md
  lighthouse-core/audits/audit.js
  lighthouse-core/audits/bootup-time.js
  lighthouse-core/audits/byte-efficiency/total-byte-weight.js
  lighthouse-core/audits/consistently-interactive.js
  lighthouse-core/audits/critical-request-chains.js
  lighthouse-core/audits/deprecations.js
  lighthouse-core/audits/dobetterweb/dom-size.js
  lighthouse-core/audits/dobetterweb/link-blocking-first-paint.js
  lighthouse-core/audits/dobetterweb/uses-http2.js
  lighthouse-core/audits/estimated-input-latency.js
  lighthouse-core/audits/first-contentful-paint.js
  lighthouse-core/audits/first-cpu-idle.js
  lighthouse-core/audits/first-meaningful-paint.js
  lighthouse-core/audits/is-on-https.js
  lighthouse-core/audits/load-fast-enough-for-pwa.js
  lighthouse-core/audits/mainthread-work-breakdown.js
  lighthouse-core/audits/mixed-content.js
  lighthouse-core/audits/predictive-perf.js
  lighthouse-core/audits/redirects.js
  lighthouse-core/audits/speed-index.js
  lighthouse-core/audits/time-to-first-byte.js
  lighthouse-core/audits/uses-rel-preload.js
  lighthouse-core/closure/closure-type-checking.js
  lighthouse-core/lib/url-shim.js
  lighthouse-core/report/html/html-report-assets.js
  lighthouse-core/report/html/renderer/category-renderer.js
  lighthouse-core/report/html/renderer/crc-details-renderer.js
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/report/html/renderer/dom.js
  lighthouse-core/report/html/renderer/logger.js
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/report/html/renderer/report-renderer.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/report/html/report-template.html
  lighthouse-core/report/html/templates.html
  lighthouse-core/report/report-generator.js
  lighthouse-core/runner.js
  lighthouse-core/scripts/roll-to-devtools.sh
  lighthouse-core/test/report/html/renderer/category-renderer-test.js
  lighthouse-core/test/report/html/renderer/crc-details-renderer-test.js
  lighthouse-core/test/report/html/renderer/details-renderer-test.js
  lighthouse-core/test/report/html/renderer/dom-test.js
  lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
  lighthouse-core/test/report/html/renderer/report-renderer-test.js
  lighthouse-core/test/report/html/renderer/util-test.js
  lighthouse-core/test/report/report-generator-test.js
  lighthouse-extension/gulpfile.js
  lighthouse-viewer/gulpfile.js
Labels: waiting4reviewer

#5036 docs(readme): Bye Bye Greta
  readme.md
Labels: waiting4reviewer

#5035 core(lhr): savingsMs, savingsBytes
  typings/lhr-lite.d.ts
Labels: waiting4reviewer

#4995 core: merge render blocking audits to lantern
  lighthouse-cli/test/smokehouse/dbw-config.js
  lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
  lighthouse-cli/test/smokehouse/offline-config.js
  lighthouse-cli/test/smokehouse/offline-local/offline-expectations.js
  lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
  lighthouse-core/audits/byte-efficiency/render-blocking-resources.js
  lighthouse-core/audits/dobetterweb/link-blocking-first-paint.js
  lighthouse-core/audits/dobetterweb/script-blocking-first-paint.js
  lighthouse-core/config/default-config.js
  lighthouse-core/gather/computed/metrics/lantern-metric.js
  lighthouse-core/lib/dependency-graph/network-node.js
  lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
  lighthouse-core/test/audits/byte-efficiency/render-blocking-resources-test.js
  lighthouse-core/test/audits/dobetterweb/link-blocking-first-paint-test.js
  lighthouse-core/test/audits/dobetterweb/script-blocking-first-paint-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: I/O-Expedite, waiting4reviewer

#5021 core(tti): update ignorable network requests and start point
  lighthouse-core/gather/computed/metrics/consistently-interactive.js
  lighthouse-core/lib/errors.js
  lighthouse-core/test/gather/computed/metrics/consistently-interactive-test.js
  typings/web-inspector.d.ts
Labels: waiting4reviewer

#5040 report: only appendScoreScale to scoreHeader if it exists
  lighthouse-core/report/html/renderer/report-renderer.js
Labels: waiting4reviewer

#5025 tests(viewer): add pptr test for viewer
  .travis.yml
  lighthouse-cli/test/fixtures/static-server.js
  lighthouse-viewer/package.json
  lighthouse-viewer/test/viewer-test-pptr.js
  package.json
Labels: waiting4reviewer

#4362 new_audit(preconnect): add preconnect audit
  lighthouse-cli/test/fixtures/perf/preload_tester.js
  lighthouse-cli/test/smokehouse/perf/expectations.js
  lighthouse-core/audits/audit.js
  lighthouse-core/audits/uses-rel-preconnect.js
  lighthouse-core/config/default-config.js
  lighthouse-core/report/html/renderer/crc-details-renderer.js
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/test/audits/uses-rel-preconnect-test.js
  lighthouse-core/test/report/html/renderer/details-renderer-test.js
  lighthouse-core/test/results/sample_v2.json
  typings/artifacts.d.ts
  typings/audit.d.ts
  typings/web-inspector.d.ts
Labels: new_audit, waiting4reviewer

#5024 core(metrics): add lantern EIL
  lighthouse-core/audits/estimated-input-latency.js
  lighthouse-core/audits/metrics.js
  lighthouse-core/audits/predictive-perf.js
  lighthouse-core/gather/computed/metrics/estimated-input-latency.js
  lighthouse-core/gather/computed/metrics/lantern-estimated-input-latency.js
  lighthouse-core/test/audits/estimated-input-latency-test.js
  lighthouse-core/test/audits/metrics-test.js
  lighthouse-core/test/gather/computed/metrics/estimated-input-latency-test.js
  lighthouse-core/test/gather/computed/metrics/lantern-estimated-input-latency-test.js
  lighthouse-core/test/results/sample_v2.json
  typings/artifacts.d.ts
Labels: waiting4reviewer

#5039 core(render-blocking): address followup feedback
  lighthouse-core/audits/byte-efficiency/render-blocking-resources.js
Labels: waiting4reviewer

#5052 tests: fix cli handling empty runnerResult during gatherMode
  lighthouse-cli/run.js
  lighthouse-cli/test/cli/run-test.js
  lighthouse-core/runner.js
Labels: waiting4reviewer

#5045 report: rework the DOM of audits
  lighthouse-core/gather/computed/metrics/lantern-consistently-interactive.js
  lighthouse-core/gather/computed/metrics/lantern-first-cpu-idle.js
  lighthouse-core/gather/computed/metrics/lantern-speed-index.js
  lighthouse-core/report/html/renderer/category-renderer.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/report/html/report-template.html
  lighthouse-core/report/html/templates.html
  lighthouse-core/test/report/html/renderer/category-renderer-test.js
  lighthouse-core/test/report/html/renderer/dom-test.js
  lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
  lighthouse-extension/test/extension-test.js
  lighthouse-viewer/test/viewer-test-pptr.js
Labels: waiting4reviewer

#4885 new_audit: efficient-animated-content - use videos instead of gifs
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
  lighthouse-cli/test/fixtures/dobetterweb/lighthouse-rotating.gif
  lighthouse-cli/test/smokehouse/dbw-config.js
  lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
  lighthouse-core/audits/byte-efficiency/efficient-animated-content.js
  lighthouse-core/config/default-config.js
  lighthouse-core/test/audits/byte-efficiency/efficient-animated-content-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: waiting4reviewer

#5051 core(tsc): add type checking to computed artifacts
  lighthouse-core/audits/critical-request-chains.js
  lighthouse-core/audits/predictive-perf.js
  lighthouse-core/audits/redirects.js
  lighthouse-core/audits/seo/canonical.js
  lighthouse-core/audits/seo/hreflang.js
  lighthouse-core/audits/seo/http-status-code.js
  lighthouse-core/audits/seo/is-crawlable.js
  lighthouse-core/audits/uses-rel-preconnect.js
  lighthouse-core/audits/uses-rel-preload.js
  lighthouse-core/gather/computed/computed-artifact.js
  lighthouse-core/gather/computed/critical-request-chains.js
  lighthouse-core/gather/computed/dtm-model.js
  lighthouse-core/gather/computed/load-simulator.js
  lighthouse-core/gather/computed/main-resource.js
  lighthouse-core/gather/computed/manifest-values.js
  lighthouse-core/gather/computed/metrics/lantern-consistently-interactive.js
  lighthouse-core/gather/computed/metrics/lantern-estimated-input-latency.js
  lighthouse-core/gather/computed/metrics/lantern-first-contentful-paint.js
  lighthouse-core/gather/computed/metrics/lantern-first-meaningful-paint.js
  lighthouse-core/gather/computed/metrics/lantern-metric.js
  lighthouse-core/gather/computed/metrics/lantern-speed-index.js
  lighthouse-core/gather/computed/metrics/metric.js
  lighthouse-core/gather/computed/metrics/speed-index.js
  lighthouse-core/gather/computed/network-analysis.js
  lighthouse-core/gather/computed/network-records.js
  lighthouse-core/gather/computed/network-throughput.js
  lighthouse-core/gather/computed/page-dependency-graph.js
  lighthouse-core/gather/computed/pushed-requests.js
  lighthouse-core/gather/computed/screenshots.js
  lighthouse-core/gather/computed/speedline.js
  lighthouse-core/gather/computed/trace-of-tab.js
  lighthouse-core/lib/console-quieter.js
  lighthouse-core/lib/icons.js
  lighthouse-core/lib/manifest-parser.js
  lighthouse-core/lib/traces/devtools-timeline-model.js
  lighthouse-core/runner.js
  lighthouse-core/test/gather/computed/computed-artifact-test.js
  lighthouse-core/test/gather/computed/critical-request-chains-test.js
  lighthouse-core/test/gather/computed/main-resource-test.js
  lighthouse-core/test/gather/computed/manifest-values-test.js
  lighthouse-core/test/gather/computed/metrics/lantern-consistently-interactive-test.js
  lighthouse-core/test/gather/computed/metrics/lantern-first-contentful-paint-test.js
  lighthouse-core/test/gather/computed/metrics/lantern-first-cpu-idle-test.js
  lighthouse-core/test/gather/computed/metrics/lantern-first-meaningful-paint-test.js
  lighthouse-core/test/gather/computed/metrics/lantern-speed-index-test.js
  lighthouse-core/test/gather/computed/network-throughput-test.js
  lighthouse-core/test/gather/computed/trace-of-tab-test.js
  lighthouse-core/test/lib/traces/tracing-processor-test.js
  tsconfig.json
  typings/artifacts.d.ts
  typings/config.d.ts
  typings/externs.d.ts
  typings/speedline/index.d.ts
  typings/web-inspector.d.ts
Labels: waiting4reviewer

#5061 core(tsc): update for new @types/css-font-loading-module
  lighthouse-core/gather/gatherers/fonts.js
  package.json
  yarn.lock
Labels: waiting4reviewer

#5060 tests(appeveyor): exclude perf smoketest until flake is fixed
  .appveyor.yml
Labels: waiting4reviewer

#5059 docs: add html report overview writeup
  docs/architecture.md
  docs/report.md
Labels: waiting4reviewer

#5063 docs(report): minor fix of markdown link
  docs/report.md
Labels: waiting4reviewer
