Repository GoogleChrome/lighthouse, pull requests merged in 2018-08, with the labels that each got.

#5730 report(i18n): localize CRC renderer strings
  lighthouse-core/lib/locales/en-US.json
  lighthouse-core/lib/locales/en-XA.json
  lighthouse-core/report/html/renderer/crc-details-renderer.js
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/report/html/templates.html
  lighthouse-core/test/report/html/renderer/crc-details-renderer-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: i18n

#5771 core(i18n): sort the ICU messages when saved
  lighthouse-core/lib/locales/en-US.json
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/test/results/sample_v2.json
Labels: i18n

#5769 extension: refactor option/flag passing (breaking change)
  lighthouse-core/runner.js
  lighthouse-extension/app/src/lighthouse-background.js
  lighthouse-extension/app/src/lighthouse-ext-background.js
  lighthouse-extension/app/src/popup.js
Labels: chillin ❄

#5877 report(psi): reset template styles on every call of prepareLabData
  lighthouse-core/report/html/renderer/psi.js
Labels: needs-roll
