Repository GoogleChrome/lighthouse, pull requests merged in 2018-07, with the labels that each got.

#5274 new_audit(dobetterweb): add new audit for doctype
  lighthouse-core/audits/dobetterweb/doctype.js
  lighthouse-core/config/default-config.js
  lighthouse-core/gather/gatherers/dobetterweb/doctype.js
  lighthouse-core/test/audits/dobetterweb/doctype-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  typings/artifacts.d.ts
Labels: waiting4committer

#5409 core(preload): remove blob protocol from preload audit
  lighthouse-core/audits/uses-rel-preload.js
  lighthouse-core/lib/url-shim.js
  lighthouse-core/test/audits/uses-rel-preload-test.js
Labels: waiting4reviewer

#5578 core(response-compression): graceful recovery
  lighthouse-core/audits/byte-efficiency/uses-text-compression.js
  lighthouse-core/gather/gatherers/dobetterweb/response-compression.js
  lighthouse-core/test/gather/gatherers/dobetterweb/response-compression-test.js
  typings/artifacts.d.ts
Labels: 3.0
