Repository GoogleChrome/lighthouse, pull requests merged in 2019-11, with the labels that each got.

#9904 deps: bump chrome-launcher to 0.12.0
  package.json
  yarn.lock
Labels: cla: yes

#9783 core: use flatten protocol
  lighthouse-core/gather/connections/connection.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js
  lighthouse-core/gather/gatherers/dobetterweb/response-compression.js
  lighthouse-core/lib/network-recorder.js
  lighthouse-core/lib/network-request.js
  lighthouse-core/test/gather/driver-test.js
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/gather/mock-commands.js
  lighthouse-core/test/lib/network-recorder-test.js
  types/protocol.d.ts
Labels: 6.0, cla: yes

#9843 tests: refactor smokehouse for extensibility
  .appveyor.yml
  build/tests/bundle-smoke-test.js
  lighthouse-cli/test/smokehouse/firehouse.js
  lighthouse-cli/test/smokehouse/frontends/node.js
  lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js
  lighthouse-cli/test/smokehouse/lib/child-process-error.js
  lighthouse-cli/test/smokehouse/lib/concurrent-mapper.js
  lighthouse-cli/test/smokehouse/lib/local-console.js
  lighthouse-cli/test/smokehouse/lighthouse-runners/cli.js
  lighthouse-cli/test/smokehouse/readme.md
  lighthouse-cli/test/smokehouse/report-assert.js
  lighthouse-cli/test/smokehouse/run-smoke.js
  lighthouse-cli/test/smokehouse/smokehouse.js
  lighthouse-cli/test/smokehouse/test-definitions/a11y/a11y-config.js
  lighthouse-cli/test/smokehouse/test-definitions/a11y/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/byte-config.js
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/core-tests.js
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-config.js
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/errors/error-config.js
  lighthouse-cli/test/smokehouse/test-definitions/errors/error-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/lantern/lantern-config.js
  lighthouse-cli/test/smokehouse/test-definitions/lantern/lantern-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/offline-local/offline-config.js
  lighthouse-cli/test/smokehouse/test-definitions/offline-local/offline-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/oopif/oopif-config.js
  lighthouse-cli/test/smokehouse/test-definitions/oopif/oopif-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/perf/perf-config.js
  lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa-config.js
  lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa2-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa3-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/redirects/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/redirects/redirects-config.js
  lighthouse-cli/test/smokehouse/test-definitions/seo/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/seo/seo-config.js
  lighthouse-cli/test/smokehouse/test-definitions/tricky-metrics/expectations.js
  lighthouse-core/scripts/release/test.sh
  package.json
  types/smokehouse.d.ts
Labels: cla: yes

#9901 core(lightwallet): add timing-budget audit
  lighthouse-core/audits/performance-budget.js
  lighthouse-core/audits/timing-budget.js
  lighthouse-core/computed/metrics/timing-summary.js
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
  lighthouse-core/test/audits/__snapshots__/metrics-test.js.snap
  lighthouse-core/test/audits/timing-budget-test.js
  lighthouse-core/test/computed/metrics/timing-summary-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
  types/artifacts.d.ts
Labels: cla: yes

#9931 i18n: Use log.verbose for outdated strings warning
  lighthouse-core/lib/i18n/i18n.js
Labels: cla: yes

#9854 core(config): enable unused-javascript by default
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/audits/byte-efficiency/unused-javascript.js
  lighthouse-core/config/default-config.js
  lighthouse-core/config/full-config.js
  lighthouse-core/gather/gatherers/js-usage.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes

#9935 core: fix icu error thrown while throwing protocol error
  lighthouse-core/lib/lh-error.js
Labels: cla: yes

#9930 core: delete full config
  docs/configuration.md
  docs/readme.md
  lighthouse-cli/cli-flags.js
  lighthouse-cli/test/cli/bin-test.js
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/byte-config.js
  lighthouse-cli/test/smokehouse/test-definitions/lantern/lantern-config.js
  lighthouse-core/config/config.js
  lighthouse-core/test/config/config-test.js
  types/config.d.ts
Labels: cla: yes

#9933 docs: devtools throttling deprecation notice
  docs/throttling.md
Labels: cla: yes

#9932 core(lantern): use fixed times for data URLs
  lighthouse-core/lib/dependency-graph/network-node.js
  lighthouse-core/lib/dependency-graph/simulator/simulator.js
  lighthouse-core/test/fixtures/lantern-master-computed-values.json
  lighthouse-core/test/lib/dependency-graph/simulator/simulator-test.js
Labels: cla: yes

#9928 core(font-size): don't allow a deleted node to fail gatherer
  lighthouse-core/gather/gatherers/seo/font-size.js
Labels: cla: yes

#9936 bundling pubads for devtools
  build/build-bundle.js
  clients/devtools-entry.js
  lighthouse-core/config/config-helpers.js
  lighthouse-core/config/config.js
Labels: 6.0, cla: yes

#9942 misc: update location for devtools roll script
  lighthouse-core/scripts/roll-to-devtools.sh
Labels: 6.0, cla: yes

#9923 core: add new base artifact, HostFormFactor
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-core/config/config.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/scripts/build-report-for-autodeployment.js
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  types/artifacts.d.ts
Labels: cla: yes

#9951 misc(lhci): build-dir => staticDistDir
  lighthouse-core/scripts/dogfood-lhci.sh
Labels: cla: yes

#9911 core: use the same scoring curve for desktop in all channels
  lighthouse-core/audits/metrics/first-contentful-paint.js
  lighthouse-core/audits/metrics/first-cpu-idle.js
  lighthouse-core/audits/metrics/first-meaningful-paint.js
  lighthouse-core/audits/metrics/interactive.js
  lighthouse-core/audits/metrics/speed-index.js
  lighthouse-core/config/lr-desktop-config.js
  lighthouse-core/test/computed/metrics/first-contentful-paint-test.js
  lighthouse-core/test/computed/metrics/first-meaningful-paint-test.js
  lighthouse-core/test/computed/metrics/interactive-test.js
  lighthouse-core/test/computed/metrics/speed-index-test.js
Labels: 6.0, cla: yes

#9905 core: add largest contentful paint to lantern and default config
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/audits/metrics/largest-contentful-paint.js
  lighthouse-core/audits/predictive-perf.js
  lighthouse-core/computed/metrics/lantern-largest-contentful-paint.js
  lighthouse-core/computed/metrics/largest-contentful-paint.js
  lighthouse-core/config/default-config.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/scripts/lantern/print-correlations.js
  lighthouse-core/scripts/lantern/run-on-all-assets.js
  lighthouse-core/test/audits/__snapshots__/metrics-test.js.snap
  lighthouse-core/test/audits/metrics-test.js
  lighthouse-core/test/computed/metrics/lantern-largest-contentful-paint-test.js
  lighthouse-core/test/computed/metrics/largest-contentful-paint-test.js
  lighthouse-core/test/fixtures/traces/lcp-m78.devtools.log.json
  lighthouse-core/test/fixtures/traces/lcp-m78.json
  lighthouse-core/test/fixtures/traces/lcp-m79.devtools.log.json
  lighthouse-core/test/fixtures/traces/lcp-m79.json
  lighthouse-core/test/lib/tracehouse/trace-processor-test.js
  lighthouse-core/test/results/artifacts/defaultPass.trace.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: 6.0, cla: yes, land-when-ci-is-green

#9940 i18n(import): stack packs and small corrections
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
  package.json
Labels: 6.0, cla: yes, land-when-ci-is-green

#9967 core(emulation): bump emulated chrome UA to m80
  lighthouse-core/lib/emulation.js
Labels: cla: yes

#9972 misc: fix lhci to 0.3.x
  lighthouse-core/scripts/dogfood-lhci.sh
Labels: cla: yes

#9980 patrick's tweaks to lantern collection script
  lighthouse-core/scripts/lantern/collect/collect.js
  lighthouse-core/scripts/lantern/collect/common.js
  lighthouse-core/scripts/lantern/collect/gcp-create-and-run.sh
  lighthouse-core/scripts/lantern/collect/gcp-run.sh
  lighthouse-core/scripts/lantern/collect/gcp-setup.sh
Labels: cla: yes

#9954 docs: add auto-lighthouse entry to 'related projects'
  readme.md
Labels: cla: yes

#9377 core: add settings.internalDisableDeviceScreenEmulation
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/config/constants.js
  lighthouse-core/gather/driver.js
  lighthouse-core/lib/emulation.js
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/lib/emulation-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  types/externs.d.ts
Labels: 6.0, cla: no

#9984 docs(readme): add link to official lighthouse ci
  readme.md
Labels: cla: yes

#9988 clients(extension): use new settings when form updates
  clients/extension/scripts/popup.js
Labels: cla: yes

#9989 docs(releasing): update procedure for extension
  clients/extension/manifest.json
  docs/releasing.md
  lighthouse-core/scripts/release/prepare-commit.sh
Labels: cla: yes

#9354 report: source-location for linkifying
  lighthouse-cli/test/smokehouse/test-definitions/seo/expectations.js
  lighthouse-core/audits/deprecations.js
  lighthouse-core/audits/seo/font-size.js
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/test/audits/deprecations-test.js
  lighthouse-core/test/audits/seo/font-size-test.js
  lighthouse-core/test/report/html/renderer/details-renderer-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
  types/audit-details.d.ts
Labels: cla: yes

#9955 report: fix flicker in normal case report
  lighthouse-core/report/html/templates.html
Labels: cla: yes

#9991 viewer: use new logo
  lighthouse-viewer/app/images/lh_logo_bg.png
  lighthouse-viewer/app/images/lighthouse-logo.svg
  lighthouse-viewer/app/index.html
Labels: cla: yes

#9962 cli: allow extraHeaders as object
  lighthouse-cli/bin.js
  lighthouse-cli/test/cli/cli-flags-test.js
  lighthouse-cli/test/fixtures/cli-flags-path.json
Labels: cla: yes

#9997 docs(plugins): update recipe, suggest NODE_ENV=.. hack
  docs/plugins.md
  docs/recipes/lighthouse-plugin-example/package.json
  docs/recipes/lighthouse-plugin-example/readme.md
Labels: cla: yes, land-when-ci-is-green

#9722 docs(integration-tests): using Lighthouse with Jest; verify in our CI
  .appveyor.yml
  .travis.yml
  docs/recipes/auth/README.md
  docs/recipes/auth/example-lh-auth.js
  docs/recipes/auth/server/public/unauthenticated.html
  docs/recipes/auth/server/server.js
  docs/recipes/integration-test/README.md
  docs/recipes/integration-test/example-lh-auth.test.js
  docs/recipes/integration-test/package.json
  jest.config.js
  package.json
  yarn.lock
Labels: cla: yes

#9978 core(artifacts): add property attribute to MetaElements
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-core/gather/gatherers/meta-elements.js
  lighthouse-core/test/results/artifacts/artifacts.json
  types/artifacts.d.ts
Labels: cla: yes

#9999 clients(viewer): tweak line height
  lighthouse-viewer/app/styles/viewer.css
Labels: cla: yes

#9998 misc: bump-versions.js release script
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  lighthouse-core/scripts/release/bump-versions.js
  lighthouse-core/scripts/release/prepare-commit.sh
Labels: cla: yes

#10002 clients(viewer): update manifest icons
  lighthouse-viewer/app/images/android-chrome-192x192.png
  lighthouse-viewer/app/images/android-chrome-512x512.png
  lighthouse-viewer/app/images/lh_favicon_32px.png
  lighthouse-viewer/app/images/lh_favicon_76px.png
  lighthouse-viewer/app/images/lighthouse-logo_512px.png
  lighthouse-viewer/app/manifest.json
Labels: cla: yes

#10005 clients(devtools): split up runLighthouseInWorker and expose to worker
  clients/devtools-entry.js
Labels: cla: yes

#10018 docs(readme): add PageSpeed Green to to related projects
  readme.md
Labels: cla: yes

#9910 core(lantern): Remove min task duration from lantern graphs
  lighthouse-core/computed/page-dependency-graph.js
  lighthouse-core/lib/dependency-graph/base-node.js
  lighthouse-core/test/computed/page-dependency-graph-test.js
  lighthouse-core/test/fixtures/lantern-master-computed-values.json
Labels: cla: yes

#10006 core(third-party-summary): check main domain against all third party domains
  lighthouse-core/audits/third-party-summary.js
  lighthouse-core/test/audits/third-party-summary-test.js
Labels: cla: yes
