Repository GoogleChrome/lighthouse, pull requests merged in 2019-01, with the labels that each got.

#6783 core: change 'not-applicable' to 'notApplicable'
  docs/understanding-results.md
  lighthouse-cli/test/smokehouse/offline-local/offline-expectations.js
  lighthouse-cli/test/smokehouse/seo/expectations.js
  lighthouse-core/audits/audit.js
  lighthouse-core/lib/proto-preprocessor.js
  lighthouse-core/report/html/renderer/category-renderer.js
  lighthouse-core/report/html/renderer/pwa-category-renderer.js
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/test/audits/audit-test.js
  lighthouse-core/test/lib/proto-preprocessor-test.js
  lighthouse-core/test/report/html/renderer/category-renderer-test.js
  lighthouse-core/test/report/html/renderer/report-renderer-test.js
  lighthouse-core/test/report/html/renderer/util-test.js
  lighthouse-core/test/results/sample_v2.json
  lighthouse-core/test/scoring-test.js
  proto/lighthouse-result.proto
  proto/sample_v2_round_trip.json
  types/audit.d.ts
  types/lhr-lite.d.ts
Labels: 4.0, waiting4reviewer

#6932 misc(emulation): Use Nexus 5X emulation real screen size
  lighthouse-cli/cli-flags.js
  lighthouse-core/lib/emulation.js
  lighthouse-core/test/fixtures/artifacts/perflog/artifacts.json
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/runner-test.js
  readme.md
Labels: 4.0

#6930 report: expand groups within Passed Audits
  lighthouse-core/report/html/renderer/category-renderer.js
  lighthouse-core/test/report/html/renderer/category-renderer-test.js
Labels: 4.0

#6982 report: clean up more clump/group/expandable crossover noise
  lighthouse-core/report/html/renderer/category-renderer.js
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/report/html/renderer/pwa-category-renderer.js
  lighthouse-core/report/html/templates.html
Labels: 4.0

#6608 core: INSECURE_DOCUMENT_REQUEST errors still return lhr
  clients/extension/scripts/popup.js
  lighthouse-cli/run.js
  lighthouse-cli/test/smokehouse/error-expectations.js
  lighthouse-cli/test/smokehouse/smokehouse.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/lib/i18n/en-US.json
  lighthouse-core/lib/lh-error.js
  lighthouse-core/test/gather/driver-test.js
  lighthouse-core/test/gather/fake-driver.js
  lighthouse-core/test/gather/gather-runner-test.js
Labels: 4.0, waiting4committer

#6989 report: New audit clump for audits with warnings (#5327)
  lighthouse-core/lib/i18n/en-US.json
  lighthouse-core/report/html/renderer/category-renderer.js
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/test/report/html/renderer/category-renderer-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/lighthouse-result.proto
  proto/sample_v2_round_trip.json
Labels: 4.0

#7020 deps: update axe-core to latest
  .appveyor.yml
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/fixtures/a11y/a11y_tester.html
  lighthouse-cli/test/smokehouse/a11y/expectations.js
  lighthouse-cli/test/smokehouse/run-smoke.js
  lighthouse-core/audits/accessibility/aria-allowed-attr.js
  lighthouse-core/audits/accessibility/aria-required-attr.js
  lighthouse-core/audits/accessibility/aria-required-children.js
  lighthouse-core/audits/accessibility/aria-required-parent.js
  lighthouse-core/audits/accessibility/aria-roles.js
  lighthouse-core/audits/accessibility/aria-valid-attr-value.js
  lighthouse-core/audits/accessibility/aria-valid-attr.js
  lighthouse-core/audits/accessibility/audio-caption.js
  lighthouse-core/audits/accessibility/button-name.js
  lighthouse-core/audits/accessibility/bypass.js
  lighthouse-core/audits/accessibility/color-contrast.js
  lighthouse-core/audits/accessibility/definition-list.js
  lighthouse-core/audits/accessibility/dlitem.js
  lighthouse-core/audits/accessibility/duplicate-id.js
  lighthouse-core/audits/accessibility/frame-title.js
  lighthouse-core/audits/accessibility/html-has-lang.js
  lighthouse-core/audits/accessibility/html-lang-valid.js
  lighthouse-core/audits/accessibility/image-alt.js
  lighthouse-core/audits/accessibility/input-image-alt.js
  lighthouse-core/audits/accessibility/label.js
  lighthouse-core/audits/accessibility/layout-table.js
  lighthouse-core/audits/accessibility/link-name.js
  lighthouse-core/audits/accessibility/list.js
  lighthouse-core/audits/accessibility/listitem.js
  lighthouse-core/audits/accessibility/manual/accesskeys.js
  lighthouse-core/audits/accessibility/meta-refresh.js
  lighthouse-core/audits/accessibility/meta-viewport.js
  lighthouse-core/audits/accessibility/object-alt.js
  lighthouse-core/audits/accessibility/tabindex.js
  lighthouse-core/audits/accessibility/td-headers-attr.js
  lighthouse-core/audits/accessibility/th-has-data-cells.js
  lighthouse-core/audits/accessibility/valid-lang.js
  lighthouse-core/audits/accessibility/video-caption.js
  lighthouse-core/audits/accessibility/video-description.js
  lighthouse-core/config/default-config.js
  lighthouse-core/lib/i18n/en-US.json
  lighthouse-core/test/audits/accessibility/accesskeys-test.js
  lighthouse-core/test/report/html/renderer/category-renderer-test.js
  lighthouse-core/test/report/html/renderer/dom-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  proto/sample_v2_round_trip.json
  yarn.lock
Labels: 4.0

#6959 core: add Lighthouse plugins
  lighthouse-core/config/config-plugin.js
  lighthouse-core/config/config.js
  lighthouse-core/test/config/__snapshots__/config-plugin-test.js.snap
  lighthouse-core/test/config/config-plugin-test.js
  lighthouse-core/test/config/config-test.js
  lighthouse-core/test/fixtures/config-plugins/lighthouse-plugin-no-category/package.json
  lighthouse-core/test/fixtures/config-plugins/lighthouse-plugin-no-category/plugin-no-category.js
  lighthouse-core/test/fixtures/config-plugins/lighthouse-plugin-simple/package.json
  lighthouse-core/test/fixtures/config-plugins/lighthouse-plugin-simple/plugin-simple.js
  types/config.d.ts
Labels: 4.1

#7008 i18n: import translated accessibility and lh-error messages
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
Labels: 4.2
