Repository GoogleChrome/lighthouse, pull requests merged in 2019-09, with the labels that each got.

#9629 misc(viewer): fix favicon typo
  lighthouse-viewer/app/index.html
Labels: cla: yes

#9636 report: remove PWA badge flicker workaround for Chrome
  lighthouse-core/report/html/report-styles.css
Labels: cla: yes

#9638 i18n: add registerLocaleData() method
  lighthouse-core/index.js
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/test/lib/i18n/i18n-test.js
Labels: cla: yes

#9626 report: don't use unnessary monospace
  lighthouse-core/audits/deprecations.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes

#9639 misc(build): include locale files in devtools roll
  lighthouse-core/scripts/roll-to-devtools.sh
Labels: cla: yes

#9644 docs(audits): distinguish document.write() audit from intervention
  lighthouse-core/audits/dobetterweb/no-document-write.js
Labels: cla: yes, land-when-ci-is-green

#9654 tests: migrate travis to xenial for modern Chrome support
  .travis.yml
Labels: cla: yes

#9670 deps: update transitive deps
  yarn.lock
Labels: cla: yes

#9672 tests: simplify serving of zone.js
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
  lighthouse-cli/test/fixtures/dobetterweb/third_party/aggressive-promise-polyfill.js
  lighthouse-cli/test/fixtures/static-server.js
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green

#9557 report: unknown details type
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/test/report/html/renderer/details-renderer-test.js
Labels: cla: yes

#9674 v5.3.0
  changelog.md
  clients/extension/manifest.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  proto/sample_v2_round_trip.json
Labels: 5.3, cla: yes

#9653 docs(plugins): update recipe example's lighthouse peer dependency version
  docs/recipes/lighthouse-plugin-example/package.json
  docs/recipes/lighthouse-plugin-example/readme.md
Labels: cla: yes

#9665 tests(smokehouse): fix unintentional 404. remove max-len rule for expectations
  .eslintrc.js
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
  lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
Labels: cla: yes

#9687 i18n: treat Infinity and NaN as numeric values
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/test/lib/i18n/i18n-test.js
Labels: cla: yes

#8979 core(iframe-elements): Include new IFrameElements gatherer
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/fixtures/oopif.html
  lighthouse-cli/test/smokehouse/oopif-config.js
  lighthouse-cli/test/smokehouse/oopif-expectations.js
  lighthouse-core/config/default-config.js
  lighthouse-core/gather/gatherers/iframe-elements.js
  lighthouse-core/lib/page-functions.js
  types/artifacts.d.ts
Labels: cla: yes

#9688 report: update favicon
  lighthouse-core/report/html/report-template.html
  lighthouse-viewer/app/index.html
Labels: cla: yes

#9693 v5.4.0
  changelog.md
  clients/extension/manifest.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  proto/sample_v2_round_trip.json
Labels: cla: yes, waiting4committer

#9628 docs(auth): running Lighthouse on authenticated pages
  .gitignore
  docs/authenticated-pages.md
  docs/recipes/auth/.eslintrc.js
  docs/recipes/auth/README.md
  docs/recipes/auth/example-lh-auth.js
  docs/recipes/auth/package.json
  docs/recipes/auth/server/public/dashboard-unauthenticated.html
  docs/recipes/auth/server/public/dashboard.html
  docs/recipes/auth/server/public/home-unauthenticated.html
  docs/recipes/auth/server/public/home.html
  docs/recipes/auth/server/server.js
Labels: cla: yes

#9645 clients(devtools): expose registerLocaleData to worker
  clients/devtools-entry.js
  lighthouse-core/index.js
  lighthouse-core/lib/i18n/locales.js
  lighthouse-core/test/lib/i18n/i18n-test.js
Labels: cla: yes, land-when-ci-is-green

#9694 misc(assets): update logo
  assets/lh_favicon.svg
  assets/lh_favicon_32px.png
  assets/lh_favicon_76px.png
  assets/lh_logo_icon.png
  assets/lighthouse-logo-canary.svg
  assets/lighthouse-logo.png
  assets/lighthouse-logo.svg
  assets/lighthouse-logo_1024px.png
  assets/lighthouse-logo_512px.png
  assets/lighthouse-logo_no-light.png
Labels: cla: yes

#9705 docs(readme): update link to authenticated docs
  readme.md
Labels: cla: yes

#9702 clients(devtools): remove version replacement for expectations
  lighthouse-core/scripts/roll-to-devtools.sh
Labels: cla: yes

#9729 docs: update scoring calculator link to v5
  docs/scoring.md
Labels: cla: yes

#9712 core(network-recorder): optimize network idle detection
  lighthouse-core/lib/network-recorder.js
Labels: cla: yes

#9716 docs: add lighthouse-monitor, minor adjust list layout
  readme.md
Labels: cla: yes

#9732 tests(smokehouse): check runWarnings
  lighthouse-cli/test/smokehouse/error-expectations.js
  lighthouse-cli/test/smokehouse/seo/expectations.js
  lighthouse-cli/test/smokehouse/smokehouse-report.js
  types/smokehouse.d.ts
Labels: cla: yes

#9734 docs: add links to more info about throttling and variability
  docs/throttling.md
  docs/variability.md
Labels: cla: yes

#9711 core(audits): link apple-touch-icon audit to web.dev
  lighthouse-core/audits/apple-touch-icon.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes

#9677 misc: add lhci dogfood script to travis
  .travis.yml
  lighthouse-core/scripts/dogfood-lhci.sh
  package.json
Labels: cla: yes

#9731 core(unused-css-rules): no more inifinity savings
  lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
  lighthouse-core/audits/byte-efficiency/unused-css-rules.js
  lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
  lighthouse-core/test/audits/byte-efficiency/unused-css-rules-test.js
Labels: cla: yes

#9491 core(tracehouse): structure main thread task creation to be more forgiving
  lighthouse-core/lib/tracehouse/main-thread-tasks.js
  lighthouse-core/test/lib/tracehouse/main-thread-tasks-test.js
Labels: 5.3, cla: yes

#9745 misc: support unset variables in lhci dogfood script
  lighthouse-core/scripts/dogfood-lhci.sh
Labels: cla: yes

#9743 docs(related-project): add lighthouse-ci-action
  readme.md
Labels: cla: yes, land-when-ci-is-green

#9737 tests: update report-wide utm_medium check for web.dev
  lighthouse-core/test/report/html/renderer/report-renderer-test.js
Labels: cla: yes

#9718 core(scriptelements): expose id attribute for ScriptElements
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
  lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
  lighthouse-core/gather/gatherers/script-elements.js
  lighthouse-core/test/results/artifacts/artifacts.json
  types/artifacts.d.ts
Labels: cla: yes, land-when-ci-is-green

#9540 core(audits): point perf audit description links to web.dev
  lighthouse-core/audits/bootup-time.js
  lighthouse-core/audits/byte-efficiency/efficient-animated-content.js
  lighthouse-core/audits/byte-efficiency/offscreen-images.js
  lighthouse-core/audits/byte-efficiency/render-blocking-resources.js
  lighthouse-core/audits/byte-efficiency/total-byte-weight.js
  lighthouse-core/audits/byte-efficiency/unminified-css.js
  lighthouse-core/audits/byte-efficiency/unminified-javascript.js
  lighthouse-core/audits/byte-efficiency/unused-css-rules.js
  lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
  lighthouse-core/audits/byte-efficiency/uses-optimized-images.js
  lighthouse-core/audits/byte-efficiency/uses-responsive-images.js
  lighthouse-core/audits/byte-efficiency/uses-text-compression.js
  lighthouse-core/audits/byte-efficiency/uses-webp-images.js
  lighthouse-core/audits/critical-request-chains.js
  lighthouse-core/audits/font-display.js
  lighthouse-core/audits/mainthread-work-breakdown.js
  lighthouse-core/audits/metrics/estimated-input-latency.js
  lighthouse-core/audits/metrics/first-contentful-paint.js
  lighthouse-core/audits/metrics/first-cpu-idle.js
  lighthouse-core/audits/metrics/first-meaningful-paint.js
  lighthouse-core/audits/metrics/interactive.js
  lighthouse-core/audits/metrics/speed-index.js
  lighthouse-core/audits/redirects.js
  lighthouse-core/audits/time-to-first-byte.js
  lighthouse-core/audits/user-timings.js
  lighthouse-core/audits/uses-rel-preconnect.js
  lighthouse-core/audits/uses-rel-preload.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes, land-when-ci-is-green

#9744 core(network-recorder): remove quic-request-finished workaround
  lighthouse-core/lib/network-recorder.js
  lighthouse-core/test/lib/network-recorder-test.js
Labels: cla: yes

#9758 clients(devtools): update references to Runtime.cachedResources
  build/build-dt-report-resources.js
  clients/devtools-report-assets.js
Labels: cla: yes

#9695 docs(releasing): add schedule, more explicit integration testing
  docs/releasing.md
Labels: cla: yes
