Repository GoogleChrome/lighthouse, pull requests merged in 2019-10, with the labels that each got.

#9761 docs(scoring): link to web.dev explainers
  docs/scoring.md
Labels: cla: yes

#9706 core(largest-contentful-paint): add new metric
  lighthouse-core/audits/metrics.js
  lighthouse-core/computed/metrics/lantern-first-meaningful-paint.js
  lighthouse-core/computed/metrics/largest-contentful-paint.js
  lighthouse-core/lib/lh-error.js
  lighthouse-core/lib/minify-trace.js
  lighthouse-core/lib/tracehouse/trace-processor.js
  lighthouse-core/test/audits/__snapshots__/metrics-test.js.snap
  lighthouse-core/test/audits/metrics-test.js
  lighthouse-core/test/computed/metrics/largest-contentful-paint-test.js
  lighthouse-core/test/computed/trace-of-tab-test.js
  lighthouse-core/test/fixtures/traces/lcp-m79.devtools.log.json
  lighthouse-core/test/fixtures/traces/lcp-m79.json
  lighthouse-core/test/lib/tracehouse/trace-processor-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
  types/artifacts.d.ts
Labels: 5.5, cla: yes

#9766 tests(lantern): attempt to download test set a few times
  lighthouse-core/scripts/test-lantern.sh
Labels: cla: yes

#9771 5.5.0
  changelog.md
  clients/extension/manifest.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  proto/sample_v2_round_trip.json
Labels: cla: yes

#9501 test(smokehouse): use static requires for test definitions
  lighthouse-cli/test/smokehouse/a11y/expectations.js
  lighthouse-cli/test/smokehouse/byte-config.js
  lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js
  lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
  lighthouse-cli/test/smokehouse/error-expectations.js
  lighthouse-cli/test/smokehouse/perf/expectations.js
  lighthouse-cli/test/smokehouse/perf/lantern-expectations.js
  lighthouse-cli/test/smokehouse/redirects/expectations.js
  lighthouse-cli/test/smokehouse/run-smoke.js
  lighthouse-cli/test/smokehouse/seo/expectations.js
  lighthouse-cli/test/smokehouse/smoke-test-dfns.js
  lighthouse-cli/test/smokehouse/smokehouse.js
  lighthouse-cli/test/smokehouse/tricky-metrics/expectations.js
  types/smokehouse.d.ts
Labels: cla: yes

#9723 misc: timings script
  .gitignore
  lighthouse-core/scripts/compare-timings.js
Labels: cla: yes

#9765 core(link-elements): ignore non-HTMLLinkElements
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
  lighthouse-cli/test/smokehouse/dbw-config.js
  lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
  lighthouse-core/gather/gatherers/link-elements.js
  types/artifacts.d.ts
Labels: cla: yes

#9782 core(optimized-images): log errors
  lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js
Labels: cla: yes

#9760 docs: update stale references to audits
  docs/configuration.md
  docs/readme.md
Labels: cla: yes

#9776 scripts: compare-timings.js --compare
  lighthouse-core/scripts/compare-timings.js
Labels: cla: yes

#9785 core(tracehouse): allow nested trace events without an end
  lighthouse-core/lib/tracehouse/main-thread-tasks.js
  lighthouse-core/test/lib/tracehouse/main-thread-tasks-test.js
Labels: cla: yes

#9802 i18n: import translations
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/vi.json
Labels: cla: yes, land-when-ci-is-green

#9800 report: remove some dead code
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/templates.html
Labels: cla: yes

#9804 core(seo): support korean in link-text audit
  lighthouse-core/audits/seo/link-text.js
Labels: cla: yes

#9787 docs(i18n): add 'meaning' to i18n README
  lighthouse-core/lib/i18n/README.md
Labels: cla: yes

#9728 report: update topbar logo
  lighthouse-core/report/html/templates.html
Labels: cla: yes

#9789 docs(related-projects): add the gradle lighthouse plugin
  readme.md
Labels: cla: yes

#9810 docs(related-projects): add the is-website-vulnerable CLI tool
  readme.md
Labels: cla: yes

#9753 docs(readme): add Lighthouse Check to related projects
  readme.md
Labels: cla: yes

#9772 misc: more releasing tweaks
  docs/releasing.md
  lighthouse-core/scripts/release/test.sh
Labels: cla: yes

#9818 core(image-elements): cache naturalSize results
  lighthouse-core/gather/gatherers/image-elements.js
Labels: cla: yes, land-when-ci-is-green

#9419 report: correct audit titles that should not be capitalized
  lighthouse-core/audits/critical-request-chains.js
  lighthouse-core/audits/third-party-summary.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes, land-when-ci-is-green

#9791 tests(build): use firehouse smoke test runner to test bundle
  .travis.yml
  build/tests/bundle-smoke-test.js
  build/tests/bundled-lighthouse-cli.js
  lighthouse-cli/test/smokehouse/firehouse.js
  lighthouse-core/lib/asset-saver.js
  package.json
  types/smokehouse.d.ts
Labels: cla: yes

#9821 misc: rewrite dom-size description
  lighthouse-core/audits/dobetterweb/dom-size.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/dobetterweb/dom-size-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes

#9596 report(viewer): minify inlined report-generator bundle
  build/build-bundle.js
  build/build-lightrider-bundles.js
  build/build-viewer.js
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green

#9480 core(errors-in-console): add ignoredPatterns option
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
  lighthouse-cli/test/smokehouse/dbw-config.js
  lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
  lighthouse-core/audits/errors-in-console.js
  lighthouse-core/test/audits/errors-in-console-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes

#9830 test(build): attempt bundle test three times in CI
  .travis.yml
Labels: cla: yes

#9823 misc(build): minify report javascript for lightrider report generator
  build/build-lightrider-bundles.js
  build/build-utils.js
  build/build-viewer.js
  package.json
Labels: cla: yes

#9831 core(driver): fix error handling for Runtime.evaluate
  lighthouse-core/gather/driver.js
Labels: cla: yes

#9828 clients(lr): don't include html report assets in bundle
  build/build-bundle.js
Labels: cla: yes

#9832 core: rename Element to LHElement
  lighthouse-core/gather/driver.js
  lighthouse-core/lib/lh-element.js
  lighthouse-core/test/gather/driver-test.js
  lighthouse-core/test/lib/lh-element-test.js
Labels: cla: yes

#9829 misc: warn on use of unrecognized audit options
  lighthouse-core/audits/errors-in-console.js
Labels: cla: yes

#9786 core(tracehouse): allow child to start <1ms before parent
  lighthouse-core/lib/tracehouse/main-thread-tasks.js
  lighthouse-core/test/lib/tracehouse/main-thread-tasks-test.js
Labels: cla: yes, land-when-ci-is-green

#9797 core(stack-packs): add angular, react, amp, and magento packs
  lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/stack-packs.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  proto/sample_v2_round_trip.json
  stack-packs/README.md
  stack-packs/index.js
  stack-packs/packs/amp.js
  stack-packs/packs/angular.js
  stack-packs/packs/magento.js
  stack-packs/packs/react.js
  yarn.lock
Labels: 6.0, cla: yes, land-when-ci-is-green

#9846 i18n(import): web.dev links and small corrections
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
Labels: cla: yes

#9781 core(gather): add new MainDocumentContent public artifact
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/smokehouse/dbw-config.js
  lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
  lighthouse-core/config/default-config.js
  lighthouse-core/gather/gatherers/main-document-content.js
  lighthouse-core/test/results/artifacts/artifacts.json
  types/artifacts.d.ts
Labels: cla: yes, land-when-ci-is-green

#9849 deps: update third-party-web to 0.11.0
  package.json
  yarn.lock
Labels: cla: yes

#9855 test(smokehouse): fix tmp dir usage
  lighthouse-cli/test/smokehouse/smokehouse.js
Labels: cla: yes

#9856 5.6.0
  changelog.md
  clients/extension/manifest.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  proto/sample_v2_round_trip.json
Labels: cla: yes

#9858 deps: remove mkdirp and make-dir for fs.mkdir
  build/build-bundle.js
  build/build-extension.js
  build/build-lightrider-bundles.js
  build/build-viewer.js
  build/tests/bundled-lighthouse-cli.js
  lighthouse-cli/test/smokehouse/smokehouse.js
  lighthouse-core/lib/asset-saver.js
  lighthouse-core/scripts/build-report-for-autodeployment.js
  package.json
  yarn.lock
Labels: cla: yes

#9850 core(audits): Link to Total Blocking Time documentation
  lighthouse-core/audits/metrics/total-blocking-time.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes, land-when-ci-is-green

#9866 misc: add chrome version field to bug report template
  .github/ISSUE_TEMPLATE/Bug_report.md
Labels: cla: yes

#9847 i18n: add localized-file matching replacements check
  lighthouse-core/scripts/i18n/assert-strings-collected.sh
Labels: cla: yes

#9814 core(lightwallet): adds computed/timing-summary.js (refactor)
  lighthouse-core/audits/metrics.js
  lighthouse-core/computed/metrics/timing-summary.js
  lighthouse-core/lib/traces/pwmetrics-events.js
  lighthouse-core/test/computed/metrics/timing-summary-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
  types/artifacts.d.ts
Labels: cla: yes

#9877 tests(viewer): don't override puppeteer's chromium
  .travis.yml
  lighthouse-viewer/test/viewer-test-pptr.js
Labels: cla: yes

#9879 misc: upgrade lhci dogfood script
  lighthouse-core/scripts/dogfood-lhci.sh
Labels: cla: yes, land-when-ci-is-green

#9871 i18n(lightwallet): centralize strings for metric names
  lighthouse-core/audits/metrics/estimated-input-latency.js
  lighthouse-core/audits/metrics/first-contentful-paint.js
  lighthouse-core/audits/metrics/first-cpu-idle.js
  lighthouse-core/audits/metrics/first-meaningful-paint.js
  lighthouse-core/audits/metrics/interactive.js
  lighthouse-core/audits/metrics/max-potential-fid.js
  lighthouse-core/audits/metrics/speed-index.js
  lighthouse-core/audits/metrics/total-blocking-time.js
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, land-when-ci-is-green

#9863 core(audits): link mpFID description to web.dev's mpFID doc
  lighthouse-core/audits/metrics/max-potential-fid.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes, land-when-ci-is-green

#9770 core(lightwallet): remove tolerance from timing budgets API
  lighthouse-cli/test/smokehouse/perf/perf-config.js
  lighthouse-core/config/budget.js
  lighthouse-core/test/config/budget-test.js
  lighthouse-core/test/fixtures/simple-budget.json
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample-config.js
  lighthouse-core/test/results/sample_v2.json
  types/budget.d.ts
Labels: 6.0, cla: yes, land-when-ci-is-green

#9859 misc: order changelog categories. add stable chrome note placeholder
  build/changelog-generator/index.js
  build/changelog-generator/templates/header.hbs
  build/changelog-generator/templates/template.hbs
  docs/releasing.md
Labels: cla: yes

#9889 misc: add note about LCP required chrome version
  lighthouse-core/computed/metrics/largest-contentful-paint.js
  lighthouse-core/lib/tracehouse/trace-processor.js
Labels: cla: yes

#9193 clients: retire extension; replace with PSI launcher
  build/build-bundle.js
  build/build-extension.js
  clients/extension/images/fail.svg
  clients/extension/images/lh_favicon_16x16.png
  clients/extension/images/lh_favicon_32x32.png
  clients/extension/images/lh_logo.svg
  clients/extension/images/lh_logo_128x128.png
  clients/extension/images/lh_logo_bg.png
  clients/extension/images/lh_logo_bg_no-light.png
  clients/extension/images/lh_logo_canary_bg.png
  clients/extension/images/lh_logo_canary_icon.png
  clients/extension/images/lh_logo_icon.png
  clients/extension/images/lh_logo_icon_light.png
  clients/extension/images/pass.svg
  clients/extension/images/verified.svg
  clients/extension/manifest.json
  clients/extension/popup.html
  clients/extension/scripts/extension-entry.js
  clients/extension/scripts/popup.js
  clients/extension/scripts/settings-controller.js
  clients/extension/styles/lighthouse-loading.css
  clients/extension/styles/lighthouse.css
  clients/test/extension/extension-test.js
  clients/test/extension/popup-test.js
  clients/test/extension/settings-controller-test.js
  lighthouse-core/gather/connections/extension.js
  lighthouse-core/gather/gather-runner.js
  package.json
Labels: cla: yes

#9895 core(lightwallet): refactor budget matching logic
  lighthouse-core/audits/performance-budget.js
  lighthouse-core/config/budget.js
  lighthouse-core/test/audits/performance-budget-test.js
  lighthouse-core/test/config/budget-test.js
Labels: cla: yes

#9888 core(stacks): match against js-lib-detector with id property
  lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
  lighthouse-core/lib/stack-collector.js
  package.json
  yarn.lock
Labels: cla: yes

#9896 core: refactor check for clearing cache
  lighthouse-core/gather/gather-runner.js
Labels: cla: yes
