Repository GoogleChrome/lighthouse, pull requests merged in 2019-04, with the labels that each got.

#7962 misc: specify types for some dependency-graph options objects
  lighthouse-core/computed/network-analysis.js
  lighthouse-core/lib/dependency-graph/simulator/connection-pool.js
  lighthouse-core/lib/dependency-graph/simulator/dns-cache.js
  lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js
  lighthouse-core/test/lib/dependency-graph/simulator/connection-pool-test.js
  lighthouse-core/test/lib/dependency-graph/simulator/dns-cache-test.js
Labels: 4.3

#8070 i18n: minor Hindi corrections
  lighthouse-core/lib/i18n/locales/hi.json
Labels: 4.3, i18n

#6750 core(jsonld): add structured data validation
  lighthouse-core/lib/sd-validation/assets/jsonldcontext.json
  lighthouse-core/lib/sd-validation/assets/schema-tree.json
  lighthouse-core/lib/sd-validation/helpers/walk-object.js
  lighthouse-core/lib/sd-validation/json-expander.js
  lighthouse-core/lib/sd-validation/json-linter.js
  lighthouse-core/lib/sd-validation/jsonld-keyword-validator.js
  lighthouse-core/lib/sd-validation/schema-validator.js
  lighthouse-core/lib/sd-validation/scripts/download-jsonldcontext.js
  lighthouse-core/lib/sd-validation/scripts/generate-schema-tree.js
  lighthouse-core/lib/sd-validation/sd-validation.js
  lighthouse-core/test/lib/sd-validation-test.js
  package.json
  types/isomorphic-fetch.d.ts
  types/jsonld/index.d.ts
  types/jsonlint-mod.d.ts
  types/structured-data.d.ts
  yarn.lock
Labels: waiting4reviewer

#7888 core: gather advanced LR timing statistics
  lighthouse-core/audits/network-requests.js
  lighthouse-core/lib/network-request.js
  lighthouse-core/test/lib/network-request-test.js
Labels: 4.3, waiting4reviewer

#7513 core(lantern): FCP improvements
  lighthouse-core/computed/metrics/lantern-first-contentful-paint.js
  lighthouse-core/computed/metrics/lantern-first-meaningful-paint.js
  lighthouse-core/lib/dependency-graph/cpu-node.js
  lighthouse-core/test/audits/__snapshots__/metrics-test.js.snap
  lighthouse-core/test/audits/__snapshots__/predictive-perf-test.js.snap
  lighthouse-core/test/audits/metrics/__snapshots__/first-meaningful-paint-test.js.snap
  lighthouse-core/test/audits/metrics/first-contentful-paint-3g-test.js
  lighthouse-core/test/computed/metrics/__snapshots__/estimated-input-latency-test.js.snap
  lighthouse-core/test/computed/metrics/__snapshots__/first-contentful-paint-test.js.snap
  lighthouse-core/test/computed/metrics/__snapshots__/first-meaningful-paint-test.js.snap
  lighthouse-core/test/computed/metrics/__snapshots__/lantern-estimated-input-latency-test.js.snap
  lighthouse-core/test/computed/metrics/__snapshots__/lantern-first-contentful-paint-test.js.snap
  lighthouse-core/test/computed/metrics/__snapshots__/lantern-first-meaningful-paint-test.js.snap
  lighthouse-core/test/computed/metrics/first-meaningful-paint-test.js
  lighthouse-core/test/computed/metrics/lantern-first-meaningful-paint-test.js
  lighthouse-core/test/fixtures/lantern-master-computed-values.json
Labels: 5.0

#8117 misc: drop support for Node before 10.13 (LTS)
  .appveyor.yml
  .travis.yml
  docs/headless-chrome.md
  lighthouse-cli/run.js
  lighthouse-core/gather/connections/cri.js
  lighthouse-core/lib/asset-saver.js
  lighthouse-core/lib/i18n/en-US.json
  lighthouse-core/lib/lh-error.js
  lighthouse-core/scripts/update-report-fixtures.js
  package.json
  proto/lighthouse-result.proto
  readme.md
  types/externs.d.ts
  yarn.lock
Labels: 5.0

#7241 core(dom-size): collect only body nodes for DOM stats
  lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
  lighthouse-core/audits/dobetterweb/dom-size.js
  lighthouse-core/gather/gatherers/dobetterweb/domstats.js
  lighthouse-core/lib/i18n/en-US.json
  lighthouse-core/test/audits/dobetterweb/dom-size-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
  types/artifacts.d.ts
Labels: 5.0, i18n

#7547 core(seo): support spanish in link-text audit
  lighthouse-core/audits/seo/link-text.js
Labels: needs-discussion

#8197 client(lr): add lightrider report-generator
  build/build-lightrider-bundles.js
  clients/lightrider/lightrider-entry.js
  clients/test/lightrider-entry-test.js
  lighthouse-core/lib/file-namer.js
  lighthouse-core/report/report-generator.js
  package.json
Labels: waiting4reviewer

#8229 report(redesign): runtime settings footer
  lighthouse-core/report/html/renderer/report-renderer.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/report/html/templates.html
Labels: 5.0

#6704 fix(audit): iframe with redirect shouldn't be marked as critical
  lighthouse-core/computed/critical-request-chains.js
  lighthouse-core/test/computed/critical-request-chains-test.js
Labels: land-when-ci-is-green

#8300 report: sticky topbar
  lighthouse-core/report/html/renderer/report-renderer.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/report/html/templates.html
  lighthouse-core/test/report/html/renderer/report-renderer-test.js
Labels: 5.0

#8378 i18n: update seo group titles and descriptions
  lighthouse-core/config/default-config.js
  lighthouse-core/lib/i18n/en-US.json
  lighthouse-core/test/results/sample_v2.json
Labels: i18n

#8329 report(redesign): remove icons from non-pwa group headings
  lighthouse-core/report/html/report-styles.css
Labels: 5.0

#5504 core: enable async stacks
  lighthouse-core/computed/page-dependency-graph.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/test/computed/page-dependency-graph-test.js
  lighthouse-core/test/gather/fake-driver.js
  lighthouse-core/test/gather/gather-runner-test.js
Labels: 5.0

#8350 clients(lr): increase Page.getAppManifest timeout to 10s
  lighthouse-core/gather/driver.js
Labels: land-when-ci-is-green

#8307 report: plugin badge for plugin score gauges
  lighthouse-core/report/html/renderer/category-renderer.js
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/report/html/templates.html
  lighthouse-core/scripts/build-report-for-autodeployment.js
  lighthouse-core/test/report/html/renderer/category-renderer-test.js
  lighthouse-core/test/report/html/renderer/psi-test.js
  lighthouse-core/test/report/html/renderer/report-renderer-test.js
  lighthouse-core/test/report/report-generator-test.js
Labels: 5.0

#8222 report(redesign): score icons, audit group headers, colors
  lighthouse-core/report/html/report-styles.css
Labels: 5.0

#8425 report(redesign): dark theme
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/report/html/templates.html
Labels: land-when-ci-is-green

#6351 report(third party): filter out third party urls
  lighthouse-core/audits/seo/canonical.js
  lighthouse-core/lib/i18n/en-US.json
  lighthouse-core/lib/url-shim.js
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/report/html/templates.html
  lighthouse-core/test/lib/url-shim-test.js
  lighthouse-core/test/report/html/renderer/details-renderer-test.js
  lighthouse-core/test/report/html/renderer/report-ui-features-test.js
  lighthouse-core/test/report/html/renderer/util-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/lighthouse-result.proto
  proto/sample_v2_round_trip.json
Labels: 5.0, P1, land-when-ci-is-green
