Repository GoogleChrome/lighthouse, pull requests merged in 2019-06, with the labels that each got.

#9088 core(manifest-parser): handle blob manifests
  lighthouse-core/lib/manifest-parser.js
  lighthouse-core/test/lib/manifest-parser-test.js
Labels: cla: no

#8985 devtools: rename audits2 to audits
  clients/devtools-report-assets.js
  lighthouse-core/report/html/readme.md
  lighthouse-core/scripts/compile-against-devtools.sh
  lighthouse-core/scripts/roll-to-devtools.sh
Labels: cla: yes

#9083 docs(readme): Add gimbal integration
  readme.md
Labels: cla: yes

#8865 core(driver): security errors are no longer a fatal or pageload error
  lighthouse-cli/test/smokehouse/error-expectations.js
  lighthouse-core/gather/driver.js
  lighthouse-core/test/gather/driver-test.js
Labels: cla: yes

#9110 docs(readme): alphabetize related projects
  readme.md
Labels: cla: yes

#9112 docs: add instructions for testing with self-signed certificate
  docs/readme.md
Labels: cla: yes

#9109 core(cli): accept flags from path
  lighthouse-cli/cli-flags.js
  lighthouse-cli/test/cli/cli-flags-test.js
  lighthouse-cli/test/fixtures/cli-flags-path.json
  readme.md
Labels: cla: yes

#9111 misc: address release script feedback
  docs/releasing.md
  lighthouse-core/scripts/release/clean-pristine.sh
  lighthouse-core/scripts/release/prepare-commit.sh
  lighthouse-core/scripts/release/test.sh
Labels: cla: yes

#8975 new_audit: add TTI Companion Metric to JSON
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/audits/metrics.js
  lighthouse-core/audits/metrics/cumulative-long-queuing-delay.js
  lighthouse-core/computed/metrics/cumulative-long-queuing-delay.js
  lighthouse-core/computed/metrics/lantern-cumulative-long-queuing-delay.js
  lighthouse-core/config/default-config.js
  lighthouse-core/test/audits/__snapshots__/metrics-test.js.snap
  lighthouse-core/test/audits/metrics/cumulative-long-queuing-delay-test.js
  lighthouse-core/test/computed/metrics/cumulative-long-queuing-delay-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: no

#9056 core(perf): speed up tap-target's isVisible()
  lighthouse-cli/test/fixtures/seo/seo-tap-targets.html
  lighthouse-cli/test/smokehouse/seo/expectations.js
  lighthouse-core/gather/gatherers/seo/tap-targets.js
  lighthouse-core/lib/page-functions.js
Labels: cla: no

#9123 misc: update tracing-processor require
  lighthouse-core/computed/metrics/cumulative-long-queuing-delay.js
Labels: cla: yes

#9121 core(gather-runner): convert PAGE_HUNG to non-fatal runtimeError
  clients/extension/scripts/popup.js
  lighthouse-cli/run.js
  lighthouse-cli/test/smokehouse/error-expectations.js
  lighthouse-cli/test/smokehouse/smokehouse-report.js
  lighthouse-cli/test/smokehouse/smokehouse.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gather-runner.js
  types/smokehouse.d.ts
Labels: cla: yes

#9131 deps: bump transitive dep js-yaml
  yarn.lock
Labels: cla: yes

#9130 tests(smokehouse): always assert lhr.runtimeError
  lighthouse-cli/test/smokehouse/error-config.js
  lighthouse-cli/test/smokehouse/error-expectations.js
  lighthouse-cli/test/smokehouse/seo/expectations.js
  lighthouse-cli/test/smokehouse/smokehouse-report.js
  lighthouse-cli/test/smokehouse/smokehouse.js
  lighthouse-core/lib/asset-saver.js
  lighthouse-core/runner.js
  lighthouse-core/scripts/update-report-fixtures.js
  types/smokehouse.d.ts
Labels: cla: yes

#9060 core(gather-runner): always reset scroll position
  lighthouse-core/config/default-config.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/test/gather/driver-test.js
  lighthouse-core/test/gather/fake-driver.js
  lighthouse-core/test/gather/gather-runner-test.js
Labels: cla: yes

#9079 core(page-functions): don't try to clone a ShadowRoot
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
  lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
  lighthouse-core/lib/page-functions.js
  lighthouse-core/test/lib/page-functions-test.js
Labels: cla: yes, land-when-ci-is-green

#9144 report: remove unused css vars
  lighthouse-core/report/html/report-styles.css
Labels: cla: yes

#9127 i18n: perf-budget and res-summary column headers
  lighthouse-core/audits/network-requests.js
  lighthouse-core/audits/performance-budget.js
  lighthouse-core/audits/resource-summary.js
  lighthouse-core/lib/i18n/en-US.json
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, i18n

#9135 report: rename exports to tools
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/report/html/templates.html
  lighthouse-viewer/app/src/viewer-ui-features.js
  lighthouse-viewer/app/styles/viewer.css
Labels: cla: yes

#9161 docs(readme): related project: lighthouse-persist
  readme.md
Labels: cla: yes

#9169 report: make tools menu focus-able
  lighthouse-core/report/html/templates.html
Labels: cla: yes

#9016 proto: update processForProto method signature, string -> LH.Result
  clients/lightrider/lightrider-entry.js
  lighthouse-core/lib/proto-preprocessor.js
  lighthouse-core/test/lib/proto-preprocessor-test.js
  lighthouse-core/test/report/proto-test.js
Labels: cla: no, land-when-ci-is-green

#9173 report: only print light theme
  lighthouse-core/report/html/report-styles.css
Labels: cla: yes

#9151 report: ensure SVG elements in <defs> have unique ids
  lighthouse-core/report/html/renderer/pwa-category-renderer.js
  lighthouse-core/report/html/templates.html
  lighthouse-core/test/report/html/renderer/pwa-category-renderer-test.js
Labels: cla: yes

#9186 report: position sticky-header highlighter with css grid
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/templates.html
Labels: cla: yes

#9157 report(devtools): enable report features
  build/build-dt-report-resources.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/templates.html
Labels: cla: yes

#9188 report: update permalink calculations for correct hash nav scroll position
  lighthouse-core/report/html/report-styles.css
Labels: cla: yes

#9172 docs(readme): related project: lighthouse-jest-example
  readme.md
Labels: cla: no

#9171 i18n: add es-419
  lighthouse-core/lib/i18n/locales.js
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/pt.json
  types/externs.d.ts
Labels: cla: yes

#9158 docs(readme): update lighthouse-mocha-example repo and description
  readme.md
Labels: cla: yes

#9176 core(gather-runner): detect Chrome interstitials
  lighthouse-cli/test/smokehouse/error-expectations.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/lib/i18n/en-US.json
  lighthouse-core/lib/lh-error.js
  lighthouse-core/test/gather/gather-runner-test.js
Labels: cla: yes

#9148 core(font-display): limit false positives
  lighthouse-core/audits/font-display.js
  lighthouse-core/lib/i18n/en-US.json
  lighthouse-core/test/audits/font-display-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: no

#9201 report: add aria-labels to tools button and metric toggle
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/report/html/templates.html
Labels: cla: yes

#9202 misc: use `CHROME_PATH` variable in CI and scripts
  .appveyor.yml
  lighthouse-core/scripts/download-chrome.sh
Labels: cla: yes

#9225 docs: change score type from 'string' to 'number'
  docs/understanding-results.md
Labels: cla: yes

#9217 misc: suggest uploading issue repro
  .github/ISSUE_TEMPLATE/Bug_report.md
Labels: cla: no

#9149 report: create naming convention for css variables
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/report/html/templates.html
Labels: cla: yes

#9227 tests: clean up crufty gather-runner tests
  lighthouse-core/test/gather/gather-runner-test.js
Labels: cla: yes

#9198 core(gather-runner): don't save trace on pass with pageLoadError
  lighthouse-cli/test/smokehouse/seo/expectations.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/test/gather/gather-runner-test.js
Labels: cla: yes

#9226 docs: update understanding-results.md
  docs/understanding-results.md
Labels: cla: yes

#9174 core(tracehouse): allow missing FCP
  lighthouse-core/computed/trace-of-tab.js
  lighthouse-core/lib/tracehouse/trace-processor.js
  lighthouse-core/test/lib/tracehouse/trace-processor-test.js
Labels: cla: yes

#9237 report: allow CRC to use renderTextUrl
  lighthouse-core/report/html/renderer/crc-details-renderer.js
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/report/html/templates.html
  lighthouse-core/test/report/html/renderer/crc-details-renderer-test.js
Labels: cla: yes

#9243 docs(readme): add Exthouse - ext perf analyzer
  readme.md
Labels: cla: yes

#9246 deps: remove commitizen as local dep
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green

#9236 core(gather-runner): add PageLoadError base artifact
  lighthouse-cli/test/smokehouse/error-config.js
  lighthouse-cli/test/smokehouse/error-expectations.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/runner.js
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/runner-test.js
  types/artifacts.d.ts
Labels: cla: yes

#9274 clients(devtools): unset overflow in print
  lighthouse-core/report/html/report-styles.css
Labels: cla: yes, land-when-ci-is-green

#8755 i18n: introduce script to swap in new locale to LHR
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/lib/i18n/swap-locale.js
  lighthouse-core/test/lib/i18n/swap-locale-test.js
  package.json
  types/lhr.d.ts
  yarn.lock
Labels: cla: yes

#9067 new_audit: add third party entity summary
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/audits/bootup-time.js
  lighthouse-core/audits/third-party-summary.js
  lighthouse-core/config/default-config.js
  lighthouse-core/lib/i18n/en-US.json
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/test/audits/third-party-summary-test.js
  lighthouse-core/test/report/html/renderer/details-renderer-test.js
  lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
  lighthouse-core/test/results/sample_v2.json
  package.json
  proto/sample_v2_round_trip.json
  types/audit-details.d.ts
  yarn.lock
Labels: cla: yes

#9092 i18n: localize audits in best-practices
  lighthouse-core/audits/deprecations.js
  lighthouse-core/audits/dobetterweb/appcache-manifest.js
  lighthouse-core/audits/dobetterweb/doctype.js
  lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js
  lighthouse-core/audits/dobetterweb/geolocation-on-start.js
  lighthouse-core/audits/dobetterweb/js-libraries.js
  lighthouse-core/audits/dobetterweb/no-document-write.js
  lighthouse-core/audits/dobetterweb/no-vulnerable-libraries.js
  lighthouse-core/audits/dobetterweb/notification-on-start.js
  lighthouse-core/audits/dobetterweb/password-inputs-can-be-pasted-into.js
  lighthouse-core/audits/dobetterweb/uses-http2.js
  lighthouse-core/audits/dobetterweb/uses-passive-event-listeners.js
  lighthouse-core/audits/errors-in-console.js
  lighthouse-core/audits/image-aspect-ratio.js
  lighthouse-core/audits/is-on-https.js
  lighthouse-core/config/default-config.js
  lighthouse-core/lib/i18n/en-US.json
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/test/audits/deprecations-test.js
  lighthouse-core/test/audits/dobetterweb/doctype-test.js
  lighthouse-core/test/audits/dobetterweb/no-vulnerable-libraries-test.js
  lighthouse-core/test/audits/dobetterweb/uses-http2-test.js
  lighthouse-core/test/audits/is-on-https-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: no, i18n

#9280 misc(build): generate report variants in deployment
  .build-for-now.sh
  lighthouse-core/runner.js
  lighthouse-core/scripts/build-report-for-autodeployment.js
  now.json
  package.json
Labels: cla: yes, land-when-ci-is-green

#9275 misc: add .idea folder to .gitignore file
  .gitignore
Labels: cla: yes

#9244 misc: fix typo in performance-budget smoke test
  lighthouse-cli/test/fixtures/perf/perf-budgets/load-things.html
  lighthouse-cli/test/smokehouse/perf/expectations.js
Labels: cla: yes

#9271 report: center and style top-level runtimeError
  lighthouse-core/report/html/report-styles.css
Labels: cla: yes

#9192 i18n: enable local debug locale, en-XL
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/lib/i18n/locales.js
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/scripts/i18n/collect-strings.js
  types/externs.d.ts
Labels: cla: yes, i18n

#9293 misc: yarn static-server
  package.json
Labels: cla: yes

#9284 core(config): assert all audit requiredArtifacts will be gathered
  lighthouse-core/config/config.js
  lighthouse-core/lib/i18n/en-US.json
  lighthouse-core/lib/lh-error.js
  lighthouse-core/runner.js
  lighthouse-core/test/config/config-test.js
Labels: cla: yes

#9290 misc(runner): add assertion for devtoolsLog as requiredArtifact
  lighthouse-core/runner.js
  lighthouse-core/test/runner-test.js
Labels: cla: yes

#9295 misc: remove duplicate colon from regex
  lighthouse-core/lib/file-namer.js
Labels: cla: yes

#9291 misc: localize logged GatherRunner error
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/lib/i18n/i18n-test.js
Labels: cla: yes

#9273 report: use css grid for metrics
  lighthouse-core/report/html/report-styles.css
Labels: cla: yes

#9224 report: make urls clickable
  lighthouse-core/report/html/renderer/crc-details-renderer.js
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/report/html/templates.html
  lighthouse-core/test/report/html/renderer/crc-details-renderer-test.js
  lighthouse-core/test/report/html/renderer/details-renderer-test.js
  lighthouse-core/test/report/html/renderer/report-ui-features-test.js
Labels: cla: no

#9283 misc(build): create error-y LHR for the deploy
  lighthouse-core/scripts/build-report-for-autodeployment.js
Labels: cla: yes
