Repository GoogleChrome/lighthouse, pull requests merged in 2019-07, with the labels that each got.

#9301 report: remove unnecessary attribute in svg
  lighthouse-core/report/html/templates.html
Labels: cla: yes

#9309 deps(intl): move from devDep to dep
  package.json
Labels: cla: yes

#9312 deps(brfs): upgrade to 2.0.2 to resolve source map debug issue
  build/build-bundle.js
  package.json
  yarn.lock
Labels: cla: yes

#9314 tests: improve drag-and-drop coverage
  lighthouse-viewer/test/drag-and-drop-test.js
Labels: cla: yes

#9334 core: localize invalid URL error message
  lighthouse-core/index.js
  lighthouse-core/runner.js
  lighthouse-core/test/index-test.js
  lighthouse-core/test/runner-test.js
Labels: cla: yes

#9338 misc(build): adjust deployment filenames
  lighthouse-core/scripts/build-report-for-autodeployment.js
Labels: cla: yes

#9292 tests(smokehouse): assert on expected array length
  lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js
  lighthouse-cli/test/smokehouse/error-expectations.js
  lighthouse-cli/test/smokehouse/smokehouse-report.js
Labels: cla: yes

#9339 deps: chrome-launcher@0.11.1
  lighthouse-core/scripts/manual-chrome-launcher.js
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green

#9299 report: show disabled checkbox when all/no urls are third-party
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/templates.html
  lighthouse-core/test/report/html/renderer/report-ui-features-test.js
Labels: cla: yes

#9340 core(domstats): support an empty html body
  lighthouse-core/gather/gatherers/dobetterweb/domstats.js
Labels: cla: yes

#9343 deps: axe-core@3.3.0
  lighthouse-cli/test/smokehouse/a11y/expectations.js
  lighthouse-core/gather/gatherers/accessibility.js
  package.json
  yarn.lock
Labels: cla: yes

#9347 deps: update outdated transitive deps
  yarn.lock
Labels: cla: yes

#9248 tests(tags-blocking-first-paint): alternate stylesheets are not blocking
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
  lighthouse-cli/test/fixtures/dobetterweb/empty.css
  lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
Labels: cla: yes

#9344 clients(devtools): audits2 -> audits1 and defer reading resources
  clients/devtools-report-assets.js
  lighthouse-core/scripts/roll-to-devtools.sh
Labels: cla: yes

#9357 deps: update to typescript 3.5.3
  lighthouse-core/computed/network-analysis.js
  lighthouse-core/config/config.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/lib/lantern-trace-saver.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/runner.js
  lighthouse-core/scripts/update-report-fixtures.js
  lighthouse-viewer/app/src/lighthouse-report-viewer.js
  package.json
  types/externs.d.ts
  yarn.lock
Labels: cla: yes

#9362 tests: run CI with a frozen yarn.lock
  .travis.yml
Labels: cla: yes

#9361 docs: add i18n overview & authoring documentation
  lighthouse-core/lib/i18n/README.md
Labels: cla: yes, land-when-ci-is-green

#9267 deps: update to open from opn
  docs/readme.md
  lighthouse-cli/run.js
  package.json
  yarn.lock
Labels: cla: yes

#9363 core(font-size): comment why source = Other happens
  lighthouse-core/audits/seo/font-size.js
Labels: cla: yes

#9356 audits(font-size): calculate accurate line/column for inline styles
  lighthouse-cli/test/fixtures/seo/seo-tester-styles.css
  lighthouse-cli/test/fixtures/seo/seo-tester.html
  lighthouse-cli/test/smokehouse/seo/expectations.js
  lighthouse-core/audits/seo/font-size.js
Labels: cla: yes

#9384 tests(i18n): no ICU value given to preprocess
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/test/lib/i18n/i18n-test.js
Labels: cla: no

#9388 core: fix serverResponseTime typo in network-server-latency
  lighthouse-core/audits/network-server-latency.js
  lighthouse-core/test/audits/network-server-latency-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes

#9404 misc: fix yarn.lock and translations master drift
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
  yarn.lock
Labels: cla: yes

#9398 deps(logger): debug@2.6.9
  lighthouse-logger/package.json
  lighthouse-logger/yarn.lock
Labels: cla: yes

#9400 tests(font-size): add test for attributing styles to node
  lighthouse-core/gather/gatherers/seo/font-size.js
  lighthouse-core/test/audits/seo/font-size-test.js
  types/artifacts.d.ts
Labels: cla: yes

#9411 docs: fix typo
  docs/architecture.md
  docs/understanding-results.md
  docs/variability.md
Labels: cla: yes

#9238 report: full bleed image thumbnails
  lighthouse-core/report/html/report-styles.css
Labels: cla: yes

#9355 report: add perf score explanation and link
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/config/default-config.js
  lighthouse-core/lib/i18n/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: 5.2, cla: yes

#9397 core: support saving and loading error artifacts
  lighthouse-core/lib/asset-saver.js
  lighthouse-core/lib/lh-error.js
  lighthouse-core/test/lib/asset-saver-test.js
  lighthouse-core/test/runner-test.js
Labels: cla: yes

#9308 tests(snyk): assert upper bounds
  lighthouse-core/test/audits/dobetterweb/no-vulnerable-libraries-test.js
Labels: cla: yes

#9422 report(accessibility): add heading role to report category gauges
  lighthouse-core/report/html/templates.html
Labels: cla: yes

#9434 misc: nest deployed-report directory
  lighthouse-core/scripts/build-report-for-autodeployment.js
  now.json
Labels: cla: yes

#9413 tests(font-size): assert on source
  lighthouse-core/test/audits/seo/font-size-test.js
Labels: cla: yes

#9409 core(tbt): Clean up total blocking time code
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/audits/metrics.js
  lighthouse-core/audits/metrics/total-blocking-time.js
  lighthouse-core/computed/metrics/lantern-total-blocking-time.js
  lighthouse-core/computed/metrics/total-blocking-time.js
  lighthouse-core/config/default-config.js
  lighthouse-core/lib/i18n/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/__snapshots__/metrics-test.js.snap
  lighthouse-core/test/audits/metrics/total-blocking-time-test.js
  lighthouse-core/test/computed/metrics/cumulative-long-queuing-delay-test.js
  lighthouse-core/test/computed/metrics/total-blocking-time-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: 5.3, cla: yes

#9441 tests: relax contrast font size expectation
  lighthouse-cli/test/smokehouse/a11y/expectations.js
Labels: cla: yes

#9440 docs: link to good first issues
  CONTRIBUTING.md
Labels: cla: yes

#9439 report: fix explanation rendering
  lighthouse-core/audits/seo/font-size.js
  lighthouse-core/lib/i18n/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/test/audits/seo/font-size-test.js
Labels: cla: yes

#9410 clients(lightrider): serialize errors in artifacts
  clients/lightrider/lightrider-entry.js
  clients/test/lightrider-entry-test.js
  lighthouse-core/lib/asset-saver.js
Labels: cla: yes

#9442 v5.2.0
  changelog.md
  clients/extension/manifest.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  proto/sample_v2_round_trip.json
Labels: cla: yes

#9449 misc: add note about global.URL in node 10
  lighthouse-core/lib/url-shim.js
Labels: cla: yes

#9114 i18n: placeholders
  .gitignore
  lighthouse-core/audits/byte-efficiency/unminified-css.js
  lighthouse-core/audits/dobetterweb/appcache-manifest.js
  lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js
  lighthouse-core/audits/dobetterweb/js-libraries.js
  lighthouse-core/audits/font-display.js
  lighthouse-core/audits/image-aspect-ratio.js
  lighthouse-core/audits/resource-summary.js
  lighthouse-core/audits/seo/canonical.js
  lighthouse-core/audits/seo/robots-txt.js
  lighthouse-core/audits/seo/tap-targets.js
  lighthouse-core/audits/user-timings.js
  lighthouse-core/audits/uses-rel-preconnect.js
  lighthouse-core/audits/uses-rel-preload.js
  lighthouse-core/lib/i18n/README.md
  lighthouse-core/lib/i18n/en-US.json
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/lib/i18n/locales.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/lh-error.js
  lighthouse-core/scripts/i18n/assert-strings-collected.sh
  lighthouse-core/scripts/i18n/bake-ctc-to-lhl.js
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/test/results/sample_v2.json
  lighthouse-core/test/scripts/i18n/bake-ctc-to-lhl-test.js
  lighthouse-core/test/scripts/i18n/collect-strings-test.js
  package.json
  proto/sample_v2_round_trip.json
Labels: cla: yes, i18n

#9414 core(font-size): gather style declaration of type Attributes
  lighthouse-core/gather/gatherers/seo/font-size.js
  lighthouse-core/test/gather/gatherers/seo/font-size-test.js
Labels: cla: yes

#9101 core: gather source maps
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gatherers/source-maps.js
  lighthouse-core/test/gather/driver-test.js
  lighthouse-core/test/gather/gatherers/source-maps-test.js
  lighthouse-core/test/gather/mock-commands.js
  types/artifacts.d.ts
Labels: cla: yes

#9084 core(audits): Point a11y audit links to web.dev
  lighthouse-core/audits/accessibility/accesskeys.js
  lighthouse-core/audits/accessibility/aria-allowed-attr.js
  lighthouse-core/audits/accessibility/aria-required-attr.js
  lighthouse-core/audits/accessibility/aria-required-children.js
  lighthouse-core/audits/accessibility/aria-required-parent.js
  lighthouse-core/audits/accessibility/aria-roles.js
  lighthouse-core/audits/accessibility/aria-valid-attr-value.js
  lighthouse-core/audits/accessibility/aria-valid-attr.js
  lighthouse-core/audits/accessibility/audio-caption.js
  lighthouse-core/audits/accessibility/button-name.js
  lighthouse-core/audits/accessibility/bypass.js
  lighthouse-core/audits/accessibility/color-contrast.js
  lighthouse-core/audits/accessibility/definition-list.js
  lighthouse-core/audits/accessibility/dlitem.js
  lighthouse-core/audits/accessibility/document-title.js
  lighthouse-core/audits/accessibility/duplicate-id.js
  lighthouse-core/audits/accessibility/frame-title.js
  lighthouse-core/audits/accessibility/html-has-lang.js
  lighthouse-core/audits/accessibility/html-lang-valid.js
  lighthouse-core/audits/accessibility/image-alt.js
  lighthouse-core/audits/accessibility/input-image-alt.js
  lighthouse-core/audits/accessibility/label.js
  lighthouse-core/audits/accessibility/layout-table.js
  lighthouse-core/audits/accessibility/link-name.js
  lighthouse-core/audits/accessibility/list.js
  lighthouse-core/audits/accessibility/listitem.js
  lighthouse-core/audits/accessibility/manual/custom-controls-labels.js
  lighthouse-core/audits/accessibility/manual/custom-controls-roles.js
  lighthouse-core/audits/accessibility/manual/focus-traps.js
  lighthouse-core/audits/accessibility/manual/focusable-controls.js
  lighthouse-core/audits/accessibility/manual/heading-levels.js
  lighthouse-core/audits/accessibility/manual/interactive-element-affordance.js
  lighthouse-core/audits/accessibility/manual/logical-tab-order.js
  lighthouse-core/audits/accessibility/manual/managed-focus.js
  lighthouse-core/audits/accessibility/manual/offscreen-content-hidden.js
  lighthouse-core/audits/accessibility/manual/use-landmarks.js
  lighthouse-core/audits/accessibility/manual/visual-order-follows-dom.js
  lighthouse-core/audits/accessibility/meta-refresh.js
  lighthouse-core/audits/accessibility/meta-viewport.js
  lighthouse-core/audits/accessibility/object-alt.js
  lighthouse-core/audits/accessibility/tabindex.js
  lighthouse-core/audits/accessibility/td-headers-attr.js
  lighthouse-core/audits/accessibility/th-has-data-cells.js
  lighthouse-core/audits/accessibility/valid-lang.js
  lighthouse-core/audits/accessibility/video-caption.js
  lighthouse-core/audits/accessibility/video-description.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes

#9454 i18n: corrections for es-419, fr, id, zh-TW
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
Labels: cla: yes

#9406 misc: refactor collect-strings.js to use glob and work on windows
  lighthouse-core/scripts/i18n/collect-strings.js
Labels: cla: yes

#9461 i18n: align type names with docs
  lighthouse-core/audits/dobetterweb/appcache-manifest.js
  lighthouse-core/audits/seo/canonical.js
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/lib/i18n/locales.js
  lighthouse-core/lib/i18n/swap-locale.js
  lighthouse-core/scripts/i18n/bake-ctc-to-lhl.js
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/test/scripts/i18n/collect-strings-test.js
Labels: cla: yes

#9465 deps: update jsonlint-mod to 1.7.5
  package.json
  yarn.lock
Labels: cla: yes

#9446 core(seo): support portuguese in link-text audit
  lighthouse-core/audits/seo/link-text.js
Labels: cla: yes

#9421 tests(report): add axe-core validation of report output
  lighthouse-core/test/report/html/renderer/report-renderer-test.js
Labels: cla: yes

#9479 core(unused-css): allow up to 10KB of unused CSS per file
  lighthouse-cli/test/fixtures/byte-efficiency/tester.html
  lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js
  lighthouse-core/audits/byte-efficiency/unused-css-rules.js
  lighthouse-core/test/audits/byte-efficiency/unused-css-rules-test.js
Labels: cla: yes

#9399 doc(cli): list valid categories
  lighthouse-cli/cli-flags.js
  readme.md
Labels: cla: yes, land-when-ci-is-green
