Repository GoogleChrome/lighthouse, pull requests merged in 2019-05, with the labels that each got.

#8817 misc: expand FID -> First Input Delay
  lighthouse-core/audits/metrics/max-potential-fid.js
  lighthouse-core/lib/i18n/en-US.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: land-when-ci-is-green

#8802 tests: partial artifact update
  CONTRIBUTING.md
  lighthouse-core/scripts/update-report-fixtures.js
  lighthouse-core/test/results/artifacts/artifacts.json
Labels: land-when-ci-is-green

#8854 docs: update throttling
  docs/throttling.md
Labels: land-when-ci-is-green

#8867 misc(proto): require protobuf 3.7.1, add stricter audit details test
  lighthouse-core/test/report/proto-test.js
  package.json
Labels: P0

#8803 tests: add tap targets to dobetterweb sample page
  CONTRIBUTING.md
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
  lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
  lighthouse-core/scripts/update-report-fixtures.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: land-when-ci-is-green

#8844 report: metric toggle without JS
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/report/html/templates.html
  lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
  lighthouse-core/test/report/html/renderer/report-ui-features-test.js
Labels: P0

#8853 tests(lightwallet): add perf-budget smoke test
  lighthouse-cli/test/fixtures/perf/perf-budgets/big-script.js
  lighthouse-cli/test/fixtures/perf/perf-budgets/load-things.html
  lighthouse-cli/test/smokehouse/perf/expectations.js
  lighthouse-cli/test/smokehouse/perf/perf-config.js
  lighthouse-cli/test/smokehouse/smoke-test-dfns.js
  lighthouse-cli/test/smokehouse/smokehouse-report.js
Labels: P1

#8870 tests(lightwallet): add budget to golden LHR
  lighthouse-core/scripts/assert-golden-lhr-unchanged.sh
  lighthouse-core/scripts/update-report-fixtures.js
  lighthouse-core/test/report/html/renderer/report-renderer-test.js
  lighthouse-core/test/results/sample-config.js
  lighthouse-core/test/results/sample_v2.json
  package.json
  proto/sample_v2_round_trip.json
Labels: land-when-ci-is-green

#8843 report(redesign): toggle dark theme in menu
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/report/html/templates.html
Labels: P1, land-when-ci-is-green

#8785 report(redesign): design review feedback
  lighthouse-core/report/html/renderer/category-renderer.js
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/report/html/templates.html
Labels: P0, land-when-ci-is-green

#8871 docs: update budget link
  lighthouse-core/audits/performance-budget.js
  lighthouse-core/audits/resource-summary.js
  lighthouse-core/lib/i18n/en-US.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: land-when-ci-is-green

#8857 audit: add apple-touch-icon audit
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/smokehouse/pwa-expectations.js
  lighthouse-cli/test/smokehouse/pwa2-expectations.js
  lighthouse-cli/test/smokehouse/pwa3-expectations.js
  lighthouse-core/audits/apple-touch-icon.js
  lighthouse-core/config/default-config.js
  lighthouse-core/lib/i18n/en-US.json
  lighthouse-core/test/audits/apple-touch-icon-test.js
  lighthouse-core/test/report/html/renderer/category-renderer-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: P0, new_audit

#8708 report(lightwallet): render performance-budget section
  clients/test/extension/extension-test.js
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/config/default-config.js
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/report/html/templates.html
  lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
  lighthouse-core/test/report/html/renderer/report-renderer-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: P0

#8891 report(redesign): metrics padding, font weights
  lighthouse-core/report/html/report-styles.css
Labels: P0

#8842 report(redesign): respect prefers-color-scheme
  lighthouse-core/report/html/renderer/report-renderer.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/test/report/html/renderer/report-renderer-test.js
  lighthouse-core/test/report/html/renderer/report-ui-features-test.js
Labels: P1, land-when-ci-is-green

#8893 report(redesign): move gauge styles to main stylesheet
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/report/html/templates.html
  lighthouse-core/test/report/html/renderer/dom-test.js
  lighthouse-core/test/report/html/renderer/psi-test.js
Labels: land-when-ci-is-green

#8971 docs(readme): add performance-budgets to related projects
  readme.md
Labels: land-when-ci-is-green

#8999 i18n: Minor translation corrections
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/ta.json
Labels: i18n

#7778 core(tap-targets): don't exclude visible position absolute elements from audit
  lighthouse-cli/test/fixtures/seo/seo-tap-targets.html
  lighthouse-cli/test/smokehouse/seo/expectations.js
  lighthouse-core/gather/gatherers/seo/tap-targets.js
  lighthouse-core/lib/rect-helpers.js
Labels: land-when-ci-is-green

#9057 report: make gauge font size and positioning dynamic
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/scripts/roll-to-devtools.sh
Labels: 5.1

#8894 tests(smoke): re-enable dialog prompt
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
  lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js
Labels: land-when-ci-is-green

#9072 core(runner): fix missing timing properties in the browser
  lighthouse-core/runner.js
Labels: cla: yes, land-when-ci-is-green

#9073 report: show fireworks only if all core categories score 100
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/test/report/html/renderer/report-ui-features-test.js
Labels: 5.1, cla: yes, land-when-ci-is-green

#9054 report: show metric descriptions by default when errors exist
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/test/report/html/renderer/report-ui-features-test.js
Labels: 5.1

#9023 devtools: enable sticky header, top bar, and report ui features
  lighthouse-core/report/html/renderer/report-renderer.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/report/html/templates.html
  lighthouse-core/test/report/html/renderer/report-renderer-test.js
  lighthouse-viewer/tsconfig.json
  package.json
  yarn.lock
Labels: 5.1, cla: yes

#9082 devtools: do not query system preferences for dark mode
  lighthouse-core/report/html/renderer/report-ui-features.js
Labels: cla: yes

#9077 devtools: move topbar out of scrollable container
  lighthouse-core/report/html/renderer/report-renderer.js
  lighthouse-core/report/html/report-styles.css
Labels: 5.1, cla: no

#9086 5.1.0
  changelog.md
  clients/extension/manifest.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  proto/sample_v2_round_trip.json
Labels: cla: yes

#9090 misc: release script should commit with format vx.y.z
  lighthouse-core/scripts/release/prepare-commit.sh
Labels: cla: yes

#9089 deps: update bundlesize, add more budgets
  package.json
  yarn.lock
Labels: cla: yes
