Repository GoogleChrome/lighthouse, pull requests merged in 2019-08, with the labels that each got.

#9487 i18n: use tsc to collect UIStrings
  lighthouse-core/config/default-config.js
  lighthouse-core/scripts/i18n/bake-ctc-to-lhl.js
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/test/scripts/i18n/collect-strings-test.js
  package.json
  yarn.lock
Labels: cla: yes

#9230 core(tracehouse): sort trace events by nesting order
  lighthouse-core/lib/tracehouse/trace-processor.js
  lighthouse-core/test/lib/tracehouse/main-thread-tasks-test.js
  lighthouse-core/test/lib/tracehouse/trace-processor-test.js
Labels: cla: yes

#9512 misc: retry cli tests up to 3 times in appveyor
  .appveyor.yml
Labels: cla: yes

#9515 deps(chrome-launcher): update to 0.11.2
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green

#9497 report(topbar): fix overflowing url
  lighthouse-core/report/html/renderer/report-renderer.js
  lighthouse-core/report/html/templates.html
Labels: cla: yes

#9524 fix(link): Update broken plugin example link
  readme.md
Labels: cla: yes

#9514 misc: share markdown parsing in collect-strings and the report
  lighthouse-core/report/html/renderer/dom.js
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/test/report/html/renderer/dom-test.js
  lighthouse-core/test/report/html/renderer/util-test.js
  lighthouse-core/test/scripts/i18n/collect-strings-test.js
Labels: cla: yes

#9532 clients(devtools): update test command to run only .js files
  lighthouse-core/scripts/roll-to-devtools.sh
Labels: cla: yes

#9509 core(constants): increase default maxWaitForFcp
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/config/constants.js
  lighthouse-core/config/lr-desktop-config.js
  lighthouse-core/config/lr-mobile-config.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes

#9105 i18n: pwa
  lighthouse-core/audits/apple-touch-icon.js
  lighthouse-core/audits/content-width.js
  lighthouse-core/audits/installable-manifest.js
  lighthouse-core/audits/load-fast-enough-for-pwa.js
  lighthouse-core/audits/manual/pwa-cross-browser.js
  lighthouse-core/audits/manual/pwa-each-page-has-url.js
  lighthouse-core/audits/manual/pwa-page-transitions.js
  lighthouse-core/audits/multi-check-audit.js
  lighthouse-core/audits/offline-start-url.js
  lighthouse-core/audits/redirects-http.js
  lighthouse-core/audits/service-worker.js
  lighthouse-core/audits/splash-screen.js
  lighthouse-core/audits/themed-omnibox.js
  lighthouse-core/audits/viewport.js
  lighthouse-core/audits/without-javascript.js
  lighthouse-core/audits/works-offline.js
  lighthouse-core/config/default-config.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/offline-start-url-test.js
  lighthouse-core/test/audits/service-worker-test.js
  lighthouse-core/test/audits/viewport-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes, i18n

#9542 tests(smokehouse): use mime-types + proper encoding for response write
  lighthouse-cli/test/fixtures/static-server.js
  lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js
  lighthouse-cli/test/smokehouse/perf/expectations.js
Labels: cla: yes

#9520 i18n: add link to cldr parentLocales
  lighthouse-core/lib/i18n/locales.js
Labels: cla: yes

#9538 core(audits): Point best practices audit links to web.dev
  lighthouse-core/audits/deprecations.js
  lighthouse-core/audits/dobetterweb/appcache-manifest.js
  lighthouse-core/audits/dobetterweb/doctype.js
  lighthouse-core/audits/dobetterweb/dom-size.js
  lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js
  lighthouse-core/audits/dobetterweb/geolocation-on-start.js
  lighthouse-core/audits/dobetterweb/js-libraries.js
  lighthouse-core/audits/dobetterweb/no-document-write.js
  lighthouse-core/audits/dobetterweb/no-vulnerable-libraries.js
  lighthouse-core/audits/dobetterweb/notification-on-start.js
  lighthouse-core/audits/dobetterweb/password-inputs-can-be-pasted-into.js
  lighthouse-core/audits/dobetterweb/uses-http2.js
  lighthouse-core/audits/dobetterweb/uses-passive-event-listeners.js
  lighthouse-core/audits/errors-in-console.js
  lighthouse-core/audits/image-aspect-ratio.js
  lighthouse-core/audits/is-on-https.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes

#9541 tests(smokehouse): index for static server. print address
  lighthouse-cli/test/fixtures/static-server.js
Labels: cla: yes

#9552 deps: details-element-polyfill@2.4.0
  package.json
  yarn.lock
Labels: cla: yes

#9537 core(audits): Point SEO audit links to web.dev
  lighthouse-core/audits/seo/canonical.js
  lighthouse-core/audits/seo/font-size.js
  lighthouse-core/audits/seo/hreflang.js
  lighthouse-core/audits/seo/http-status-code.js
  lighthouse-core/audits/seo/is-crawlable.js
  lighthouse-core/audits/seo/link-text.js
  lighthouse-core/audits/seo/manual/structured-data.js
  lighthouse-core/audits/seo/meta-description.js
  lighthouse-core/audits/seo/plugins.js
  lighthouse-core/audits/seo/robots-txt.js
  lighthouse-core/audits/seo/tap-targets.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes

#9553 clients(viewer): remove polyfills
  build/build-viewer.js
  lighthouse-viewer/app/src/main.js
  package.json
  yarn.lock
Labels: cla: yes

#9555 report: add utm params to web.dev links
  lighthouse-core/report/html/renderer/dom.js
  lighthouse-core/test/report/html/renderer/dom-test.js
Labels: cla: yes

#9433 report(accessibility): make dropdown match ARIA action menu button pattern
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/templates.html
  lighthouse-core/test/report/html/renderer/report-ui-features-test.js
Labels: cla: yes

#9451 core(start-url): stay offline for entirety of offlinePass
  lighthouse-core/gather/gatherers/offline.js
  lighthouse-core/gather/gatherers/start-url.js
  lighthouse-core/test/gather/gatherers/start-url-test.js
Labels: cla: yes

#9554 clients(proto): don't filter channel from configSettings
  lighthouse-core/lib/proto-preprocessor.js
  proto/sample_v2_round_trip.json
Labels: cla: yes

#9486 core(third-party-summary): add blocking time impact
  lighthouse-core/audits/third-party-summary.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/third-party-summary-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes

#9564 report(refactor): Move drop down logic into a separate class
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/test/report/html/renderer/report-ui-features-test.js
Labels: cla: yes

#9567 i18n: capitalize robots.txt displayValue
  lighthouse-core/audits/seo/robots-txt.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
Labels: cla: yes

#9453 core(lightwallet): add path to budget.json
  lighthouse-cli/test/smokehouse/perf/perf-config.js
  lighthouse-core/audits/performance-budget.js
  lighthouse-core/config/budget.js
  lighthouse-core/test/audits/performance-budget-test.js
  lighthouse-core/test/config/budget-test.js
  lighthouse-core/test/config/config-test.js
  lighthouse-core/test/fixtures/simple-budget.json
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample-config.js
  lighthouse-core/test/results/sample_v2.json
  types/budget.d.ts
Labels: cla: yes

#9460 i18n: fix custom formatted ICU within plurals
  lighthouse-core/audits/resource-summary.js
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/lib/i18n/i18n-test.js
  types/intl-messageformat-parser/index.d.ts
Labels: cla: yes

#9577 i18n: import translations from tc/
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
  package.json
Labels: cla: yes

#9568 i18n: add code spans to uses-rel-preconnect description
  lighthouse-core/audits/uses-rel-preconnect.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes

#9579 core(lightwallet): Add link to new budget.json repo
  types/budget.d.ts
Labels: cla: yes

#9570 i18n: use better types for intl-messageformat
  build/build-bundle.js
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/test/lib/i18n/i18n-test.js
  package.json
  types/intl-messageformat-parser/index.d.ts
  yarn.lock
Labels: cla: yes

#9546 viewer: add option for loading from the PSI API
  lighthouse-viewer/README.md
  lighthouse-viewer/app/index.html
  lighthouse-viewer/app/src/lighthouse-report-viewer.js
  lighthouse-viewer/app/src/main.js
  lighthouse-viewer/app/src/psi-api.js
  lighthouse-viewer/app/styles/viewer.css
  lighthouse-viewer/test/viewer-test-pptr.js
  lighthouse-viewer/types/viewer.d.ts
  package.json
  yarn.lock
Labels: cla: yes

#9584 core(i18n): improve Intl polyfill and use it in Util
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/test/lib/i18n/swap-locale-test.js
  lighthouse-core/test/report/html/renderer/util-test.js
Labels: cla: yes

#9576 core(gather-runner): only fail for mainRecord interstitials
  lighthouse-cli/test/fixtures/badssl-iframe.html
  lighthouse-cli/test/smokehouse/error-expectations.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/test/gather/gather-runner-test.js
Labels: cla: yes

#9591 misc: update favicon to new logo
  lighthouse-core/report/html/report-template.html
  lighthouse-viewer/app/index.html
  package.json
Labels: cla: yes

#9587 a11y: rewrite td-headers-attr titles
  lighthouse-core/audits/accessibility/td-headers-attr.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes

#9595 proto: update import hooks, obey line length
  proto/lighthouse-result.proto
Labels: cla: yes, land-when-ci-is-green

#9594 chore(lighthouse-viewer): replace deprecated uglify-es with terser
  build/build-viewer.js
  lighthouse-viewer/README.md
  package.json
  yarn.lock
Labels: cla: yes

#9600 chore: deduplicate yarn.lock dependencies
  yarn.lock
Labels: cla: yes

#9603 misc: trim missed yarn.lock cruft
  yarn.lock
Labels: cla: yes

#9598 i18n: remove translated messages when ICU arguments change
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/scripts/i18n/prune-obsolete-lhl-messages.js
  lighthouse-core/test/scripts/i18n/prune-obsolete-lhl-messages-test.js
  package.json
Labels: cla: yes

#9580 core(i18n): throw on excess placeholder replacement values
  lighthouse-core/audits/third-party-summary.js
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/lib/lh-error.js
  lighthouse-core/test/lib/i18n/i18n-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes

#9539 core(audits): point PWA audit description links to web.dev
  lighthouse-core/audits/content-width.js
  lighthouse-core/audits/installable-manifest.js
  lighthouse-core/audits/load-fast-enough-for-pwa.js
  lighthouse-core/audits/manual/pwa-cross-browser.js
  lighthouse-core/audits/manual/pwa-each-page-has-url.js
  lighthouse-core/audits/manual/pwa-page-transitions.js
  lighthouse-core/audits/offline-start-url.js
  lighthouse-core/audits/redirects-http.js
  lighthouse-core/audits/service-worker.js
  lighthouse-core/audits/splash-screen.js
  lighthouse-core/audits/themed-omnibox.js
  lighthouse-core/audits/viewport.js
  lighthouse-core/audits/without-javascript.js
  lighthouse-core/audits/works-offline.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes

#9620 i18n: import translated strings
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
  package.json
Labels: cla: yes

#9590 i18n: rewrite aria-required-children titles
  lighthouse-core/audits/accessibility/aria-required-children.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes

#9621 i18n: fix import scripts
  lighthouse-core/scripts/i18n/bake-ctc-to-lhl.js
  lighthouse-core/scripts/i18n/prune-obsolete-lhl-messages.js
  lighthouse-core/test/scripts/i18n/bake-ctc-to-lhl-test.js
Labels: cla: yes
