Repository GoogleChrome/lighthouse, pull requests merged in 2020-03, with the labels that each got.

#10384 misc(viewer): mention other lighthouse channels
  lighthouse-viewer/app/index.html
  lighthouse-viewer/app/src/lighthouse-report-viewer.js
Labels: cla: yes, waiting4committer

#10324 core(lightwallet): add firstPartyHostnames to budget.json
  lighthouse-core/audits/performance-budget.js
  lighthouse-core/computed/origin-summary.js
  lighthouse-core/computed/resource-summary.js
  lighthouse-core/config/budget.js
  lighthouse-core/test/audits/performance-budget-test.js
  lighthouse-core/test/audits/resource-summary-test.js
  lighthouse-core/test/computed/origin-summary-test.js
  lighthouse-core/test/computed/resource-summary-test.js
  lighthouse-core/test/config/budget-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
  types/budget.d.ts
Labels: cla: yes, waiting4committer

#10364 report: fix link contrast issue in dark mode
  lighthouse-core/report/html/report-styles.css
Labels: cla: yes, waiting4committer

#10344 deps: update axe-core to 3.5.1
  lighthouse-cli/test/smokehouse/test-definitions/a11y/expectations.js
  lighthouse-core/gather/gatherers/accessibility.js
  lighthouse-core/test/report/html/renderer/report-renderer-test.js
  package.json
  yarn.lock
Labels: cla: yes, waiting4committer

#10314 core(duplicated-javascript): new audit
  lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
  lighthouse-core/audits/byte-efficiency/duplicated-javascript.js
  lighthouse-core/computed/module-duplication.js
  lighthouse-core/config/experimental-config.js
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/byte-efficiency/duplicated-javascript-test.js
  lighthouse-core/test/computed/module-duplication-test.js
  lighthouse-core/test/fixtures/source-maps/coursehero-bundle-1.js
  lighthouse-core/test/fixtures/source-maps/coursehero-bundle-1.js.map
  lighthouse-core/test/fixtures/source-maps/coursehero-bundle-2.js
  lighthouse-core/test/fixtures/source-maps/coursehero-bundle-2.js.map
Labels: cla: yes, land-when-ci-is-green

#10427 core(cls): add learn more link
  lighthouse-core/audits/metrics/cumulative-layout-shift.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: chillin ❄, cla: yes, waiting4reviewer

#10447 misc: resolve jest-haste-map naming collision warning
  docs/recipes/custom-gatherer-puppeteer/package.json
Labels: cla: yes

#10418 tests: add github action w/ basic CI tasks
  .github/workflows/basics.yml
Labels: cla: yes, land-when-ci-is-green

#9949 core(scoring): apply v6 score weightings
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/audits/metrics/cumulative-layout-shift.js
  lighthouse-core/config/default-config.js
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/test/config/config-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: 6.0, cla: yes

#10448 tests: update coveragePathIgnore jest configuration
  jest.config.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#10451 v6.0.0-beta.0
  changelog.md
  lighthouse-core/test/results/sample_v2.json
  package.json
  proto/sample_v2_round_trip.json
Labels: cla: yes, waiting4reviewer

#10454 misc: add non-null annotations to keep internal lint happy
  lighthouse-core/report/html/renderer/category-renderer.js
  lighthouse-core/report/html/renderer/dom.js
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/report/html/renderer/pwa-category-renderer.js
  lighthouse-core/report/html/renderer/report-renderer.js
  lighthouse-core/report/html/renderer/snippet-renderer.js
  lighthouse-core/report/html/renderer/util.js
Labels: cla: yes, waiting4reviewer

#10452 core(lcp): remove todo, mark score curve points as official
  lighthouse-core/audits/metrics/largest-contentful-paint.js
Labels: 6.0, cla: yes, waiting4reviewer

#10473 tests(smoke): use range for unused bytes expectations
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
Labels: cla: yes

#9459 core(source-maps): workaround CORS for fetching maps
  lighthouse-cli/test/fixtures/source-map/script.js.map
  lighthouse-cli/test/fixtures/source-map/source-map-tester.html
  lighthouse-cli/test/smokehouse/test-definitions/core-tests.js
  lighthouse-cli/test/smokehouse/test-definitions/source-maps/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/source-maps/source-maps-config.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/fetcher.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/gather/gatherers/source-maps.js
  lighthouse-core/test/gather/fake-driver.js
  lighthouse-core/test/gather/gatherers/source-maps-test.js
Labels: cla: yes, waiting4committer

#10481 misc: add usesPixelArtScaling flag to images
  lighthouse-core/gather/gatherers/image-elements.js
  types/artifacts.d.ts
Labels: cla: yes, waiting4committer

#10482 misc: ignore duplicate builds in lhci dogfood
  lighthouse-core/scripts/dogfood-lhci.sh
Labels: cla: yes, waiting4reviewer

#10466 docs(readme): update PageSpeed Green in related projects
  readme.md
Labels: cla: yes, land-when-ci-is-green

#10460 new_audit: check images are big enough
  AUTHORS
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-core/audits/image-size-responsive.js
  lighthouse-core/config/default-config.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/image-size-responsive-test.js
  lighthouse-core/test/results/sample_v2.json
  package.json
  proto/sample_v2_round_trip.json
Labels: cla: yes, land-when-ci-is-green

#10491 core: remove some dead code in driver.js
  lighthouse-core/gather/driver.js
  lighthouse-core/test/gather/driver-test.js
Labels: 6.0, cla: yes

#10475 docs(readme): add AwesomeTechStack to lighthouse integrations
  readme.md
Labels: cla: yes, waiting4committer

#10496 core(unused-javascript): update doc link to web.dev
  lighthouse-core/audits/byte-efficiency/unused-javascript.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#10483 docs(variability): expand on hardware recommendations
  docs/variability.md
Labels: cla: yes, land-when-ci-is-green

#10505 core(driver): pause after FCP event before resolving load
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/fixtures/tricky-tti-late-fcp.html
  lighthouse-cli/test/smokehouse/test-definitions/core-tests.js
  lighthouse-cli/test/smokehouse/test-definitions/tricky-metrics/expectations.js
  lighthouse-core/config/config.js
  lighthouse-core/config/constants.js
  lighthouse-core/config/default-config.js
  lighthouse-core/config/no-throttling-config.js
  lighthouse-core/gather/driver.js
  lighthouse-core/test/config/config-test.js
  lighthouse-core/test/gather/driver-test.js
  types/config.d.ts
Labels: cla: yes, waiting4reviewer

#10453 core(audits): remove audio-caption accessibility audit
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/fixtures/a11y/a11y_tester.html
  lighthouse-cli/test/smokehouse/test-definitions/a11y/expectations.js
  lighthouse-core/audits/accessibility/audio-caption.js
  lighthouse-core/config/default-config.js
  lighthouse-core/gather/gatherers/accessibility.js
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/test/audits/accessibility/audio-caption-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: 6.0, cla: yes, waiting4reviewer

#10480 docs: add link to gist for using lighthouse audits directly
  docs/hacking-tips.md
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#10376 docs: emphasize some points on what makes a good audit
  assets/detail-type-examples.png
  docs/new-audits.md
  docs/plugins.md
  readme.md
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#10516 misc: rename ForFCP to ForFcp
  lighthouse-cli/test/smokehouse/test-definitions/core-tests.js
  lighthouse-cli/test/smokehouse/test-definitions/tricky-metrics/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/tricky-metrics/no-throttling-config.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/test/gather/driver-test.js
Labels: cla: yes, land-when-ci-is-green

#10519 misc(compare-runs): fix filter, allow for resume, reorganize output
  lighthouse-core/scripts/compare-runs.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#10437 report: update table and inline code formatting
  lighthouse-core/report/html/report-styles.css
Labels: cla: yes, waiting4committer
