Repository GoogleChrome/lighthouse, pull requests merged in 2020-07, with the labels that each got.

#11016 core: error if chrome version does not support lcp metric
  lighthouse-core/audits/metrics/largest-contentful-paint.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/lh-error.js
  lighthouse-core/test/audits/metrics/largest-contentful-paint-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11022 core(hreflang): check the hreflang uses a fully qualified href
  changelog.md
  lighthouse-cli/test/fixtures/seo/seo-failure-cases.html
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/seo/expectations.js
  lighthouse-core/audits/seo/hreflang.js
  lighthouse-core/gather/gatherers/link-elements.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/seo/hreflang-test.js
Labels: cla: yes, waiting4committer

#11052 tests(smoke): use caltrainschedule instead of polymer shop
  lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa2-expectations.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11040 docs: update architecture.md
  assets/architecture.jpg
  assets/architecture.png
  docs/architecture.md
Labels: cla: yes, waiting4reviewer

#11015 misc(compare-runs): fix error when no lh-flags arg passed
  lighthouse-core/scripts/compare-runs.js
Labels: cla: yes, land-when-ci-is-green

#11044 core(fetcher): plug more fetcher dangling promise leaks
  lighthouse-core/gather/fetcher.js
Labels: 6.1.1?, cla: yes, waiting4reviewer

#11036 core(fetcher): ensure fetch doesn't cause unhandled promise
  lighthouse-core/gather/fetcher.js
Labels: cla: yes, waiting4committer

#11065 v6.1.1
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  lighthouse-core/test/results/sample_v2.json
  package.json
Labels: cla: yes, waiting4reviewer

#11067 misc: remove last extendedInfo in LH.Audit.Product
  types/audit.d.ts
Labels: cla: yes, waiting4reviewer

#11042 core(gather-runner): error on non-HTML
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/lh-error.js
  lighthouse-core/test/gather/gather-runner-test.js
  proto/lighthouse-result.proto
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11050 docs(readme): update Foo integration
  readme.md
Labels: cla: yes, land-when-ci-is-green

#11068 core(font-display): dedupe warnings by font origin
  lighthouse-core/audits/font-display.js
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
  lighthouse-core/test/audits/font-display-test.js
Labels: cla: yes, land-when-ci-is-green

#11021 misc(release): tweaks
  docs/releasing.md
  lighthouse-core/scripts/lantern/download-traces.sh
  lighthouse-core/scripts/release/prepare-commit.sh
  lighthouse-core/scripts/release/test.sh
  lighthouse-core/scripts/roll-to-devtools.sh
Labels: cla: yes, waiting4committer

#11073 core(link-text): removing inicio from blocklist resolves
  lighthouse-core/audits/seo/link-text.js
Labels: cla: yes, waiting4reviewer

#11080 docs: fix typo in viewer readme for loading json from url
  lighthouse-viewer/README.md
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11083 tests: use latest windows image on appveyor
  .appveyor.yml
Labels: cla: yes, waiting4reviewer

#10976 tests(smoke): skip expectation with _chromeMajorVersion
  lighthouse-cli/test/smokehouse/readme.md
  lighthouse-cli/test/smokehouse/report-assert.js
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
Labels: cla: yes, waiting4reviewer

#11082 i18n(import): new audit strings, KiB, and updated urls for 6.1
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
Labels: cla: yes, waiting4reviewer

#10975 core(is-on-https): add mixed-content resolution
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-core/audits/is-on-https.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/is-on-https-test.js
  lighthouse-core/test/config/config-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4reviewer

#11079 core(cls): manually add first shift event to score if it was ignored
  lighthouse-core/computed/metrics/cumulative-layout-shift.js
  lighthouse-core/gather/gatherers/trace-elements.js
  lighthouse-core/test/computed/metrics/cumulative-layout-shift-test.js
  lighthouse-core/test/gather/gatherers/trace-elements-test.js
  types/externs.d.ts
Labels: cla: yes, waiting4reviewer

#11089 docs(architecture): correct link to description guidelines
  docs/architecture.md
Labels: cla: yes, waiting4reviewer

#11092 docs: update devtools screenshot
  assets/example_dev_tools.png
  readme.md
Labels: cla: yes, waiting4reviewer

#11069 core: add cap to amp stylesheet links for simulated throttling
  lighthouse-core/audits/byte-efficiency/render-blocking-resources.js
  lighthouse-core/test/audits/byte-efficiency/render-blocking-resources-test.js
  lighthouse-core/test/fixtures/traces/amp-m86.devtoolslog.json
  lighthouse-core/test/fixtures/traces/amp-m86.trace.json
Labels: cla: yes, waiting4committer

#11027 core(redirects): surface client-side redirects
  lighthouse-cli/test/smokehouse/test-definitions/redirects/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/redirects/redirects-config.js
  lighthouse-core/audits/redirects.js
  lighthouse-core/test/audits/redirects-test.js
Labels: cla: yes, land-when-ci-is-green

#11099 core(config): remove typo in a11y tables lists group
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/config/default-config.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4reviewer

#11101 core(image-elements): gather correct natural size for srcset
  lighthouse-cli/test/fixtures/byte-efficiency/tester.html
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/byte-config.js
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
  lighthouse-core/audits/byte-efficiency/uses-responsive-images.js
  lighthouse-core/gather/gatherers/image-elements.js
  types/artifacts.d.ts
Labels: cla: yes, waiting4reviewer

#10984 report: truncate long attribute values in HTML snippets
  lighthouse-core/lib/page-functions.js
  lighthouse-core/test/lib/page-functions-test.js
Labels: cla: yes, waiting4reviewer

#10985 core(unused-javascript): update "learn more" link
  lighthouse-core/audits/byte-efficiency/unused-javascript.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4reviewer

#11103 core(config): duplicated-javascript, legacy-javascript to default
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/smokehouse/test-definitions/legacy-javascript/legacy-javascript-config.js
  lighthouse-core/config/default-config.js
  lighthouse-core/config/experimental-config.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4committer

#11116 docs(readme): fix logging in programmatic use code example
  docs/readme.md
Labels: cla: yes, waiting4reviewer

#11126 docs(readme): add Screpy to the list of integrations
  readme.md
Labels: cla: yes, waiting4committer

#11034 core(tracehouse): expose navigationStart only as timeOrigin
  docs/architecture.md
  docs/recipes/custom-audit/readme.md
  docs/recipes/custom-audit/searchable-audit.js
  lighthouse-core/audits/final-screenshot.js
  lighthouse-core/computed/metrics/first-cpu-idle.js
  lighthouse-core/computed/metrics/interactive.js
  lighthouse-core/computed/metrics/timing-summary.js
  lighthouse-core/computed/speedline.js
  lighthouse-core/computed/user-timings.js
  lighthouse-core/lib/tracehouse/trace-processor.js
  lighthouse-core/lib/traces/pwmetrics-events.js
  lighthouse-core/test/audits/__snapshots__/metrics-test.js.snap
  lighthouse-core/test/audits/load-fast-enough-for-pwa-test.js
  lighthouse-core/test/audits/long-tasks-test.js
  lighthouse-core/test/computed/metrics/first-cpu-idle-test.js
  lighthouse-core/test/computed/metrics/interactive-test.js
  lighthouse-core/test/computed/metrics/timing-summary-test.js
  lighthouse-core/test/computed/trace-of-tab-test.js
  lighthouse-core/test/create-test-trace.js
  lighthouse-core/test/lib/asset-saver-test.js
  lighthouse-core/test/lib/tracehouse/trace-processor-test.js
  lighthouse-core/test/lib/traces/pwmetrics-events-test.js
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: cla: yes, waiting4reviewer

#11088 i18n: update AMP Optimizer URLs
  docs/plugins.md
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
  stack-packs/packs/amp.js
Labels: cla: yes, waiting4reviewer

#11061 core(link-elements): add devtoolsNodePath
  lighthouse-core/audits/seo/hreflang.js
  lighthouse-core/gather/gatherers/link-elements.js
  lighthouse-core/test/results/artifacts/artifacts.json
  types/artifacts.d.ts
Labels: cla: yes, waiting4committer

#11087 tests: add windows to GitHub actions CI
  .github/workflows/ci.yml
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  package.json
  proto/scripts/json_roundtrip_via_proto.py
  yarn.lock
Labels: cla: yes, waiting4reviewer

#11085 new_audit: add no-unload-listeners audit
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-core/audits/no-unload-listeners.js
  lighthouse-core/config/default-config.js
  lighthouse-core/gather/gatherers/global-listeners.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/no-unload-listeners-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: cla: yes, waiting4committer

#11136 misc: ignore coverage of page-functions
  lighthouse-core/lib/page-functions.js
Labels: cla: yes, waiting4reviewer

#11141 docs(configuration): updates and tweaks
  docs/configuration.md
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11135 i18n: disallow invalid text outside complex ICU arguments
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/test/scripts/i18n/collect-strings-test.js
Labels: cla: yes, waiting4reviewer

#11149 i18n: log the percentage of translated messages
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/scripts/i18n/count-translated.js
Labels: cla: yes, waiting4reviewer

#11137 deps: update third-party-web
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#11148 core(lantern): ignore circular initiators
  lighthouse-core/computed/page-dependency-graph.js
  lighthouse-core/lib/dependency-graph/base-node.js
  lighthouse-core/lib/network-recorder.js
  lighthouse-core/test/computed/page-dependency-graph-test.js
  lighthouse-core/test/fixtures/lantern-master-accuracy.json
  lighthouse-core/test/fixtures/lantern-master-computed-values.json
  lighthouse-core/test/lib/dependency-graph/base-node-test.js
  lighthouse-core/test/lib/network-recorder-test.js
Labels: cla: yes, land-when-ci-is-green

#11151 core(critical-request-chains): prune requests without an initiator
  lighthouse-core/computed/critical-request-chains.js
  lighthouse-core/test/audits/critical-request-chains-test.js
  lighthouse-core/test/computed/critical-request-chains-test.js
  lighthouse-core/test/lib/third-party-web-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4reviewer

#10626 core(uses-http2): convert into opportunity
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/byte-config.js
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-core/audits/dobetterweb/uses-http2.js
  lighthouse-core/config/default-config.js
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
  lighthouse-core/test/audits/dobetterweb/uses-http2-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4committer

#11138 core: generalize TraceElements gatherer and add animated elements
  lighthouse-cli/test/fixtures/perf/delayed-element.js
  lighthouse-cli/test/fixtures/perf/trace-elements.html
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-core/audits/largest-contentful-paint-element.js
  lighthouse-core/audits/layout-shift-elements.js
  lighthouse-core/gather/gatherers/trace-elements.js
  lighthouse-core/test/audits/largest-contentful-paint-element-test.js
  lighthouse-core/test/audits/layout-shift-elements-test.js
  lighthouse-core/test/gather/gatherers/trace-elements-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  types/artifacts.d.ts
Labels: cla: yes, waiting4committer

#11139 cli: warn if Chrome died on its own instead of exit
  lighthouse-cli/run.js
  lighthouse-cli/test/smokehouse/test-definitions/oopif/oopif-config.js
  lighthouse-cli/test/smokehouse/test-definitions/redirects/redirects-config.js
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#11168 core: resolve animation name in TraceElements gatherer
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-core/gather/gatherers/trace-elements.js
  lighthouse-core/test/gather/gatherers/trace-elements-test.js
  types/externs.d.ts
Labels: cla: yes, waiting4committer

#11167 deps: update jpeg-js to 0.4.x
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#11175 misc: tighten RecursivePartial type
  lighthouse-core/test/gather/gather-runner-test.js
  types/externs.d.ts
Labels: cla: yes, waiting4committer

#11115 new_audit: add sized-images to experimental config
  lighthouse-core/audits/dobetterweb/password-inputs-can-be-pasted-into.js
  lighthouse-core/audits/unsized-images.js
  lighthouse-core/config/experimental-config.js
  lighthouse-core/gather/gatherers/image-elements.js
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
  lighthouse-core/test/audits/unsized-images-test.js
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: cla: yes, waiting4reviewer

#11152 report: tweak naming in element-screenshot renderer
  lighthouse-core/report/html/renderer/element-screenshot-renderer.js
  lighthouse-core/test/report/html/renderer/element-screenshot-renderer-test.js
Labels: cla: yes, land-when-ci-is-green

#11174 core(lantern): fallback to FCP in 0-weight SI situations
  lighthouse-core/computed/metrics/lantern-speed-index.js
  lighthouse-core/test/computed/metrics/__snapshots__/speed-index-test.js.snap
  lighthouse-core/test/computed/metrics/speed-index-test.js
  lighthouse-core/test/fixtures/traces/speedindex-1ms-layout-m84.devtoolslog.json
  lighthouse-core/test/fixtures/traces/speedindex-1ms-layout-m84.trace.json
Labels: cla: yes, land-when-ci-is-green

#11171 misc: remove all appveyor references
  .appveyor.yml
  .npmignore
  lighthouse-cli/test/smokehouse/lighthouse-runners/cli.js
  lighthouse-cli/test/smokehouse/test-definitions/lantern/lantern-expectations.js
  lighthouse-core/scripts/download-chrome.sh
  readme.md
Labels: cla: yes, land-when-ci-is-green

#11195 tests: run test-viewer in github actions
  .github/workflows/ci.yml
Labels: cla: yes, waiting4reviewer

#11192 deps(angular): update minor version of angular fixture redux
  lighthouse-core/test/lib/minification-estimator-test.js
  yarn.lock
Labels: cla: yes, waiting4reviewer

#11170 cli: clearTimeout for faster exit
  lighthouse-cli/run.js
Labels: cla: yes, waiting4reviewer

#11191 tests(minification-est): add testcase with pre-minified bundle
  lighthouse-core/test/lib/minification-estimator-test.js
Labels: cla: yes, waiting4committer

#11189 misc: add GCP collection scripts
  lighthouse-core/scripts/gcp-collection/README.md
  lighthouse-core/scripts/gcp-collection/gcp-run-on-url.sh
  lighthouse-core/scripts/gcp-collection/gcp-run.sh
  lighthouse-core/scripts/gcp-collection/gcp-setup.sh
  lighthouse-core/scripts/gcp-collection/run.sh
  lighthouse-core/scripts/gcp-collection/urls.txt
Labels: cla: yes, waiting4reviewer
