Repository GoogleChrome/lighthouse, pull requests merged in 2020-04, with the labels that each got.

#10530 core: include finished state on hidden network-requests audit
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
  lighthouse-core/audits/network-requests.js
  lighthouse-core/test/audits/network-requests-test.js
  lighthouse-core/test/fixtures/traces/cutoff-load-m83.devtoolslog.json
  lighthouse-core/test/fixtures/traces/cutoff-load-m83.trace.json
  lighthouse-core/test/results/sample_v2.json
  lighthouse-core/test/test-utils.js
  proto/sample_v2_round_trip.json
  types/jest.d.ts
Labels: cla: yes, waiting4committer

#10097 core(lantern): add edges from initiatorRequest when there are duplicate records
  lighthouse-core/computed/page-dependency-graph.js
  lighthouse-core/lib/network-recorder.js
  lighthouse-core/test/computed/page-dependency-graph-test.js
  lighthouse-core/test/fixtures/lantern-master-accuracy.json
  lighthouse-core/test/fixtures/lantern-master-computed-values.json
  lighthouse-core/test/fixtures/prefetched-script.devtoolslog.json
  lighthouse-core/test/lib/network-recorder-test.js
Labels: 6.0, cla: yes, waiting4committer

#10546 docs(lantern): add deep dive video
  docs/architecture.md
  docs/lantern.md
Labels: cla: yes, waiting4reviewer

#10506 core(responsive-images): find offscreen images larger than viewport
  lighthouse-cli/test/fixtures/byte-efficiency/lighthouse-2048x1356.webp
  lighthouse-cli/test/fixtures/byte-efficiency/tester.html
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
  lighthouse-core/audits/byte-efficiency/uses-responsive-images.js
  lighthouse-core/test/audits/byte-efficiency/uses-responsive-images-test.js
Labels: cla: yes, waiting4committer

#10544 deps: upgrade publisher ads
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#10420 report: specify transfer or resource size for columns
  lighthouse-core/audits/byte-efficiency/efficient-animated-content.js
  lighthouse-core/audits/byte-efficiency/offscreen-images.js
  lighthouse-core/audits/byte-efficiency/render-blocking-resources.js
  lighthouse-core/audits/byte-efficiency/total-byte-weight.js
  lighthouse-core/audits/byte-efficiency/unminified-css.js
  lighthouse-core/audits/byte-efficiency/unminified-javascript.js
  lighthouse-core/audits/byte-efficiency/unused-css-rules.js
  lighthouse-core/audits/byte-efficiency/unused-javascript.js
  lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
  lighthouse-core/audits/byte-efficiency/uses-optimized-images.js
  lighthouse-core/audits/byte-efficiency/uses-responsive-images.js
  lighthouse-core/audits/byte-efficiency/uses-text-compression.js
  lighthouse-core/audits/byte-efficiency/uses-webp-images.js
  lighthouse-core/audits/third-party-summary.js
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: 6.0, cla: yes, land-when-ci-is-green

#10538 core(driver): add run warning on page load timeout
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/gather/driver-test.js
  lighthouse-core/test/gather/fake-driver.js
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/runner-test.js
  readme.md
Labels: cla: yes, waiting4committer

#10561 tests(smokehouse): loosen wastedMs for unused-javascript
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
Labels: cla: yes, waiting4reviewer

#10461 deps(typescript): update to 3.8.3
  lighthouse-core/computed/metrics/lantern-estimated-input-latency.js
  lighthouse-core/computed/metrics/lantern-first-cpu-idle.js
  lighthouse-core/computed/metrics/lantern-interactive.js
  lighthouse-core/computed/metrics/lantern-max-potential-fid.js
  lighthouse-core/computed/metrics/lantern-metric.js
  lighthouse-core/computed/metrics/lantern-speed-index.js
  lighthouse-core/computed/metrics/lantern-total-blocking-time.js
  lighthouse-core/config/experimental-config.js
  lighthouse-core/config/lr-mobile-config.js
  lighthouse-core/lib/cdt/SDK.js
  lighthouse-core/report/html/renderer/crc-details-renderer.js
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/report/html/renderer/report-renderer.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/renderer/snippet-renderer.js
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/test/gather/driver-test.js
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-viewer/app/src/viewer-ui-features.js
  package.json
  yarn.lock
Labels: cla: yes, waiting4committer

#10479 core(audits): mention <div> is allowed to group content in <dl>
  lighthouse-core/audits/accessibility/definition-list.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes, waiting4committer

#10542 docs: add explainer on performance budgets
  docs/performance-budgets.md
  readme.md
Labels: cla: yes, waiting4committer

#10551 misc(build): disable fail-fast on gh basics workflow
  .github/workflows/basics.yml
Labels: cla: yes, waiting4committer

#10555 core(runner): make LH.Audit.Context immutable
  lighthouse-core/audits/bootup-time.js
  lighthouse-core/audits/metrics/first-contentful-paint-3g.js
  lighthouse-core/audits/performance-budget.js
  lighthouse-core/audits/timing-budget.js
  lighthouse-core/computed/computed-artifact.js
  lighthouse-core/computed/load-simulator.js
  lighthouse-core/computed/resource-summary.js
  lighthouse-core/config/budget.js
  lighthouse-core/lib/asset-saver.js
  lighthouse-core/runner.js
  lighthouse-core/scripts/legacy-javascript/examine-latest-run.js
  lighthouse-core/scripts/legacy-javascript/summary-sizes.txt
  lighthouse-core/test/runner-test.js
  types/artifacts.d.ts
  types/audit.d.ts
  types/externs.d.ts
Labels: 6.0, cla: yes

#10526 misc(compare-runs): category scores, url filter, sort abs.val
  lighthouse-core/scripts/compare-runs.js
Labels: cla: yes, waiting4committer

#10571 core: delete unused driver.queryPermissionState()
  lighthouse-core/gather/driver.js
Labels: cla: yes, waiting4reviewer

#10550 misc(build): report to buildtracker on commit via ghactions
  .github/workflows/basics.yml
  build-tracker.config.js
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green

#10584 misc: npmignore += timings-data/
  .npmignore
Labels: cla: yes, waiting4reviewer

#10585 cli: experimental preset
  lighthouse-cli/cli-flags.js
Labels: cla: yes, waiting4reviewer

#10529 core(lantern): improve LCP tail error
  lighthouse-core/computed/metrics/lantern-largest-contentful-paint.js
  lighthouse-core/lib/dependency-graph/simulator/simulator.js
  lighthouse-core/test/audits/__snapshots__/metrics-test.js.snap
  lighthouse-core/test/audits/__snapshots__/predictive-perf-test.js.snap
  lighthouse-core/test/audits/byte-efficiency/__snapshots__/byte-efficiency-audit-test.js.snap
  lighthouse-core/test/audits/metrics/__snapshots__/first-meaningful-paint-test.js.snap
  lighthouse-core/test/computed/metrics/__snapshots__/first-meaningful-paint-test.js.snap
  lighthouse-core/test/computed/metrics/__snapshots__/lantern-first-meaningful-paint-test.js.snap
  lighthouse-core/test/computed/metrics/lantern-largest-contentful-paint-test.js
  lighthouse-core/test/computed/metrics/lantern-speed-index-test.js
  lighthouse-core/test/computed/metrics/largest-contentful-paint-test.js
  lighthouse-core/test/computed/metrics/timing-summary-test.js
  lighthouse-core/test/fixtures/lantern-master-accuracy.json
  lighthouse-core/test/fixtures/lantern-master-computed-values.json
  lighthouse-core/test/lib/dependency-graph/simulator/simulator-test.js
  package.json
Labels: 6.0, cla: yes, waiting4committer

#10595 tests: fix i18n-test bugs in Node 13
  lighthouse-core/test/lib/i18n/i18n-test.js
  lighthouse-core/test/lib/i18n/swap-locale-test.js
Labels: cla: yes

#10603 misc: minor cleanup of audit-details type names
  lighthouse-core/report/html/renderer/details-renderer.js
  types/audit-details.d.ts
Labels: cla: yes

#10557 tests: remove protoc roundtrip check from update:sample-json
  .github/workflows/basics.yml
  .gitignore
  lighthouse-core/test/report/html/renderer/psi-test.js
  lighthouse-core/test/report/proto-test.js
  lighthouse-core/test/test-utils.js
  package.json
  proto/sample_v2_round_trip.json
Labels: cla: yes, waiting4reviewer

#10607 cli: add support for multiple --chrome-flags
  lighthouse-cli/run.js
  lighthouse-cli/test/cli/run-test.js
  types/externs.d.ts
Labels: cla: yes, land-when-ci-is-green

#10609 docs(readme): add seo guard entry to integrations
  readme.md
Labels: cla: yes

#10622 misc(build): also run GH workflow on pull_request
  .github/workflows/basics.yml
Labels: cla: yes, waiting4reviewer

#10620 tests: add all tests to GitHub workflow
  .github/workflows/ci.yml
Labels: cla: yes, waiting4reviewer

#10568 tests(legacy-javascript): cache variants, check in lockfile, …
  .travis.yml
  lighthouse-core/scripts/legacy-javascript/README.md
  lighthouse-core/scripts/legacy-javascript/run.js
  lighthouse-core/scripts/legacy-javascript/summary-sizes.txt
  lighthouse-core/scripts/legacy-javascript/update-sizes.sh
  lighthouse-core/scripts/legacy-javascript/yarn.lock
  lighthouse-core/test/audits/legacy-javascript-test.js
Labels: cla: yes, waiting4committer

#10579 core(perf-budgets): support CLS & LCP budgets; fix SpeedIndex budget
  docs/performance-budgets.md
  lighthouse-core/audits/metrics/cumulative-layout-shift.js
  lighthouse-core/audits/metrics/largest-contentful-paint.js
  lighthouse-core/audits/timing-budget.js
  lighthouse-core/config/budget.js
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
  lighthouse-core/test/audits/timing-budget-test.js
  lighthouse-core/test/config/budget-test.js
  lighthouse-core/test/results/sample_v2.json
  types/budget.d.ts
Labels: 6.0, cla: yes, waiting4committer

#10387 core: unused-javascript-summary computed artifact
  lighthouse-core/audits/byte-efficiency/unused-javascript.js
  lighthouse-core/computed/unused-javascript-summary.js
  lighthouse-core/gather/gatherers/js-usage.js
  lighthouse-core/test/audits/byte-efficiency/unused-javascript-test.js
  lighthouse-core/test/computed/unused-javascript-summary-test.js
  types/artifacts.d.ts
Labels: cla: yes, waiting4committer

#10625 tests: budget tests use an observed throttlingMethod
  lighthouse-core/test/audits/timing-budget-test.js
Labels: cla: yes, waiting4reviewer

#10583 misc(build): yarn unlink before linking
  package.json
Labels: cla: yes, waiting4reviewer

#10608 report(viewer): add option for loading from JSON
  lighthouse-viewer/README.md
  lighthouse-viewer/app/src/github-api.js
  lighthouse-viewer/app/src/lighthouse-report-viewer.js
Labels: cla: yes, waiting4reviewer

#10648 tests(smoke): fork pwa.rocks
  lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa3-expectations.js
Labels: cla: yes, waiting4reviewer

#10631 docs(readme): add variability and throttling to FAQ
  readme.md
Labels: cla: yes, waiting4reviewer

#10570 core(cls): shorten description
  lighthouse-core/audits/metrics/cumulative-layout-shift.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4reviewer

#10646 core(a11y): ensure errors can be serialized properly
  lighthouse-core/audits/accessibility/axe-audit.js
  lighthouse-core/gather/gatherers/accessibility.js
  lighthouse-core/test/audits/accessibility/axe-audit-test.js
  lighthouse-core/test/audits/audit-test.js
  types/artifacts.d.ts
Labels: cla: yes

#10495 core(scoring): update CLS score curve - 0.25 is now failing
  lighthouse-core/audits/metrics/cumulative-layout-shift.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, land-when-ci-is-green

#10652 misc(compare-runs): use execFile
  lighthouse-core/scripts/compare-runs.js
Labels: cla: yes, waiting4reviewer

#10661 tests(ci): authenticate protoc download
  .github/workflows/ci.yml
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#10656 core(report-generator): add url to CSV output
  lighthouse-core/report/report-generator.js
  lighthouse-core/test/report/report-generator-test.js
Labels: cla: yes, waiting4reviewer

#10535 deps: upgrade chrome-launcher@0.13.1
  package.json
  yarn.lock
Labels: cla: yes, waiting4committer

#10658 misc: close variability issues to master issue
  lighthouse-core/scripts/git3po-rules/close-variability-issues.yaml
Labels: cla: yes

#10633 docs(scoring): update and refine scoring.md
  docs/scoring.md
Labels: cla: yes, waiting4reviewer

#10675 core: remove length check from csv report test
  lighthouse-core/test/report/report-generator-test.js
Labels: cla: yes, waiting4committer

#10623 report: add Trust & Safety group under Best Practices
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/smokehouse/test-definitions/offline-local/offline-expectations.js
  lighthouse-core/audits/dobetterweb/no-document-write.js
  lighthouse-core/config/default-config.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/config/config-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, land-when-ci-is-green
