Repository GoogleChrome/lighthouse, pull requests merged in 2020-01, with the labels that each got.

#10179 docs: fix typo in docs/readme.md
  docs/readme.md
Labels: cla: yes

#9987 core(config): add loadFailureMode warn
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/config/config.js
  lighthouse-core/config/constants.js
  lighthouse-core/config/default-config.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/test/config/config-test.js
  lighthouse-core/test/gather/gather-runner-test.js
  types/config.d.ts
Labels: cla: yes, land-when-ci-is-green

#10181 tests(speedline): remove flaky test
  lighthouse-core/test/computed/speedline-test.js
Labels: cla: yes

#10130 gatherers: use isolation for fetch
  lighthouse-core/gather/gatherers/seo/robots-txt.js
  lighthouse-core/gather/gatherers/source-maps.js
  lighthouse-core/test/gather/gatherers/source-maps-test.js
Labels: cla: yes

#10184 cli: --chrome-ignore-default-flags
  lighthouse-cli/cli-flags.js
  lighthouse-cli/run.js
  lighthouse-cli/test/cli/bin-test.js
  types/externs.d.ts
Labels: cla: yes

#10176 core(js-libraries): hide fast path items from table, put all in debugData
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-core/audits/dobetterweb/js-libraries.js
  lighthouse-core/test/audits/dobetterweb/js-libraries-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  proto/sample_v2_round_trip.json
  yarn.lock
Labels: cla: yes

#10153 report: remove Util.UIStrings mutation, add I18n renderer class
  lighthouse-core/audits/dobetterweb/dom-size.js
  lighthouse-core/audits/mixed-content.js
  lighthouse-core/audits/predictive-perf.js
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/report/html/html-report-assets.js
  lighthouse-core/report/html/renderer/category-renderer.js
  lighthouse-core/report/html/renderer/crc-details-renderer.js
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/report/html/renderer/i18n.js
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/report/html/renderer/psi.js
  lighthouse-core/report/html/renderer/report-renderer.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/renderer/snippet-renderer.js
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/test/audits/dobetterweb/dom-size-test.js
  lighthouse-core/test/audits/mixed-content-test.js
  lighthouse-core/test/audits/predictive-perf-test.js
  lighthouse-core/test/report/html/renderer/category-renderer-test.js
  lighthouse-core/test/report/html/renderer/crc-details-renderer-test.js
  lighthouse-core/test/report/html/renderer/details-renderer-test.js
  lighthouse-core/test/report/html/renderer/dom-test.js
  lighthouse-core/test/report/html/renderer/i18n-test.js
  lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
  lighthouse-core/test/report/html/renderer/psi-test.js
  lighthouse-core/test/report/html/renderer/pwa-category-renderer-test.js
  lighthouse-core/test/report/html/renderer/report-renderer-test.js
  lighthouse-core/test/report/html/renderer/report-ui-features-test.js
  lighthouse-core/test/report/html/renderer/snippet-renderer-test.js
  lighthouse-core/test/report/html/renderer/util-test.js
  types/html-renderer.d.ts
  types/lhr.d.ts
Labels: cla: yes

#10186 tests: remove global.URL
  lighthouse-core/test/report/html/renderer/category-renderer-test.js
  lighthouse-core/test/report/html/renderer/crc-details-renderer-test.js
  lighthouse-core/test/report/html/renderer/details-renderer-test.js
  lighthouse-core/test/report/html/renderer/dom-test.js
  lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
  lighthouse-core/test/report/html/renderer/psi-test.js
  lighthouse-core/test/report/html/renderer/pwa-category-renderer-test.js
  lighthouse-core/test/report/html/renderer/report-renderer-test.js
Labels: cla: yes

#10188 cli: fix csv for --output
  lighthouse-cli/cli-flags.js
  lighthouse-cli/test/cli/run-test.js
Labels: cla: yes

#10193 misc: release script push tag
  docs/releasing.md
Labels: cla: yes

#10199 tests(report-ui-features): fix tools button suite to pass isolated run
  lighthouse-core/test/report/html/renderer/report-ui-features-test.js
Labels: cla: yes

#10189 docs(auth): use --disable-storage-reset for chrome-debug
  docs/authenticated-pages.md
  docs/recipes/auth/README.md
  docs/recipes/auth/example-lh-auth.js
  docs/recipes/integration-test/example-lh-auth.test.js
Labels: cla: yes

#10201 tests(report-ui-features): add empty list and single item test cases
  lighthouse-core/test/report/html/renderer/report-ui-features-test.js
Labels: cla: yes

#10205 core: measure time for GatherRunner.runPass
  lighthouse-core/gather/gather-runner.js
Labels: cla: yes

#10209 misc: add predictive perf to lantern test set
  lighthouse-core/scripts/lantern/run-once.js
  lighthouse-core/scripts/test-lantern.sh
Labels: cla: yes

#10207 deps(devtools-protocol): upgrade to 0.0.729809
  lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
  lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
  lighthouse-core/computed/critical-request-chains.js
  lighthouse-core/computed/resource-summary.js
  lighthouse-core/gather/gatherers/dobetterweb/response-compression.js
  lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js
  lighthouse-core/lib/network-request.js
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green

#10123 tests(driver): type check
  lighthouse-core/test/gather/driver-test.js
  lighthouse-core/test/gather/fake-driver.js
  lighthouse-core/test/gather/mock-commands.js
  tsconfig.json
  types/externs.d.ts
  types/jest.d.ts
Labels: cla: yes

#10136 tests(gather-runner): replace getMockedEmulationDriver w/ mock-commands
  lighthouse-core/test/gather/gather-runner-test.js
Labels: cla: yes

#10190 core(resource-summary): ignore /favicon.ico
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-core/computed/resource-summary.js
  lighthouse-core/test/computed/resource-summary-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes

#10200 core(font-size): speed up gatherer
  lighthouse-cli/test/smokehouse/test-definitions/seo/expectations.js
  lighthouse-core/audits/seo/font-size.js
  lighthouse-core/gather/gatherers/seo/font-size.js
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
  lighthouse-core/test/audits/seo/font-size-test.js
  lighthouse-core/test/gather/gatherers/seo/font-size-test.js
  types/artifacts.d.ts
Labels: cla: yes

#10223 docs(scoring.md): Updates links to use new spreadsheet
  docs/scoring.md
Labels: cla: yes

#10216 report: fix ghost menu in print
  lighthouse-core/report/html/templates.html
Labels: cla: yes

#10215 tests(gather-runner): type check
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/network-records-to-devtools-log.js
  tsconfig.json
  types/externs.d.ts
Labels: cla: yes

#9166 i18n(report): runtime settings and tools
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/report/html/renderer/report-renderer.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/report/html/templates.html
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/test/report/html/renderer/report-renderer-test.js
  lighthouse-core/test/report/html/renderer/report-ui-features-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/lighthouse-result.proto
  proto/sample_v2_round_trip.json
Labels: cla: yes, i18n, land-when-ci-is-green

#9713 core(script-elements): parallelize getting request contents
  lighthouse-cli/test/fixtures/byte-efficiency/tester.html
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
  lighthouse-core/gather/gatherers/script-elements.js
Labels: cla: yes

#10208 report: close drop down menu when focus is lost
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/test/report/html/renderer/report-ui-features-test.js
Labels: cla: yes, land-when-ci-is-green

#10160 core: move unused-css to computed artifact
  lighthouse-core/audits/byte-efficiency/render-blocking-resources.js
  lighthouse-core/audits/byte-efficiency/unminified-css.js
  lighthouse-core/audits/byte-efficiency/unused-css-rules.js
  lighthouse-core/computed/unused-css.js
  lighthouse-core/test/audits/byte-efficiency/unused-css-rules-test.js
  lighthouse-core/test/computed/unused-css-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes

#10157 core: warn if document was redirected
  lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/redirects/expectations.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/gather/fake-driver.js
  types/smokehouse.d.ts
Labels: cla: yes

#9986 core(audits): Add more keywords to blocklist
  lighthouse-core/audits/seo/link-text.js
Labels: cla: yes

#10230 tests: avoid redirect in failureMode warn test
  lighthouse-core/test/gather/gather-runner-test.js
Labels: cla: yes

#10213 core(largest-contentful-paint): update docs link
  lighthouse-core/audits/metrics/largest-contentful-paint.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes

#9979 core(lhr): add numericUnit to audit result
  lighthouse-core/audits/audit.js
  lighthouse-core/audits/bootup-time.js
  lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
  lighthouse-core/audits/byte-efficiency/render-blocking-resources.js
  lighthouse-core/audits/byte-efficiency/total-byte-weight.js
  lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
  lighthouse-core/audits/dobetterweb/dom-size.js
  lighthouse-core/audits/errors-in-console.js
  lighthouse-core/audits/load-fast-enough-for-pwa.js
  lighthouse-core/audits/main-thread-tasks.js
  lighthouse-core/audits/mainthread-work-breakdown.js
  lighthouse-core/audits/metrics.js
  lighthouse-core/audits/metrics/estimated-input-latency.js
  lighthouse-core/audits/metrics/first-contentful-paint-3g.js
  lighthouse-core/audits/metrics/first-contentful-paint.js
  lighthouse-core/audits/metrics/first-cpu-idle.js
  lighthouse-core/audits/metrics/first-meaningful-paint.js
  lighthouse-core/audits/metrics/interactive.js
  lighthouse-core/audits/metrics/largest-contentful-paint.js
  lighthouse-core/audits/metrics/max-potential-fid.js
  lighthouse-core/audits/metrics/speed-index.js
  lighthouse-core/audits/metrics/total-blocking-time.js
  lighthouse-core/audits/network-requests.js
  lighthouse-core/audits/network-rtt.js
  lighthouse-core/audits/network-server-latency.js
  lighthouse-core/audits/predictive-perf.js
  lighthouse-core/audits/redirects.js
  lighthouse-core/audits/time-to-first-byte.js
  lighthouse-core/audits/uses-rel-preconnect.js
  lighthouse-core/audits/uses-rel-preload.js
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/test/audits/errors-in-console-test.js
  lighthouse-core/test/audits/network-requests-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/lighthouse-result.proto
  proto/sample_v2_round_trip.json
  types/audit.d.ts
Labels: cla: yes, land-when-ci-is-green

#10227 tests(smokehouse): make bytes gzip size checks less restrictive
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
Labels: cla: yes, land-when-ci-is-green

#10175 core(installable-manifest): icon requirement 192px -> 144px
  lighthouse-cli/test/fixtures/manifest.json
  lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa-expectations-details.js
  lighthouse-core/audits/installable-manifest.js
  lighthouse-core/computed/manifest-values.js
  lighthouse-core/test/audits/installable-manifest-test.js
  types/artifacts.d.ts
Labels: cla: yes

#9922 lantern: keep first layout/paint/parse events regardless of duration
  lighthouse-core/computed/page-dependency-graph.js
  lighthouse-core/test/audits/__snapshots__/metrics-test.js.snap
  lighthouse-core/test/audits/__snapshots__/predictive-perf-test.js.snap
  lighthouse-core/test/audits/byte-efficiency/__snapshots__/byte-efficiency-audit-test.js.snap
  lighthouse-core/test/audits/metrics/__snapshots__/first-meaningful-paint-test.js.snap
  lighthouse-core/test/audits/metrics/first-contentful-paint-3g-test.js
  lighthouse-core/test/computed/metrics/__snapshots__/first-contentful-paint-test.js.snap
  lighthouse-core/test/computed/metrics/__snapshots__/first-meaningful-paint-test.js.snap
  lighthouse-core/test/computed/metrics/__snapshots__/lantern-first-contentful-paint-test.js.snap
  lighthouse-core/test/computed/metrics/__snapshots__/lantern-first-meaningful-paint-test.js.snap
  lighthouse-core/test/computed/metrics/__snapshots__/speed-index-test.js.snap
  lighthouse-core/test/computed/metrics/first-contentful-paint-test.js
  lighthouse-core/test/computed/metrics/first-cpu-idle-test.js
  lighthouse-core/test/computed/metrics/first-meaningful-paint-test.js
  lighthouse-core/test/computed/metrics/interactive-test.js
  lighthouse-core/test/computed/metrics/lantern-first-contentful-paint-test.js
  lighthouse-core/test/computed/metrics/lantern-first-cpu-idle-test.js
  lighthouse-core/test/computed/metrics/lantern-first-meaningful-paint-test.js
  lighthouse-core/test/computed/metrics/lantern-interactive-test.js
  lighthouse-core/test/computed/metrics/lantern-largest-contentful-paint-test.js
  lighthouse-core/test/computed/metrics/lantern-speed-index-test.js
  lighthouse-core/test/computed/metrics/largest-contentful-paint-test.js
  lighthouse-core/test/computed/metrics/timing-summary-test.js
  lighthouse-core/test/computed/page-dependency-graph-test.js
  lighthouse-core/test/fixtures/lantern-master-computed-values.json
Labels: cla: yes

#10232 report: align audit warnings
  lighthouse-core/report/html/renderer/category-renderer.js
  lighthouse-core/report/html/report-styles.css
Labels: cla: yes

#10244 i18n(import): new audit strings and small edits
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
Labels: cla: yes

#10191 core(emulation): use Moto G4 for mobile emulation
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
  lighthouse-core/lib/emulation.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/test/report/html/renderer/report-renderer-test.js
  lighthouse-core/test/report/html/renderer/util-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes

#10245 misc: bump bundlesize threshold for LR
  package.json
Labels: cla: yes

#10231 misc: add git3po scripts
  lighthouse-core/scripts/git3po-rules/cannot-attach-to-this-target.yaml
  lighthouse-core/scripts/git3po-rules/failed-document-request.yaml
  lighthouse-core/scripts/git3po-rules/failed-to-construct-url.yaml
  lighthouse-core/scripts/git3po-rules/invalid-url.yaml
  lighthouse-core/scripts/git3po-rules/multiple-tabs.yaml
  lighthouse-core/scripts/git3po-rules/no-fcp.yaml
  lighthouse-core/scripts/git3po-rules/no-tabid-set-for-sendcommand.yaml
  lighthouse-core/scripts/git3po-rules/page-hung.yaml
  lighthouse-core/scripts/git3po-rules/parsing-problem.yaml
  lighthouse-core/scripts/git3po-rules/protocol-timeout.yaml
  lighthouse-core/scripts/git3po-rules/read-failed.yaml
  lighthouse-core/scripts/git3po-rules/resolve-current-tab.yaml
  lighthouse-core/scripts/git3po-rules/tracing-start-wasnt-found.yaml
  lighthouse-core/scripts/git3po-rules/tracing.yaml
  lighthouse-core/scripts/git3po-rules/url-runner.yaml
  lighthouse-core/scripts/run-git3po.sh
Labels: cla: yes

#10242 core(noopener): use node detail type
  lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js
  lighthouse-core/gather/gatherers/anchor-elements.js
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
  lighthouse-core/test/audits/dobetterweb/external-anchors-use-rel-noopener-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
  types/artifacts.d.ts
Labels: cla: yes

#10254 build: use npm pack'd lighthouse in doc integrations
  .appveyor.yml
  .npmignore
  build/build-pack.sh
  docs/recipes/auth/package.json
  docs/recipes/integration-test/package.json
  package.json
Labels: cla: yes, land-when-ci-is-green

#10253 docs: recipe for using puppeteer in a gatherer
  docs/recipes/custom-gatherer-puppeteer/custom-audit.js
  docs/recipes/custom-gatherer-puppeteer/custom-config.js
  docs/recipes/custom-gatherer-puppeteer/custom-gatherer.js
  docs/recipes/custom-gatherer-puppeteer/package.json
  docs/recipes/custom-gatherer-puppeteer/readme.md
  docs/recipes/custom-gatherer-puppeteer/test.sh
  package.json
Labels: cla: yes, land-when-ci-is-green

#10263 docs(readme): yarn test-docs, jq
  readme.md
Labels: cla: yes

#10256 misc(git3po): land-when-green
  lighthouse-core/scripts/git3po-rules/land-when-green.yaml
Labels: cla: yes

#10265 misc: delete CODEOWNERS now that we have a review rotation
  .github/CODEOWNERS
Labels: cla: yes, land-when-ci-is-green

#10250 docs: add protobuf install directions
  readme.md
Labels: cla: yes, land-when-ci-is-green

#10266 misc(git3po): use --start-at
  lighthouse-core/scripts/git3po-rules/cannot-attach-to-this-target.yaml
  lighthouse-core/scripts/git3po-rules/failed-document-request.yaml
  lighthouse-core/scripts/git3po-rules/failed-to-construct-url.yaml
  lighthouse-core/scripts/git3po-rules/invalid-url.yaml
  lighthouse-core/scripts/git3po-rules/multiple-tabs.yaml
  lighthouse-core/scripts/git3po-rules/no-fcp.yaml
  lighthouse-core/scripts/git3po-rules/no-tabid-set-for-sendcommand.yaml
  lighthouse-core/scripts/git3po-rules/page-hung.yaml
  lighthouse-core/scripts/git3po-rules/parsing-problem.yaml
  lighthouse-core/scripts/git3po-rules/protocol-timeout.yaml
  lighthouse-core/scripts/git3po-rules/read-failed.yaml
  lighthouse-core/scripts/git3po-rules/resolve-current-tab.yaml
  lighthouse-core/scripts/git3po-rules/tracing-start-wasnt-found.yaml
  lighthouse-core/scripts/git3po-rules/tracing.yaml
  lighthouse-core/scripts/git3po-rules/url-runner.yaml
  lighthouse-core/scripts/run-git3po.sh
Labels: cla: yes, land-when-ci-is-green

#10255 misc(git3po): lock-resolved
  lighthouse-core/scripts/git3po-rules/lock-resolved.yaml
Labels: cla: yes, land-when-ci-is-green

#9836 docs(readme): Add siteimprove to integrations section
  readme.md
Labels: cla: yes, waiting4committer

#10072 core(audits): add handling of 'incomplete' results from axe-core
  lighthouse-cli/test/smokehouse/test-definitions/a11y/expectations.js
  lighthouse-core/audits/accessibility/axe-audit.js
  lighthouse-core/audits/accessibility/form-field-multiple-labels.js
  lighthouse-core/gather/gatherers/accessibility.js
  lighthouse-core/test/audits/accessibility/axe-audit-test.js
  lighthouse-core/test/report/html/renderer/category-renderer-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
  types/artifacts.d.ts
Labels: cla: yes, needs-discussion

#10001 core(tracehouse): improved attribution for XHRs + paint/layout/HTML
  lighthouse-cli/test/fixtures/tricky-main-thread-consumer.js
  lighthouse-cli/test/fixtures/tricky-main-thread-library.js
  lighthouse-cli/test/smokehouse/test-definitions/lantern/lantern-expectations.js
  lighthouse-core/audits/bootup-time.js
  lighthouse-core/computed/main-thread-tasks.js
  lighthouse-core/gather/driver.js
  lighthouse-core/lib/tracehouse/main-thread-tasks.js
  lighthouse-core/lib/tracehouse/trace-processor.js
  lighthouse-core/test/audits/bootup-time-test.js
  lighthouse-core/test/audits/third-party-summary-test.js
  lighthouse-core/test/computed/trace-of-tab-test.js
  lighthouse-core/test/lib/tracehouse/main-thread-tasks-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
  types/artifacts.d.ts
  types/externs.d.ts
Labels: cla: yes, waiting4reviewer

#10078 core(gather): new computed artifact, js-bundles
  .eslintignore
  .travis.yml
  build/build-cdt-lib.js
  lighthouse-core/computed/js-bundles.js
  lighthouse-core/gather/gatherers/source-maps.js
  lighthouse-core/lib/cdt/Common.js
  lighthouse-core/lib/cdt/SDK.js
  lighthouse-core/lib/cdt/generated/SourceMap.js
  lighthouse-core/test/computed/js-bundles-test.js
  lighthouse-core/test/fixtures/source-maps/foo.min.js
  lighthouse-core/test/fixtures/source-maps/foo.min.js.map
  lighthouse-core/test/fixtures/source-maps/squoosh.js
  lighthouse-core/test/fixtures/source-maps/squoosh.js.map
  package.json
  tsconfig.json
  types/artifacts.d.ts
  yarn.lock
Labels: cla: yes, land-when-ci-is-green

#10099 report: add channel to runtime settings
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/report/html/renderer/report-renderer.js
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/test/results/sample_v2.json
  proto/lighthouse-result.proto
  proto/sample_v2_round_trip.json
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#10271 misc(git3po): need milliseconds epoch, not seconds
  lighthouse-core/scripts/run-git3po.sh
Labels: cla: yes

#10270 tests(audits): Return type correction (LH.Audit.Result -> LH.Audit.Product)
  lighthouse-core/audits/accessibility/axe-audit.js
Labels: cla: yes

#10272 deps: bundlesize to 0.18.0
  package.json
  yarn.lock
Labels: cla: yes

#9924 misc(build): bundle pub ads plugin for devtools
  build/build-bundle.js
  clients/devtools-entry.js
  lighthouse-core/config/config-helpers.js
  lighthouse-core/config/config.js
  package.json
  types/node.d.ts
  yarn.lock
Labels: 6.0, cla: yes, land-when-ci-is-green

#10056 deps: update axe-core to 3.4.1
  lighthouse-cli/test/smokehouse/test-definitions/a11y/expectations.js
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green

#10274 misc: add CODEOWNERS to finish codereview assignment setup
  .github/CODEOWNERS
Labels: cla: yes

#10246 docs: Fix broken link to aria-toggle-field-name
  lighthouse-core/audits/accessibility/aria-toggle-field-name.js
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes, land-when-ci-is-green

#10277 docs: tweaks to auth + pptr docs
  docs/authenticated-pages.md
  docs/puppeteer.md
Labels: cla: yes

#10282 misc: tweak CODEOWNERS to finish codereview assignment setup
  .github/CODEOWNERS
Labels: cla: yes

#10283 docs(readme): add a table of contents
  readme.md
Labels: cla: yes

#10279 misc: write lantern accuracy to file on update
  lighthouse-core/scripts/lantern/assert-master-lantern-values-unchanged.js
  lighthouse-core/scripts/lantern/constants.js
  lighthouse-core/scripts/lantern/print-correlations.js
  lighthouse-core/scripts/lantern/update-master-lantern-values.js
  lighthouse-core/test/fixtures/lantern-master-accuracy.json
  lighthouse-core/test/scripts/lantern/constants-test.js
  tsconfig.json
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#10280 core(lantern): do not create self-dependencies via timers
  lighthouse-core/computed/page-dependency-graph.js
  lighthouse-core/lib/dependency-graph/base-node.js
  lighthouse-core/test/computed/page-dependency-graph-test.js
  lighthouse-core/test/lib/dependency-graph/base-node-test.js
Labels: cla: yes

#9903 core(uses-rel-preconnect): warn on 3+ preconnects
  lighthouse-core/audits/uses-rel-preconnect.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/uses-rel-preconnect-test.js
Labels: cla: yes, waiting4committer

#10168 core(installable-manifest): check for fetchable icon
  lighthouse-cli/test/fixtures/launcher-icon-4x.png
  lighthouse-cli/test/smokehouse/test-definitions/offline-local/offline-expectations.js
  lighthouse-core/audits/installable-manifest.js
  lighthouse-core/audits/service-worker.js
  lighthouse-core/audits/splash-screen.js
  lighthouse-core/audits/themed-omnibox.js
  lighthouse-core/computed/manifest-values.js
  lighthouse-core/config/config.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/gather/gatherers/start-url.js
  lighthouse-core/scripts/build-report-for-autodeployment.js
  lighthouse-core/test/audits/installable-manifest-test.js
  lighthouse-core/test/audits/service-worker-test.js
  lighthouse-core/test/audits/splash-screen-test.js
  lighthouse-core/test/audits/themed-omnibox-test.js
  lighthouse-core/test/computed/manifest-values-test.js
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/gather/gatherers/start-url-test.js
  lighthouse-core/test/report/html/renderer/report-renderer-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
  types/artifacts.d.ts
Labels: cla: yes, land-when-ci-is-green, waiting4committer
