Repository GoogleChrome/lighthouse, pull requests merged in 2020-05, with the labels that each got.

#10627 tests(gh): increase cli test timeout to reduce flakes
  lighthouse-cli/test/cli/run-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#10682 misc(build): fix npm link issue
  package.json
Labels: cla: yes, waiting4reviewer

#10339 core(driver): use last frameNavigated event to determine finalUrl
  lighthouse-cli/test/fixtures/js-redirect.html
  lighthouse-cli/test/fixtures/redirects-final.html
  lighthouse-cli/test/fixtures/static-server.js
  lighthouse-cli/test/smokehouse/test-definitions/redirects/expectations.js
  lighthouse-core/gather/driver.js
  lighthouse-core/test/gather/driver-test.js
Labels: 6.0, cla: yes, land-when-ci-is-green

#10637 deps(axe-core): upgrade to 3.5.3
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#10663 misc(lantern-collect): update gcp scripts
  lighthouse-core/scripts/lantern/collect/gcp-create-and-run.sh
  lighthouse-core/scripts/lantern/collect/gcp-run.sh
Labels: cla: yes, land-when-ci-is-green

#10700 core(resource-summary): rename size to transferSize
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-core/audits/performance-budget.js
  lighthouse-core/audits/resource-summary.js
  lighthouse-core/computed/resource-summary.js
  lighthouse-core/test/audits/performance-budget-test.js
  lighthouse-core/test/audits/resource-summary-test.js
  lighthouse-core/test/computed/resource-summary-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: 6.0, cla: yes, land-when-ci-is-green, waiting4reviewer

#10689 core(charset): add description link to web.dev guide
  lighthouse-core/audits/dobetterweb/charset.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes

#10711 deps: bump third-party-web to 0.11.1
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green

#10634 core(unused-javascript): check for SourceMaps before trying to use
  lighthouse-core/audits/byte-efficiency/unused-javascript.js
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#10714 core(maskable-icon): update description link to new web.dev guide
  lighthouse-core/audits/maskable-icon.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#10718 misc(build): don't let buildtracker fail the build
  .github/workflows/ci.yml
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#10676 docs(scoring): drop performance bit and update the rest
  docs/scoring.md
Labels: 6.0, cla: yes, waiting4reviewer

#10713 misc: add comment to TraceElements artifact
  types/artifacts.d.ts
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#10694 docs(readme): fix small typo
  readme.md
Labels: cla: yes, land-when-ci-is-green

#10715 core(scoring): redefine log-normal curves with median and p10 points
  lighthouse-core/audits/audit.js
  lighthouse-core/audits/bootup-time.js
  lighthouse-core/audits/byte-efficiency/total-byte-weight.js
  lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
  lighthouse-core/audits/dobetterweb/dom-size.js
  lighthouse-core/audits/mainthread-work-breakdown.js
  lighthouse-core/audits/metrics/cumulative-layout-shift.js
  lighthouse-core/audits/metrics/estimated-input-latency.js
  lighthouse-core/audits/metrics/first-contentful-paint-3g.js
  lighthouse-core/audits/metrics/first-contentful-paint.js
  lighthouse-core/audits/metrics/first-cpu-idle.js
  lighthouse-core/audits/metrics/first-meaningful-paint.js
  lighthouse-core/audits/metrics/interactive.js
  lighthouse-core/audits/metrics/largest-contentful-paint.js
  lighthouse-core/audits/metrics/max-potential-fid.js
  lighthouse-core/audits/metrics/speed-index.js
  lighthouse-core/audits/metrics/total-blocking-time.js
  lighthouse-core/audits/predictive-perf.js
  lighthouse-core/lib/statistics.js
  lighthouse-core/test/audits/audit-test.js
  lighthouse-core/test/lib/statistics-test.js
  lighthouse-core/test/results/sample_v2.json
  types/audit.d.ts
Labels: 6.0, cla: yes

#10727 tests: use brfs when bundling smokehouse
  build/build-smokehouse-bundle.js
  lighthouse-cli/test/smokehouse/test-definitions/source-maps/expectations.js
Labels: 6.0, cla: yes, land-when-ci-is-green, waiting4reviewer

#10643 core(offscreen-images): loosen to 3 viewports
  lighthouse-cli/test/fixtures/byte-efficiency/tester.html
  lighthouse-core/audits/byte-efficiency/offscreen-images.js
  lighthouse-core/test/audits/byte-efficiency/offscreen-images-test.js
Labels: cla: yes, land-when-ci-is-green

#10712 core(is-on-https): add Mixed Content verbiage to description
  lighthouse-core/audits/is-on-https.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4committer

#10728 core(metrics): do not round CLS in output
  lighthouse-core/audits/metrics.js
  lighthouse-core/computed/metrics/timing-summary.js
  lighthouse-core/test/audits/__snapshots__/metrics-test.js.snap
  lighthouse-core/test/audits/metrics-test.js
  lighthouse-core/test/computed/metrics/timing-summary-test.js
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: cla: yes, waiting4reviewer

#10731 Use Runtime.callFunctionOn to set marker attribute
  lighthouse-core/audits/largest-contentful-paint-element.js
  lighthouse-core/gather/gatherers/trace-elements.js
Labels: cla: yes, waiting4reviewer

#10733 core: assert.strict doesn't work in bundles
  lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
  lighthouse-core/computed/critical-request-chains.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#10725 report: link to updated scoring documentation
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/config/default-config.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: 6.0, cla: yes, waiting4reviewer

#10645 i18n(import): new audits, dropdowns, and columns
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
  package.json
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#10743 report(resource-summary): fix size heading key
  lighthouse-core/audits/resource-summary.js
  lighthouse-core/test/results/sample_v2.json
Labels: 6.0, cla: yes

#10723 deps: upgrade yargs-parser to latest
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green

#10735 core: change ttfb audit name to server-response-time
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-core/audits/server-response-time.js
  lighthouse-core/config/default-config.js
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
  lighthouse-core/lib/i18n/swap-locale.js
  lighthouse-core/test/audits/server-response-time-test.js
  lighthouse-core/test/results/sample_v2.json
  stack-packs/packs/magento.js
  stack-packs/packs/react.js
  stack-packs/packs/wordpress.js
Labels: 6.0, cla: yes, waiting4reviewer

#10745 misc: add Wattspeed to the integrations list
  readme.md
Labels: cla: yes, waiting4committer

#10750 core(mixed-content): delete preset and audit
  docs/configuration.md
  docs/readme.md
  lighthouse-cli/bin.js
  lighthouse-cli/cli-flags.js
  lighthouse-cli/test/cli/bin-test.js
  lighthouse-cli/test/smokehouse/test-definitions/core-tests.js
  lighthouse-cli/test/smokehouse/test-definitions/mixed-content/mixed-content-expectations.js
  lighthouse-core/audits/mixed-content.js
  lighthouse-core/config/mixed-content-config.js
  lighthouse-core/gather/gatherers/mixed-content.js
  lighthouse-core/test/audits/mixed-content-test.js
  lighthouse-core/test/gather/gatherers/mixed-content-test.js
  package.json
  readme.md
  types/externs.d.ts
Labels: 6.0, cla: yes, land-when-ci-is-green

#10749 core(emulation): keep DPR at 2.625 for mobile emulation
  lighthouse-cli/test/fixtures/byte-efficiency/tester.html
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
  lighthouse-core/lib/emulation.js
Labels: 6.0, cla: yes, waiting4reviewer

#10636 report: improve color contrast of top-level errors
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/report/html/templates.html
Labels: 6.0, cla: yes, land-when-ci-is-green, waiting4committer

#10758 misc(scripts): fix devtools filename doublecheck
  lighthouse-core/scripts/roll-to-devtools.sh
Labels: 6.0, cla: yes, land-when-ci-is-green, waiting4reviewer

#10761 report: define monospace fontsize relative to report-font-size
  lighthouse-core/report/html/report-styles.css
Labels: 6.0??, DevTools, cla: yes, land-when-ci-is-green

#10762 clients(devtools): fix Runtime.cachedResources reference
  build/build-dt-report-resources.js
  clients/devtools-report-assets.js
  lighthouse-core/report/html/html-report-assets.js
Labels: 6.0, cla: yes, land-when-ci-is-green, waiting4reviewer

#10765 misc: drop trailing whitespace in css
  lighthouse-core/report/html/report-styles.css
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#10695 report(metrics): use css grid so metrics are aligned
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
  lighthouse-viewer/test/viewer-test-pptr.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#10754 report: link to calculator w/ values
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/lighthouse-result.proto
Labels: 6.0, cla: yes, land-when-ci-is-green, waiting4reviewer

#10766 misc: .mailmap
  .mailmap
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#10756 core: add desktop score curves for TBT and LCP
  lighthouse-core/audits/metrics/largest-contentful-paint.js
  lighthouse-core/audits/metrics/total-blocking-time.js
  lighthouse-core/test/audits/metrics/largest-contentful-paint-test.js
  lighthouse-core/test/audits/metrics/total-blocking-time-test.js
Labels: 6.0, cla: yes, land-when-ci-is-green

#10724 deps: upgrade chrome-launcher@0.13.2
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green

#10763 report: add device type and version to scorecalc link
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/report/html/renderer/report-renderer.js
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
Labels: 6.0??, cla: yes, waiting4reviewer

#10767 report: correctly handle CLS values of 0 for calc link
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
Labels: 6.0??, cla: yes, waiting4reviewer

#10771 deps(snyk): update snyk snapshot
  lighthouse-core/test/results/sample_v2.json
  third-party/snyk/snapshot.json
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#10773 report: fix regression in report renderer for devtools
  lighthouse-core/report/html/renderer/report-renderer.js
Labels: 6.0, cla: yes, land-when-ci-is-green, waiting4reviewer

#10776 deps: lighthouse-plugin-publisher-ads@^1.1.0-beta.0
  package.json
  yarn.lock
Labels: 6.0, cla: yes, land-when-ci-is-green, waiting4reviewer

#10778 report(metrics): [revert] use css grid so metrics are aligned (#10695)
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
  lighthouse-viewer/test/viewer-test-pptr.js
Labels: 6.0, cla: yes, land-when-ci-is-green, waiting4reviewer

#10780 v6.0.0
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  lighthouse-core/test/results/sample_v2.json
  package.json
Labels: cla: yes

#10787 core(emulation): bump chrome versions
  lighthouse-core/lib/emulation.js
Labels: cla: yes, land-when-ci-is-green

#10804 misc(changelog): update for latest version
  changelog.md
Labels: cla: yes, waiting4reviewer

#10801 core(image-size-responsive): quantize DPRs
  lighthouse-core/audits/image-size-responsive.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/image-size-responsive-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4reviewer

#10690 docs(contributing): add tips for audit and gatherer PRs
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  docs/hacking-tips.md
  proto/README.md
  readme.md
Labels: cla: yes, waiting4reviewer

#10807 misc: update changelog for v6.0.0
  changelog.md
Labels: cla: yes, waiting4reviewer

#10821 misc(changelog): add missing 6.0.0 new contributors
  changelog.md
Labels: cla: yes, land-when-ci-is-green

#10662 new_audit(crawlable-anchors): adds an anchor-href audit
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/fixtures/seo/seo-failure-cases.html
  lighthouse-cli/test/fixtures/seo/seo-tester.html
  lighthouse-cli/test/smokehouse/test-definitions/seo/expectations.js
  lighthouse-core/audits/seo/crawlable-anchors.js
  lighthouse-core/config/default-config.js
  lighthouse-core/gather/gatherers/anchor-elements.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/seo/crawlable-anchors-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: cla: yes

#10818 docs(readme): update PageSpeed Green description
  readme.md
Labels: cla: yes, waiting4reviewer

#10847 core(preload): ignore cross-frame requests
  lighthouse-core/audits/uses-rel-preload.js
  lighthouse-core/test/audits/uses-rel-preload-test.js
  lighthouse-core/test/network-records-to-devtools-log.js
Labels: cla: yes, waiting4reviewer

#10855 report: fix the width of the 3-dots menu in topbar
  lighthouse-core/report/html/templates.html
Labels: cla: yes, waiting4reviewer

#10849 core(legacy-javascript): use third-party-web for scoring
  lighthouse-core/audits/legacy-javascript.js
  lighthouse-core/audits/third-party-summary.js
  lighthouse-core/lib/third-party-web.js
  lighthouse-core/test/audits/legacy-javascript-test.js
  lighthouse-core/test/lib/third-party-web-test.js
Labels: cla: yes, waiting4reviewer

#10858 report: update onMenuFocusOut typing to remove FocusEvent cast
  lighthouse-core/report/html/renderer/report-ui-features.js
Labels: cla: yes, waiting4reviewer

#10828 deps: update to lhci 0.4.0
  lighthouse-core/scripts/dogfood-lhci.sh
Labels: cla: yes, waiting4reviewer

#10852 core(legacy-javascript): fix core-js 3 detection
  lighthouse-core/audits/legacy-javascript.js
  lighthouse-core/scripts/legacy-javascript/run.js
  lighthouse-core/scripts/legacy-javascript/summary-signals-nomaps.json
  lighthouse-core/scripts/legacy-javascript/summary-signals.json
  lighthouse-core/scripts/legacy-javascript/summary-sizes.txt
Labels: cla: yes, waiting4reviewer

#10822 core(renderer): fix null Util.i18n in PSI renderer
  lighthouse-core/report/html/renderer/psi.js
  lighthouse-core/test/report/html/renderer/psi-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#10859 core(median-run): add computeMedianRun to lib
  docs/variability.md
  lighthouse-core/lib/median-run.js
  lighthouse-core/test/lib/median-run-test.js
Labels: cla: yes, waiting4reviewer

#10664 core: new inspector issues gatherer for Audit.IssueAdded events
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-core/config/default-config.js
  lighthouse-core/gather/gatherers/inspector-issues.js
  package.json
  types/artifacts.d.ts
  yarn.lock
Labels: cla: yes, waiting4reviewer

#10827 tests(smokehouse): do not assert on flaky node path
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
Labels: cla: yes, waiting4reviewer

#10826 docs(readme): update integrations section
  readme.md
Labels: cla: yes, waiting4reviewer

#10789 report(metrics): use css grid so metrics are aligned
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
  lighthouse-viewer/test/viewer-test-pptr.js
Labels: cla: yes, waiting4reviewer
