Repository GoogleChrome/lighthouse, pull requests merged in 2020-08, with the labels that each got.

#11198 deps: update dot-prop secondary dependency
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#11221 tests: update chromestatus expecatations
  lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa-expectations.js
Labels: cla: yes, waiting4reviewer

#11105 new_audit: report animations not run on compositor
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/fixtures/perf/animations.html
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-core/audits/non-composited-animations.js
  lighthouse-core/config/default-config.js
  lighthouse-core/gather/gatherers/trace-elements.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/minify-trace.js
  lighthouse-core/test/audits/non-composited-animations-test.js
  lighthouse-core/test/fixtures/traces/animation.json
  lighthouse-core/test/gather/gatherers/trace-elements-test.js
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
  types/externs.d.ts
Labels: cla: yes, waiting4committer

#11062 core: add FormElements gatherer
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/fixtures/form.html
  lighthouse-cli/test/smokehouse/test-definitions/core-tests.js
  lighthouse-cli/test/smokehouse/test-definitions/forms/form-config.js
  lighthouse-cli/test/smokehouse/test-definitions/forms/form-expectations.js
  lighthouse-core/config/default-config.js
  lighthouse-core/gather/gatherers/form-elements.js
  types/artifacts.d.ts
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#11188 core(image-elements): collect CSS sizing, ShadowRoot, & position
  lighthouse-cli/test/fixtures/byte-efficiency/tester.html
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/byte-config.js
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
  lighthouse-core/audits/unsized-images.js
  lighthouse-core/gather/gatherers/image-elements.js
  lighthouse-core/gather/gatherers/seo/font-size.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/unsized-images-test.js
  types/artifacts.d.ts
Labels: cla: yes, land-when-ci-is-green

#11217 core(config): unsized-images to default
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/config/default-config.js
  lighthouse-core/config/experimental-config.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4committer

#11172 core(stacks): timeout stack detection
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-core/lib/stack-collector.js
Labels: cla: yes, land-when-ci-is-green

#11223 deps(snyk): update script to prune <0.0.0 and update snapshot
  lighthouse-core/scripts/cleanup-vuln-snapshot.js
  third-party/snyk/snapshot.json
Labels: cla: yes, waiting4reviewer

#11229 tests: istanbul ignore inpage function
  lighthouse-core/gather/gatherers/image-elements.js
Labels: cla: yes, waiting4reviewer

#11225 i18n: import
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
Labels: cla: yes, waiting4reviewer

#11220 report: vertically center thumbnails
  lighthouse-core/report/html/report-styles.css
Labels: cla: yes, waiting4reviewer

#11230 pr
  lighthouse-core/audits/timing-budget.js
Labels: cla: yes, waiting4reviewer

#11209 report: correctly display CLS in budget table
  lighthouse-core/audits/timing-budget.js
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/test/audits/timing-budget-test.js
  types/audit-details.d.ts
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11232 v6.2.0
  build/changelog-generator/index.js
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  lighthouse-core/scripts/release/bump-versions.js
  lighthouse-core/test/results/sample_v2.json
  package.json
Labels: cla: yes, waiting4reviewer

#11233 misc: tweak gcp scripts to work in google corp
  .gitignore
  lighthouse-core/scripts/gcp-collection/README.md
  lighthouse-core/scripts/gcp-collection/run.sh
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11228 misc: rephrase comments to be more inclusive
  docs/releasing.md
  lighthouse-core/lib/tracehouse/main-thread-tasks.js
  lighthouse-core/lib/tracehouse/trace-processor.js
  lighthouse-core/scripts/i18n/bake-ctc-to-lhl.js
  lighthouse-core/test/lib/tracehouse/main-thread-tasks-test.js
  lighthouse-core/test/report/html/renderer/psi-test.js
Labels: cla: yes, waiting4reviewer

#10299 i18n: make double dollar validation less strict
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/test/scripts/i18n/collect-strings-test.js
Labels: cla: yes, waiting4reviewer

#11239 misc: fix typo in method name
  lighthouse-core/audits/server-response-time.js
Labels: cla: yes, waiting4reviewer

#11248 core(font-size): remove deprecated DOM.getFlattenedDocument
  lighthouse-core/audits/seo/font-size.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gatherers/seo/font-size.js
  lighthouse-core/test/audits/seo/font-size-test.js
  lighthouse-core/test/gather/gatherers/seo/font-size-test.js
  types/artifacts.d.ts
Labels: cla: yes, waiting4reviewer

#11250 docs(readme): add related project: lighthouse-viewer
  readme.md
Labels: cla: yes, waiting4reviewer

#11212 docs: add Code of Conduct to project
  CODE_OF_CONDUCT.md
Labels: cla: yes, waiting4committer

#11143 docs(throttling): replace comcast with throttle and add more windows options
  docs/throttling.md
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11257 misc: add gcp fleet creation scripts
  lighthouse-core/scripts/gcp-collection/README.md
  lighthouse-core/scripts/gcp-collection/fleet-create-directories.js
  lighthouse-core/scripts/gcp-collection/fleet-create.sh
  lighthouse-core/scripts/gcp-collection/fleet-status.sh
  lighthouse-core/scripts/gcp-collection/run.sh
Labels: cla: yes, waiting4reviewer

#11096 new_audit: add large-javascript-libraries audit
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/audits/large-javascript-libraries.js
  lighthouse-core/config/default-config.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/large-javascript-libraries/bundlephobia-database.json
  lighthouse-core/lib/large-javascript-libraries/library-suggestions.js
  lighthouse-core/scripts/generate-bundlephobia-database.js
  lighthouse-core/test/audits/byte-efficiency/large-javascript-libraries-test.js
  lighthouse-core/test/results/sample_v2.json
  package.json
  types/bundle-phobia-cli/index.d.ts
  yarn.lock
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#11246 core: add unsupported css properties to non-composited-animations audit
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-core/audits/non-composited-animations.js
  lighthouse-core/gather/gatherers/trace-elements.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/non-composited-animations-test.js
  lighthouse-core/test/fixtures/traces/animation.json
  lighthouse-core/test/gather/gatherers/trace-elements-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
  types/externs.d.ts
Labels: cla: yes, waiting4reviewer

#11024 report: use dash gauge for categories with entirely n/a audits
  lighthouse-core/report/html/renderer/category-renderer.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/test/report/html/renderer/category-renderer-test.js
Labels: cla: yes, waiting4committer

#11268 core(non-composited-animations): add more actionable failure reasons
  lighthouse-core/audits/non-composited-animations.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/non-composited-animations-test.js
Labels: cla: yes, land-when-ci-is-green

#9822 core(renderer): improve the unknown timezone checks in util.js
  lighthouse-core/report/html/renderer/i18n.js
  lighthouse-core/test/report/html/renderer/i18n-test.js
Labels: cla: yes, waiting4committer

#11278 misc: fix types in duplicated-javascript
  lighthouse-core/audits/byte-efficiency/duplicated-javascript.js
Labels: cla: yes, waiting4reviewer

#11288 docs(readme): align headings with table of contents
  readme.md
Labels: cla: yes, waiting4reviewer

#11236 new_audit: add valid-source-maps audit
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/audits/valid-source-maps.js
  lighthouse-core/config/default-config.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/valid-source-maps-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11219 report(third-party-summary): show resources for entity
  lighthouse-core/audits/third-party-summary.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/third-party-summary-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11258 core(non-composited-animations): update the "learn more" link
  lighthouse-core/audits/non-composited-animations.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4reviewer

#11299 report: handle invalid urls for source location items
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/test/report/html/renderer/details-renderer-test.js
Labels: cla: yes, rls-blocker, waiting4reviewer

#11308 docs: add audit naming guide
  docs/new-audits.md
Labels: cla: yes, waiting4reviewer

#11304 misc(benchmark): update BenchmarkIndex for m86 changes
  lighthouse-core/gather/driver.js
  lighthouse-core/lib/page-functions.js
  lighthouse-core/scripts/benchmark.js
  package.json
Labels: cla: yes, waiting4reviewer

#11301 deps: lighthouse-plugin-publisher-ads@1.2.0
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#11305 docs(readme): add related project: site-audit-seo
  readme.md
Labels: cla: yes, waiting4reviewer

#11277 core(module-duplication): ignore smaller modules
  lighthouse-core/computed/module-duplication.js
  lighthouse-core/test/audits/byte-efficiency/duplicated-javascript-test.js
  lighthouse-core/test/computed/module-duplication-test.js
Labels: cla: yes, waiting4reviewer

#11298 core(trace-elements): do not break on unresolvable node id
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gatherers/trace-elements.js
  lighthouse-core/test/gather/gatherers/trace-elements-test.js
Labels: cla: yes, rls-blocker, waiting4reviewer

#11255 new_audit: add preload-fonts audit
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/fixtures/perf/cors-fonts.css
  lighthouse-cli/test/fixtures/perf/fonts.html
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/perf/perf-config.js
  lighthouse-core/audits/font-display.js
  lighthouse-core/audits/preload-fonts.js
  lighthouse-core/config/default-config.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/preload-fonts-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4reviewer

#11307 core(response-time): add time spent to details
  lighthouse-core/audits/server-response-time.js
  lighthouse-core/test/audits/server-response-time-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4reviewer

#11176 tests: run chromium webtests for devtools integration
  .eslintignore
  .github/workflows/devtools.yml
  lighthouse-core/scripts/roll-to-devtools.sh
  lighthouse-core/test/chromium-web-tests/README.md
  lighthouse-core/test/chromium-web-tests/blink-tools.patch
  lighthouse-core/test/chromium-web-tests/download-blink-tools.sh
  lighthouse-core/test/chromium-web-tests/download-content-shell.sh
  lighthouse-core/test/chromium-web-tests/download-depot-tools.sh
  lighthouse-core/test/chromium-web-tests/download-devtools.sh
  lighthouse-core/test/chromium-web-tests/run-web-tests.sh
  lighthouse-core/test/chromium-web-tests/test-locally.sh
  package.json
  third-party/chromium-webtests/README.md
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-flags-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-flags-run.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-limited-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-limited-run.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-prevent-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-prevent-run.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/resources/lighthouse-basic.html
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/resources/lighthouse-emulate-pass.html
  third-party/download-content-shell/LICENSE
  third-party/download-content-shell/README.md
  third-party/download-content-shell/download-content-shell.js
  third-party/download-content-shell/utils.js
  tsconfig.json
Labels: cla: yes, waiting4reviewer

#11317 new_audit(revert): move unsized-images to experimental due to perf impact
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/fixtures/byte-efficiency/tester.html
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/byte-config.js
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
  lighthouse-core/audits/unsized-images.js
  lighthouse-core/config/default-config.js
  lighthouse-core/config/experimental-config.js
  lighthouse-core/gather/gatherers/image-elements.js
  lighthouse-core/gather/gatherers/seo/font-size.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/unsized-images-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: cla: yes, rls-blocker, waiting4reviewer

#11303 core(global-listeners): dedupe duplicate events in GlobalListener gatherer
  lighthouse-core/gather/gatherers/global-listeners.js
  lighthouse-core/test/gather/gatherers/global-listeners-test.js
Labels: cla: yes, waiting4reviewer

#11324 i18n: import
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
Labels: cla: yes, waiting4reviewer

#11328 tests(devtools): script improvements and rebaseline
  lighthouse-core/test/chromium-web-tests/download-depot-tools.sh
  lighthouse-core/test/chromium-web-tests/download-devtools.sh
  lighthouse-core/test/chromium-web-tests/test-locally.sh
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run-expected.txt
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#10729 report: show axe version in runtime settings
  lighthouse-core/gather/gatherers/accessibility.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/report/html/renderer/report-renderer.js
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/runner.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  proto/lighthouse-result.proto
  types/artifacts.d.ts
  types/lhr.d.ts
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11327 i18n: translate remaining strings in font-size
  lighthouse-core/audits/seo/font-size.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/seo/font-size-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes

#11247 misc: add benchmark script with octane and speedometer
  lighthouse-core/scripts/benchmark-plus-extras.js
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#11332 v6.3.0
  build/changelog-generator/templates/header.hbs
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  docs/releasing.md
  lighthouse-core/scripts/release/test.sh
  lighthouse-core/scripts/roll-to-devtools.sh
  lighthouse-core/test/chromium-web-tests/test-locally.sh
  lighthouse-core/test/results/sample_v2.json
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes, waiting4committer

#11306 core(preconnect): ignore unimportant origins
  lighthouse-cli/test/fixtures/perf/preload_tester.js
  lighthouse-core/audits/uses-rel-preconnect.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/uses-rel-preconnect-test.js
  lighthouse-core/test/create-test-trace.js
Labels: cla: yes, waiting4reviewer

#11325 docs: add CPU throttling guide
  docs/throttling.md
Labels: cla: yes, waiting4reviewer

#11338 i18n: add more translator strings to font-size
  lighthouse-core/audits/seo/font-size.js
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes

#11331 tests(devtools): fail on unset/unbound env variable
  lighthouse-core/scripts/download-chrome.sh
  lighthouse-core/test/chromium-web-tests/download-blink-tools.sh
  lighthouse-core/test/chromium-web-tests/download-depot-tools.sh
  lighthouse-core/test/chromium-web-tests/download-devtools.sh
  lighthouse-core/test/chromium-web-tests/run-web-tests.sh
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#11072 core(tracehouse): add CPU trace profiler model
  lighthouse-core/lib/minify-trace.js
  lighthouse-core/lib/tracehouse/cpu-profile-model.js
  lighthouse-core/scripts/lantern/minify-trace.js
  lighthouse-core/test/fixtures/traces/cpu-profiler-m86.trace.json
  lighthouse-core/test/lib/tracehouse/cpu-profile-model-test.js
  types/externs.d.ts
Labels: cla: yes, waiting4reviewer

#11340 new_audit: unsized-images reland
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/fixtures/byte-efficiency/tester.html
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/byte-config.js
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
  lighthouse-core/audits/unsized-images.js
  lighthouse-core/config/default-config.js
  lighthouse-core/config/experimental-config.js
  lighthouse-core/gather/gatherers/image-elements.js
  lighthouse-core/gather/gatherers/seo/font-size.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/unsized-images-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: cla: yes, waiting4reviewer

#11329 core: expose service worker url on service worker audit
  lighthouse-core/audits/service-worker.js
  lighthouse-core/test/audits/service-worker-test.js
Labels: cla: yes, waiting4reviewer

#11346 misc: fix run-web-tests.sh
  lighthouse-core/test/chromium-web-tests/run-web-tests.sh
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#11349 i18n: accept array of locales in lookupLocale
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/test/lib/i18n/i18n-test.js
  types/lookup-closest-locale/index.d.ts
Labels: cla: yes, waiting4reviewer
