Repository GoogleChrome/lighthouse, pull requests merged in 2020-12, with the labels that each got.

#11730 v6.5.0
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  docs/releasing.md
  lighthouse-core/test/results/sample_v2.json
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes, waiting4committer

#11731 tests: update failing trace webtest to use Tooltip module
  .github/workflows/devtools.yml
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run.js
Labels: cla: yes, land-when-ci-is-green

#11656 misc: drop support for node 10
  .eslintrc.js
  .github/workflows/ci.yml
  .github/workflows/devtools.yml
  .travis.yml
  build/build-bundle.js
  build/build-lightrider-bundles.js
  build/build-smokehouse-bundle.js
  build/build-utils.js
  build/gh-pages-app.js
  docs/headless-chrome.md
  lighthouse-core/gather/driver.js
  lighthouse-core/scripts/dogfood-lhci.sh
  package.json
  readme.md
  yarn.lock
Labels: 7.0, breaking, cla: yes, land-when-ci-is-green, waiting4committer

#10816 core(driver): create eval code using interface
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/driver/execution-context.js
  lighthouse-core/gather/fetcher.js
  lighthouse-core/gather/gatherers/link-elements.js
  lighthouse-core/gather/gatherers/meta-elements.js
  lighthouse-core/gather/gatherers/script-elements.js
  lighthouse-core/gather/gatherers/seo/tap-targets.js
  lighthouse-core/lib/page-functions.js
  lighthouse-core/test/gather/driver/execution-context-test.js
  lighthouse-core/test/gather/gatherers/link-elements-test.js
Labels: cla: yes

#11736 misc(release): print-contributors.js script
  lighthouse-core/scripts/print-contributors.js
  lighthouse-core/scripts/release/prepare-commit.sh
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11743 core(config): remove gatherer options support
  lighthouse-core/config/config.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/test/config/config-test.js
  lighthouse-core/test/gather/gather-runner-test.js
  types/config.d.ts
  types/gatherer.d.ts
Labels: 7.0, breaking, cla: yes, land-when-ci-is-green

#11742 core(fr): add fraggle rock driver
  lighthouse-core/fraggle-rock/gather/driver.js
  lighthouse-core/fraggle-rock/gather/session.js
  lighthouse-core/gather/driver.js
  lighthouse-core/test/fraggle-rock/gather/driver-test.js
  lighthouse-core/test/fraggle-rock/gather/session-test.js
  tsconfig.json
  types/gatherer.d.ts
Labels: cla: yes, waiting4committer

#11752 core: fix NodeDetails type mismatch
  lighthouse-core/audits/accessibility/axe-audit.js
  lighthouse-core/audits/autocomplete.js
  lighthouse-core/audits/dobetterweb/dom-size.js
  lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js
  lighthouse-core/audits/dobetterweb/password-inputs-can-be-pasted-into.js
  lighthouse-core/audits/largest-contentful-paint-element.js
  lighthouse-core/audits/layout-shift-elements.js
  lighthouse-core/audits/unsized-images.js
  lighthouse-core/gather/gatherers/link-elements.js
  lighthouse-core/gather/gatherers/script-elements.js
  lighthouse-core/test/gather/gatherers/link-elements-test.js
  types/artifacts.d.ts
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11753 misc: remove unneeded type casts
  lighthouse-cli/bin.js
  lighthouse-core/audits/byte-efficiency/offscreen-images.js
  lighthouse-core/audits/byte-efficiency/render-blocking-resources.js
  lighthouse-core/audits/critical-request-chains.js
  lighthouse-core/audits/errors-in-console.js
  lighthouse-core/audits/image-size-responsive.js
  lighthouse-core/audits/large-javascript-libraries.js
  lighthouse-core/audits/preload-lcp-image.js
  lighthouse-core/audits/redirects.js
  lighthouse-core/audits/seo/plugins.js
  lighthouse-core/audits/third-party-summary.js
  lighthouse-core/audits/uses-rel-preload.js
  lighthouse-core/audits/valid-source-maps.js
  lighthouse-core/computed/metrics/first-meaningful-paint.js
  lighthouse-core/computed/metrics/largest-contentful-paint-all-frames.js
  lighthouse-core/computed/metrics/largest-contentful-paint.js
  lighthouse-core/config/config.js
  lighthouse-core/gather/connections/connection.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gatherers/css-usage.js
  lighthouse-core/lib/dependency-graph/simulator/simulator.js
  lighthouse-core/lib/lantern-trace-saver.js
  lighthouse-core/lib/network-request.js
  lighthouse-core/lib/page-functions.js
  lighthouse-core/lib/sd-validation/sd-validation.js
  lighthouse-core/lib/stack-collector.js
  lighthouse-core/report/html/renderer/i18n.js
  lighthouse-core/report/html/renderer/psi.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/runner.js
  lighthouse-core/scripts/lantern/collect/common.js
  lighthouse-core/scripts/legacy-javascript/examine-latest-run.js
  lighthouse-core/test/gather/driver/execution-context-test.js
  lighthouse-core/test/lib/i18n/swap-locale-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#11648 misc(build): fix bundling publisher ads plugin in Lightrider
  lighthouse-core/config/config.js
Labels: cla: yes, waiting4reviewer

#11768 core(full-page-screenshot): simplify details shape
  lighthouse-core/audits/full-page-screenshot.js
  lighthouse-core/gather/gatherers/full-page-screenshot.js
  lighthouse-core/report/html/renderer/report-renderer.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/test/test-utils.js
  types/audit-details.d.ts
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#11698 misc: avoid splitting node labels in the middle of unicode surrogate pairs
  .github/scripts/git-get-shared-history.sh
  lighthouse-core/lib/page-functions.js
  lighthouse-core/test/lib/page-functions-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11733 core(image-elements): remove resourceSize property
  lighthouse-core/audits/byte-efficiency/offscreen-images.js
  lighthouse-core/audits/byte-efficiency/uses-responsive-images.js
  lighthouse-core/gather/gatherers/image-elements.js
  lighthouse-core/test/audits/byte-efficiency/offscreen-images-test.js
  lighthouse-core/test/audits/byte-efficiency/uses-responsive-images-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: 7.0, breaking, cla: yes, land-when-ci-is-green, waiting4reviewer

#11744 core(simulator): clearer intermediate timing types
  lighthouse-core/lib/dependency-graph/simulator/simulator-timing-map.js
  lighthouse-core/lib/dependency-graph/simulator/simulator.js
Labels: cla: yes, waiting4reviewer

#11666 core(lantern): maximize throughput under HTTP/2
  lighthouse-core/lib/dependency-graph/simulator/connection-pool.js
  lighthouse-core/test/audits/__snapshots__/metrics-test.js.snap
  lighthouse-core/test/audits/byte-efficiency/render-blocking-resources-test.js
  lighthouse-core/test/audits/dobetterweb/uses-http2-test.js
  lighthouse-core/test/audits/timing-budget-test.js
  lighthouse-core/test/computed/metrics/__snapshots__/estimated-input-latency-test.js.snap
  lighthouse-core/test/computed/metrics/__snapshots__/lantern-estimated-input-latency-test.js.snap
  lighthouse-core/test/computed/metrics/total-blocking-time-test.js
  lighthouse-core/test/fixtures/lantern-master-accuracy.json
  lighthouse-core/test/fixtures/lantern-master-computed-values.json
  lighthouse-core/test/lib/dependency-graph/simulator/connection-pool-test.js
  lighthouse-core/test/lib/dependency-graph/simulator/simulator-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: 7.0, breaking, chillin ❄, cla: yes

#11717 tests: refresh devtools checkout for webtests
  lighthouse-core/test/chromium-web-tests/download-devtools.sh
Labels: cla: yes, waiting4reviewer

#11782 core(gather-runner): remove <M82 compat for InstallabilityErrors
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/test/gather/gather-runner-test.js
Labels: cla: yes, waiting4reviewer

#11789 tests: clear changes in tmp devtools checkout
  lighthouse-core/test/chromium-web-tests/download-devtools.sh
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11786 tests: update flaky 3p facades smoke test
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
Labels: cla: yes, land-when-ci-is-green

#11777 clients(lr): skip uses-h2 audit (again)
  lighthouse-core/config/lr-desktop-config.js
  lighthouse-core/config/lr-mobile-config.js
Labels: 7.0, cla: yes, land-when-ci-is-green, waiting4reviewer

#11785 misc(buildtracker): skip git deepen if no token
  .github/scripts/git-get-shared-history.sh
  .github/workflows/ci.yml
Labels: cla: yes

#11350 core(gather-runner): warn when BenchmarkIndex is sufficiently low
  docs/throttling.md
  lighthouse-cli/test/smokehouse/report-assert.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/report/html/renderer/report-renderer.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/report/html/renderer/dom-test.js
  lighthouse-core/test/report/html/renderer/report-renderer-test.js
Labels: cla: yes, waiting4committer

#11707 core(image-elements): surface css properties in artifact
  lighthouse-core/audits/image-aspect-ratio.js
  lighthouse-core/audits/image-size-responsive.js
  lighthouse-core/gather/gatherers/image-elements.js
  lighthouse-core/test/audits/image-aspect-ratio-test.js
  lighthouse-core/test/audits/image-size-responsive-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: 7.0, breaking, cla: yes, land-when-ci-is-green

#11769 core(full-page-screenshot): move to default config
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/smokehouse/test-definitions/screenshot/screenshot-config.js
  lighthouse-core/config/default-config.js
  lighthouse-core/config/experimental-config.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
Labels: 7.0, cla: yes, waiting4committer

#11738 core(driver): wait for critical network requests
  lighthouse-cli/test/fixtures/delayed-lcp.html
  lighthouse-cli/test/fixtures/static-server.js
  lighthouse-cli/test/smokehouse/report-assert.js
  lighthouse-cli/test/smokehouse/test-definitions/tricky-metrics/expectations.js
  lighthouse-core/gather/driver/wait-for-condition.js
  lighthouse-core/lib/network-recorder.js
  lighthouse-core/test/gather/driver/wait-for-condition-test.js
  lighthouse-core/test/lib/network-recorder-test.js
Labels: 7.0, breaking, cla: yes, land-when-ci-is-green

#11748 core(fr): add base fraggle rock snapshot runner
  jest.config.js
  lighthouse-cli/test/fixtures/static-server.js
  lighthouse-core/fraggle-rock/api.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/gather/gatherers/accessibility.js
  lighthouse-core/gather/gatherers/gatherer.js
  lighthouse-core/test/fixtures/fraggle-rock/snapshot-basic/onclick.html
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  tsconfig.json
  types/config.d.ts
  types/gatherer.d.ts
Labels: cla: yes

#11791 tests(smoke): fix failureReasonsMask flake
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
Labels: P1, cla: yes, waiting4reviewer

#11793 misc: eslintignore .d.ts files
  .eslintignore
Labels: cla: yes, land-when-ci-is-green

#11751 misc: update run-devtools script to use a list of urls
  lighthouse-core/test/chromium-web-tests/test-page-devtools.sh
Labels: cla: yes, waiting4reviewer

#11799 tests(smoke): handle warn-not-offline-capable in smoketest
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/offline-local/offline-expectations.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11790 tests: sync devtools webtests
  lighthouse-core/test/chromium-web-tests/download-devtools.sh
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-i18n-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-i18n-run.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run.js
Labels: cla: yes, land-when-ci-is-green

#11788 core(stacks): actually support joomla and october cms
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/stack-packs.js
  lighthouse-core/test/lib/stack-packs-test.js
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green

#11775 docs(readme): add websu to integrations
  readme.md
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11783 misc(build): quiet the 'npm pack' command
  build/build-pack.sh
Labels: cla: yes, waiting4reviewer

#11703 core(image-elements): make naturalWidth/Height property optional
  lighthouse-core/audits/byte-efficiency/uses-optimized-images.js
  lighthouse-core/audits/byte-efficiency/uses-responsive-images.js
  lighthouse-core/audits/byte-efficiency/uses-webp-images.js
  lighthouse-core/audits/image-aspect-ratio.js
  lighthouse-core/audits/image-size-responsive.js
  lighthouse-core/gather/gatherers/image-elements.js
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
  lighthouse-core/test/audits/byte-efficiency/uses-responsive-images-test.js
  lighthouse-core/test/audits/image-aspect-ratio-test.js
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: 7.0, breaking, cla: yes, land-when-ci-is-green

#11804 tests: do not update devtools checkout every time in ci
  .github/workflows/devtools.yml
  lighthouse-core/test/chromium-web-tests/download-devtools.sh
Labels: cla: yes, waiting4reviewer

#11792 misc: add nightly release
  .github/scripts/bump-nightly-version.sh
  .github/workflows/devtools.yml
  .github/workflows/publish.yml
  lighthouse-core/scripts/release/bump-versions.js
  lighthouse-core/scripts/release/prepare-commit.sh
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11805 misc: fix yarn install in nightly release
  .github/workflows/publish.yml
Labels: cla: yes, waiting4reviewer

#11801 tests: reenable change-related tests in github actions
  .github/workflows/ci.yml
  lighthouse-core/scripts/dogfood-lhci.sh
  lighthouse-core/scripts/github-actions-commit-range.sh
  lighthouse-core/scripts/legacy-javascript/summary-sizes.txt
  lighthouse-core/scripts/test-lantern.sh
  lighthouse-core/scripts/test-legacy-javascript.sh
Labels: cla: yes, waiting4reviewer

#11809 tests: fix unbound variable in download-devtools.sh
  lighthouse-core/test/chromium-web-tests/download-devtools.sh
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11810 misc: fix npm auth in nightly release
  .github/workflows/publish.yml
Labels: cla: yes, waiting4reviewer

#11767 core(lantern): allow non-XHRs to depend on CPU Nodes
  lighthouse-core/computed/page-dependency-graph.js
  lighthouse-core/test/audits/__snapshots__/metrics-test.js.snap
  lighthouse-core/test/audits/__snapshots__/predictive-perf-test.js.snap
  lighthouse-core/test/audits/byte-efficiency/__snapshots__/byte-efficiency-audit-test.js.snap
  lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
  lighthouse-core/test/audits/dobetterweb/uses-http2-test.js
  lighthouse-core/test/computed/metrics/__snapshots__/estimated-input-latency-test.js.snap
  lighthouse-core/test/computed/metrics/__snapshots__/first-cpu-idle-test.js.snap
  lighthouse-core/test/computed/metrics/__snapshots__/interactive-test.js.snap
  lighthouse-core/test/computed/metrics/__snapshots__/lantern-estimated-input-latency-test.js.snap
  lighthouse-core/test/computed/metrics/__snapshots__/lantern-first-cpu-idle-test.js.snap
  lighthouse-core/test/computed/metrics/__snapshots__/lantern-interactive-test.js.snap
  lighthouse-core/test/computed/metrics/first-cpu-idle-test.js
  lighthouse-core/test/computed/metrics/interactive-test.js
  lighthouse-core/test/computed/metrics/lantern-first-cpu-idle-test.js
  lighthouse-core/test/computed/metrics/lantern-interactive-test.js
  lighthouse-core/test/computed/metrics/speed-index-test.js
  lighthouse-core/test/fixtures/lantern-master-accuracy.json
  lighthouse-core/test/fixtures/lantern-master-computed-values.json
  lighthouse-core/test/results/sample_v2.json
Labels: 7.0, breaking, cla: yes, waiting4committer

#11813 misc: temporarily allow css in redirectPass
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/config/default-config.js
Labels: cla: yes, waiting4reviewer

#11696 core: support local plugins from global Lighthouse
  .gitignore
  lighthouse-core/config/config-helpers.js
  lighthouse-core/test/config/config-helpers-test.js
  lighthouse-core/test/fixtures/config/config/config.js
  lighthouse-core/test/fixtures/config/config/node_modules/plugin-in-config-directory/package.json
  lighthouse-core/test/fixtures/config/config/node_modules/plugin-in-config-directory/plugin-in-config-directory.js
  lighthouse-core/test/fixtures/config/lighthouse-plugin-config-helper/package.json
  lighthouse-core/test/fixtures/config/lighthouse-plugin-config-helper/plugin-config-helper.js
  lighthouse-core/test/fixtures/config/node_modules/plugin-in-working-directory/package.json
  lighthouse-core/test/fixtures/config/node_modules/plugin-in-working-directory/plugin-in-working-directory.js
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#11663 core(console): replace ConsoleMessages and RuntimeExceptions artifacts
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-core/audits/byte-efficiency/polyfill-graph-data.json
  lighthouse-core/audits/deprecations.js
  lighthouse-core/audits/errors-in-console.js
  lighthouse-core/audits/violation-audit.js
  lighthouse-core/config/default-config.js
  lighthouse-core/gather/gatherers/console-messages.js
  lighthouse-core/gather/gatherers/runtime-exceptions.js
  lighthouse-core/test/audits/deprecations-test.js
  lighthouse-core/test/audits/dobetterweb/geolocation-on-start-test.js
  lighthouse-core/test/audits/dobetterweb/no-document-write-test.js
  lighthouse-core/test/audits/dobetterweb/notification-on-start-test.js
  lighthouse-core/test/audits/dobetterweb/uses-passive-event-listeners-test.js
  lighthouse-core/test/audits/errors-in-console-test.js
  lighthouse-core/test/gather/gatherers/console-messages-test.js
  lighthouse-core/test/gather/gatherers/runtime-exceptions-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
  types/artifacts.d.ts
Labels: 7.0, breaking, cla: yes

#11811 deps: update old transitive deps
  lighthouse-cli/test/static-server-test.js
  lighthouse-core/lib/sd-validation/scripts/download-jsonldcontext.js
  lighthouse-core/lib/sd-validation/scripts/generate-schema-tree.js
  lighthouse-core/scripts/internal-analysis/download-issues.js
  lighthouse-core/scripts/lantern/collect/collect.js
  lighthouse-core/scripts/legacy-javascript/yarn.lock
  lighthouse-core/scripts/print-contributors.js
  package.json
  types/node-fetch.d.ts
  yarn.lock
Labels: 7.0, cla: yes, land-when-ci-is-green

#11794 deps: update yargs to latest
  lighthouse-cli/bin.js
  lighthouse-cli/cli-flags.js
  lighthouse-cli/test/cli/bin-test.js
  lighthouse-cli/test/cli/cli-flags-test.js
  lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js
  lighthouse-core/scripts/compare-runs.js
  package.json
  readme.md
  tsconfig.json
  types/externs.d.ts
  yarn.lock
Labels: 7.0, breaking, cla: yes, land-when-ci-is-green

#11798 report(pwa): move service-worker to the pwa-optimized group
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa2-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa3-expectations.js
  lighthouse-core/config/default-config.js
  lighthouse-core/test/config/config-test.js
  lighthouse-core/test/report/html/renderer/category-renderer-test.js
  lighthouse-core/test/report/html/renderer/pwa-category-renderer-test.js
  lighthouse-core/test/results/sample_v2.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-limited-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: 7.0, breaking, cla: yes, land-when-ci-is-green, waiting4reviewer

#11745 core(installable-manifest): use devtools InstallabilityErrors
  lighthouse-cli/test/smokehouse/test-definitions/offline-local/offline-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa2-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa3-expectations.js
  lighthouse-core/audits/installable-manifest.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/test/audits/installable-manifest-test.js
  lighthouse-core/test/results/sample_v2.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: 7.0, breaking, cla: yes, land-when-ci-is-green

#11808 tests: use font-size for non-composited animations in smoke tests
  lighthouse-cli/test/fixtures/perf/animations.html
  lighthouse-cli/test/fixtures/perf/trace-elements.html
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
Labels: cla: yes, waiting4reviewer

#11834 core(uses-http2): remove mention of push
  lighthouse-core/audits/dobetterweb/uses-http2.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4reviewer

#11833 misc: add log files to GCP run results
  lighthouse-core/scripts/gcp-collection/fleet-status.sh
  lighthouse-core/scripts/gcp-collection/run.sh
Labels: cla: yes, waiting4reviewer

#11825 core(script-treemap-data): fix sourceRoot & missing coverage bugs
  lighthouse-core/audits/script-treemap-data.js
  lighthouse-core/test/audits/__snapshots__/script-treemap-data-test.js.snap
  lighthouse-core/test/audits/script-treemap-data-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#11835 core(config): only allow lighthouse:default extension
  docs/configuration.md
  lighthouse-core/config/config.js
  lighthouse-core/test/config/config-test.js
  types/config.d.ts
Labels: 7.0, breaking, cla: yes, waiting4reviewer

#11836 tests(smoke): restore dbw_tester exception assertions
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-core/config/default-config.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11829 core(config): special case full-page-screenshot audit in filtering
  lighthouse-core/config/config.js
  lighthouse-core/test/config/config-test.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-limited-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run-expected.txt
Labels: 7.0, cla: yes, land-when-ci-is-green

#11851 core(network): do not consider cross frame requests critical
  lighthouse-core/lib/network-recorder.js
  lighthouse-core/test/lib/network-recorder-test.js
Labels: 7.0, cla: yes, land-when-ci-is-green, waiting4committer

#11846 report: fix element screenshot position, lifecycle, styles
  lighthouse-core/report/html/renderer/element-screenshot-renderer.js
  lighthouse-core/report/html/report-styles.css
Labels: cla: yes, waiting4reviewer

#11852 core(full-page-screenshot): handle ShadowRoots
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-core/lib/page-functions.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11839 v7.0.0
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11760 core(trace): compute trace for main frame and any child frames
  lighthouse-core/computed/metrics/cumulative-layout-shift-all-frames.js
  lighthouse-core/lib/minify-trace.js
  lighthouse-core/lib/tracehouse/main-thread-tasks.js
  lighthouse-core/lib/tracehouse/trace-processor.js
  lighthouse-core/test/audits/__snapshots__/metrics-test.js.snap
  lighthouse-core/test/audits/metrics-test.js
  lighthouse-core/test/computed/metrics/cumulative-layout-shift-all-frames-test.js
  lighthouse-core/test/computed/metrics/largest-contentful-paint-all-frames-test.js
  lighthouse-core/test/computed/metrics/timing-summary-test.js
  lighthouse-core/test/computed/trace-of-tab-test.js
  lighthouse-core/test/create-test-trace.js
  lighthouse-core/test/fixtures/traces/frame-metrics-m89.devtools.log.json
  lighthouse-core/test/fixtures/traces/frame-metrics-m89.json
  lighthouse-core/test/lib/tracehouse/trace-processor-test.js
  lighthouse-core/test/results/artifacts/defaultPass.trace.json
  types/artifacts.d.ts
  types/externs.d.ts
Labels: cla: yes, waiting4reviewer

#11841 misc: add type checking to TagsBlockingFirstPaint
  lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js
  lighthouse-core/test/gather/gatherers/dobetterweb/tags-blocking-first-paint-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#11842 test: add warn-not-offline-capable smoketest
  lighthouse-cli/test/fixtures/offline-ready-sw.js
  lighthouse-cli/test/fixtures/offline-ready.html
  lighthouse-cli/test/smokehouse/test-definitions/offline-local/offline-expectations.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11845 misc(scripts): fix unbound variable in open-devtools
  lighthouse-core/scripts/open-devtools.sh
Labels: cla: yes, waiting4reviewer

#11754 core: replace most usages of evaluateAsync with structured evaluate
  docs/recipes/custom-gatherer-puppeteer/custom-gatherer.js
  lighthouse-core/fraggle-rock/gather/driver.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/driver/execution-context.js
  lighthouse-core/gather/driver/wait-for-condition.js
  lighthouse-core/gather/gatherers/accessibility.js
  lighthouse-core/gather/gatherers/anchor-elements.js
  lighthouse-core/gather/gatherers/cache-contents.js
  lighthouse-core/gather/gatherers/dobetterweb/doctype.js
  lighthouse-core/gather/gatherers/dobetterweb/domstats.js
  lighthouse-core/gather/gatherers/dobetterweb/password-inputs-with-prevented-paste.js
  lighthouse-core/gather/gatherers/form-elements.js
  lighthouse-core/gather/gatherers/full-page-screenshot.js
  lighthouse-core/gather/gatherers/iframe-elements.js
  lighthouse-core/gather/gatherers/image-elements.js
  lighthouse-core/gather/gatherers/seo/embedded-content.js
  lighthouse-core/gather/gatherers/seo/robots-txt.js
  lighthouse-core/gather/gatherers/viewport-dimensions.js
  lighthouse-core/lib/page-functions.js
  lighthouse-core/lib/stack-collector.js
  lighthouse-core/test/gather/fake-driver.js
  lighthouse-core/test/gather/gatherers/accessibility-test.js
  lighthouse-core/test/gather/gatherers/dobetterweb/password-inputs-with-prevented-paste-test.js
  lighthouse-core/test/gather/gatherers/full-page-screenshot-test.js
  lighthouse-core/test/gather/gatherers/viewport-dimensions-test.js
  lighthouse-core/test/lib/stack-collector-test.js
  types/externs.d.ts
  types/gatherer.d.ts
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11848 misc(update-report-fixtures): use a consistent server port
  lighthouse-core/audits/byte-efficiency/unused-javascript.js
  lighthouse-core/scripts/update-report-fixtures.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4committer

#11728 tests: add more files in lighthouse-core/tests to tsconfig
  tsconfig.json
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#11876 report: convert v6 emulatedFormFactor to v7 formFactor
  lighthouse-core/report/html/renderer/util.js
Labels: cla: yes, waiting4reviewer

#11871 tests: add missing arrays to InspectorIssues sample artifact
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/artifacts/defaultPass.trace.json
  lighthouse-core/test/results/sample_v2.json
  lighthouse-core/test/sample-json-test.js
Labels: cla: yes, waiting4reviewer

#11853 core(full-page-screenshot): do not render zero size rects
  lighthouse-core/gather/gatherers/full-page-screenshot.js
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/test/report/html/renderer/details-renderer-test.js
Labels: cla: yes, waiting4reviewer

#11868 docs(readme): add plugin: lighthouse-plugin-crux
  readme.md
Labels: cla: yes, waiting4reviewer
