Repository GoogleChrome/lighthouse, pull requests merged in 2020-02, with the labels that each got.

#10257 misc(git3po): add-needs-priority, remove-needs-priority
  lighthouse-core/scripts/git3po-rules/add-needs-priority.yaml
  lighthouse-core/scripts/git3po-rules/remove-needs-priority.yaml
Labels: cla: yes, waiting4reviewer

#10295 core(stacks): handle numeric version from library detector
  lighthouse-core/lib/stack-collector.js
  lighthouse-core/test/lib/stack-collector-test.js
Labels: cla: yes, land-when-ci-is-green, needs-priority

#10293 core(preconnect): pass without warning at 2 links
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-core/audits/uses-rel-preconnect.js
  lighthouse-core/test/audits/uses-rel-preconnect-test.js
Labels: cla: yes, needs-priority

#10304 misc(git3po): filter out pull requests for need-priority scripts
  lighthouse-core/scripts/git3po-rules/add-needs-priority.yaml
  lighthouse-core/scripts/git3po-rules/remove-needs-priority.yaml
Labels: cla: yes, land-when-ci-is-green, needs-priority

#9925 core(lightwallet): render timing-budget audit
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/config/default-config.js
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes, waiting4reviewer

#10105 core(lightwallet): compute resource metrics by origin
  lighthouse-core/computed/origin-summary.js
  lighthouse-core/test/computed/origin-summary-test.js
Labels: cla: yes, land-when-ci-is-green

#10311 core: add temporary config for source map features
  lighthouse-core/config/source-maps-config.js
Labels: cla: yes, waiting4committer

#10305 viewer(css): adding grayscale & wait cursor while loading
  lighthouse-viewer/app/styles/viewer.css
Labels: cla: yes, waiting4reviewer

#10320 core: support old version of Page.getInstallabilityErrors
  lighthouse-cli/test/smokehouse/test-definitions/offline-local/offline-expectations.js
  lighthouse-core/computed/manifest-values.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/test/audits/installable-manifest-test.js
  lighthouse-core/test/computed/manifest-values-test.js
  lighthouse-core/test/gather/gather-runner-test.js
  package.json
  types/artifacts.d.ts
  yarn.lock
Labels: cla: yes, land-when-ci-is-green

#10327 misc: add script for examining polyfills
  lighthouse-core/scripts/legacy-javascript/examine-latest-run.js
Labels: cla: yes

#10333 core: experimental config
  lighthouse-core/config/experimental-config.js
Labels: cla: yes

#10338 misc: add git3po script for PR assignee
  lighthouse-core/scripts/git3po-rules/pr-assignee.yaml
Labels: cla: yes, land-when-ci-is-green

#10310 devtools: update roll script to print correct command for tests
  lighthouse-core/scripts/roll-to-devtools.sh
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#10332 clients(extension): firefox
  build/build-extension.js
  clients/extension/_locales/en/messages.json
  clients/extension/_locales/en/messages_canary.json
  clients/extension/manifest.json
  clients/extension/popup.html
  clients/extension/scripts/popup.js
  clients/extension/styles/lighthouse.css
  clients/test/extension/popup-test.js
  docs/releasing.md
  lighthouse-core/scripts/release/prepare-package.sh
  package.json
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#9872 tests(static-server): allow hook to modify response body
  lighthouse-cli/test/fixtures/static-server.js
  lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js
  lighthouse-cli/test/static-server-test.js
  lighthouse-core/scripts/update-report-fixtures.js
Labels: cla: yes, land-when-ci-is-green

#10284 new_audit: add charset declaration audit
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-core/audits/dobetterweb/charset.js
  lighthouse-core/config/default-config.js
  lighthouse-core/gather/gatherers/meta-elements.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/dobetterweb/charset-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
  types/artifacts.d.ts
Labels: cla: yes, new_audit

#10355 core: audit.meta.__internalOptionalArtifacts
  lighthouse-core/config/config.js
  lighthouse-core/runner.js
  lighthouse-core/test/config/config-test.js
  lighthouse-core/test/runner-test.js
  types/audit.d.ts
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#9873 build(smokehouse): bundle smoke test runner
  build/build-smokehouse-bundle.js
  lighthouse-cli/test/smokehouse/firehouse.js
  lighthouse-cli/test/smokehouse/frontends/lib.js
  lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js
  lighthouse-cli/test/smokehouse/readme.md
  lighthouse-cli/test/smokehouse/smokehouse.js
  package.json
  types/smokehouse.d.ts
Labels: cla: yes, land-when-ci-is-green

#10348 viewer(css): cursor:wait indicator no longer blocked by pointer-events: none
  lighthouse-viewer/app/styles/viewer.css
Labels: cla: yes, land-when-ci-is-green

#10371 misc: update commitlint config to latest, loosen subject-case
  commitlint.config.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#10361 tests(smoke): deep clone expectations. do not use p.stdout
  lighthouse-cli/test/smokehouse/frontends/lib.js
  lighthouse-cli/test/smokehouse/smokehouse.js
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green

#10281 build: fix appveyor cache failures
  .appveyor.yml
Labels: cla: yes, waiting4reviewer

#10322 clients(devtools): use the same desktop throttling as lightrider
  clients/devtools-entry.js
  lighthouse-core/config/constants.js
  lighthouse-core/config/lr-desktop-config.js
Labels: cla: yes, land-when-ci-is-green

#10090 core(unused-javascript): augment with source maps
  .eslintignore
  .eslintrc.js
  lighthouse-cli/test/fixtures/byte-efficiency/bundle.js
  lighthouse-cli/test/fixtures/byte-efficiency/bundle.js.map
  lighthouse-cli/test/fixtures/byte-efficiency/tester.html
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/byte-config.js
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
  lighthouse-core/audits/byte-efficiency/unused-javascript.js
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/test/audits/byte-efficiency/unused-javascript-test.js
  lighthouse-core/test/computed/js-bundles-test.js
  lighthouse-core/test/config/config-test.js
  lighthouse-core/test/fixtures/source-maps/squoosh.usage.json
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  proto/sample_v2_round_trip.json
Labels: cla: yes, land-when-ci-is-green

#10380 clients(extension): remove content security policy
  clients/extension/manifest.json
Labels: cla: yes, waiting4reviewer

#10389 core(charset audit): loosen CHARSET_HTML_REGEX and CHARSET_HTTP_REGEX
  lighthouse-core/audits/dobetterweb/charset.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/dobetterweb/charset-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
Labels: cla: yes, waiting4reviewer

#10385 docs(readme): add lighthouse-batch-parallel to related projects
  readme.md
Labels: cla: yes, waiting4committer

#10275 deps: pptr to 1.20.0
  yarn.lock
Labels: cla: yes

#9037 new_audit: add cumulative layout shift metric
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/audits/metrics/cumulative-layout-shift.js
  lighthouse-core/computed/metrics/cumulative-layout-shift.js
  lighthouse-core/computed/metrics/timing-summary.js
  lighthouse-core/config/default-config.js
  lighthouse-core/gather/driver.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/lh-error.js
  lighthouse-core/test/audits/__snapshots__/metrics-test.js.snap
  lighthouse-core/test/computed/metrics/timing-summary-test.js
  lighthouse-core/test/results/artifacts/defaultPass.trace.json
  lighthouse-core/test/results/sample_v2.json
  proto/sample_v2_round_trip.json
  types/artifacts.d.ts
  types/audit.d.ts
  types/externs.d.ts
Labels: 6.0, cla: yes, land-when-ci-is-green

#10296 misc(compare-runs): report metrics, add gather/audit modes, etc
  lighthouse-core/scripts/compare-runs.js
Labels: cla: yes, land-when-ci-is-green

#10036 clients(devtools): roll to front_end/third_party
  clients/devtools-report-assets.js
  lighthouse-core/scripts/roll-to-devtools.sh
Labels: cla: yes, land-when-ci-is-green
