Repository GoogleChrome/lighthouse, pull requests merged in 2020-06, with the labels that each got.

#10901 docs(readme): add PageWatch to the integrations section
  readme.md
Labels: cla: yes, waiting4reviewer

#10870 report: use KiB instead of KB
  docs/performance-budgets.md
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-core/audits/byte-efficiency/total-byte-weight.js
  lighthouse-core/audits/byte-efficiency/unused-css-rules.js
  lighthouse-core/audits/resource-summary.js
  lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js
  lighthouse-core/lib/i18n/README.md
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/report/html/renderer/crc-details-renderer.js
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/report/html/renderer/i18n.js
  lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
  lighthouse-core/test/audits/resource-summary-test.js
  lighthouse-core/test/config/budget-test.js
  lighthouse-core/test/report/html/renderer/crc-details-renderer-test.js
  lighthouse-core/test/report/html/renderer/details-renderer-test.js
  lighthouse-core/test/report/html/renderer/i18n-test.js
  lighthouse-core/test/results/sample_v2.json
  types/budget.d.ts
Labels: cla: yes, waiting4reviewer

#10878 docs(readme): update programmatic usage recipe
  docs/readme.md
  lighthouse-core/scripts/release/test.sh
Labels: cla: yes, waiting4committer

#10906 core(unused-javascript): increase threshold to 20KiB
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/byte-config.js
  lighthouse-core/audits/byte-efficiency/unused-javascript.js
  lighthouse-core/test/audits/byte-efficiency/unused-javascript-test.js
Labels: cla: yes, waiting4reviewer

#10850 core(legacy-javascript): use prescriptive language in title
  lighthouse-core/audits/legacy-javascript.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
Labels: cla: yes, waiting4reviewer

#10867 core: subRow refactor, rename to subItem
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/legacy-javascript/expectations.js
  lighthouse-core/audits/byte-efficiency/duplicated-javascript.js
  lighthouse-core/audits/byte-efficiency/unused-javascript.js
  lighthouse-core/audits/legacy-javascript.js
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/test/audits/byte-efficiency/duplicated-javascript-test.js
  lighthouse-core/test/audits/byte-efficiency/unused-javascript-test.js
  lighthouse-core/test/audits/legacy-javascript-test.js
  lighthouse-core/test/report/html/renderer/details-renderer-test.js
  types/audit-details.d.ts
Labels: cla: yes, land-when-ci-is-green

#10838 docs(readme): adding cypress-audit to the related projects
  readme.md
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#10877 core: improve resilience of nodeId-dependent gatherers
  lighthouse-cli/test/fixtures/perf/delayed-element.js
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-core/audits/largest-contentful-paint-element.js
  lighthouse-core/audits/layout-shift-elements.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gatherers/anchor-elements.js
  lighthouse-core/gather/gatherers/trace-elements.js
Labels: cla: yes, land-when-ci-is-green

#10949 misc: use more inclusive and descriptive language
  changelog.md
  docs/configuration.md
  lighthouse-core/audits/user-timings.js
  lighthouse-core/config/config.js
  lighthouse-core/test/audits/user-timing-test.js
  lighthouse-logger/index.js
Labels: cla: yes, land-when-ci-is-green

#10919 tests(smoke): use --debug in github action
  .github/workflows/ci.yml
Labels: cla: yes, waiting4reviewer

#10937 core(legacy-javascript): reduce polyfills, fix core-js import in test
  lighthouse-cli/test/fixtures/legacy-javascript.html
  lighthouse-cli/test/fixtures/legacy-javascript.js
  lighthouse-cli/test/smokehouse/test-definitions/legacy-javascript/expectations.js
  lighthouse-core/audits/legacy-javascript.js
  lighthouse-core/scripts/legacy-javascript/main.js
  lighthouse-core/scripts/legacy-javascript/run.js
  lighthouse-core/scripts/legacy-javascript/summary-signals-nomaps.json
  lighthouse-core/scripts/legacy-javascript/summary-signals.json
  lighthouse-core/scripts/legacy-javascript/summary-sizes.txt
  lighthouse-core/test/audits/legacy-javascript-test.js
Labels: cla: yes, land-when-ci-is-green

#10879 misc(viewer): expose LHR as __LIGHTHOUSE_JSON__
  lighthouse-core/report/html/report-template.html
  lighthouse-viewer/app/src/lighthouse-report-viewer.js
Labels: cla: yes, waiting4reviewer

#10936 clients(psi): show disclaimer and calclink
  lighthouse-core/report/html/renderer/performance-category-renderer.js
Labels: cla: yes, waiting4reviewer

#10944 report: update link for budgets audit
  lighthouse-core/audits/resource-summary.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#10911 deps: upgrade chrome-launcher@0.13.3
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#10946 tests(legacy-javascript): exit code 1 on failure
  lighthouse-core/scripts/legacy-javascript/run.js
Labels: cla: yes, land-when-ci-is-green

#10701 core(duplicated-javascript): display as transfer size
  lighthouse-core/audits/byte-efficiency/duplicated-javascript.js
  lighthouse-core/computed/module-duplication.js
  lighthouse-core/test/audits/byte-efficiency/duplicated-javascript-test.js
  lighthouse-core/test/computed/module-duplication-test.js
Labels: cla: yes, waiting4committer

#10978 report: fix zebra styling, sub item rows for 3p filter
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/test/report/html/renderer/report-ui-features-test.js
Labels: cla: yes, land-when-ci-is-green

#10979 misc: rename subHeading to subItemsHeading
  lighthouse-core/audits/byte-efficiency/duplicated-javascript.js
  lighthouse-core/audits/byte-efficiency/unused-javascript.js
  lighthouse-core/audits/legacy-javascript.js
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/test/report/html/renderer/details-renderer-test.js
  types/audit-details.d.ts
Labels: cla: yes, land-when-ci-is-green

#10983 misc: fix merge error for subHeading -> subItemsHeading rename
  lighthouse-core/test/report/html/renderer/report-ui-features-test.js
Labels: cla: yes, land-when-ci-is-green

#10942 core(long-tasks): add startTime property
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-core/audits/long-tasks.js
  lighthouse-core/lib/dependency-graph/simulator/simulator.js
  lighthouse-core/test/audits/long-tasks-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, land-when-ci-is-green

#10989 tests: run ToT and stable Chrome for smoke tests in github workflow
  .github/workflows/ci.yml
Labels: cla: yes, waiting4committer

#10954 report: use acronyms and round metrics for shorter calc url
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
Labels: cla: yes, waiting4reviewer

#10746 tests: add heading key tests
  lighthouse-cli/test/smokehouse/lighthouse-runners/cli.js
  lighthouse-core/audits/audit.js
  lighthouse-core/audits/byte-efficiency/duplicated-javascript.js
  lighthouse-core/lib/lh-env.js
  lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
Labels: cla: yes, land-when-ci-is-green

#11006 docs: add note about git repo required for @lhci/cli usage
  docs/variability.md
Labels: cla: yes, waiting4reviewer

#10986 deps(axe-core): upgrade to 3.5.5
  package.json
  yarn.lock
Labels: 6.1, cla: yes, waiting4reviewer

#10999 deps: remove bundlesize
  .travis.yml
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#10968 core(layout-shift-elements): surface CLS contribution per shifted element
  lighthouse-core/audits/layout-shift-elements.js
  lighthouse-core/gather/gatherers/trace-elements.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/test/audits/layout-shift-elements-test.js
  lighthouse-core/test/gather/gatherers/trace-elements-test.js
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
  types/externs.d.ts
Labels: 6.1, cla: yes, waiting4committer

#10981 report: don't dim disclaimer anchor links
  lighthouse-core/report/html/report-styles.css
Labels: cla: yes, waiting4reviewer

#10990 core: add source-maps gatherer to default config
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/byte-config.js
  lighthouse-cli/test/smokehouse/test-definitions/legacy-javascript/legacy-javascript-config.js
  lighthouse-cli/test/smokehouse/test-definitions/source-maps/source-maps-config.js
  lighthouse-core/audits/byte-efficiency/unused-javascript.js
  lighthouse-core/config/default-config.js
  lighthouse-core/config/experimental-config.js
  lighthouse-core/test/config/config-test.js
Labels: 6.1, cla: yes, waiting4reviewer

#10995 tests: move proto roundtrip json to .tmp/
  .gitignore
  lighthouse-core/test/test-utils.js
  package.json
  proto/scripts/json_roundtrip_via_proto.py
Labels: cla: yes, waiting4reviewer

#11018 i18n: adjust LCP element description
  lighthouse-core/audits/largest-contentful-paint-element.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
Labels: waiting4reviewer

#11025 v6.1.0
  build/changelog-generator/templates/header.hbs
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  lighthouse-core/test/results/sample_v2.json
  package.json
Labels: cla: yes, waiting4committer

#11009 tests: parallelize all the tests
  .github/workflows/ci.yml
  lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js
  lighthouse-cli/test/smokehouse/lighthouse-runners/bundle.js
Labels: cla: no, waiting4reviewer

#11035 misc: run GitHub Actions on master and PRs
  .github/workflows/ci.yml
  package.json
Labels: cla: yes, land-when-ci-is-green

#10779 core: remove uses of deprecated extendedInfo field
  lighthouse-core/audits/accessibility/axe-audit.js
  lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
  lighthouse-core/audits/byte-efficiency/total-byte-weight.js
  lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
  lighthouse-core/audits/critical-request-chains.js
  lighthouse-core/audits/deprecations.js
  lighthouse-core/audits/dobetterweb/dom-size.js
  lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js
  lighthouse-core/audits/dobetterweb/geolocation-on-start.js
  lighthouse-core/audits/dobetterweb/no-document-write.js
  lighthouse-core/audits/dobetterweb/no-vulnerable-libraries.js
  lighthouse-core/audits/dobetterweb/notification-on-start.js
  lighthouse-core/audits/dobetterweb/password-inputs-can-be-pasted-into.js
  lighthouse-core/audits/dobetterweb/uses-http2.js
  lighthouse-core/audits/dobetterweb/uses-passive-event-listeners.js
  lighthouse-core/audits/is-on-https.js
  lighthouse-core/audits/legacy-javascript.js
  lighthouse-core/audits/metrics/interactive.js
  lighthouse-core/audits/redirects.js
  lighthouse-core/audits/server-response-time.js
  lighthouse-core/audits/user-timings.js
  lighthouse-core/audits/uses-rel-preconnect.js
  lighthouse-core/audits/uses-rel-preload.js
  lighthouse-core/test/audits/byte-efficiency/total-byte-weight-test.js
  lighthouse-core/test/audits/byte-efficiency/uses-long-cache-ttl-test.js
  lighthouse-core/test/audits/dobetterweb/no-vulnerable-libraries-test.js
  lighthouse-core/test/audits/dobetterweb/password-inputs-can-be-pasted-into-test.js
  lighthouse-core/test/audits/dobetterweb/uses-passive-event-listeners-test.js
  lighthouse-core/test/audits/is-on-https-test.js
  lighthouse-core/test/audits/legacy-javascript-test.js
  lighthouse-core/test/audits/user-timing-test.js
  lighthouse-core/test/audits/uses-rel-preconnect-test.js
  lighthouse-core/test/scoring-test.js
Labels: cla: yes, waiting4committer

#11032 core(page-functions): expose simulated throttling requestIdleCallback shim
  lighthouse-cli/test/fixtures/ric-shim.html
  lighthouse-cli/test/smokehouse/test-definitions/lantern/lantern-expectations.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/lib/page-functions.js
  lighthouse-core/test/gather/fake-driver.js
  lighthouse-core/test/gather/gather-runner-test.js
Labels: cla: yes, land-when-ci-is-green

#11020 misc: add tools to track issue response time
  lighthouse-core/scripts/internal-analysis/analyze-issues.js
  lighthouse-core/scripts/internal-analysis/download-issues.js
Labels: cla: yes, waiting4reviewer

#11039 deps: upgrade codecov to 3.7.0
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#11041 tests: relax requestIdleCallback smoke expectation
  lighthouse-cli/test/fixtures/ric-shim.html
  lighthouse-cli/test/smokehouse/test-definitions/lantern/lantern-expectations.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11019 misc: annotate version-specific logic with COMPAT comments
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-core/gather/connections/cri.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/lib/page-functions.js
  lighthouse-core/lib/tracehouse/trace-processor.js
  lighthouse-core/test/gather/driver-test.js
Labels: cla: yes, waiting4reviewer
