Repository GoogleChrome/lighthouse, pull requests merged in 2020-10, with the labels that each got.

#11493 tests: run every smoke test (except forms) for bundle
  .github/workflows/ci.yml
  lighthouse-cli/test/smokehouse/lighthouse-runners/bundle.js
  package.json
Labels: cla: yes, waiting4committer

#11512 misc: add chromium webtests to npmignore
  .npmignore
Labels: cla: yes, waiting4reviewer

#11509 core(runner): save lhr on -A
  lighthouse-core/lib/asset-saver.js
  lighthouse-core/runner.js
  lighthouse-core/test/fixtures/artifacts/alphabet-artifacts/lhr.json
  lighthouse-core/test/fixtures/artifacts/empty-artifacts/lhr.json
  lighthouse-core/test/fixtures/artifacts/perflog/lhr.json
  lighthouse-core/test/runner-test.js
Labels: cla: yes, waiting4reviewer

#11513 v6.4.1
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes, waiting4reviewer

#11402 core(full-page-screenshot): use layoutViewport width
  lighthouse-cli/test/smokehouse/test-definitions/screenshot/expectations.js
  lighthouse-core/gather/gatherers/full-page-screenshot.js
  lighthouse-core/test/gather/gatherers/full-page-screenshot-test.js
Labels: cla: yes, waiting4committer

#11502 docs(releasing): update release process
  docs/releasing.md
Labels: cla: yes, waiting4reviewer

#11489 i18n: format bytes with consistent fractional width
  lighthouse-core/report/html/renderer/i18n.js
  lighthouse-core/test/report/html/renderer/i18n-test.js
  lighthouse-core/test/report/html/renderer/report-ui-features-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#11517 deps: add @types/yargs-parser
  package.json
  types/yargs-parser/index.d.ts
  yarn.lock
Labels: cla: yes, waiting4reviewer

#11488 docs(configuration): update some wording of the "extends" property
  docs/configuration.md
Labels: cla: yes, waiting4committer

#10449 core(js-bundles): return error object when sizes cannot be determined
  lighthouse-core/audits/byte-efficiency/unused-javascript.js
  lighthouse-core/computed/js-bundles.js
  lighthouse-core/computed/module-duplication.js
  lighthouse-core/scripts/legacy-javascript/create-polyfill-size-estimation.js
  lighthouse-core/test/computed/js-bundles-test.js
  types/artifacts.d.ts
Labels: cla: yes, land-when-ci-is-green

#11519 tests: mock saveLhr and assert no unit test source changes
  .github/workflows/ci.yml
  lighthouse-core/lib/asset-saver.js
  lighthouse-core/runner.js
  lighthouse-core/scripts/assert-golden-lhr-unchanged.sh
  lighthouse-core/test/fixtures/artifacts/alphabet-artifacts/lhr.json
  lighthouse-core/test/fixtures/artifacts/empty-artifacts/lhr.json
  lighthouse-core/test/fixtures/artifacts/perflog/lhr.json
  lighthouse-core/test/runner-test.js
Labels: cla: yes, waiting4reviewer

#11271 new_audit: add script-treemap-data to experimental
  lighthouse-core/audits/script-treemap-data.js
  lighthouse-core/computed/module-duplication.js
  lighthouse-core/computed/resource-summary.js
  lighthouse-core/config/experimental-config.js
  lighthouse-core/test/audits/__snapshots__/script-treemap-data-test.js.snap
  lighthouse-core/test/audits/byte-efficiency/duplicated-javascript-test.js
  lighthouse-core/test/audits/byte-efficiency/unused-javascript-test.js
  lighthouse-core/test/audits/script-treemap-data-test.js
  lighthouse-core/test/audits/valid-source-maps-test.js
  lighthouse-core/test/computed/js-bundles-test.js
  lighthouse-core/test/computed/module-duplication-test.js
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/test-utils.js
  tsconfig.json
Labels: cla: yes, land-when-ci-is-green

#11523 tests: add tests for networkRecordsToDevtoolsLog
  lighthouse-core/test/network-records-to-devtools-log-test.js
  lighthouse-core/test/network-records-to-devtools-log.js
Labels: cla: yes, waiting4reviewer

#11520 misc: remove compile-against-devtools.sh
  lighthouse-core/scripts/compile-against-devtools.sh
  package.json
Labels: cla: yes, land-when-ci-is-green

#11538 report: do not show element screenshot if out of bounds
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/report/html/renderer/element-screenshot-renderer.js
  lighthouse-core/test/report/html/renderer/element-screenshot-renderer-test.js
Labels: cla: yes, waiting4reviewer

#11518 core(hidpr-images): never recommend more than 2x
  lighthouse-core/audits/image-size-responsive.js
  lighthouse-core/test/audits/image-size-responsive-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4reviewer

#11534 tests: reset smoke transferSize expectations to reality
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/oopif/oopif-config.js
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
Labels: cla: yes, waiting4reviewer

#11516 misc: add save latest run script
  lighthouse-core/scripts/save-latest-run.sh
  package.json
Labels: cla: yes, land-when-ci-is-green

#11554 core: mailto: anchor with window.open onclick is crawlable
  lighthouse-core/audits/seo/crawlable-anchors.js
  lighthouse-core/test/audits/seo/crawlable-anchors-test.js
Labels: cla: yes, waiting4reviewer

#11533 core(critical-requests): refactor to use lantern graph
  lighthouse-core/audits/critical-request-chains.js
  lighthouse-core/computed/critical-request-chains.js
  lighthouse-core/lib/network-recorder.js
  lighthouse-core/lib/network-request.js
  lighthouse-core/test/audits/critical-request-chains-test.js
  lighthouse-core/test/computed/critical-request-chains-test.js
  lighthouse-core/test/fixtures/artifacts/perflog/defaultPass.trace.json
  lighthouse-core/test/fixtures/wikipedia-redirect.critical-request-chains.json
  lighthouse-core/test/lib/asset-saver-test.js
  lighthouse-core/test/network-records-to-devtools-log.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, land-when-ci-is-green

#11544 tests: add devtools test for important data warning
  .github/workflows/devtools.yml
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-clear-data-warning-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-clear-data-warning.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/resources/lighthouse-storage.html
Labels: cla: yes, land-when-ci-is-green

#11563 core(dom-size): remove formatNumber
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-core/audits/dobetterweb/dom-size.js
  lighthouse-core/test/audits/dobetterweb/dom-size-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4reviewer

#11446 core(tracehouse): use tasks to improve profiler timing data
  lighthouse-core/lib/tracehouse/cpu-profile-model.js
  lighthouse-core/lib/tracehouse/main-thread-tasks.js
  lighthouse-core/test/lib/tracehouse/cpu-profile-model-test.js
  lighthouse-core/test/lib/tracehouse/main-thread-tasks-test.js
Labels: cla: yes, waiting4reviewer

#11584 tests: update MixedContent test to match ToT
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
Labels: cla: yes, waiting4reviewer

#11253 core(tracehouse): split timeOrigin determination out of computeTraceOfTab
  lighthouse-core/computed/trace-of-tab.js
  lighthouse-core/lib/lh-error.js
  lighthouse-core/lib/tracehouse/trace-processor.js
  lighthouse-core/test/audits/__snapshots__/metrics-test.js.snap
  lighthouse-core/test/lib/tracehouse/trace-processor-test.js
  proto/lighthouse-result.proto
Labels: cla: yes, waiting4reviewer

#11486 new_audit: preload-lcp-image
  lighthouse-core/audits/preload-lcp-image.js
  lighthouse-core/config/experimental-config.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/page-functions.js
  lighthouse-core/test/audits/preload-lcp-image-test.js
  lighthouse-core/test/audits/uses-rel-preconnect-test.js
  lighthouse-core/test/create-test-trace.js
Labels: cla: yes, waiting4committer
