Repository GoogleChrome/lighthouse, pull requests merged in 2020-11, with the labels that each got.

#11625 tests: limit LCP element audit to m87 and earlier
  lighthouse-cli/test/smokehouse/report-assert.js
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
Labels: cla: yes, waiting4reviewer

#11623 core(runner): abstract gather phase out of runner
  lighthouse-core/index.js
  lighthouse-core/runner.js
  lighthouse-core/test/runner-test.js
Labels: cla: yes, land-when-ci-is-green

#11564 misc(build): refactor viewer bundler into reusable GhPagesApp
  build-tracker.config.js
  build/build-viewer.js
  build/gh-pages-app.js
  lighthouse-cli/test/fixtures/static-server.js
  lighthouse-viewer/README.md
  lighthouse-viewer/app/index.html
  lighthouse-viewer/app/sw.js
  lighthouse-viewer/test/viewer-test-pptr.js
  package.json
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#11634 tests: update static content shell version
  third-party/download-content-shell/download-content-shell.js
Labels: cla: yes, land-when-ci-is-green

#11620 core(gather-runner): use final document when reporting non-HTML error
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/lib/dependency-graph/simulator/network-analyzer-test.js
Labels: cla: yes, waiting4reviewer

#11636 core(lantern): traverse generator method
  lighthouse-core/lib/dependency-graph/base-node.js
Labels: cla: yes, waiting4reviewer

#11578 core: add devtools path to DOMStats
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-core/audits/dobetterweb/dom-size.js
  lighthouse-core/gather/gatherers/dobetterweb/domstats.js
  lighthouse-core/lib/page-functions.js
  lighthouse-core/test/audits/dobetterweb/dom-size-test.js
  lighthouse-core/test/lib/i18n/swap-locale-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/artifacts/defaultPass.trace.json
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: cla: yes, waiting4committer

#11650 clients(viewer): extract the LHR from PSI json
  lighthouse-viewer/app/src/lighthouse-report-viewer.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11645 docs: update throttling reference
  docs/throttling.md
Labels: cla: yes, waiting4reviewer

#11612 core(preload-lcp-image): properly calculate the potential savings
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/audits/preload-lcp-image.js
  lighthouse-core/config/default-config.js
  lighthouse-core/config/experimental-config.js
  lighthouse-core/test/audits/preload-lcp-image-test.js
  lighthouse-core/test/results/sample_v2.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run-expected.txt
Labels: cla: yes, waiting4committer

#11665 tests: use setup-protoc bugfix branch
  .github/workflows/ci.yml
Labels: cla: yes, waiting4reviewer

#11660 deps: upgrade lighthouse-plugin-publisher-ads to 1.3.0
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
  yarn.lock
Labels: cla: yes, waiting4reviewer

#11635 misc(treemap): initialize app structure
  .github/workflows/ci.yml
  .travis.yml
  build/build-treemap.js
  docs/releasing.md
  jest.config.js
  lighthouse-cli/test/fixtures/static-server.js
  lighthouse-core/audits/script-treemap-data.js
  lighthouse-treemap/README.md
  lighthouse-treemap/app/debug.json
  lighthouse-treemap/app/index.html
  lighthouse-treemap/app/src/main.js
  lighthouse-treemap/app/src/util.js
  lighthouse-treemap/app/styles/treemap.css
  lighthouse-treemap/test/treemap-test-pptr.js
  lighthouse-treemap/tsconfig.json
  lighthouse-treemap/types/treemap.d.ts
  lighthouse-viewer/test/viewer-test-pptr.js
  package.json
  types/treemap.d.ts
  yarn.lock
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11664 tests: remove unnecessary jest babel transform
  jest.config.js
  lighthouse-cli/test/cli/bin-test.js
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/runner-test.js
Labels: cla: yes, land-when-ci-is-green

#11674 tests: update github actions to use env files
  .github/workflows/ci.yml
  .github/workflows/devtools.yml
Labels: cla: yes, waiting4reviewer

#11667 report: treemap opener, ?dev for localhost viewer and treemap
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/report-template.html
  lighthouse-viewer/app/src/lighthouse-report-viewer.js
Labels: cla: yes, waiting4reviewer

#11676 deps: update brfs to fix build in node 15
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11655 docs(readme): Apdex integration
  readme.md
Labels: cla: yes, waiting4reviewer

#11633 core(driver): extract evaluateAsync logic for FR driver
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/driver/execution-context.js
  lighthouse-core/gather/gatherers/accessibility.js
  lighthouse-core/test/gather/driver-test.js
  lighthouse-core/test/gather/driver/execution-context-test.js
  lighthouse-core/test/gather/mock-commands.js
  lighthouse-core/test/test-utils.js
  tsconfig.json
  types/gatherer.d.ts
Labels: cla: yes

#11608 core(tracehouse): improve CPU profiler timing refinement
  lighthouse-core/lib/tracehouse/cpu-profile-model.js
  lighthouse-core/lib/tracehouse/main-thread-tasks.js
  lighthouse-core/test/lib/tracehouse/cpu-profile-model-test.js
  lighthouse-core/test/lib/tracehouse/main-thread-tasks-test.js
  types/externs.d.ts
Labels: cla: yes

#11449 misc(build): give build-tracker a shared git history on PRs
  .github/scripts/git-get-shared-history.sh
  .github/workflows/ci.yml
  readme.md
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#11579 core(error): add dedicated error string for NO_FCP
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/lh-error.js
  lighthouse-core/test/runner-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#11426 tests(smoke): attempt to fix cls-elements flake
  lighthouse-cli/test/fixtures/perf/delayed-element.js
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#11685 core(driver): extract waitFor methods
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/driver/wait-for-condition.js
  lighthouse-core/test/gather/driver-test.js
  lighthouse-core/test/gather/driver/wait-for-condition-test.js
  types/gatherer.d.ts
Labels: cla: yes, waiting4reviewer

#11693 deps: bump various dependencies to quiet security alerts
  yarn.lock
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11702 tests: rebaseline devtools test, print each .lh-audit id
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run.js
Labels: cla: yes

#11690 deps: update to typescript 4.1.2
  build/gh-pages-app.js
  lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
  lighthouse-core/audits/byte-efficiency/unminified-css.js
  lighthouse-core/audits/dobetterweb/charset.js
  lighthouse-core/config/config.js
  lighthouse-core/gather/fetcher.js
  lighthouse-core/gather/gatherers/image-elements.js
  lighthouse-core/lib/dependency-graph/simulator/simulator.js
  lighthouse-core/lib/i18n/swap-locale.js
  lighthouse-core/lib/lh-error.js
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/scripts/generate-bundlephobia-database.js
  lighthouse-core/scripts/lantern/constants.js
  lighthouse-core/scripts/lantern/print-correlations.js
  package.json
  types/lhr.d.ts
  yarn.lock
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#11688 core(full-page-screenshot): use dpr 1
  lighthouse-core/gather/gatherers/full-page-screenshot.js
  lighthouse-core/test/gather/gatherers/full-page-screenshot-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11689 core(full-page-screenshot): drop max datauri size constraints
  lighthouse-core/gather/gatherers/full-page-screenshot.js
  lighthouse-core/test/gather/gatherers/full-page-screenshot-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#11715 i18n: import
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
Labels: cla: yes, waiting4committer

#11701 core(metrics): support LCP in all frames for devtools throttling
  lighthouse-core/computed/metrics/largest-contentful-paint-all-frames.js
  lighthouse-core/computed/metrics/timing-summary.js
  lighthouse-core/lib/lh-error.js
  lighthouse-core/lib/tracehouse/trace-processor.js
  lighthouse-core/test/audits/__snapshots__/metrics-test.js.snap
  lighthouse-core/test/audits/metrics-test.js
  lighthouse-core/test/computed/metrics/largest-contentful-paint-all-frames-test.js
  lighthouse-core/test/computed/metrics/timing-summary-test.js
  lighthouse-core/test/fixtures/traces/lcp-all-frames-m89.devtools.log.json
  lighthouse-core/test/fixtures/traces/lcp-all-frames-m89.json
  lighthouse-core/test/lib/tracehouse/trace-processor-test.js
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: cla: yes, waiting4reviewer

#11672 core: add timing instrumentation for base artifacts
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/lib/stack-collector.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11713 core(metrics): support CLS for all frames
  lighthouse-core/audits/metrics.js
  lighthouse-core/computed/metrics/cumulative-layout-shift-all-frames.js
  lighthouse-core/computed/metrics/timing-summary.js
  lighthouse-core/lib/minify-trace.js
  lighthouse-core/test/audits/__snapshots__/metrics-test.js.snap
  lighthouse-core/test/audits/metrics-test.js
  lighthouse-core/test/computed/metrics/cumulative-layout-shift-all-frames-test.js
  lighthouse-core/test/computed/metrics/largest-contentful-paint-all-frames-test.js
  lighthouse-core/test/computed/metrics/timing-summary-test.js
  lighthouse-core/test/fixtures/traces/frame-metrics-m89.devtools.log.json
  lighthouse-core/test/fixtures/traces/frame-metrics-m89.json
  lighthouse-core/test/fixtures/traces/lcp-all-frames-m89.devtools.log.json
  lighthouse-core/test/fixtures/traces/lcp-all-frames-m89.json
  lighthouse-core/test/lib/tracehouse/trace-processor-test.js
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: cla: yes, waiting4committer

#11719 deps: remove cz-customizable as local dep
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#11536 core(full-page-screenshot): resolve node rects during emulation
  lighthouse-cli/test/fixtures/screenshot.html
  lighthouse-cli/test/smokehouse/test-definitions/screenshot/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/screenshot/screenshot-config.js
  lighthouse-core/audits/accessibility/axe-audit.js
  lighthouse-core/audits/full-page-screenshot.js
  lighthouse-core/audits/largest-contentful-paint-element.js
  lighthouse-core/audits/layout-shift-elements.js
  lighthouse-core/audits/seo/tap-targets.js
  lighthouse-core/gather/driver/execution-context.js
  lighthouse-core/gather/gatherers/full-page-screenshot.js
  lighthouse-core/lib/page-functions.js
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/report/html/renderer/element-screenshot-renderer.js
  lighthouse-core/report/html/renderer/report-renderer.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/gather/gatherers/full-page-screenshot-test.js
  lighthouse-core/test/report/html/renderer/details-renderer-test.js
  lighthouse-core/test/runner-test.js
  lighthouse-core/test/test-utils.js
  types/artifacts.d.ts
  types/audit-details.d.ts
  types/externs.d.ts
Labels: cla: yes, waiting4reviewer

#11727 core(driver): resume on debugger statements
  lighthouse-cli/test/fixtures/debugger.html
  lighthouse-cli/test/smokehouse/test-definitions/tricky-metrics/expectations.js
  lighthouse-core/gather/driver.js
Labels: cla: yes, waiting4reviewer

#11729 core(stacks): update to support october cms and joomla
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/stack-packs.js
  lighthouse-core/test/lib/stack-packs-test.js
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer
