Repository GoogleChrome/lighthouse, pull requests merged in 2020-09, with the labels that each got.

#11330 core(installable-manifest): expose app manifest url
  lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa2-expectations.js
  lighthouse-core/audits/installable-manifest.js
  lighthouse-core/lib/manifest-parser.js
  lighthouse-core/test/audits/installable-manifest-test.js
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4reviewer

#11351 tests(webtests): rebaseline
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run-expected.txt
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11361 misc: flatten new service-worker audit details
  lighthouse-cli/test/smokehouse/test-definitions/offline-local/offline-expectations.js
  lighthouse-core/audits/service-worker.js
  lighthouse-core/test/audits/service-worker-test.js
Labels: cla: yes, waiting4reviewer

#11362 core(axe): use our html snippet rather than axe's
  lighthouse-cli/test/smokehouse/test-definitions/a11y/expectations.js
  lighthouse-core/audits/accessibility/axe-audit.js
  lighthouse-core/test/audits/accessibility/axe-audit-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4reviewer

#11364 tests(webtests): test pub ads plugin
  build/build-bundle.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run.js
Labels: cla: yes, waiting4reviewer

#11359 report: set min-width on code table column
  lighthouse-core/report/html/report-styles.css
Labels: cla: yes, waiting4reviewer

#11333 docs(releasing): align 2 days before branch. update managers
  docs/releasing.md
Labels: cla: yes, waiting4reviewer

#11366 misc(build): include publisher ads plugin in lightrider bundle
  build/build-bundle.js
  lighthouse-core/config/config-helpers.js
Labels: cla: yes, waiting4committer

#11367 misc: fix typos in jsdoc types
  lighthouse-core/gather/gatherers/trace-elements.js
Labels: cla: yes, land-when-ci-is-green

#11353 report: normalize -0 to 0
  lighthouse-core/report/html/renderer/i18n.js
  lighthouse-core/test/report/html/renderer/i18n-test.js
Labels: cla: yes, waiting4reviewer

#11048 docs: add microlink as tool
  readme.md
Labels: cla: yes, land-when-ci-is-green

#11302 core(js-usage): normalize url key
  lighthouse-cli/test/fixtures/byte-efficiency/tester.html
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-core/audits/no-unload-listeners.js
  lighthouse-core/computed/unused-javascript-summary.js
  lighthouse-core/gather/gatherers/js-usage.js
  lighthouse-core/test/audits/no-unload-listeners-test.js
  lighthouse-core/test/gather/driver-test.js
  lighthouse-core/test/gather/gatherers/js-usage-test.js
  lighthouse-core/test/gather/gatherers/source-maps-test.js
  package.json
  types/artifacts.d.ts
  yarn.lock
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11342 core(autocomplete): add chrome suggestions, invalid warning
  lighthouse-cli/bin.js
  lighthouse-cli/run.js
  lighthouse-cli/test/fixtures/form.html
  lighthouse-cli/test/smokehouse/test-definitions/a11y/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/forms/form-expectations.js
  lighthouse-core/audits/autocomplete.js
  lighthouse-core/gather/gatherers/form-elements.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/page-functions.js
  lighthouse-core/test/audits/autocomplete-test.js
  types/artifacts.d.ts
Labels: cla: yes, waiting4committer

#11370 core(stack-packs): move to lighthouse-stack-packs npm package
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
  lighthouse-core/lib/stack-packs.js
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/test/results/sample_v2.json
  package.json
  stack-packs/README.md
  stack-packs/index.js
  stack-packs/package.json
  stack-packs/packs/angular.js
  stack-packs/stack-packs.d.ts
  yarn.lock
Labels: cla: yes

#11390 docs(readme): remove PageSpeed Green from related projects
  readme.md
Labels: cla: yes, waiting4reviewer

#11377 docs(variability): expand on lighthouse-ci usage
  docs/variability.md
Labels: cla: yes, waiting4reviewer

#11373 core(is-on-https): remove <M84 codepaths
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-core/audits/is-on-https.js
  lighthouse-core/test/audits/is-on-https-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4reviewer

#11395 core(minification-estimator): minify nested template literals in JavaScript
  lighthouse-core/lib/minification-estimator.js
  lighthouse-core/test/lib/minification-estimator-test.js
Labels: cla: yes, waiting4committer

#11401 i18n: code-escape <link> in preconnect and preload
  lighthouse-core/audits/uses-rel-preconnect.js
  lighthouse-core/audits/uses-rel-preload.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
Labels: cla: yes, waiting4reviewer

#11363 misc: hide locale files by default in PRs
  .gitattributes
Labels: cla: yes, waiting4committer

#11404 report: show overall category scores in csv output
  lighthouse-core/report/report-generator.js
  lighthouse-core/test/report/report-generator-test.js
Labels: cla: yes, waiting4committer

#11358 tests: add markdown link checker
  .github/workflows/check-md-links.yml
  .github/workflows/ci.yml
  .github/workflows/markdown.links.config.json
  docs/readme.md
Labels: cla: yes, waiting4reviewer

#11418 misc(build): fix devtools tests by making empty type files
  build/build-dt-report-resources.js
Labels: cla: yes, waiting4reviewer

#10522 core(stack-packs): add Drupal pack
  lighthouse-core/lib/stack-packs.js
  package.json
  yarn.lock
Labels: cla: yes

#10956 core: traverse shadow hosts in getNodePath
  lighthouse-cli/test/fixtures/perf/delayed-element.js
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-core/lib/page-functions.js
Labels: cla: yes, waiting4reviewer

#11425 tests(smoke): fix preconnect flake w/ a non-locally installed font
  lighthouse-cli/test/fixtures/perf/preload_tester.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11396 misc: update stack packs, remove duplicated stack pack files
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
  lighthouse-core/lib/stack-packs.js
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/test/lib/stack-packs-test.js
  lighthouse-core/test/results/sample_v2.json
  package.json
  stack-packs/packs/amp.js
  stack-packs/packs/magento.js
  stack-packs/packs/react.js
  stack-packs/packs/wordpress.js
  yarn.lock
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11417 tests: hash more files for devtools test cache
  .github/workflows/devtools.yml
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11200 report: let fireworks eligibility ignore PWA category
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/test/report/html/renderer/report-ui-features-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#11411 clients(devtools): update report-generator.js to match DevTools changes
  build/build-bundle.js
  clients/devtools-report-assets.js
  lighthouse-cli/test/smokehouse/lighthouse-runners/bundle.js
Labels: cla: yes, waiting4committer

#11432 misc(axe): rename axe types
  lighthouse-core/gather/gatherers/accessibility.js
  types/artifacts.d.ts
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11437 tests: check for dependencies when setting up blink tools
  lighthouse-core/test/chromium-web-tests/download-blink-tools.sh
Labels: cla: yes, waiting4reviewer

#11405 core: normalize node information in gathering
  lighthouse-cli/test/smokehouse/test-definitions/seo/expectations.js
  lighthouse-core/audits/accessibility/axe-audit.js
  lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js
  lighthouse-core/audits/seo/crawlable-anchors.js
  lighthouse-core/audits/seo/tap-targets.js
  lighthouse-core/gather/gatherers/accessibility.js
  lighthouse-core/gather/gatherers/anchor-elements.js
  lighthouse-core/gather/gatherers/dobetterweb/password-inputs-with-prevented-paste.js
  lighthouse-core/gather/gatherers/form-elements.js
  lighthouse-core/gather/gatherers/iframe-elements.js
  lighthouse-core/gather/gatherers/image-elements.js
  lighthouse-core/gather/gatherers/link-elements.js
  lighthouse-core/gather/gatherers/script-elements.js
  lighthouse-core/gather/gatherers/seo/tap-targets.js
  lighthouse-core/gather/gatherers/trace-elements.js
  lighthouse-core/lib/page-functions.js
  lighthouse-core/test/gather/gatherers/link-elements-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: cla: yes, waiting4committer

#11416 core(password-inputs-can-be-pasted-into): add devtoolsNodePath
  lighthouse-cli/test/smokehouse/test-definitions/a11y/expectations.js
  lighthouse-core/audits/accessibility/axe-audit.js
  lighthouse-core/audits/dobetterweb/password-inputs-can-be-pasted-into.js
  lighthouse-core/gather/gatherers/accessibility.js
  lighthouse-core/test/report/html/renderer/category-renderer-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4committer

#11439 clients(lr): enable uses-http2, add protocol override header
  lighthouse-core/audits/network-requests.js
  lighthouse-core/config/lr-desktop-config.js
  lighthouse-core/config/lr-mobile-config.js
  lighthouse-core/lib/network-request.js
  lighthouse-core/test/lib/network-request-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4reviewer

#11441 deps(inquirer): upgrade to 7.3.3
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#10630 i18n: use IcuMessage objects instead of string IDs
  clients/test/extension/settings-controller-test.js
  lighthouse-cli/run.js
  lighthouse-core/audits/audit.js
  lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
  lighthouse-core/audits/byte-efficiency/render-blocking-resources.js
  lighthouse-core/audits/content-width.js
  lighthouse-core/audits/deprecations.js
  lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js
  lighthouse-core/audits/dobetterweb/no-vulnerable-libraries.js
  lighthouse-core/audits/dobetterweb/uses-http2.js
  lighthouse-core/audits/font-display.js
  lighthouse-core/audits/image-aspect-ratio.js
  lighthouse-core/audits/is-on-https.js
  lighthouse-core/audits/load-fast-enough-for-pwa.js
  lighthouse-core/audits/non-composited-animations.js
  lighthouse-core/audits/offline-start-url.js
  lighthouse-core/audits/performance-budget.js
  lighthouse-core/audits/resource-summary.js
  lighthouse-core/audits/seo/hreflang.js
  lighthouse-core/audits/service-worker.js
  lighthouse-core/audits/third-party-summary.js
  lighthouse-core/audits/timing-budget.js
  lighthouse-core/audits/user-timings.js
  lighthouse-core/audits/uses-rel-preconnect.js
  lighthouse-core/audits/uses-rel-preload.js
  lighthouse-core/config/config-helpers.js
  lighthouse-core/config/config-plugin.js
  lighthouse-core/config/config.js
  lighthouse-core/lib/i18n/README.md
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/lib/i18n/swap-locale.js
  lighthouse-core/lib/stack-packs.js
  lighthouse-core/lib/type-verifiers.js
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/runner.js
  lighthouse-core/scoring.js
  lighthouse-core/scripts/legacy-javascript/examine-latest-run.js
  lighthouse-core/test/audits/autocomplete-test.js
  lighthouse-core/test/audits/third-party-summary-test.js
  lighthouse-core/test/chromium-web-tests/run-web-tests.sh
  lighthouse-core/test/config/config-plugin-test.js
  lighthouse-core/test/config/config-test.js
  lighthouse-core/test/lib/i18n/i18n-test.js
  lighthouse-core/test/lib/i18n/swap-locale-test.js
  lighthouse-core/test/results/sample_v2.json
  lighthouse-core/test/runner-test.js
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  types/artifacts.d.ts
  types/audit-details.d.ts
  types/audit.d.ts
  types/config.d.ts
  types/gatherer.d.ts
  types/i18n.d.ts
  types/lhr.d.ts
  yarn.lock
Labels: cla: yes, waiting4reviewer

#11448 deps: update transitive lodash
  yarn.lock
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#9605 misc(build): minify bundles with terser
  build/banner.txt
  build/build-bundle.js
  lighthouse-core/gather/gatherers/seo/tap-targets.js
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11433 tests(page-functions): add test for getNodePath
  lighthouse-core/lib/page-functions.js
  lighthouse-core/test/lib/page-functions-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11434 deps: chrome-launcher to v0.13.4
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11447 misc: tweak typescript jsdoc for list format
  types/audit.d.ts
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11461 misc(build): use terser on inline assets
  build/build-bundle.js
  build/build-utils.js
  package.json
Labels: cla: yes, waiting4committer

#11445 misc: yarn open-devtools
  lighthouse-core/scripts/open-devtools.sh
  package.json
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#11466 core(is-on-https): add missing space in description
  lighthouse-core/audits/is-on-https.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11406 i18n: use placeholders more for html terms
  lighthouse-cli/test/smokehouse/test-definitions/forms/form-expectations.js
  lighthouse-core/audits/autocomplete.js
  lighthouse-core/audits/dobetterweb/charset.js
  lighthouse-core/audits/uses-rel-preconnect.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/autocomplete-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11469 deps: update third-party-web
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#11476 misc: make FormElements not a public artifact
  types/artifacts.d.ts
Labels: cla: yes, land-when-ci-is-green

#11457 core(image-elements): do not set untrusted natural dimensions
  lighthouse-cli/test/fixtures/byte-efficiency/tester.html
  lighthouse-cli/test/fixtures/static-server.js
  lighthouse-core/gather/gatherers/image-elements.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11484 core(large-javascript-libraries): move to experimental
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/config/default-config.js
  lighthouse-core/config/experimental-config.js
  lighthouse-core/test/results/sample_v2.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run-expected.txt
Labels: cla: yes, waiting4reviewer

#11483 core(benchmarkindex): add workaround for Intel microcode fixes
  lighthouse-core/lib/page-functions.js
Labels: cla: yes, waiting4reviewer

#11473 docs(auth): add setCookie example
  docs/authenticated-pages.md
  docs/puppeteer.md
  docs/recipes/auth/README.md
Labels: cla: yes, land-when-ci-is-green

#11492 deps(lighthouse-stack-packs): update
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/lib/stack-packs-test.js
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#11463 misc(build): fix mangling for tap-targets gatherer
  lighthouse-core/gather/gatherers/seo/tap-targets.js
Labels: cla: yes, rls-blocker, waiting4committer

#11487 i18n: remove incorrect aliases
  lighthouse-core/lib/i18n/locales.js
  types/externs.d.ts
Labels: cla: yes, waiting4reviewer

#11494 i18n: import
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
Labels: cla: yes

#11438 core(driver): don't clear indexedb, websql, or localstorage before run
  lighthouse-core/audits/multi-check-audit.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/gather/driver-test.js
  lighthouse-core/test/gather/fake-driver.js
  lighthouse-core/test/gather/gather-runner-test.js
  types/jest.d.ts
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11499 v6.4.0
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes
