Repository GoogleChrome/lighthouse, pull requests merged in 2021-01, with the labels that each got.

#11759 core(config): refactor config cloning for fraggle rock
  lighthouse-core/config/config-helpers.js
  lighthouse-core/config/config.js
  lighthouse-core/runner.js
  lighthouse-core/test/config/config-helpers-test.js
  types/config.d.ts
Labels: cla: yes, waiting4committer

#11916 tests: increase treemap pptr timeouts
  lighthouse-treemap/test/treemap-test-pptr.js
  lighthouse-viewer/test/viewer-test-pptr.js
Labels: cla: yes, waiting4reviewer

#11917 core(fr): add base gatherer class
  lighthouse-core/fraggle-rock/api.js
  lighthouse-core/fraggle-rock/gather/base-gatherer.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/gather/gatherers/accessibility.js
  lighthouse-core/test/fraggle-rock/gather/base-gatherer-test.js
  types/gatherer.d.ts
Labels: cla: yes, waiting4committer

#11915 core(fr): add base config
  lighthouse-core/config/config-helpers.js
  lighthouse-core/config/config.js
  lighthouse-core/fraggle-rock/config/config.js
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/test/config/config-helpers-test.js
  lighthouse-core/test/fraggle-rock/config/config-test.js
Labels: cla: yes, waiting4reviewer

#11902 tests: remove travis
  .eslintignore
  .npmignore
  .travis.yml
  docs/hacking-tips.md
  docs/headless-chrome.md
  lighthouse-core/lib/lh-env.js
  lighthouse-core/scripts/cleanup-LHR-for-diff.js
  lighthouse-core/scripts/log-travis-durations.rb
  lighthouse-core/scripts/restart-travis-builds.rb
  readme.md
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#11684 docs(chromium-web-tests): add debugging tips
  lighthouse-core/test/chromium-web-tests/README.md
Labels: cla: yes, waiting4reviewer

#11946 core(proto): clarify deprecated state of EmulatedFormFactor enum
  proto/lighthouse-result.proto
Labels: cla: yes, land-when-ci-is-green

#11877 core: normalize creation of NodeValue
  lighthouse-core/audits/accessibility/axe-audit.js
  lighthouse-core/audits/audit.js
  lighthouse-core/audits/autocomplete.js
  lighthouse-core/audits/dobetterweb/dom-size.js
  lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js
  lighthouse-core/audits/dobetterweb/password-inputs-can-be-pasted-into.js
  lighthouse-core/audits/largest-contentful-paint-element.js
  lighthouse-core/audits/layout-shift-elements.js
  lighthouse-core/audits/non-composited-animations.js
  lighthouse-core/audits/seo/crawlable-anchors.js
  lighthouse-core/audits/seo/plugins.js
  lighthouse-core/audits/seo/tap-targets.js
  lighthouse-core/audits/unsized-images.js
  lighthouse-core/gather/gatherers/seo/embedded-content.js
  lighthouse-core/lib/page-functions.js
  lighthouse-core/test/audits/autocomplete-test.js
  lighthouse-core/test/audits/seo/plugins-test.js
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
  types/externs.d.ts
Labels: cla: yes, waiting4reviewer

#11947 i18n: import
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11901 core(errors-in-console): ignore BLOCKED_BY_CLIENT.Inspector errors
  lighthouse-core/audits/errors-in-console.js
  lighthouse-core/test/audits/errors-in-console-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11847 core(full-page-screenshot): get the MAX_TEXTURE_SIZE from the browser
  lighthouse-core/gather/gatherers/full-page-screenshot.js
  lighthouse-core/lib/page-functions.js
  lighthouse-core/test/gather/gatherers/full-page-screenshot-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11941 core(fr): filter configs by gather mode
  lighthouse-core/fraggle-rock/api.js
  lighthouse-core/fraggle-rock/config/config.js
  lighthouse-core/fraggle-rock/config/filters.js
  lighthouse-core/fraggle-rock/config/validation.js
  lighthouse-core/runner.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/fraggle-rock/config/config-test.js
  lighthouse-core/test/fraggle-rock/config/filters-test.js
  lighthouse-core/test/fraggle-rock/config/validation-test.js
  types/config.d.ts
Labels: cla: yes, waiting4reviewer

#11944 core(fr): add basic timespan support
  lighthouse-core/fraggle-rock/api.js
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/fraggle-rock/gather/base-artifacts.js
  lighthouse-core/fraggle-rock/gather/base-gatherer.js
  lighthouse-core/fraggle-rock/gather/snapshot-runner.js
  lighthouse-core/fraggle-rock/gather/timespan-runner.js
  lighthouse-core/gather/gatherers/console-messages.js
  lighthouse-core/test/fixtures/fraggle-rock/snapshot-basic/onclick.html
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/fraggle-rock/gather/base-gatherer-test.js
  lighthouse-core/test/gather/gatherers/console-messages-test.js
  types/gatherer.d.ts
Labels: cla: yes, waiting4reviewer

#11770 tests: run code coverage in github actions
  .github/workflows/ci.yml
  lighthouse-core/gather/fetcher.js
  lighthouse-core/gather/gatherers/accessibility.js
  lighthouse-core/gather/gatherers/anchor-elements.js
  lighthouse-core/gather/gatherers/cache-contents.js
  lighthouse-core/gather/gatherers/dobetterweb/domstats.js
  lighthouse-core/gather/gatherers/dobetterweb/password-inputs-with-prevented-paste.js
  lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js
  lighthouse-core/gather/gatherers/form-elements.js
  lighthouse-core/gather/gatherers/iframe-elements.js
  lighthouse-core/gather/gatherers/image-elements.js
  lighthouse-core/gather/gatherers/link-elements.js
  lighthouse-core/gather/gatherers/meta-elements.js
  lighthouse-core/gather/gatherers/script-elements.js
  lighthouse-core/gather/gatherers/seo/robots-txt.js
  lighthouse-core/gather/gatherers/seo/tap-targets.js
  lighthouse-core/gather/gatherers/trace-elements.js
  lighthouse-core/gather/gatherers/viewport-dimensions.js
  lighthouse-core/lib/page-functions.js
  lighthouse-core/lib/rect-helpers.js
  lighthouse-core/lib/stack-collector.js
  lighthouse-core/scripts/c8.sh
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11955 tests: revert mistaken change to yarn unit-core
  package.json
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11899 core(console-messages): use source-location
  lighthouse-core/audits/audit.js
  lighthouse-core/audits/deprecations.js
  lighthouse-core/audits/dobetterweb/geolocation-on-start.js
  lighthouse-core/audits/dobetterweb/no-document-write.js
  lighthouse-core/audits/dobetterweb/notification-on-start.js
  lighthouse-core/audits/dobetterweb/uses-passive-event-listeners.js
  lighthouse-core/audits/errors-in-console.js
  lighthouse-core/audits/no-unload-listeners.js
  lighthouse-core/audits/violation-audit.js
  lighthouse-core/gather/gatherers/console-messages.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: cla: yes, waiting4committer

#11958 core: add type checking to page functions
  lighthouse-core/gather/driver.js
  lighthouse-core/lib/page-functions.js
  lighthouse-core/test/gather/driver/execution-context-test.js
  lighthouse-core/test/lib/page-functions-test.js
  types/externs.d.ts
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#11932 tests(smoke): add category to run some perf tests in parallel
  lighthouse-cli/test/smokehouse/test-definitions/core-tests.js
  lighthouse-cli/test/smokehouse/test-definitions/perf-diagnostics/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/perf-diagnostics/perf-diagnostics-config.js
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
Labels: cla: yes, waiting4reviewer

#11957 core(fr): add navigations to config
  lighthouse-core/config/constants.js
  lighthouse-core/fraggle-rock/config/config.js
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/test/fraggle-rock/config/config-test.js
  lighthouse-core/test/fraggle-rock/config/filters-test.js
  types/config.d.ts
Labels: cla: yes, waiting4reviewer

#11934 core(font-size): handle valueless attributes for inline styles
  lighthouse-cli/test/fixtures/seo/seo-tester.html
  lighthouse-cli/test/smokehouse/test-definitions/seo/expectations.js
  lighthouse-core/audits/seo/font-size.js
  lighthouse-core/test/audits/seo/font-size-test.js
Labels: cla: yes, waiting4reviewer

#11874 core(metrics): support FCP for all frames with devtools throttling
  lighthouse-cli/test/fixtures/perf/frame-metrics-inner.html
  lighthouse-cli/test/fixtures/perf/frame-metrics.html
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-core/computed/metrics/first-contentful-paint-all-frames.js
  lighthouse-core/computed/metrics/timing-summary.js
  lighthouse-core/computed/trace-of-tab.js
  lighthouse-core/lib/tracehouse/trace-processor.js
  lighthouse-core/test/audits/__snapshots__/metrics-test.js.snap
  lighthouse-core/test/computed/metrics/first-contentful-paint-all-frames-test.js
  lighthouse-core/test/computed/metrics/largest-contentful-paint-all-frames-test.js
  lighthouse-core/test/computed/metrics/timing-summary-test.js
  lighthouse-core/test/computed/trace-of-tab-test.js
  lighthouse-core/test/lib/tracehouse/trace-processor-test.js
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: cla: yes, land-when-ci-is-green

#11976 i18n: prevent strings with identical message and description
  lighthouse-core/audits/accessibility/aria-command-name.js
  lighthouse-core/audits/accessibility/aria-meter-name.js
  lighthouse-core/audits/accessibility/aria-progressbar-name.js
  lighthouse-core/audits/accessibility/aria-tooltip-name.js
  lighthouse-core/audits/accessibility/aria-treeitem-name.js
  lighthouse-core/audits/installable-manifest.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/test/audits/installable-manifest-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11977 misc(build): extract 'yarn link…' rigamarole to own npm script
  package.json
Labels: cla: yes, waiting4reviewer

#11980 tests(legacy-javascript): sync results
  lighthouse-core/scripts/legacy-javascript/summary-sizes.txt
  lighthouse-core/scripts/test-legacy-javascript.sh
Labels: cla: yes, waiting4reviewer

#10930 report: use source maps to show original file name
  lighthouse-core/audits/byte-efficiency/legacy-javascript.js
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/test/audits/byte-efficiency/legacy-javascript-test.js
  lighthouse-core/test/report/html/renderer/details-renderer-test.js
  types/audit-details.d.ts
Labels: cla: yes, waiting4reviewer

#11978 misc(proto): backport proto formatting fixes
  proto/lighthouse-result.proto
Labels: cla: yes, waiting4reviewer

#11987 core: handle timer throttling in DevTools to avoid timeouts
  lighthouse-core/lib/page-functions.js
Labels: cla: yes, waiting4reviewer

#11526 misc: return specific html element type for dom.find
  lighthouse-core/report/html/renderer/category-renderer.js
  lighthouse-core/report/html/renderer/dom.js
  lighthouse-core/report/html/renderer/element-screenshot-renderer.js
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/report/html/renderer/pwa-category-renderer.js
  lighthouse-core/report/html/renderer/report-renderer.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  package.json
  yarn.lock
Labels: cla: yes, waiting4committer

#11990 misc: use typed-query-selector for native querySelector
  clients/extension/scripts/popup.js
  lighthouse-core/gather/fetcher.js
  lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js
  lighthouse-core/report/html/renderer/category-renderer.js
  lighthouse-core/report/html/renderer/dom.js
  lighthouse-core/report/html/renderer/logger.js
  lighthouse-core/report/html/renderer/report-renderer.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-treemap/app/src/util.js
  lighthouse-viewer/app/src/lighthouse-report-viewer.js
  types/externs.d.ts
Labels: cla: yes, land-when-ci-is-green

#11975 core(fr): add navigation runner
  lighthouse-core/fraggle-rock/api.js
  lighthouse-core/fraggle-rock/config/config.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/test/fixtures/fraggle-rock/navigation-basic/index.html
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/fraggle-rock/config/config-test.js
  lighthouse-core/test/fraggle-rock/gather/mock-driver.js
  lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
  lighthouse-core/test/gather/driver/execution-context-test.js
  types/config.d.ts
Labels: cla: yes, waiting4reviewer

#11997 misc: fix "fast" npm script
  package.json
Labels: cla: yes, land-when-ci-is-green

#11989 report: remove title from audit clump expand
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
  lighthouse-core/report/html/renderer/category-renderer.js
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/report/html/templates.html
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, land-when-ci-is-green

#12004 v7.0.1
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes

#11995 core(fr): add session.onAnyProtocolMessage listener
  lighthouse-core/fraggle-rock/gather/driver.js
  lighthouse-core/fraggle-rock/gather/session.js
  lighthouse-core/gather/driver.js
  lighthouse-core/test/fraggle-rock/gather/driver-test.js
  lighthouse-core/test/fraggle-rock/gather/session-test.js
  types/gatherer.d.ts
Labels: cla: yes

#11993 core(fr): initial gatherer migration for snapshot, navigation
  lighthouse-core/gather/driver/execution-context.js
  lighthouse-core/gather/gatherers/accessibility.js
  lighthouse-core/gather/gatherers/cache-contents.js
  lighthouse-core/gather/gatherers/console-messages.js
  lighthouse-core/gather/gatherers/dobetterweb/appcache.js
  lighthouse-core/gather/gatherers/dobetterweb/doctype.js
  lighthouse-core/gather/gatherers/dobetterweb/domstats.js
  lighthouse-core/gather/gatherers/dobetterweb/password-inputs-with-prevented-paste.js
  lighthouse-core/gather/gatherers/form-elements.js
  lighthouse-core/gather/gatherers/global-listeners.js
  lighthouse-core/gather/gatherers/iframe-elements.js
  lighthouse-core/gather/gatherers/meta-elements.js
  lighthouse-core/gather/gatherers/seo/embedded-content.js
  lighthouse-core/gather/gatherers/seo/font-size.js
  lighthouse-core/gather/gatherers/seo/robots-txt.js
  lighthouse-core/gather/gatherers/seo/tap-targets.js
  lighthouse-core/gather/gatherers/viewport-dimensions.js
  lighthouse-core/test/config/config-test.js
  lighthouse-core/test/gather/driver/execution-context-test.js
  lighthouse-core/test/gather/gatherers/seo/font-size-test.js
Labels: cla: yes

#12013 misc: tighten querySelector types
  lighthouse-core/lib/page-functions.js
  types/externs.d.ts
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12006 core(fr): extract network monitor class
  lighthouse-core/computed/metrics/interactive.js
  lighthouse-core/fraggle-rock/gather/driver.js
  lighthouse-core/fraggle-rock/gather/session.js
  lighthouse-core/gather/connections/connection.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/driver/network-monitor.js
  lighthouse-core/gather/driver/wait-for-condition.js
  lighthouse-core/lib/network-recorder.js
  lighthouse-core/test/fraggle-rock/gather/session-test.js
  lighthouse-core/test/gather/driver-test.js
  lighthouse-core/test/gather/driver/network-monitor-test.js
  lighthouse-core/test/gather/mock-commands.js
  lighthouse-core/test/lib/network-recorder-test.js
  types/gatherer.d.ts
Labels: cla: yes, waiting4reviewer
