Repository GoogleChrome/lighthouse, pull requests merged in 2021-03, with the labels that each got.

#12154 docs: fixed typo in documentation throttling.md
  docs/throttling.md
Labels: cla: yes, waiting4reviewer

#12076 misc: reorganize accessibility gatherer
  lighthouse-core/audits/accessibility/axe-audit.js
  lighthouse-core/gather/gatherers/accessibility.js
  lighthouse-core/test/audits/accessibility/axe-audit-test.js
  lighthouse-core/test/gather/gatherers/accessibility-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#12140 cli: only launch Chrome when running against localhost
  lighthouse-cli/run.js
Labels: cla: yes, waiting4reviewer

#12202 tests(fr): update test artifact
  lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
Labels: cla: yes, waiting4reviewer

#12200 core(errors-in-console): properly define default options
  lighthouse-core/audits/errors-in-console.js
  lighthouse-core/test/audits/errors-in-console-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12044 new_audit: csp-xss
  .eslintignore
  lighthouse-core/audits/csp-xss.js
  lighthouse-core/config/experimental-config.js
  lighthouse-core/lib/csp-evaluator.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/csp-xss-test.js
  lighthouse-core/test/lib/csp-evaluator-test.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt
  third-party/csp-evaluator/optimized_binary.js
Labels: cla: yes, land-when-ci-is-green

#12220 misc: remove patrickhulce from issue assigner
  .github/workflows/issue-assigner.yml
Labels: cla: yes, waiting4reviewer

#12207 deps: update typescript and axe-core to latest
  build/build-bundle.js
  lighthouse-core/gather/gatherers/accessibility.js
  lighthouse-core/lib/proto-preprocessor.js
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12130 tests(devtools): update chromium dependencies
  .github/workflows/devtools.yml
  lighthouse-core/test/chromium-web-tests/download-blink-tools.sh
  third-party/download-content-shell/download-content-shell.js
Labels: cla: yes, waiting4reviewer

#12236 tests(devtools): fix webserver
  lighthouse-core/test/chromium-web-tests/download-blink-tools.sh
  lighthouse-core/test/chromium-web-tests/roll-devtools.sh
  lighthouse-core/test/chromium-web-tests/web-test-server.sh
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12221 core(csp-xss): csp evaluator npm module
  lighthouse-core/audits/csp-xss.js
  lighthouse-core/lib/csp-evaluator.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/csp-xss-test.js
  lighthouse-core/test/lib/csp-evaluator-test.js
  package.json
  third-party/csp-evaluator/optimized_binary.js
  yarn.lock
Labels: cla: yes, land-when-ci-is-green

#12232 tests(devtools): dynamically fetch chromium version
  third-party/download-content-shell/download-content-shell.js
  third-party/download-content-shell/utils.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12142 misc(treemap): unused-bytes view mode
  lighthouse-core/audits/byte-efficiency/unused-javascript.js
  lighthouse-treemap/app/index.html
  lighthouse-treemap/app/src/main.js
  lighthouse-treemap/app/styles/treemap.css
  types/treemap.d.ts
Labels: cla: yes, waiting4reviewer

#12250 cli: correctly parse screenEmulation boolean flags
  lighthouse-cli/cli-flags.js
  lighthouse-cli/test/cli/cli-flags-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12256 tests(smoke): ignore lantern script attribution in ToT
  lighthouse-cli/test/smokehouse/test-definitions/lantern/lantern-expectations.js
Labels: cla: yes, waiting4reviewer

#12257 deps: update jsonld to latest
  lighthouse-core/lib/sd-validation/json-expander.js
  lighthouse-core/test/lib/sd-validation-test.js
  package.json
  types/jsonld/index.d.ts
  yarn.lock
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12255 i18n: import
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
Labels: cla: yes, land-when-ci-is-green

#12201 report: css var for FPS, move overlay to container
  lighthouse-core/gather/gatherers/full-page-screenshot.js
  lighthouse-core/report/html/renderer/element-screenshot-renderer.js
  lighthouse-core/report/html/renderer/report-renderer.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/report-styles.css
Labels: cla: yes, rls-blocker, waiting4reviewer

#12265 tests(legacy-javascript): pin to specific versions of core-js
  lighthouse-core/scripts/legacy-javascript/run.js
  lighthouse-core/scripts/legacy-javascript/summary-sizes.txt
Labels: cla: yes, waiting4reviewer

#12266 v7.3.0
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes, waiting4reviewer

#12270 tests(smoke): remove max chrome for lantern script attribution
  lighthouse-cli/test/smokehouse/test-definitions/lantern/lantern-expectations.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12268 misc(sentry): tag protocol method
  lighthouse-core/lib/sentry.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12273 core(hreflang): use Audit.makeNodeItem
  lighthouse-core/audits/seo/hreflang.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12280 misc: fix PhaseArtifact type to include Stacks
  types/gatherer.d.ts
Labels: cla: yes, waiting4reviewer

#12288 clients(psi): support element screenshots
  lighthouse-core/report/html/renderer/element-screenshot-renderer.js
  lighthouse-core/report/html/renderer/psi.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/test/report/html/renderer/psi-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12240 core(csp-xss): hidden severity
  lighthouse-core/audits/csp-xss.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/test/audits/csp-xss-test.js
Labels: cla: yes, waiting4reviewer

#12310 tests(devtools): sync tests
  .github/workflows/devtools.yml
  third-party/chromium-webtests/README.md
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-block-url.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-clear-data-warning.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-flags-run.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-i18n-run.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-limited-run.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-prevent-run.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run.js
Labels: cla: yes, waiting4reviewer

#12312 tests(smoke): temporarily disable offline-warning check
  lighthouse-cli/test/smokehouse/test-definitions/offline-local/offline-expectations.js
Labels: cla: yes, waiting4reviewer

#12307 misc: include SVG elements by default in typed querySelector
  lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js
  lighthouse-core/report/html/renderer/dom.js
  lighthouse-treemap/app/src/util.js
  types/externs.d.ts
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer
