Repository GoogleChrome/lighthouse, pull requests merged in 2021-06, with the labels that each got.

#12574 core(fr): add settings to context
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/fraggle-rock/gather/runner-helpers.js
  lighthouse-core/fraggle-rock/gather/snapshot-runner.js
  lighthouse-core/fraggle-rock/gather/timespan-runner.js
  lighthouse-core/gather/gatherers/full-page-screenshot.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/fraggle-rock/config/config-test.js
  lighthouse-core/test/fraggle-rock/gather/mock-driver.js
  lighthouse-core/test/fraggle-rock/gather/runner-helpers-test.js
  lighthouse-core/test/gather/gatherers/css-usage-test.js
  lighthouse-core/test/gather/gatherers/full-page-screenshot-test.js
  types/artifacts.d.ts
  types/gatherer.d.ts
Labels: cla: yes, land-when-ci-is-green

#12576 core(scoring): update TBT score curve
  lighthouse-core/audits/metrics/total-blocking-time.js
  lighthouse-core/test/audits/metrics/total-blocking-time-test.js
  lighthouse-core/test/report/report-generator-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: 8.0, breaking, cla: yes, waiting4reviewer

#12577 core(scoring): rebalance perf metric weightings
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/config/default-config.js
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/test/report/report-generator-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: 8.0, breaking, cla: yes, land-when-ci-is-green, waiting4committer

#12590 report: fix addButton for provided container element
  lighthouse-core/report/html/renderer/report-ui-features.js
Labels: 8.0, cla: yes, land-when-ci-is-green, waiting4reviewer

#12591 i18n: import
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
Labels: 8.0, cla: yes, land-when-ci-is-green, waiting4reviewer

#12592 deps: update lighthouse-plugin-publisher-ads to latest
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
  yarn.lock
Labels: 8.0, cla: yes, land-when-ci-is-green, waiting4reviewer

#12597 docs: add v8.0 Performance FAQ
  changelog.md
  docs/v8-perf-faq.md
Labels: 8.0, cla: yes

#12596 docs: in-progress changelog for v8.0
  changelog.md
  docs/v8-perf-faq.md
Labels: 8.0, cla: yes, waiting4reviewer

#12593 v8.0.0
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  docs/v8-perf-faq.md
  lighthouse-core/test/results/sample_v2.json
  lighthouse-treemap/README.md
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: 8.0, cla: yes, land-when-ci-is-green, waiting4reviewer

#12603 misc(treemap): fix node coverage shading
  lighthouse-treemap/app/src/main.js
  lighthouse-treemap/app/styles/treemap.css
Labels: cla: yes, waiting4reviewer

#12598 misc(treemap): elide origin from url if same as requestedUrl
  lighthouse-treemap/app/src/main.js
  lighthouse-treemap/app/src/util.js
Labels: cla: yes, waiting4committer

#12510 core(fr): align base artifacts with legacy gather-runner
  lighthouse-core/fraggle-rock/config/filters.js
  lighthouse-core/fraggle-rock/gather/base-artifacts.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/fraggle-rock/gather/snapshot-runner.js
  lighthouse-core/fraggle-rock/gather/timespan-runner.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/fraggle-rock/config/filters-test.js
  lighthouse-core/test/fraggle-rock/gather/base-artifacts-test.js
Labels: cla: yes, waiting4reviewer

#12605 misc: fix typos and update faq answer
  docs/v8-perf-faq.md
  lighthouse-core/lib/lh-error.js
  lighthouse-core/report/html/readme.md
  lighthouse-core/report/html/renderer/util.js
  proto/README.md
  proto/lighthouse-result.proto
  readme.md
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12607 tests(smoke): relative source map hash
  lighthouse-cli/test/fixtures/csp.html
  lighthouse-cli/test/smokehouse/test-definitions/csp/csp-expectations.js
Labels: cla: yes, land-when-ci-is-green

#12606 tests: fix flaky cache test
  lighthouse-core/test/audits/byte-efficiency/uses-long-cache-ttl-test.js
Labels: cla: yes, waiting4committer

#12454 deps(jest): upgrade to 27.0.3
  clients/test/lightrider-entry-test.js
  jest.config.js
  lighthouse-core/test/report/html/renderer/report-ui-features-test.js
  lighthouse-treemap/test/treemap-test-pptr.js
  lighthouse-viewer/test/viewer-test-pptr.js
  package.json
  yarn.lock
Labels: cla: yes, waiting4committer

#12610 tests(report): increase timeout for running axe on report renderer
  lighthouse-core/test/report/html/renderer/report-renderer-test.js
Labels: cla: yes, waiting4committer

#12594 core(fr): convert additional base artifacts
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/fraggle-rock/config/filters.js
  lighthouse-core/fraggle-rock/gather/base-artifacts.js
  lighthouse-core/gather/gatherers/host-form-factor.js
  lighthouse-core/gather/gatherers/host-user-agent.js
  lighthouse-core/test/fraggle-rock/config/filters-test.js
  lighthouse-core/test/fraggle-rock/gather/base-artifacts-test.js
  lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
  types/artifacts.d.ts
  types/gatherer.d.ts
Labels: cla: yes, land-when-ci-is-green

#12609 tests(treemap): add test for node coverage shading
  lighthouse-treemap/test/treemap-test-pptr.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12621 core(fr): convert script-elements gatherer
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/gather/gatherers/script-elements.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/fraggle-rock/config/config-test.js
  lighthouse-core/test/gather/gatherers/script-elements-test.js
  types/artifacts.d.ts
Labels: cla: yes, waiting4committer

#12622 core(fr): more precise AnyFRInterface types
  lighthouse-core/fraggle-rock/config/config.js
  lighthouse-core/fraggle-rock/config/filters.js
  lighthouse-core/fraggle-rock/config/validation.js
  lighthouse-core/fraggle-rock/gather/runner-helpers.js
  lighthouse-core/test/fraggle-rock/gather/mock-driver.js
  lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
  lighthouse-core/test/fraggle-rock/gather/runner-helpers-test.js
  types/config.d.ts
  types/gatherer.d.ts
Labels: cla: yes, waiting4reviewer

#12625 deps(webtreemap): bump to fix focus traversal bug
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#12632 core(fr): fix main-document-content
  lighthouse-core/gather/driver/prepare.js
  lighthouse-core/gather/fetcher.js
  lighthouse-core/lib/emulation.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/gather/fetcher-test.js
  lighthouse-core/test/lib/emulation-test.js
Labels: cla: yes, waiting4committer

#12638 deps: update `ws` to latest
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#12644 tests(renderer): reduce console output about unknown types
  lighthouse-core/test/report/html/renderer/details-renderer-test.js
Labels: cla: yes, land-when-ci-is-green

#12634 core(tap-targets): add stylesheet over protocol
  lighthouse-cli/test/smokehouse/test-definitions/csp/csp-expectations.js
  lighthouse-core/gather/gatherers/seo/tap-targets.js
Labels: cla: yes, land-when-ci-is-green

#12649 core(fr): add audit mode filter
  lighthouse-core/fraggle-rock/config/filters.js
  lighthouse-core/test/fraggle-rock/config/filters-test.js
  types/audit.d.ts
Labels: cla: yes, land-when-ci-is-green

#12672 core(csp-xss): update learn more link
  lighthouse-core/audits/csp-xss.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4reviewer

#12662 core(fr): convert service-worker gatherer
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/gather/gatherers/service-worker.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/fraggle-rock/config/config-test.js
  lighthouse-core/test/gather/gatherers/service-worker-test.js
  types/artifacts.d.ts
Labels: cla: yes, waiting4reviewer

#12663 core(fr): add snapshot support to ImageElements gatherer
  lighthouse-core/audits/byte-efficiency/uses-responsive-images.js
  lighthouse-core/computed/image-records.js
  lighthouse-core/gather/gatherers/image-elements.js
  lighthouse-core/lib/url-shim.js
  lighthouse-core/test/audits/byte-efficiency/uses-responsive-images-test.js
  lighthouse-core/test/audits/image-aspect-ratio-test.js
  lighthouse-core/test/computed/image-records-test.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/gather/gatherers/image-elements-test.js
  lighthouse-core/test/lib/url-shim-test.js
  lighthouse-core/test/results/sample_v2.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes, waiting4committer

#12665 core(total-byte-weight): count partially finished requests
  lighthouse-core/audits/byte-efficiency/total-byte-weight.js
  lighthouse-core/test/audits/byte-efficiency/total-byte-weight-test.js
  lighthouse-core/test/network-records-to-devtools-log.js
Labels: cla: yes, waiting4committer

#12678 core(installable-manifest): align descriptions with applicatons panel
  lighthouse-core/audits/installable-manifest.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
Labels: cla: yes, land-when-ci-is-green

#12679 misc(scripts): error handling for pptr-run-devtools.js
  lighthouse-core/scripts/pptr-run-devtools.js
Labels: cla: yes, waiting4reviewer

#12680 core(fr): add timespan support to viewport-dimensions
  lighthouse-core/gather/gatherers/viewport-dimensions.js
  lighthouse-core/test/config/config-test.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
Labels: cla: yes, waiting4reviewer

#12681 core(network-request): consider HSTS redirects secure
  lighthouse-core/lib/network-request.js
  lighthouse-core/test/lib/network-request-test.js
Labels: cla: yes, waiting4reviewer

#12661 core(preload): temporarily disable all preload advice
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-core/audits/preload-fonts.js
  lighthouse-core/audits/preload-lcp-image.js
  lighthouse-core/audits/uses-rel-preload.js
  lighthouse-core/test/audits/preload-fonts-test.js
  lighthouse-core/test/audits/preload-lcp-image-test.js
  lighthouse-core/test/audits/uses-rel-preload-test.js
  lighthouse-core/test/report/html/renderer/category-renderer-test.js
  lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
  lighthouse-core/test/results/sample_v2.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes, waiting4committer

#12688 core(fr): add lighthouseMarker timeOrigin support
  lighthouse-core/gather/gatherers/trace.js
  lighthouse-core/lib/tracehouse/trace-processor.js
  lighthouse-core/test/fixtures/traces/timespan-trace-m91.json
  lighthouse-core/test/lib/tracehouse/trace-processor-test.js
  types/externs.d.ts
Labels: cla: yes, waiting4reviewer

#12694 misc: add GitHub bug report form
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: cla: yes, waiting4reviewer

#12701 tests: tweak variability assertion for load-things transferSize
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12695 core(fr): enable traces artifact in timespan mode
  lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
  lighthouse-core/audits/byte-efficiency/duplicated-javascript.js
  lighthouse-core/audits/byte-efficiency/efficient-animated-content.js
  lighthouse-core/audits/byte-efficiency/legacy-javascript.js
  lighthouse-core/audits/byte-efficiency/modern-image-formats.js
  lighthouse-core/audits/byte-efficiency/offscreen-images.js
  lighthouse-core/audits/byte-efficiency/render-blocking-resources.js
  lighthouse-core/audits/byte-efficiency/total-byte-weight.js
  lighthouse-core/audits/byte-efficiency/unminified-css.js
  lighthouse-core/audits/byte-efficiency/unminified-javascript.js
  lighthouse-core/audits/byte-efficiency/unused-css-rules.js
  lighthouse-core/audits/byte-efficiency/unused-javascript.js
  lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
  lighthouse-core/audits/byte-efficiency/uses-optimized-images.js
  lighthouse-core/audits/byte-efficiency/uses-responsive-images.js
  lighthouse-core/audits/byte-efficiency/uses-text-compression.js
  lighthouse-core/audits/critical-request-chains.js
  lighthouse-core/audits/diagnostics.js
  lighthouse-core/audits/dobetterweb/uses-http2.js
  lighthouse-core/audits/largest-contentful-paint-element.js
  lighthouse-core/audits/metrics/first-contentful-paint-3g.js
  lighthouse-core/audits/metrics/first-contentful-paint.js
  lighthouse-core/audits/metrics/first-meaningful-paint.js
  lighthouse-core/audits/metrics/interactive.js
  lighthouse-core/audits/metrics/largest-contentful-paint.js
  lighthouse-core/audits/metrics/max-potential-fid.js
  lighthouse-core/audits/metrics/speed-index.js
  lighthouse-core/audits/metrics/total-blocking-time.js
  lighthouse-core/audits/predictive-perf.js
  lighthouse-core/audits/preload-lcp-image.js
  lighthouse-core/audits/redirects.js
  lighthouse-core/audits/screenshot-thumbnails.js
  lighthouse-core/audits/third-party-facades.js
  lighthouse-core/audits/third-party-summary.js
  lighthouse-core/audits/timing-budget.js
  lighthouse-core/audits/uses-rel-preconnect.js
  lighthouse-core/audits/uses-rel-preload.js
  lighthouse-core/computed/metrics/timing-summary.js
  lighthouse-core/gather/gatherers/trace-compat.js
  lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js
  lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
  lighthouse-core/test/audits/byte-efficiency/duplicated-javascript-test.js
  lighthouse-core/test/audits/metrics/total-blocking-time-test.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/lib/dependency-graph/simulator/network-analyzer-test.js
  types/artifacts.d.ts
Labels: cla: yes, waiting4committer

#12706 deps(axe-core): upgrade to 4.2.3
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#12696 tests: add explicit small-icu detection for i18n
  lighthouse-core/test/config/config-helpers-test.js
  lighthouse-core/test/config/config-test.js
  lighthouse-core/test/lib/i18n/i18n-test.js
  lighthouse-core/test/lib/i18n/swap-locale-test.js
  lighthouse-core/test/test-utils.js
  report/test/renderer/i18n-test.js
Labels: cla: yes, waiting4committer

#12627 misc: npmignore larger unnecessary files
  .npmignore
Labels: cla: yes, waiting4reviewer

#12697 misc(scripts): improve collision check in collect-strings
  lighthouse-core/audits/accessibility/aria-progressbar-name.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4committer

#12682 core(modern-images): update to include AVIF estimates
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
  lighthouse-core/audits/byte-efficiency/modern-image-formats.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/byte-efficiency/modern-image-formats-test.js
  lighthouse-core/test/results/sample_v2.json
  report/test/renderer/report-ui-features-test.js
Labels: cla: yes, waiting4committer

#12707 misc(build): add build step for report
  .github/workflows/devtools.yml
  .github/workflows/smoke.yml
  .github/workflows/unit.yml
  .gitignore
  .npmignore
  build/build-report.js
  build/build-viewer.js
  build/readme.md
  docs/releasing.md
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/scripts/open-devtools.sh
  lighthouse-core/scripts/roll-to-devtools.sh
  package.json
  report/assets/standalone-template.html
  report/clients/standalone.js
  report/report-assets.js
Labels: cla: yes, waiting4reviewer

#12724 misc: get LH_ROOT via new file root.js
  build/build-bundle.js
  build/build-cdt-lib.js
  build/build-dt-report-resources.js
  build/build-extension.js
  build/build-lightrider-bundles.js
  build/build-smokehouse-bundle.js
  build/build-treemap.js
  build/build-viewer.js
  build/changelog-generator/index.js
  build/gh-pages-app.js
  clients/test/extension/popup-test.js
  lighthouse-cli/bin.js
  lighthouse-cli/test/cli/run-test.js
  lighthouse-cli/test/fixtures/static-server.js
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/scripts/build-report-for-autodeployment.js
  lighthouse-core/scripts/compare-runs.js
  lighthouse-core/scripts/gcp-collection/fleet-create-directories.js
  lighthouse-core/scripts/i18n/bake-ctc-to-lhl.js
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/scripts/i18n/count-translated.js
  lighthouse-core/scripts/i18n/prune-obsolete-lhl-messages.js
  lighthouse-core/scripts/internal-analysis/analyze-issues.js
  lighthouse-core/scripts/internal-analysis/download-issues.js
  lighthouse-core/scripts/lantern/collect/collect.js
  lighthouse-core/scripts/lantern/collect/common.js
  lighthouse-core/scripts/lantern/run-once.js
  lighthouse-core/scripts/legacy-javascript/examine-latest-run.js
  lighthouse-core/test/test-utils.js
  lighthouse-viewer/test/viewer-test-pptr.js
  report/test/renderer/psi-test.js
  root.js
  third-party/chromium-synchronization/inspector-issueAdded-types-test.js
  third-party/download-content-shell/download-content-shell.js
Labels: cla: yes, waiting4reviewer
