Repository GoogleChrome/lighthouse, pull requests merged in 2021-12, with the labels that each got.

#13441 deps(axe-core): upgrade to 4.3.5
  lighthouse-cli/test/smokehouse/test-definitions/a11y/expectations.js
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#13450 report: port axe test to pptr
  report/test/renderer/report-renderer-axe-test.js
Labels: cla: yes, waiting4reviewer

#13457 tests: fix devtools build command
  lighthouse-core/test/chromium-web-tests/roll-devtools.sh
Labels: cla: yes, waiting4reviewer

#13475 tests(smoke): fix chromestatus url
  changelog.md
  docs/puppeteer.md
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb.js
  lighthouse-cli/test/smokehouse/test-definitions/pwa-chromestatus.js
Labels: land-when-ci-is-green, waiting4reviewer

#13476 core: cache fetch to avoid bad polyfills
  lighthouse-core/gather/driver/execution-context.js
  lighthouse-core/test/gather/driver/execution-context-test.js
  types/externs.d.ts
Labels: waiting4reviewer

#13452 core(fcp): handle negative request `endTime`
  lighthouse-core/computed/metrics/lantern-first-contentful-paint.js
  lighthouse-core/test/computed/metrics/lantern-first-contentful-paint-test.js
  lighthouse-core/test/fixtures/lantern-baseline-accuracy.json
  lighthouse-core/test/fixtures/lantern-baseline-computed-values.json
Labels: cla: yes, waiting4reviewer

#13454 misc(treemap): add `lang` to html tag
  treemap/app/index.html
  treemap/app/src/main.js
Labels: cla: yes, waiting4reviewer

#13375 core(fr): option to skip about:blank jumps
  lighthouse-core/computed/page-dependency-graph.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/fraggle-rock/user-flow.js
  lighthouse-core/lib/dependency-graph/base-node.js
  lighthouse-core/test/computed/page-dependency-graph-test.js
  lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
  lighthouse-core/test/fraggle-rock/user-flow-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  types/config.d.ts
Labels: cla: yes, waiting4reviewer

#13355 report(psi): update styles for tighter fit in narrow viewports
  flow-report/assets/styles.css
  report/assets/styles.css
  report/assets/templates.html
  report/renderer/components.js
  report/renderer/report-renderer.js
  report/test-assets/faux-psi-template.html
  report/test-assets/faux-psi.js
Labels: cla: yes, waiting4reviewer

#13494 font-size selector specificity: add slight improvement
  lighthouse-core/gather/gatherers/seo/font-size.js
  lighthouse-core/test/gather/gatherers/seo/font-size-test.js
Labels: waiting4reviewer

#13497 core: move no-unload-listeners to perf category
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/audits/no-unload-listeners.js
  lighthouse-core/config/default-config.js
  lighthouse-core/test/results/sample_v2.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run-expected.txt
Labels: land-when-ci-is-green, waiting4reviewer

#13484 deps: bump eslint and related items
  .eslintrc.js
  lighthouse-core/audits/apple-touch-icon.js
  lighthouse-core/computed/critical-request-chains.js
  lighthouse-core/computed/unused-css.js
  lighthouse-core/fraggle-rock/gather/base-gatherer.js
  lighthouse-core/gather/driver/wait-for-condition.js
  lighthouse-core/gather/gatherers/accessibility.js
  lighthouse-core/gather/gatherers/anchor-elements.js
  lighthouse-core/gather/gatherers/cache-contents.js
  lighthouse-core/gather/gatherers/console-messages.js
  lighthouse-core/gather/gatherers/dobetterweb/doctype.js
  lighthouse-core/gather/gatherers/dobetterweb/domstats.js
  lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js
  lighthouse-core/gather/gatherers/dobetterweb/password-inputs-with-prevented-paste.js
  lighthouse-core/gather/gatherers/dobetterweb/response-compression.js
  lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js
  lighthouse-core/gather/gatherers/form-elements.js
  lighthouse-core/gather/gatherers/full-page-screenshot.js
  lighthouse-core/gather/gatherers/global-listeners.js
  lighthouse-core/gather/gatherers/iframe-elements.js
  lighthouse-core/gather/gatherers/inspector-issues.js
  lighthouse-core/gather/gatherers/js-usage.js
  lighthouse-core/gather/gatherers/main-document-content.js
  lighthouse-core/gather/gatherers/meta-elements.js
  lighthouse-core/gather/gatherers/script-elements.js
  lighthouse-core/gather/gatherers/seo/embedded-content.js
  lighthouse-core/gather/gatherers/seo/font-size.js
  lighthouse-core/gather/gatherers/seo/robots-txt.js
  lighthouse-core/gather/gatherers/service-worker.js
  lighthouse-core/gather/gatherers/source-maps.js
  lighthouse-core/gather/gatherers/trace-elements.js
  lighthouse-core/gather/gatherers/viewport-dimensions.js
  lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js
  lighthouse-core/test/audits/csp-xss-test.js
  lighthouse-core/test/gather/gatherers/console-messages-test.js
  lighthouse-core/test/gather/gatherers/dobetterweb/response-compression-test.js
  lighthouse-core/test/gather/gatherers/main-document-content-test.js
  lighthouse-core/test/gather/gatherers/trace-elements-test.js
  lighthouse-core/test/lib/tracehouse/trace-processor-test.js
  package.json
  viewer/app/src/drag-and-drop.js
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer

#13455 core(font-size): fix CSS selector regex
  lighthouse-core/gather/gatherers/seo/font-size.js
  lighthouse-core/test/gather/gatherers/seo/font-size-test.js
Labels: cla: yes, waiting4reviewer

#13478 core(fr): compute timespan saving with observed throughput
  lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
  lighthouse-core/computed/load-simulator.js
  lighthouse-core/lib/dependency-graph/simulator/simulator.js
  lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
  lighthouse-core/test/lib/dependency-graph/simulator/simulator-test.js
  types/gatherer.d.ts
Labels: waiting4reviewer

#13502 v9.2.0
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  docs/releasing.md
  lighthouse-core/test/results/sample_v2.json
  package.json
  third-party/chromium-synchronization/inspector-issueAdded-types-test.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: waiting4reviewer

#13500 misc: fix build-smokehouse-bundle build
  lighthouse-cli/test/smokehouse/smokehouse.js
Labels: waiting4reviewer

#13499 core(fr): don't throw on unknown --only-categories value
  lighthouse-core/fraggle-rock/config/filters.js
  lighthouse-core/test/fraggle-rock/config/filters-test.js
Labels: waiting4reviewer

#13517 core(object-alt): remove md syntax around "alt"
  lighthouse-core/audits/accessibility/object-alt.js
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/test/results/sample_v2.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: waiting4reviewer

#13515 misc(git3po): only install latest git3po if out of date
  lighthouse-core/scripts/run-git3po.sh
Labels: waiting4reviewer

#13483 deps: update various runtime deps
  package.json
  yarn.lock
Labels: waiting4reviewer

#13471 tests: clean up and add comments to cdt layout test scripts
  lighthouse-core/scripts/build-devtools.sh
  lighthouse-core/scripts/open-devtools.sh
  lighthouse-core/scripts/pptr-run-devtools.js
  lighthouse-core/test/chromium-web-tests/README.md
  lighthouse-core/test/chromium-web-tests/run-web-tests.sh
  lighthouse-core/test/chromium-web-tests/setup.sh
  lighthouse-core/test/chromium-web-tests/test-locally.sh
Labels: waiting4committer

#13485 deps: update various devDeps
  build/build-extension.js
  package.json
  yarn.lock
Labels: waiting4reviewer

#13518 report: allow client to configure how save-html is implemented
  report/assets/templates.html
  report/clients/standalone.js
  report/renderer/components.js
  report/renderer/report-ui-features.js
  report/test/renderer/report-ui-features-test.js
  report/types/report-renderer.d.ts
  viewer/app/src/lighthouse-report-viewer.js
  viewer/app/src/viewer-ui-features.js
  viewer/test/viewer-test-pptr.js
Labels: waiting4reviewer
