Repository GoogleChrome/lighthouse, pull requests merged in 2021-11, with the labels that each got.

#13233 report(flow): fix report anchors
  flow-report/src/app.tsx
  flow-report/src/header.tsx
  flow-report/src/sidebar/flow.tsx
  flow-report/src/sidebar/sidebar.tsx
  flow-report/src/util.ts
  flow-report/src/wrappers/report.tsx
  flow-report/test/header-test.tsx
  flow-report/test/util-test.tsx
  types/lhr/flow.d.ts
Labels: cla: yes, waiting4reviewer

#13283 report(flow): use filmstrip thumbnail in navigation
  flow-report/src/common.tsx
  flow-report/test/common-test.tsx
Labels: cla: yes, waiting4reviewer

#13297 tests: longer timeout for installability errors check
  third-party/chromium-synchronization/installability-errors-test.js
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13270 core(config): use abbreviation for pwa category title
  clients/extension/scripts/settings-controller.js
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/config/default-config.js
  lighthouse-core/test/results/sample_v2.json
  report/test/renderer/report-renderer-test.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: cla: yes, waiting4reviewer

#13298 core(external-anchors-use-rel-noopener): remove audit
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/offline-local/offline-expectations.js
  lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js
  lighthouse-core/config/default-config.js
  lighthouse-core/test/audits/dobetterweb/external-anchors-use-rel-noopener-test.js
  lighthouse-core/test/fraggle-rock/scenarios/api-test-pptr.js
  lighthouse-core/test/results/sample_v2.json
  shared/localization/locales/ar-XB.json
  shared/localization/locales/ar.json
  shared/localization/locales/bg.json
  shared/localization/locales/ca.json
  shared/localization/locales/cs.json
  shared/localization/locales/da.json
  shared/localization/locales/de.json
  shared/localization/locales/el.json
  shared/localization/locales/en-GB.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XA.json
  shared/localization/locales/en-XL.json
  shared/localization/locales/es-419.json
  shared/localization/locales/es.json
  shared/localization/locales/fi.json
  shared/localization/locales/fil.json
  shared/localization/locales/fr.json
  shared/localization/locales/he.json
  shared/localization/locales/hi.json
  shared/localization/locales/hr.json
  shared/localization/locales/hu.json
  shared/localization/locales/id.json
  shared/localization/locales/it.json
  shared/localization/locales/ja.json
  shared/localization/locales/ko.json
  shared/localization/locales/lt.json
  shared/localization/locales/lv.json
  shared/localization/locales/nl.json
  shared/localization/locales/no.json
  shared/localization/locales/pl.json
  shared/localization/locales/pt-PT.json
  shared/localization/locales/pt.json
  shared/localization/locales/ro.json
  shared/localization/locales/ru.json
  shared/localization/locales/sk.json
  shared/localization/locales/sl.json
  shared/localization/locales/sr-Latn.json
  shared/localization/locales/sr.json
  shared/localization/locales/sv.json
  shared/localization/locales/ta.json
  shared/localization/locales/te.json
  shared/localization/locales/th.json
  shared/localization/locales/tr.json
  shared/localization/locales/uk.json
  shared/localization/locales/vi.json
  shared/localization/locales/zh-HK.json
  shared/localization/locales/zh-TW.json
  shared/localization/locales/zh.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes, waiting4reviewer

#13284 misc: support old devtools in yarn run-devtools
  lighthouse-core/scripts/pptr-run-devtools.js
Labels: cla: yes, waiting4reviewer

#13301 core: fix launching chrome in node 17
  lighthouse-cli/cli-flags.js
  lighthouse-core/gather/connections/cri.js
  package.json
  yarn.lock
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer, 9.0

#13249 report: make denser. changes to typography, group descriptions, more
  flow-report/assets/styles.css
  package.json
  report/assets/styles.css
  report/assets/templates.html
  report/renderer/category-renderer.js
  report/renderer/components.js
  report/renderer/performance-category-renderer.js
  report/renderer/report-renderer.js
  report/renderer/report-ui-features.js
  report/test-assets/faux-psi.js
  report/test/renderer/category-renderer-test.js
  report/test/renderer/performance-category-renderer-test.js
  report/test/renderer/report-ui-features-test.js
  viewer/test/viewer-test-pptr.js
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer, 9.0

#13307 misc(build): call close method on rollup builds
  build/build-bundle.js
  build/build-lightrider-bundles.js
  build/build-report.js
  build/build-smokehouse-bundle.js
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13309 misc(proto): add throttling and throttling_method
  lighthouse-core/lib/proto-preprocessor.js
  proto/lighthouse-result.proto
Labels: cla: yes, waiting4reviewer

#13308 report: translate newly added report strings
  lighthouse-core/test/results/sample_v2.json
  lighthouse-core/util-commonjs.js
  proto/lighthouse-result.proto
  report/assets/styles.css
  report/assets/templates.html
  report/renderer/category-renderer.js
  report/renderer/components.js
  report/renderer/performance-category-renderer.js
  report/renderer/util.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13282 tests(eslint): add export rule
  build/build-treemap.js
  flow-report/.eslintrc.cjs
  flow-report/src/common.tsx
  flow-report/src/i18n/i18n.tsx
  flow-report/src/icons.tsx
  flow-report/src/sidebar/sidebar.tsx
  flow-report/src/summary/category.tsx
  flow-report/src/summary/summary.tsx
  flow-report/src/util.ts
  flow-report/src/wrappers/report-renderer.tsx
  flow-report/src/wrappers/report.tsx
  flow-report/test/setup/env-setup.ts
  lighthouse-cli/.eslintrc.cjs
  lighthouse-core/audits/audit.js
  lighthouse-core/computed/resource-summary.js
  lighthouse-core/lib/url-shim.js
  lighthouse-core/scripts/.eslintrc.cjs
  lighthouse-core/scripts/copy-util-commonjs.sh
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/util-commonjs.js
  report/.eslintrc.cjs
  report/renderer/crc-details-renderer.js
  report/renderer/open-tab.js
  report/renderer/util.js
  treemap/.eslintrc.cjs
  treemap/app/src/util.js
  viewer/.eslintrc.cjs
  viewer/app/src/psi-api.js
  viewer/test/test-helpers.js
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13305 report(flow): network throttling settings
  flow-report/src/icons.tsx
  flow-report/src/sidebar/sidebar.tsx
  flow-report/test/sidebar/sidebar-test.tsx
Labels: cla: yes, waiting4reviewer

#13277 report: introduce the new report api, add dom.rootEl
  build/build-report-components.js
  flow-report/assets/standalone-flow-template.html
  flow-report/src/wrappers/report-renderer.tsx
  flow-report/src/wrappers/report.tsx
  flow-report/standalone-flow.tsx
  report/assets/standalone-template.html
  report/assets/styles.css
  report/clients/bundle.js
  report/clients/standalone.js
  report/renderer/api.js
  report/renderer/category-renderer.js
  report/renderer/components.js
  report/renderer/dom.js
  report/renderer/drop-down-menu.js
  report/renderer/element-screenshot-renderer.js
  report/renderer/features-util.js
  report/renderer/report-renderer.js
  report/renderer/report-ui-features.js
  report/renderer/swap-locale-feature.js
  report/renderer/topbar-features.js
  report/test-assets/faux-psi-template.html
  report/test-assets/faux-psi.js
  report/test/clients/bundle-test.js
  report/test/renderer/report-renderer-axe-test.js
  report/test/renderer/report-renderer-test.js
  report/test/renderer/report-ui-features-test.js
  report/types/html-renderer.d.ts
  report/types/report-renderer.d.ts
  viewer/app/index.html
  viewer/app/src/lighthouse-report-viewer.js
  viewer/app/src/viewer-ui-features.js
  viewer/app/styles/viewer.css
  viewer/test/viewer-test-pptr.js
Labels: report, waiting4committer, land-when-ci-is-green, cla: yes, 9.0

#13279 report: fix sticky header toggling too late
  report/renderer/topbar-features.js
  report/test/clients/bundle-test.js
  report/test/renderer/report-ui-features-test.js
Labels: cla: yes, waiting4reviewer, 9.0

#13342 core(deprecations): use inspector issues
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-core/audits/deprecations.js
  lighthouse-core/gather/gatherers/inspector-issues.js
  lighthouse-core/test/audits/deprecations-test.js
  lighthouse-core/test/gather/gatherers/inspector-issues-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  third-party/chromium-synchronization/inspector-issueAdded-types-test.js
  types/artifacts.d.ts
  types/lhr/audit-details.d.ts
  yarn.lock
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13340 core(emulation): bump chrome version to m98
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/cli/index-test.js
  lighthouse-core/config/constants.js
  lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/artifacts/defaultPass.devtoolslog.json
  lighthouse-core/test/results/artifacts/offlinePass.devtoolslog.json
  lighthouse-core/test/results/artifacts/redirectPass.devtoolslog.json
  lighthouse-core/test/results/sample_v2.json
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13345 report: layout metrics naturally
  lighthouse-core/config/default-config.js
  lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  lighthouse-core/test/results/sample_v2.json
  report/renderer/performance-category-renderer.js
  report/test/renderer/performance-category-renderer-test.js
Labels: cla: yes, waiting4reviewer

#13311 misc(build): do not assign runBundledLighthouse in devtools bundle
  clients/devtools-entry.js
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer, 9.0

#13333 misc: preserve error stack when using promise timeout
  lighthouse-cli/run.js
  lighthouse-core/fraggle-rock/gather/session.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/fetcher.js
Labels: cla: yes, waiting4reviewer

#13341 core(emulation): set client-hints metadata when spoofing the UA
  lighthouse-core/lib/emulation.js
  lighthouse-core/test/lib/emulation-test.js
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13339 deps: bump lighthouse-plugin-publisher-ads
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
  yarn.lock
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer, 9.0

#13328 report: order metrics by row
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/config/default-config.js
  lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  lighthouse-core/test/results/sample_v2.json
  report/assets/styles.css
  report/renderer/components.js
  report/renderer/performance-category-renderer.js
  report/test/renderer/performance-category-renderer-test.js
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#12814 core(fr): add timespan support to h2
  lighthouse-core/audits/dobetterweb/uses-http2.js
  lighthouse-core/test/audits/dobetterweb/uses-http2-test.js
  lighthouse-core/test/fraggle-rock/scenarios/api-test-pptr.js
Labels: cla: yes, waiting4reviewer, 9.0

#13312 core: avoid fatal errors when collecting base artifacts
  lighthouse-core/audits/installable-manifest.js
  lighthouse-core/gather/gather-runner.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer, 9.0

#13354 report(help-dialog): remove timespan SEO
  flow-report/src/help-dialog.tsx
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13337 core(fr): clone default categories to avoid modification
  lighthouse-core/fraggle-rock/config/default-config.js
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer, 9.0

#13350 report: handle missing credits when rendering meta block
  report/renderer/report-renderer.js
  types/lhr/lhr.d.ts
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer, 9.0

#13310 report: hidden group backcompat
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  lighthouse-core/test/results/sample_v2.json
  lighthouse-core/util-commonjs.js
  package.json
  report/renderer/util.js
  report/test/renderer/util-test.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: waiting4committer, land-when-ci-is-green, cla: yes, 9.0

#13323 core(fr): handle 0 throughput in timespan
  lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
  lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
Labels: cla: yes, waiting4reviewer

#13317 report(flow): remove smooth scrolling
  flow-report/src/app.tsx
Labels: cla: yes, waiting4reviewer

#13349 misc(publish): include the report bundle in npm package
  .npmignore
  package.json
Labels: cla: yes, waiting4reviewer, 9.0

#13360 i18n: import
  shared/localization/locales/ar-XB.json
  shared/localization/locales/ar.json
  shared/localization/locales/bg.json
  shared/localization/locales/ca.json
  shared/localization/locales/cs.json
  shared/localization/locales/da.json
  shared/localization/locales/de.json
  shared/localization/locales/el.json
  shared/localization/locales/en-GB.json
  shared/localization/locales/en-XA.json
  shared/localization/locales/es-419.json
  shared/localization/locales/es.json
  shared/localization/locales/fi.json
  shared/localization/locales/fil.json
  shared/localization/locales/fr.json
  shared/localization/locales/he.json
  shared/localization/locales/hi.json
  shared/localization/locales/hr.json
  shared/localization/locales/hu.json
  shared/localization/locales/id.json
  shared/localization/locales/it.json
  shared/localization/locales/ja.json
  shared/localization/locales/ko.json
  shared/localization/locales/lt.json
  shared/localization/locales/lv.json
  shared/localization/locales/nl.json
  shared/localization/locales/no.json
  shared/localization/locales/pl.json
  shared/localization/locales/pt-PT.json
  shared/localization/locales/pt.json
  shared/localization/locales/ro.json
  shared/localization/locales/ru.json
  shared/localization/locales/sk.json
  shared/localization/locales/sl.json
  shared/localization/locales/sr-Latn.json
  shared/localization/locales/sr.json
  shared/localization/locales/sv.json
  shared/localization/locales/ta.json
  shared/localization/locales/te.json
  shared/localization/locales/th.json
  shared/localization/locales/tr.json
  shared/localization/locales/uk.json
  shared/localization/locales/vi.json
  shared/localization/locales/zh-HK.json
  shared/localization/locales/zh-TW.json
  shared/localization/locales/zh.json
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13361 report: fix scrolling, buttons and gauge word breaks in devtools
  report/assets/styles.css
  report/renderer/components.js
  report/renderer/topbar-features.js
Labels: cla: yes, waiting4reviewer

#13353 deps: update chrome-launcher to 0.15.0
  package.json
  yarn.lock
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer, 9.0

#13362 v9.0.0
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  docs/releasing.md
  lighthouse-core/test/results/sample_v2.json
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes, waiting4reviewer

#13356 misc(treemap): remove postMessage. refactor options input
  treemap/app/src/main.js
  treemap/test/treemap-test-pptr.js
Labels: cla: yes, waiting4reviewer

#13382 report(treemap): correct percentages when 0 bytes JS
  treemap/app/src/main.js
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13377 clients(devtools): remove report.css
  build/build-dt-report-resources.js
  clients/devtools-report-assets.js
Labels: cla: yes, waiting4reviewer

#13366 misc(build): prevent over optimization of computeBenchmarkIndex
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-core/lib/page-functions.js
Labels: cla: yes, waiting4reviewer

#13386 tests: increase timeout for axe test
  report/test/renderer/report-renderer-axe-test.js
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13365 core(installable-manifest): pipeline-restarted check
  lighthouse-core/audits/installable-manifest.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  third-party/chromium-synchronization/installability-errors-test.js
Labels: cla: yes, waiting4reviewer

#13391 report: consistent red display text
  report/assets/styles.css
  report/renderer/components.js
Labels: cla: yes, waiting4reviewer

#13371 docs(throttling): clarify throttle npm name
  docs/throttling.md
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13374 report(flow): report api
  flow-report/assets/standalone-flow-template.html
  flow-report/src/app.tsx
  flow-report/src/topbar.tsx
  flow-report/src/util.ts
  flow-report/src/wrappers/category-score.tsx
  flow-report/src/wrappers/markdown.tsx
  flow-report/src/wrappers/report-renderer.tsx
  flow-report/src/wrappers/report.tsx
  flow-report/standalone-flow.tsx
  flow-report/test/setup/env-setup.ts
  flow-report/test/summary/category-test.tsx
  flow-report/test/summary/summary-test.tsx
  flow-report/test/topbar-test.tsx
  flow-report/test/util-test.tsx
  flow-report/test/wrappers/category-score-test.tsx
  flow-report/test/wrappers/markdown-test.tsx
  report/renderer/api.js
  report/renderer/category-renderer.js
  report/renderer/report-renderer.js
  report/test/renderer/category-renderer-test.js
  report/test/renderer/report-renderer-test.js
  report/types/report-renderer.d.ts
Labels: cla: yes, waiting4reviewer

#13392 core: ensure log-normal score is always in correct range
  .eslintrc.js
  lighthouse-core/lib/statistics.js
  lighthouse-core/test/lib/statistics-test.js
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13408 misc(build): use rollup to create extension bundle
  build/build-extension.js
Labels: cla: yes, waiting4reviewer

#13407 misc(build): use rollup to create viewer report generator
  build/build-viewer.js
Labels: cla: yes, waiting4reviewer

#13409 report: remove margin when saving html in standalone report
  report/renderer/report-ui-features.js
Labels: cla: yes, waiting4reviewer

#13415 docs: example to save flow as json
  docs/user-flows.md
Labels: cla: yes, waiting4reviewer

#13406 misc(build): inline report generator resources for devtools
  .github/scripts/generate-devtools-hash.sh
  build/build-dt-report-resources.js
  build/readme.md
  clients/devtools-report-assets.js
  flow-report/assets/standalone-flow-template.html
  report/generator/flow-report-assets.js
  report/generator/report-assets.js
  report/generator/report-generator.js
Labels: cla: yes, waiting4reviewer

#13399 deps: update to typescript 4.5
  build/build-report-components.js
  clients/extension/scripts/popup.js
  lighthouse-cli/cli-flags.js
  lighthouse-cli/test/smokehouse/test-definitions/redirects/redirects-config.js
  lighthouse-core/audits/dobetterweb/js-libraries.js
  lighthouse-core/audits/seo/is-crawlable.js
  lighthouse-core/audits/third-party-summary.js
  lighthouse-core/audits/valid-source-maps.js
  lighthouse-core/computed/js-bundles.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/gather/driver/execution-context.js
  lighthouse-core/gather/gatherers/full-page-screenshot.js
  lighthouse-core/scripts/legacy-javascript/run.js
  lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
  lighthouse-core/test/fraggle-rock/gather/snapshot-runner-test.js
  lighthouse-core/test/fraggle-rock/gather/timespan-runner-test.js
  lighthouse-core/test/gather/driver/navigation-test.js
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/lib/navigation-error-test.js
  package.json
  report/renderer/swap-locale-feature.js
  types/externs.d.ts
  viewer/app/src/github-api.js
  yarn.lock
Labels: cla: yes, waiting4reviewer

#13358 report(flow): rebaseline sample
  lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
Labels: cla: yes, waiting4reviewer

#13416 misc(build): use rollup to create lr report generator
  build/build-lightrider-bundles.js
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13417 deps: remove browserify
  lighthouse-core/gather/gatherers/stacks.js
  package.json
  report/generator/report-assets.js
  yarn.lock
Labels: cla: yes, waiting4reviewer

#13412 core(canonical): remove cross-origin check
  lighthouse-core/audits/seo/canonical.js
  lighthouse-core/test/audits/seo/canonical-test.js
  shared/localization/locales/ar-XB.json
  shared/localization/locales/ar.json
  shared/localization/locales/bg.json
  shared/localization/locales/ca.json
  shared/localization/locales/cs.json
  shared/localization/locales/da.json
  shared/localization/locales/de.json
  shared/localization/locales/el.json
  shared/localization/locales/en-GB.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XA.json
  shared/localization/locales/en-XL.json
  shared/localization/locales/es-419.json
  shared/localization/locales/es.json
  shared/localization/locales/fi.json
  shared/localization/locales/fil.json
  shared/localization/locales/fr.json
  shared/localization/locales/he.json
  shared/localization/locales/hi.json
  shared/localization/locales/hr.json
  shared/localization/locales/hu.json
  shared/localization/locales/id.json
  shared/localization/locales/it.json
  shared/localization/locales/ja.json
  shared/localization/locales/ko.json
  shared/localization/locales/lt.json
  shared/localization/locales/lv.json
  shared/localization/locales/nl.json
  shared/localization/locales/no.json
  shared/localization/locales/pl.json
  shared/localization/locales/pt-PT.json
  shared/localization/locales/pt.json
  shared/localization/locales/ro.json
  shared/localization/locales/ru.json
  shared/localization/locales/sk.json
  shared/localization/locales/sl.json
  shared/localization/locales/sr-Latn.json
  shared/localization/locales/sr.json
  shared/localization/locales/sv.json
  shared/localization/locales/ta.json
  shared/localization/locales/te.json
  shared/localization/locales/th.json
  shared/localization/locales/tr.json
  shared/localization/locales/uk.json
  shared/localization/locales/vi.json
  shared/localization/locales/zh-HK.json
  shared/localization/locales/zh-TW.json
  shared/localization/locales/zh.json
Labels: cla: yes, waiting4reviewer

#13420 tests: make inline-fs-test not reliant on cwd
  build/test/plugins/inline-fs-test.js
Labels: cla: yes, waiting4reviewer

#13393 core: add original location to most usages of source-location
  lighthouse-core/audits/audit.js
  lighthouse-core/audits/byte-efficiency/legacy-javascript.js
  lighthouse-core/audits/deprecations.js
  lighthouse-core/audits/dobetterweb/geolocation-on-start.js
  lighthouse-core/audits/dobetterweb/no-document-write.js
  lighthouse-core/audits/dobetterweb/notification-on-start.js
  lighthouse-core/audits/dobetterweb/uses-passive-event-listeners.js
  lighthouse-core/audits/errors-in-console.js
  lighthouse-core/audits/no-unload-listeners.js
  lighthouse-core/audits/seo/font-size.js
  lighthouse-core/audits/violation-audit.js
  lighthouse-core/test/audits/deprecations-test.js
  lighthouse-core/test/audits/dobetterweb/geolocation-on-start-test.js
  lighthouse-core/test/audits/dobetterweb/no-document-write-test.js
  lighthouse-core/test/audits/dobetterweb/notification-on-start-test.js
  lighthouse-core/test/audits/dobetterweb/uses-passive-event-listeners-test.js
  lighthouse-core/test/audits/errors-in-console-test.js
  lighthouse-core/test/audits/no-unload-listeners-test.js
  lighthouse-core/test/audits/seo/font-size-test.js
  lighthouse-core/test/fraggle-rock/scenarios/api-test-pptr.js
  lighthouse-core/test/results/sample_v2.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes, waiting4reviewer

#13419 clients(viewer): save flow as gist
  flow-report/api.ts
  flow-report/clients/standalone.ts
  flow-report/src/app.tsx
  flow-report/src/sidebar/flow.tsx
  flow-report/src/sidebar/sidebar.tsx
  flow-report/src/topbar.tsx
  flow-report/src/util.ts
  flow-report/test/topbar-test.tsx
  flow-report/types/flow-report.d.ts
  report/generator/file-namer.js
  treemap/types/treemap.d.ts
  viewer/app/src/github-api.js
  viewer/app/src/lighthouse-report-viewer.js
Labels: cla: yes, waiting4reviewer

#13418 core: mindfully order properties in the lhr
  lighthouse-core/runner.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4reviewer

#13421 tests: fix undefined HTMLInputElement in bundle-test
  report/test/clients/bundle-test.js
  report/test/renderer/report-ui-features-test.js
Labels: cla: yes, waiting4reviewer

#13424 core(stacks): add next.js
  lighthouse-core/lib/stack-packs.js
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/test/lib/stack-packs-test.js
  package.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#13260 clients(viewer): add support for flow reports
  build/build-report.js
  build/build-viewer.js
  build/gh-pages-app.js
  flow-report/api.ts
  flow-report/clients/standalone.ts
  flow-report/src/app.tsx
  flow-report/src/sidebar/flow.tsx
  flow-report/src/sidebar/sidebar.tsx
  flow-report/src/topbar.tsx
  flow-report/src/util.ts
  flow-report/src/wrappers/report.tsx
  flow-report/src/wrappers/styles.tsx
  flow-report/test/topbar-test.tsx
  flow-report/types/flow-report.d.ts
  report/generator/file-namer.js
  report/renderer/api.js
  report/renderer/report-renderer.js
  report/types/report-renderer.d.ts
  treemap/types/treemap.d.ts
  viewer/app/index.html
  viewer/app/src/github-api.js
  viewer/app/src/lighthouse-report-viewer.js
  viewer/test/viewer-test-pptr.js
  viewer/tsconfig.json
  viewer/types/viewer.d.ts
Labels: cla: yes, waiting4reviewer

#13427 i18n: import
  shared/localization/locales/bg.json
  shared/localization/locales/da.json
  shared/localization/locales/en-GB.json
  shared/localization/locales/es-419.json
  shared/localization/locales/fi.json
  shared/localization/locales/fil.json
  shared/localization/locales/fr.json
  shared/localization/locales/he.json
  shared/localization/locales/hr.json
  shared/localization/locales/hu.json
  shared/localization/locales/id.json
  shared/localization/locales/it.json
  shared/localization/locales/ja.json
  shared/localization/locales/ko.json
  shared/localization/locales/lt.json
  shared/localization/locales/nl.json
  shared/localization/locales/no.json
  shared/localization/locales/pl.json
  shared/localization/locales/pt-PT.json
  shared/localization/locales/pt.json
  shared/localization/locales/ru.json
  shared/localization/locales/sr-Latn.json
  shared/localization/locales/sr.json
  shared/localization/locales/sv.json
  shared/localization/locales/uk.json
Labels: cla: yes, waiting4reviewer

#13431 v9.1.0
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  docs/releasing.md
  lighthouse-core/test/results/sample_v2.json
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes, waiting4reviewer

#13442 core(legacy-javascript): remove Object.getOwnPropertyNames signal
  lighthouse-cli/test/smokehouse/test-definitions/legacy-javascript/expectations.js
  lighthouse-core/audits/byte-efficiency/legacy-javascript.js
  lighthouse-core/scripts/legacy-javascript/run.js
  lighthouse-core/scripts/legacy-javascript/summary-signals-nomaps.json
  lighthouse-core/scripts/legacy-javascript/summary-signals.json
  lighthouse-core/scripts/legacy-javascript/summary-sizes.txt
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13387 tests: move sharding higher so smokehouse-bundle can also shard
  lighthouse-cli/test/smokehouse/frontends/lib.js
  lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js
  lighthouse-cli/test/smokehouse/smokehouse.js
  types/smokehouse.d.ts
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13324 misc(build): build test flow report to same path as sample-reports
  lighthouse-core/scripts/build-test-flow-report.js
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13430 core: computed artifact keys
  lighthouse-core/computed/computed-artifact.js
  lighthouse-core/computed/critical-request-chains.js
  lighthouse-core/computed/image-records.js
  lighthouse-core/computed/js-bundles.js
  lighthouse-core/computed/load-simulator.js
  lighthouse-core/computed/main-resource.js
  lighthouse-core/computed/main-thread-tasks.js
  lighthouse-core/computed/manifest-values.js
  lighthouse-core/computed/metrics/cumulative-layout-shift.js
  lighthouse-core/computed/metrics/first-contentful-paint-all-frames.js
  lighthouse-core/computed/metrics/first-contentful-paint.js
  lighthouse-core/computed/metrics/first-meaningful-paint.js
  lighthouse-core/computed/metrics/interactive.js
  lighthouse-core/computed/metrics/lantern-first-contentful-paint.js
  lighthouse-core/computed/metrics/lantern-first-meaningful-paint.js
  lighthouse-core/computed/metrics/lantern-interactive.js
  lighthouse-core/computed/metrics/lantern-largest-contentful-paint.js
  lighthouse-core/computed/metrics/lantern-max-potential-fid.js
  lighthouse-core/computed/metrics/lantern-speed-index.js
  lighthouse-core/computed/metrics/lantern-total-blocking-time.js
  lighthouse-core/computed/metrics/largest-contentful-paint-all-frames.js
  lighthouse-core/computed/metrics/largest-contentful-paint.js
  lighthouse-core/computed/metrics/max-potential-fid.js
  lighthouse-core/computed/metrics/speed-index.js
  lighthouse-core/computed/metrics/timing-summary.js
  lighthouse-core/computed/metrics/total-blocking-time.js
  lighthouse-core/computed/module-duplication.js
  lighthouse-core/computed/network-analysis.js
  lighthouse-core/computed/network-records.js
  lighthouse-core/computed/page-dependency-graph.js
  lighthouse-core/computed/processed-navigation.js
  lighthouse-core/computed/processed-trace.js
  lighthouse-core/computed/resource-summary.js
  lighthouse-core/computed/screenshots.js
  lighthouse-core/computed/speedline.js
  lighthouse-core/computed/trace-of-tab.js
  lighthouse-core/computed/unused-css.js
  lighthouse-core/computed/unused-javascript-summary.js
  lighthouse-core/computed/user-timings.js
  lighthouse-core/computed/viewport-meta.js
  lighthouse-core/test/computed/computed-artifact-test.js
  lighthouse-core/test/results/sample_v2.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes, waiting4reviewer
