Repository GoogleChrome/lighthouse, pull requests merged in 2021-07, with the labels that each got.

#12714 new_audit(fr): uses-responsive-images-snapshot
  lighthouse-core/audits/byte-efficiency/uses-responsive-images-snapshot.js
  lighthouse-core/audits/byte-efficiency/uses-responsive-images.js
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/byte-efficiency/uses-responsive-images-snapshot-test.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
Labels: cla: yes, waiting4reviewer

#12723 i18n: allow strings with duplicate message and descriptions
  lighthouse-core/audits/accessibility/aria-command-name.js
  lighthouse-core/audits/accessibility/aria-meter-name.js
  lighthouse-core/audits/accessibility/aria-tooltip-name.js
  lighthouse-core/audits/accessibility/aria-treeitem-name.js
  lighthouse-core/scripts/i18n/collect-strings.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12742 misc: fix common typos
  clients/devtools-entry.js
  clients/extension/scripts/popup.js
  lighthouse-core/audits/audit.js
  lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
  lighthouse-core/audits/seo/font-size.js
  lighthouse-core/audits/seo/hreflang.js
  lighthouse-core/audits/seo/is-crawlable.js
  lighthouse-core/audits/seo/robots-txt.js
  lighthouse-core/audits/seo/tap-targets.js
  lighthouse-core/gather/gatherers/image-elements.js
  lighthouse-core/gather/gatherers/inspector-issues.js
  lighthouse-core/gather/gatherers/seo/font-size.js
  lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js
  lighthouse-core/lib/rect-helpers.js
  lighthouse-core/lib/sd-validation/json-expander.js
  lighthouse-core/lib/sd-validation/json-linter.js
  lighthouse-core/lib/sd-validation/line-number-from-jsonld-path.js
  lighthouse-core/lib/sd-validation/schema-validator.js
  lighthouse-core/lib/sd-validation/sd-validation.js
  lighthouse-core/lib/tappable-rects.js
  lighthouse-core/test/gather/gatherers/inspector-issues-test.js
  report/renderer/details-renderer.js
  report/renderer/i18n.js
  report/renderer/report-ui-features.js
  report/renderer/util.js
  report/test/renderer/element-screenshot-renderer-test.js
Labels: cla: yes, waiting4reviewer

#12692 core(config): include additional trace categories
  lighthouse-core/gather/gatherers/trace.js
Labels: cla: yes, waiting4reviewer

#12727 core: fallback to selector, not tagName for nodeLabel
  lighthouse-cli/test/smokehouse/test-definitions/a11y/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-core/lib/page-functions.js
  lighthouse-core/test/lib/page-functions-test.js
Labels: cla: yes, waiting4committer

#12757 core: reference chromium main instead of master
  clients/devtools-report-assets.js
  lighthouse-core/audits/autocomplete.js
  lighthouse-core/audits/dobetterweb/inspector-issues.js
  lighthouse-core/audits/installable-manifest.js
  lighthouse-core/lib/minify-trace.js
  lighthouse-core/lib/url-shim.js
  lighthouse-core/scripts/pptr-run-devtools.js
  lighthouse-core/test/chromium-web-tests/README.md
  third-party/chromium-synchronization/installability-errors-test.js
Labels: cla: yes, land-when-ci-is-green

#12758 core(fr): split timespan support for server-response-time
  lighthouse-core/audits/server-response-time.js
  lighthouse-core/test/audits/server-response-time-test.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
Labels: cla: yes, waiting4reviewer

#12676 core(canonical): proper explanation for url misuse
  lighthouse-core/audits/seo/canonical.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/seo/canonical-test.js
Labels: cla: yes, waiting4reviewer

#12741 scripts(i18n): support es modules in collect-strings
  lighthouse-core/scripts/i18n/collect-strings.js
  report/renderer/util.js
Labels: cla: yes, waiting4reviewer

#12764 core(fr): limit scope of audits to applicable modes
  lighthouse-core/audits/apple-touch-icon.js
  lighthouse-core/audits/dobetterweb/geolocation-on-start.js
  lighthouse-core/audits/dobetterweb/notification-on-start.js
  lighthouse-core/audits/final-screenshot.js
  lighthouse-core/audits/font-display.js
  lighthouse-core/audits/installable-manifest.js
  lighthouse-core/audits/maskable-icon.js
  lighthouse-core/audits/metrics.js
  lighthouse-core/audits/performance-budget.js
  lighthouse-core/audits/screenshot-thumbnails.js
  lighthouse-core/audits/seo/canonical.js
  lighthouse-core/audits/seo/hreflang.js
  lighthouse-core/audits/seo/http-status-code.js
  lighthouse-core/audits/seo/is-crawlable.js
  lighthouse-core/audits/splash-screen.js
  lighthouse-core/audits/themed-omnibox.js
  lighthouse-core/computed/resource-summary.js
  lighthouse-core/gather/gatherers/script-elements.js
  lighthouse-core/gather/gatherers/seo/tap-targets.js
  lighthouse-core/gather/gatherers/trace-elements.js
  lighthouse-core/test/audits/final-screenshot-test.js
  lighthouse-core/test/audits/screenshot-thumbnails-test.js
  lighthouse-core/test/audits/seo/http-status-code-test.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/gather/gatherers/trace-elements-test.js
Labels: cla: yes, waiting4reviewer

#12779 tests: don't double count server network requests on retry
  lighthouse-cli/test/smokehouse/smokehouse.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12765 tests(devtools): fix after renaming standalone-template.html
  build/build-dt-report-resources.js
  report/assets/standalone-template.html
  report/clients/standalone.js
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#12783 i18n: import
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
Labels: cla: yes, waiting4reviewer

#12782 misc: run build-report for vercel deployment and lhci
  package.json
Labels: cla: yes, waiting4committer

#12784 v8.1.0
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  lighthouse-core/scripts/release/test.sh
  lighthouse-core/test/results/sample_v2.json
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes, waiting4reviewer

#12801 core(csp-xss): make n/a with empty results
  lighthouse-core/audits/csp-xss.js
  lighthouse-core/test/audits/csp-xss-test.js
Labels: cla: yes, waiting4reviewer

#12728 core(fr): add timespan support to css-usage
  lighthouse-core/gather/gatherers/css-usage.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
Labels: cla: yes, waiting4committer

#12806 misc: add prefix to lighthouse-logger debug scope
  lighthouse-logger/index.js
  lighthouse-logger/package.json
Labels: cla: yes, waiting4reviewer

#12805 cli(fr): add --fraggle-rock flag
  lighthouse-cli/cli-flags.js
  lighthouse-cli/run.js
  lighthouse-cli/test/cli/bin-test.js
  lighthouse-core/fraggle-rock/config/config.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/fraggle-rock/gather/snapshot-runner.js
  lighthouse-core/fraggle-rock/gather/timespan-runner.js
  lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
  lighthouse-core/test/fraggle-rock/gather/snapshot-runner-test.js
  lighthouse-core/test/fraggle-rock/gather/timespan-runner-test.js
  types/config.d.ts
  types/externs.d.ts
Labels: cla: yes, waiting4reviewer

#12807 tests(devtools): sync tests, fix cache action
  .github/workflows/devtools.yml
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run.js
Labels: cla: yes, waiting4reviewer

#12796 core(dom): introduce safelySetHref
  lighthouse-core/test/lib/page-functions-test.js
  lighthouse-treemap/app/src/main.js
  lighthouse-treemap/app/src/util.js
  report/renderer/category-renderer.js
  report/renderer/details-renderer.js
  report/renderer/dom.js
  report/renderer/element-screenshot-renderer.js
  report/renderer/performance-category-renderer.js
  report/renderer/pwa-category-renderer.js
  report/renderer/report-renderer.js
  report/renderer/report-ui-features.js
  report/test/renderer/dom-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#12812 deps: update lighthouse-logger to 1.3.0
  lighthouse-cli/run.js
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#12818 tests(smoke): convert to single LH run per test
  lighthouse-cli/test/smokehouse/frontends/back-compat-util.js
  lighthouse-cli/test/smokehouse/frontends/lib.js
  lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js
  lighthouse-cli/test/smokehouse/lib/concurrent-mapper.js
  lighthouse-cli/test/smokehouse/report-assert.js
  lighthouse-cli/test/smokehouse/smokehouse.js
  lighthouse-cli/test/smokehouse/test-definitions/core-tests.js
  types/smokehouse.d.ts
Labels: cla: yes, waiting4reviewer

#12808 core(fr): support config filtering via only/skip settings
  lighthouse-core/fraggle-rock/config/config.js
  lighthouse-core/fraggle-rock/config/filters.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/fraggle-rock/config/config-test.js
  lighthouse-core/test/fraggle-rock/config/filters-test.js
  lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
Labels: cla: yes, waiting4committer

#12819 tests(smoke): convert core tests to single-expectations format
  .github/workflows/smoke.yml
  lighthouse-cli/test/smokehouse/frontends/lib.js
  lighthouse-cli/test/smokehouse/smokehouse.js
  lighthouse-cli/test/smokehouse/test-definitions/a11y/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/core-tests.js
  lighthouse-cli/test/smokehouse/test-definitions/csp/csp-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/errors/error-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/forms/form-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/issues/mixed-content.js
  lighthouse-cli/test/smokehouse/test-definitions/lantern/lantern-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/legacy-javascript/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/offline-local/offline-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/oopif/oopif-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/perf-diagnostics/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa2-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa3-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/redirects/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/screenshot/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/seo/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/source-maps/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/tricky-metrics/expectations.js
Labels: cla: yes, waiting4committer

#12721 misc: read locale files without using `require`
  lighthouse-core/lib/i18n/locales.js
Labels: cla: yes, waiting4reviewer

#12557 misc(viewer): accept lhr from fragment
  build/build-viewer.js
  lighthouse-viewer/app/src/lighthouse-report-viewer.js
  lighthouse-viewer/types/viewer.d.ts
  report/clients/viewer.js
  report/renderer/report-ui-features.js
Labels: cla: yes, waiting4reviewer

#12830 core(fr): add snapshot and timespan support to no-unload-listeners audit
  lighthouse-core/gather/gatherers/global-listeners.js
  lighthouse-core/gather/gatherers/js-usage.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/gather/gatherers/js-usage-test.js
Labels: cla: yes, waiting4committer

#12832 core(fr): add config extension support
  lighthouse-core/config/config-helpers.js
  lighthouse-core/fraggle-rock/config/config.js
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/test/config/config-helpers-test.js
  lighthouse-core/test/fraggle-rock/config/config-test.js
Labels: cla: yes, waiting4reviewer

#12753 deps: update third-party-web to 0.12.4
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer
