Repository GoogleChrome/lighthouse, pull requests merged in 2021-09, with the labels that each got.

#13005 core(http-status-code): navigation only
  lighthouse-core/audits/seo/http-status-code.js
  lighthouse-core/test/audits/seo/http-status-code-test.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
Labels: land-when-ci-is-green, cla: yes

#13006 clients(lightrider): use iframe fetcher
  lighthouse-core/gather/fetcher.js
  lighthouse-core/gather/gatherers/seo/robots-txt.js
Labels: cla: yes, waiting4reviewer

#13011 tests(smoke): fix dbw console error expectation
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
Labels: cla: yes, waiting4reviewer

#13007 tests(smoke): check for passing robots-txt
  lighthouse-cli/test/fixtures/robots.txt
  lighthouse-cli/test/smokehouse/test-definitions/csp/csp-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/seo/expectations.js
Labels: waiting4committer, land-when-ci-is-green, cla: yes

#13002 report(flow): sidebar mocks
  flow-report/.eslintrc.js
  flow-report/assets/styles.css
  flow-report/src/common.tsx
  flow-report/src/icons.tsx
  flow-report/src/sidebar/flow.tsx
  flow-report/src/sidebar/sidebar.tsx
  flow-report/src/summary/summary.tsx
  flow-report/src/util.ts
  flow-report/test/sidebar/flow-test.tsx
  flow-report/test/summary/summary-test.tsx
  flow-report/test/util-test.tsx
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#13012 tests: avoid node 16.9.0
  .github/workflows/unit.yml
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13017 v8.4.0
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  lighthouse-core/scripts/print-contributors.js
  lighthouse-core/test/results/sample_v2.json
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#12992 core(fr): collect OOPIF network data
  .github/workflows/smoke.yml
  lighthouse-cli/test/smokehouse/lighthouse-runners/bundle.js
  lighthouse-cli/test/smokehouse/report-assert.js
  lighthouse-cli/test/smokehouse/test-definitions/oopif/oopif-config.js
  lighthouse-core/audits/oopif-iframe-test-audit.js
  lighthouse-core/fraggle-rock/gather/driver.js
  lighthouse-core/fraggle-rock/gather/session.js
  lighthouse-core/gather/devtools-log.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/driver/network-monitor.js
  lighthouse-core/gather/driver/target-manager.js
  lighthouse-core/gather/gatherers/devtools-log.js
  lighthouse-core/lib/network-recorder.js
  lighthouse-core/test/fraggle-rock/gather/mock-driver.js
  lighthouse-core/test/fraggle-rock/gather/session-test.js
  lighthouse-core/test/gather/devtools-log-test.js
  lighthouse-core/test/gather/driver/navigation-test.js
  lighthouse-core/test/gather/driver/network-monitor-test.js
  lighthouse-core/test/gather/driver/target-manager-test.js
  lighthouse-core/test/gather/mock-commands.js
  package.json
  types/gatherer.d.ts
  types/protocol.d.ts
  yarn.lock
Labels: cla: yes, waiting4reviewer

#13013 core(fr): force use of devtools throttling in timespan mode
  lighthouse-core/computed/metrics/metric.js
  lighthouse-core/fraggle-rock/config/config.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/fraggle-rock/config/config-test.js
Labels: cla: yes, waiting4reviewer

#13010 tests(smoke): upload smokehouse artifacts on failure
  .github/workflows/smoke.yml
  lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js
  lighthouse-cli/test/smokehouse/lighthouse-runners/cli.js
  lighthouse-cli/test/smokehouse/smokehouse.js
Labels: cla: yes, waiting4reviewer

#13023 misc: remove all FR-COMPAT todos
  flow-report/src/summary/summary.tsx
  flow-report/src/util.ts
  lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
  lighthouse-core/fraggle-rock/config/config.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/gather/gatherers/css-usage.js
  lighthouse-core/gather/gatherers/js-usage.js
  lighthouse-core/gather/gatherers/trace.js
  lighthouse-core/lib/emulation.js
  lighthouse-core/runner.js
  types/lhr/flow.d.ts
Labels: cla: yes, waiting4reviewer

#12969 core(fr): move HostUserAgent/FormFactor back to base artifacts
  lighthouse-cli/test/smokehouse/test-definitions/seo/expectations.js
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/fraggle-rock/config/filters.js
  lighthouse-core/fraggle-rock/gather/base-artifacts.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/fraggle-rock/gather/runner-helpers.js
  lighthouse-core/fraggle-rock/gather/snapshot-runner.js
  lighthouse-core/fraggle-rock/gather/timespan-runner.js
  lighthouse-core/gather/gatherers/host-form-factor.js
  lighthouse-core/gather/gatherers/host-user-agent.js
  lighthouse-core/gather/gatherers/script-elements.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/fraggle-rock/gather/base-artifacts-test.js
  lighthouse-core/test/fraggle-rock/gather/mock-driver.js
  lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
  lighthouse-core/test/fraggle-rock/gather/runner-helpers-test.js
  lighthouse-core/test/gather/gatherers/css-usage-test.js
  types/artifacts.d.ts
  types/gatherer.d.ts
  types/smokehouse.d.ts
Labels: waiting4committer, cla: yes

#13027 core(fr): preserve traces on failed page load
  lighthouse-cli/test/smokehouse/test-definitions/errors/error-expectations.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
Labels: cla: yes, waiting4reviewer

#13032 clients: add canonical link to viewer and treemap
  lighthouse-treemap/app/index.html
  lighthouse-viewer/app/index.html
Labels: cla: yes, waiting4reviewer

#13009 report: add fractional category scores
  flow-report/assets/styles.css
  flow-report/src/common.tsx
  flow-report/src/summary/summary.tsx
  flow-report/src/wrappers/category-score.tsx
  flow-report/test/common-test.tsx
  flow-report/test/summary/summary-test.tsx
  lighthouse-core/util-commonjs.js
  report/assets/styles.css
  report/assets/templates.html
  report/renderer/category-renderer.js
  report/renderer/components.js
  report/renderer/performance-category-renderer.js
  report/renderer/pwa-category-renderer.js
  report/renderer/report-renderer.js
  report/renderer/util.js
  report/test/renderer/category-renderer-test.js
  report/types/report-result.d.ts
Labels: waiting4committer, cla: yes

#13031 tests: fix flaky robots smoke failure
  lighthouse-core/gather/fetcher.js
  lighthouse-core/gather/gatherers/seo/robots-txt.js
  types/artifacts.d.ts
Labels: cla: yes, waiting4reviewer

#13029 report: add gatherMode option to category score
  flow-report/src/summary/summary.tsx
  flow-report/src/wrappers/category-score.tsx
  lighthouse-core/util-commonjs.js
  report/clients/psi.js
  report/renderer/category-renderer.js
  report/renderer/performance-category-renderer.js
  report/renderer/report-renderer.js
  report/renderer/util.js
  report/test/renderer/category-renderer-test.js
  report/types/report-result.d.ts
Labels: cla: yes, waiting4reviewer

#13033 core(fr): move GatherContext to baseArtifacts
  build/build-sample-reports.js
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/config/config.js
  lighthouse-core/config/default-config.js
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/fraggle-rock/config/filters.js
  lighthouse-core/fraggle-rock/gather/base-artifacts.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/fraggle-rock/gather/snapshot-runner.js
  lighthouse-core/fraggle-rock/gather/timespan-runner.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/gather/gatherers/gather-context.js
  lighthouse-core/runner.js
  lighthouse-core/test/config/config-test.js
  lighthouse-core/test/fixtures/artifacts/alphabet-artifacts/artifacts.json
  lighthouse-core/test/fixtures/artifacts/empty-artifacts/artifacts.json
  lighthouse-core/test/fixtures/artifacts/perflog/artifacts.json
  lighthouse-core/test/fraggle-rock/gather/base-artifacts-test.js
  lighthouse-core/test/fraggle-rock/gather/mock-driver.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
  types/artifacts.d.ts
Labels: cla: yes, waiting4reviewer

#13036 report: make metric value more prominent in table
  report/assets/styles.css
  report/assets/templates.html
  report/renderer/components.js
Labels: waiting4committer, cla: yes

#13050 Fix errors encountered when auditing various profiles
  lighthouse-core/lib/network-records-from-trace.js
Labels: cla: yes, waiting4reviewer

#13049 core(lazy-lcp): fix failureTitle in lcp-lazy-loaded
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-core/audits/byte-efficiency/uses-responsive-images-snapshot.js
  lighthouse-core/audits/dobetterweb/js-libraries.js
  lighthouse-core/audits/dobetterweb/uses-http2.js
  lighthouse-core/audits/lcp-lazy-loaded.js
  lighthouse-core/audits/oopif-iframe-test-audit.js
  lighthouse-core/fraggle-rock/config/validation.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/audits/dobetterweb/js-libraries-test.js
  lighthouse-core/test/config/config-test.js
  lighthouse-core/test/fraggle-rock/config/config-test.js
  lighthouse-core/test/fraggle-rock/config/validation-test.js
  lighthouse-core/test/results/sample_v2.json
  lighthouse-core/test/runner-test.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes, waiting4reviewer

#13055 docs(readme): add Peyk to the list of integrations
  readme.md
Labels: land-when-ci-is-green, cla: yes

#13047 tests(smokehouse): add flag for test sharding
  .github/workflows/smoke.yml
  lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js
Labels: cla: yes, waiting4reviewer

#13030 core(fr): support additionalTraceCategories
  lighthouse-core/gather/gatherers/trace.js
  lighthouse-core/test/gather/gatherers/trace-test.js
Labels: cla: yes, waiting4reviewer

#13058 core(fr): setup emulation and throttling for timespans
  lighthouse-core/fraggle-rock/gather/timespan-runner.js
  lighthouse-core/gather/driver/prepare.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/fraggle-rock/gather/mock-driver.js
  lighthouse-core/test/fraggle-rock/gather/timespan-runner-test.js
  lighthouse-core/test/gather/driver/prepare-test.js
Labels: cla: yes, waiting4reviewer

#13059 tests(eslint): trailing commas for import/export
  .eslintrc.js
  lighthouse-cli/test/fixtures/static-server.js
  lighthouse-cli/test/smokehouse/frontends/back-compat-util.js
  lighthouse-cli/test/smokehouse/lighthouse-runners/bundle.js
  lighthouse-cli/test/smokehouse/lighthouse-runners/cli.js
  lighthouse-cli/test/smokehouse/smokehouse.js
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/csp/csp-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/errors/error-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/lantern/lantern-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/offline-local/offline-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/perf-diagnostics/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa2-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa3-expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/redirects/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/seo/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/tricky-metrics/expectations.js
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13069 core: make main tsc compile cacheable
  lighthouse-core/index.js
  tsconfig.json
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13068 misc(proto): add i18n.icuMessagePaths
  lighthouse-core/lib/proto-preprocessor.js
  proto/lighthouse-result.proto
  types/lhr/lhr.d.ts
Labels: cla: yes, waiting4reviewer

#13067 report(3p-filter): drop for/id as elements are already nested
  report/renderer/report-ui-features.js
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13056 core(tracing): remove cpu_profiler.hires
  lighthouse-core/gather/gatherers/trace.js
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13074 clients(lr): bundle smokehouse as commonjs
  build/build-smokehouse-bundle.js
  package.json
Labels: cla: yes

#13076 misc: fix typo in lighthouse-treemap/app/src/main.js
  lighthouse-treemap/app/src/main.js
Labels: cla: yes, waiting4reviewer

#13075 deps: update to latest @rollup/plugin-typescript
  build/build-report.js
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#13065 report(flow): topbar
  flow-report/assets/styles.css
  flow-report/src/app.tsx
  flow-report/src/icons.tsx
  flow-report/src/topbar.tsx
Labels: waiting4committer, cla: yes

#13072 core(tsc): add base tsconfig for config inheritance
  flow-report/tsconfig.json
  lighthouse-treemap/tsconfig.json
  lighthouse-viewer/tsconfig.json
  package.json
  report/generator/tsconfig.json
  report/tsconfig.json
  tsconfig-all.json
  tsconfig-base.json
  tsconfig.json
  types/lhr/tsconfig.json
Labels: waiting4committer, land-when-ci-is-green, cla: yes

#13079 tests: restore use of latest node 16 in CI
  .github/workflows/unit.yml
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13073 misc(build): fix minifyFileTransform stream bug in Node 16
  build/build-utils.js
Labels: cla: yes, waiting4reviewer

#13088 tests: update SVGOMG expectations
  lighthouse-cli/test/smokehouse/test-definitions/pwa/pwa2-expectations.js
Labels: cla: yes, waiting4reviewer

#13086 report(flow): summary sections
  flow-report/assets/styles.css
  flow-report/src/summary/summary.tsx
Labels: waiting4committer, cla: yes

#13062 core(fr): cleanup driver on run completion
  lighthouse-core/fraggle-rock/gather/driver.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/fraggle-rock/gather/session.js
  lighthouse-core/fraggle-rock/gather/snapshot-runner.js
  lighthouse-core/fraggle-rock/gather/timespan-runner.js
  lighthouse-core/gather/driver.js
  lighthouse-core/test/fraggle-rock/gather/driver-test.js
  lighthouse-core/test/fraggle-rock/gather/mock-driver.js
  lighthouse-core/test/fraggle-rock/gather/session-test.js
  types/gatherer.d.ts
Labels: cla: yes, waiting4reviewer

#13092 tests: add FR integration scenarios
  lighthouse-core/test/fraggle-rock/scenarios/api-test-pptr.js
  lighthouse-core/test/fraggle-rock/scenarios/disconnect-test-pptr.js
  lighthouse-core/test/fraggle-rock/scenarios/package.json
  lighthouse-core/test/fraggle-rock/scenarios/pptr-test-utils.js
Labels: cla: yes, waiting4reviewer

#13096 v8.5.0
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes, waiting4reviewer

#13034 core(fr): api for constructing flow result
  flow-report/src/sidebar/flow.tsx
  flow-report/src/sidebar/sidebar.tsx
  flow-report/src/summary/summary.tsx
  flow-report/src/util.ts
  flow-report/test/sidebar/flow-test.tsx
  flow-report/test/summary/summary-test.tsx
  flow-report/test/util-test.tsx
  lighthouse-core/fraggle-rock/user-flow.js
  lighthouse-core/scripts/update-flow-fixtures.js
  lighthouse-core/test/fixtures/fraggle-rock/reports/sample-lhrs.json
  types/global-lh.d.ts
  types/lhr/flow.d.ts
Labels: cla: yes, waiting4reviewer

#13043 report(flow): category tooltips
  flow-report/assets/styles.css
  flow-report/src/summary/category.tsx
  flow-report/src/summary/summary.tsx
  flow-report/test/summary/category-test.tsx
  lighthouse-core/util-commonjs.js
  report/renderer/category-renderer.js
  report/renderer/util.js
  report/test/renderer/util-test.js
Labels: cla: yes, waiting4reviewer

#13106 8.5.1
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13102 report: remove smooth scrolling css
  report/assets/styles.css
Labels: waiting4committer, cla: yes

#13110 clients(viewer): use new firebase credentials
  lighthouse-viewer/app/src/firebase-auth.js
Labels: cla: yes, waiting4reviewer

#13089 misc: add notes about software versions in issue template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: land-when-ci-is-green, cla: yes

#13116 clients(viewer): use access token regardless of firebase auth
  lighthouse-viewer/app/src/firebase-auth.js
Labels: cla: yes, waiting4reviewer

#13114 core(fr): add parity logging
  lighthouse-core/fraggle-rock/gather/driver.js
  lighthouse-core/gather/driver/navigation.js
  lighthouse-core/gather/driver/prepare.js
  lighthouse-core/gather/driver/storage.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes, waiting4reviewer

#13115 clients(viewer): upgrade to firebase 9
  lighthouse-viewer/app/index.html
  lighthouse-viewer/app/src/firebase-auth.js
  lighthouse-viewer/app/src/github-api.js
  lighthouse-viewer/app/src/lighthouse-report-viewer.js
  lighthouse-viewer/types/viewer.d.ts
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#13057 report: inject report/assets/styles.css via components.js
  build/build-dt-report-resources.js
  build/build-report-components.js
  build/build-sample-reports.js
  build/build-viewer.js
  report/assets/standalone-template.html
  report/generator/report-generator.js
  report/renderer/components.js
  report/renderer/report-renderer.js
  report/test-assets/faux-psi-template.html
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13122 misc(build): create rollup-plugins.js helper module
  build/build-report.js
  build/build-smokehouse-bundle.js
  build/gh-pages-app.js
  build/rollup-plugins.js
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#13124 report(build): don't build flow if only --standalone is requested
  build/build-report.js
  lighthouse-core/scripts/build-test-flow-report.js
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13128 report(flow): timeline header
  flow-report/assets/styles.css
  flow-report/src/app.tsx
  flow-report/src/common.tsx
  flow-report/src/header.tsx
  flow-report/src/summary/summary.tsx
  flow-report/src/util.ts
  flow-report/src/wrappers/report.tsx
  flow-report/test/header-test.tsx
  flow-report/test/summary/summary-test.tsx
  flow-report/types/flow-report.d.ts
  types/lhr/flow.d.ts
Labels: cla: yes, waiting4reviewer

#13133 core(stack-packs): simplify i18n filename lookup
  lighthouse-core/lib/stack-packs.js
Labels: cla: yes, waiting4reviewer

#13139 core(fr): add UserFlow usability improvements
  lighthouse-core/fraggle-rock/api.js
  lighthouse-core/fraggle-rock/user-flow.js
  lighthouse-core/test/fraggle-rock/user-flow-test.js
Labels: cla: yes, waiting4reviewer

#13142 report(test): split out axe test
  report/test/renderer/report-renderer-axe-test.js
  report/test/renderer/report-renderer-test.js
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13134 docs: add user flow docs
  docs/user-flows.md
Labels: cla: yes, waiting4reviewer, 9.0

#13144 clients(viewer): add body styles
  lighthouse-viewer/app/styles/viewer.css
Labels: cla: yes, waiting4reviewer

#13145 clients(viewer): remove devtools disclaimer
  lighthouse-viewer/app/index.html
Labels: waiting4committer, cla: yes

#13150 tests: centralize running of recipe tests
  docs/recipes/auth/package.json
  docs/recipes/custom-gatherer-puppeteer/test.sh
  docs/recipes/integration-test/docs-jest.config.js
  docs/recipes/integration-test/package.json
  docs/recipes/package.json
  jest.config.js
  package.json
Labels: cla: yes, waiting4reviewer

#13148 tests: make yarn unit run all available unit tests
  clients/test/extension/popup-test-pptr.js
  jest.config.js
  package.json
  third-party/chromium-synchronization/inspector-issueAdded-types-test.js
  third-party/chromium-synchronization/installability-errors-test.js
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13151 clients(psi): include global reports styles in legacy psi rendering
  report/clients/psi.js
  report/test/clients/psi-test.js
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer
