Repository GoogleChrome/lighthouse, pull requests merged in 2021-02, with the labels that each got.

#12034 core(cls-all-frames): use weighted score from trace
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-core/computed/metrics/cumulative-layout-shift-all-frames.js
  lighthouse-core/test/audits/metrics-test.js
  lighthouse-core/test/computed/metrics/cumulative-layout-shift-all-frames-test.js
  lighthouse-core/test/computed/metrics/timing-summary-test.js
  lighthouse-core/test/fixtures/traces/frame-metrics-m90.devtools.log.json
  lighthouse-core/test/fixtures/traces/frame-metrics-m90.json
  types/externs.d.ts
Labels: cla: yes, land-when-ci-is-green

#12052 misc: add issue assigner bot
  .github/workflows/issue-assigner.yml
Labels: cla: yes, waiting4reviewer

#12045 core(fr): add artifact dependency support
  lighthouse-core/fraggle-rock/config/config.js
  lighthouse-core/fraggle-rock/config/validation.js
  lighthouse-core/fraggle-rock/gather/base-gatherer.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/fraggle-rock/gather/runner-helpers.js
  lighthouse-core/fraggle-rock/gather/snapshot-runner.js
  lighthouse-core/fraggle-rock/gather/timespan-runner.js
  lighthouse-core/gather/gatherers/seo/tap-targets.js
  lighthouse-core/test/fraggle-rock/config/config-test.js
  lighthouse-core/test/fraggle-rock/config/validation-test.js
  lighthouse-core/test/fraggle-rock/gather/base-gatherer-test.js
  lighthouse-core/test/fraggle-rock/gather/mock-driver.js
  lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
  lighthouse-core/test/fraggle-rock/gather/runner-helpers-test.js
  lighthouse-core/test/fraggle-rock/gather/snapshot-runner-test.js
  lighthouse-core/test/fraggle-rock/gather/timespan-runner-test.js
  types/config.d.ts
  types/gatherer.d.ts
Labels: cla: yes, waiting4committer

#11962 tests(smoke): tweak expectations based on feedback from LR
  lighthouse-cli/test/smokehouse/test-definitions/perf-diagnostics/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/screenshot/expectations.js
Labels: cla: yes, waiting4reviewer

#12067 core: fix js edge case in minification estimator
  lighthouse-core/lib/minification-estimator.js
  lighthouse-core/test/lib/minification-estimator-test.js
Labels: cla: yes, waiting4reviewer

#12046 core: add hidden layout-shift variant metrics
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-core/audits/metrics.js
  lighthouse-core/computed/layout-shift-variants.js
  lighthouse-core/computed/metrics/timing-summary.js
  lighthouse-core/test/audits/__snapshots__/metrics-test.js.snap
  lighthouse-core/test/audits/metrics-test.js
  lighthouse-core/test/computed/layout-shift-variants-test.js
  lighthouse-core/test/computed/metrics/timing-summary-test.js
  lighthouse-core/test/fixtures/traces/jumpy-cls-m90.devtoolslog.json
  lighthouse-core/test/fixtures/traces/jumpy-cls-m90.json
  lighthouse-core/test/results/artifacts/defaultPass.trace.json
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: cla: yes, waiting4committer

#12016 core(fr): add more gatherers to config
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
Labels: cla: yes, waiting4committer

#12015 core(fr): eliminate driver delegate from internal invocations
  docs/recipes/custom-audit/searchable-gatherer.js
  docs/recipes/custom-gatherer-puppeteer/custom-gatherer.js
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
  lighthouse-core/fraggle-rock/gather/driver.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/driver/execution-context.js
  lighthouse-core/gather/fetcher.js
  lighthouse-core/gather/gatherers/accessibility.js
  lighthouse-core/gather/gatherers/anchor-elements.js
  lighthouse-core/gather/gatherers/cache-contents.js
  lighthouse-core/gather/gatherers/css-usage.js
  lighthouse-core/gather/gatherers/dobetterweb/appcache.js
  lighthouse-core/gather/gatherers/dobetterweb/doctype.js
  lighthouse-core/gather/gatherers/dobetterweb/domstats.js
  lighthouse-core/gather/gatherers/dobetterweb/password-inputs-with-prevented-paste.js
  lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js
  lighthouse-core/gather/gatherers/form-elements.js
  lighthouse-core/gather/gatherers/full-page-screenshot.js
  lighthouse-core/gather/gatherers/http-redirect.js
  lighthouse-core/gather/gatherers/iframe-elements.js
  lighthouse-core/gather/gatherers/image-elements.js
  lighthouse-core/gather/gatherers/link-elements.js
  lighthouse-core/gather/gatherers/meta-elements.js
  lighthouse-core/gather/gatherers/script-elements.js
  lighthouse-core/gather/gatherers/seo/embedded-content.js
  lighthouse-core/gather/gatherers/seo/robots-txt.js
  lighthouse-core/gather/gatherers/seo/tap-targets.js
  lighthouse-core/gather/gatherers/viewport-dimensions.js
  lighthouse-core/lib/stack-collector.js
  lighthouse-core/test/fraggle-rock/gather/driver-test.js
  lighthouse-core/test/gather/driver-test.js
  lighthouse-core/test/gather/fake-driver.js
  lighthouse-core/test/gather/gatherers/accessibility-test.js
  lighthouse-core/test/gather/gatherers/dobetterweb/password-inputs-with-prevented-paste-test.js
  lighthouse-core/test/gather/gatherers/dobetterweb/tags-blocking-first-paint-test.js
  lighthouse-core/test/gather/gatherers/full-page-screenshot-test.js
  lighthouse-core/test/gather/gatherers/http-redirect-test.js
  lighthouse-core/test/gather/gatherers/link-elements-test.js
  lighthouse-core/test/gather/gatherers/viewport-dimensions-test.js
  lighthouse-core/test/lib/stack-collector-test.js
  types/gatherer.d.ts
Labels: cla: yes, waiting4committer

#12007 core: alias element.currentSrc to element.src in node snippet
  lighthouse-core/lib/page-functions.js
  lighthouse-core/test/lib/page-functions-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#12038 cli: do not set AutofillShowTypePredictions
  lighthouse-cli/bin.js
  lighthouse-cli/test/smokehouse/lighthouse-runners/bundle.js
  lighthouse-cli/test/smokehouse/test-definitions/core-tests.js
  lighthouse-core/gather/gatherers/form-elements.js
Labels: cla: yes, waiting4reviewer

#12069 core(cls): refactor CLS and CLS-AF
  lighthouse-core/computed/layout-shift-variants.js
  lighthouse-core/computed/metrics/cumulative-layout-shift-all-frames.js
  lighthouse-core/computed/metrics/cumulative-layout-shift.js
  lighthouse-core/lib/lh-error.js
  lighthouse-core/test/computed/metrics/cumulative-layout-shift-all-frames-test.js
Labels: cla: yes, waiting4committer

#12054 core(unsized-images): skip images that are zero-sized
  lighthouse-core/audits/unsized-images.js
  lighthouse-core/test/audits/unsized-images-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#12078 misc(git3po): merge when green for unstable state too
  lighthouse-core/scripts/git3po-rules/land-when-green.yaml
Labels: cla: yes, waiting4reviewer

#12079 misc(ci): increase fetch-depth for codecov SHA
  .github/workflows/ci.yml
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#12056 tests(trace-elements): test node eviction with unit rather than smoke
  lighthouse-cli/test/fixtures/perf/delayed-element.js
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-core/test/audits/largest-contentful-paint-element-test.js
  lighthouse-core/test/audits/layout-shift-elements-test.js
  lighthouse-core/test/gather/gatherers/trace-elements-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#12075 deps(axe-core): upgrade to 4.1.2
  lighthouse-core/gather/gatherers/accessibility.js
  lighthouse-core/test/report/html/renderer/category-renderer-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  types/artifacts.d.ts
  yarn.lock
Labels: cla: yes, waiting4committer

#12065 core(image-elements): set 5s time budget, add _privateCssSizing
  lighthouse-core/audits/unsized-images.js
  lighthouse-core/gather/gatherers/image-elements.js
  lighthouse-core/test/audits/unsized-images-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  types/artifacts.d.ts
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12005 core(tap-targets): drop custom node rect creation
  lighthouse-core/audits/seo/tap-targets.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12086 v7.1.0
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  docs/releasing.md
  lighthouse-core/scripts/release/prepare-commit.sh
  lighthouse-core/scripts/release/test.sh
  lighthouse-core/test/results/sample_v2.json
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes, waiting4reviewer

#12074 core(fr): add DevtoolsLog artifact
  lighthouse-core/audits/byte-efficiency/total-byte-weight.js
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/fraggle-rock/gather/session.js
  lighthouse-core/gather/gatherers/devtools-log-compat.js
  lighthouse-core/gather/gatherers/devtools-log.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/fraggle-rock/gather/session-test.js
  types/artifacts.d.ts
  types/gatherer.d.ts
Labels: cla: yes, waiting4committer

#12099 misc(ci): update GH actions commit SHAs
  .github/workflows/ci.yml
  .github/workflows/issue-assigner.yml
Labels: cla: yes, waiting4reviewer

#12098 core(fr): add navigation phase + trace gatherer
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/fraggle-rock/config/validation.js
  lighthouse-core/fraggle-rock/gather/base-gatherer.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/fraggle-rock/gather/runner-helpers.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gatherers/trace-compat.js
  lighthouse-core/gather/gatherers/trace.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/fraggle-rock/config/config-test.js
  lighthouse-core/test/fraggle-rock/config/validation-test.js
  lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
  lighthouse-core/test/gather/driver-test.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
  types/artifacts.d.ts
  types/gatherer.d.ts
Labels: cla: yes, land-when-ci-is-green

#12120 core(unsized-images): ignore non-network SVGs
  lighthouse-cli/test/fixtures/byte-efficiency/tester.html
  lighthouse-core/audits/unsized-images.js
  lighthouse-core/test/audits/unsized-images-test.js
Labels: cla: yes, waiting4reviewer

#12122 core(preload): do not warn for cache loads
  lighthouse-core/audits/uses-rel-preload.js
  lighthouse-core/lib/network-request.js
  lighthouse-core/test/audits/uses-rel-preload-test.js
Labels: cla: yes, waiting4reviewer

#12092 misc: fixed typos More => more
  lighthouse-core/audits/metrics/largest-contentful-paint.js
  lighthouse-core/audits/no-unload-listeners.js
  lighthouse-core/audits/preload-fonts.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes

#12115 clients(lr): should skip uses-http2 audit for mobile
  lighthouse-core/config/lr-mobile-config.js
Labels: cla: yes, waiting4reviewer

#12126 docs(throttling): retitle devtools panel h2
  docs/throttling.md
Labels: cla: yes, waiting4reviewer

#12104 core(emulation): bump chrome versions
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/cli/index-test.js
  lighthouse-core/config/constants.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, land-when-ci-is-green

#12112 docs(auth): correct path in readme
  docs/recipes/auth/README.md
Labels: cla: yes, waiting4reviewer

#12127 tests: sync devtools tests
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-block-url-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-block-url.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-flags-run.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/resources/lighthouse-basic.css
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/resources/lighthouse-basic.html
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#10950 misc: rename lantern master values to baseline values
  lighthouse-core/scripts/lantern/assert-baseline-lantern-values-unchanged.js
  lighthouse-core/scripts/lantern/constants.js
  lighthouse-core/scripts/lantern/print-correlations.js
  lighthouse-core/scripts/lantern/update-baseline-lantern-values.js
  lighthouse-core/scripts/test-lantern.sh
  lighthouse-core/test/fixtures/lantern-baseline-accuracy.json
  lighthouse-core/test/fixtures/lantern-baseline-computed-values.json
  package.json
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11832 misc(treemap): first pass
  .npmignore
  build-tracker.config.js
  build/gh-pages-app.js
  lighthouse-core/audits/script-treemap-data.js
  lighthouse-core/test/audits/__snapshots__/script-treemap-data-test.js.snap
  lighthouse-core/test/audits/script-treemap-data-test.js
  lighthouse-treemap/app/debug.json
  lighthouse-treemap/app/index.html
  lighthouse-treemap/app/src/main.js
  lighthouse-treemap/app/src/util.js
  lighthouse-treemap/app/styles/treemap.css
  lighthouse-treemap/test/util-test.js
  lighthouse-treemap/types/treemap.d.ts
  package.json
  types/treemap.d.ts
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#11766 core(url): redirects-http => n/a for localhost. refactor url special cases
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency/expectations.js
  lighthouse-cli/test/smokehouse/test-definitions/offline-local/offline-expectations.js
  lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
  lighthouse-core/audits/dobetterweb/uses-http2.js
  lighthouse-core/audits/is-on-https.js
  lighthouse-core/audits/preload-lcp-image.js
  lighthouse-core/audits/redirects-http.js
  lighthouse-core/audits/unsized-images.js
  lighthouse-core/audits/uses-rel-preload.js
  lighthouse-core/computed/resource-summary.js
  lighthouse-core/gather/driver/network-monitor.js
  lighthouse-core/lib/dependency-graph/network-node.js
  lighthouse-core/lib/network-request.js
  lighthouse-core/lib/url-shim.js
  lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
  lighthouse-core/test/audits/byte-efficiency/render-blocking-resources-test.js
  lighthouse-core/test/audits/is-on-https-test.js
  lighthouse-core/test/audits/redirects-http-test.js
  lighthouse-core/test/computed/load-simulator-test.js
  lighthouse-core/test/computed/metrics/interactive-test.js
  lighthouse-core/test/computed/resource-summary-test.js
  lighthouse-core/test/gather/driver/network-monitor-test.js
  lighthouse-core/test/lib/dependency-graph/simulator/simulator-test.js
  lighthouse-core/test/lib/network-request-test.js
  lighthouse-core/test/lib/url-shim-test.js
  lighthouse-core/test/report/html/renderer/category-renderer-test.js
  lighthouse-core/test/report/html/renderer/pwa-category-renderer-test.js
  lighthouse-core/test/results/sample_v2.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: P1, cla: yes, land-when-ci-is-green, waiting4reviewer

#12100 misc: add LIGHTHOUSE_FLAGS to gcp script. tweak extract script
  lighthouse-core/scripts/gcp-collection/README.md
  lighthouse-core/scripts/gcp-collection/extract-data.sh
  lighthouse-core/scripts/gcp-collection/run.sh
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#12136 v7.2.0
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes, waiting4reviewer

#12129 core(fr): convert base artifacts to gatherer artifacts
  lighthouse-core/fraggle-rock/config/config.js
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/fraggle-rock/gather/base-artifacts.js
  lighthouse-core/fraggle-rock/gather/driver.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/fraggle-rock/gather/snapshot-runner.js
  lighthouse-core/fraggle-rock/gather/timespan-runner.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/driver/environment.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/gather/gatherers/installability-errors.js
  lighthouse-core/gather/gatherers/network-user-agent.js
  lighthouse-core/gather/gatherers/stacks.js
  lighthouse-core/gather/gatherers/web-app-manifest.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/fraggle-rock/gather/driver-test.js
  lighthouse-core/test/fraggle-rock/gather/mock-driver.js
  lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
  lighthouse-core/test/fraggle-rock/gather/snapshot-runner-test.js
  lighthouse-core/test/fraggle-rock/gather/timespan-runner-test.js
  lighthouse-core/test/gather/driver-test.js
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/gather/gatherers/installability-errors-test.js
  lighthouse-core/test/gather/gatherers/network-user-agent-test.js
  lighthouse-core/test/gather/gatherers/stacks-test.js
  lighthouse-core/test/gather/gatherers/web-app-manifest-test.js
  lighthouse-core/test/test-utils.js
  tsconfig.json
  types/artifacts.d.ts
  types/gatherer.d.ts
Labels: cla: yes, waiting4committer

#12135 core(driver): remove unused goOffline/goOnline methods
  lighthouse-core/gather/driver.js
  lighthouse-core/lib/emulation.js
  lighthouse-core/test/gather/driver-test.js
Labels: cla: yes, waiting4reviewer
