Repository GoogleChrome/lighthouse, pull requests merged in 2021-04, with the labels that each got.

#12333 deps: update eslint to latest
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js
  lighthouse-core/gather/gatherers/seo/robots-txt.js
  lighthouse-core/lib/file-namer.js
  lighthouse-core/lib/page-functions.js
  lighthouse-core/lib/url-shim.js
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/report/html/renderer/dom.js
  lighthouse-core/report/html/renderer/i18n.js
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/scripts/generate-bundlephobia-database.js
  lighthouse-core/test/audits/dobetterweb/no-vulnerable-libraries-test.js
  lighthouse-core/test/gather/gatherers/dobetterweb/response-compression-test.js
  lighthouse-core/test/report/html/renderer/util-test.js
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green

#12323 tests: fix split of smoke tests across jobs
  .github/workflows/ci.yml
  package.json
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12274 core(meta-elements): add NodeDetails
  lighthouse-core/audits/seo/is-crawlable.js
  lighthouse-core/gather/gatherers/meta-elements.js
  lighthouse-core/lib/asset-saver.js
  lighthouse-core/test/audits/seo/is-crawlable-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12334 report: move budgets after diagnostics
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/test/report/html/renderer/performance-category-renderer-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12313 misc: fix open-devtools script
  lighthouse-core/scripts/open-devtools.sh
Labels: cla: yes

#12317 deps: replace inquirer with enquirer
  lighthouse-cli/sentry-prompt.js
  package.json
  types/enquirer.d.ts
  yarn.lock
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12338 deps: update jsonld to latest
  package.json
  readme.md
  yarn.lock
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12353 tests(smoke): update CLS-AF expectation
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
Labels: cla: yes, waiting4reviewer

#12354 tests(smoke): remove html imports from dbw_tester
  lighthouse-cli/test/fixtures/dobetterweb/dbw_partial_a.html
  lighthouse-cli/test/fixtures/dobetterweb/dbw_partial_b.html
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-core/test/lib/i18n/swap-locale-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4reviewer

#12348 cli(asset-saver): print one devtoolsLog event per line
  lighthouse-cli/test/smokehouse/lighthouse-runners/bundle.js
  lighthouse-core/lib/asset-saver.js
  lighthouse-core/test/lib/asset-saver-test.js
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12357 misc: add patrickhulce back to issue assignment
  .github/workflows/issue-assigner.yml
Labels: cla: yes, waiting4reviewer

#11763 tests: cron to check for relevant chromium changes
  .github/workflows/cron-weekly.yml
  jest.config.js
  third-party/chromium-synchronization/inspector-issueAdded-types-test.js
  third-party/chromium-synchronization/installability-errors-test.js
Labels: cla: yes, waiting4committer

#12341 core(deprecations): ignore warning for ::-webkit-details-marker
  lighthouse-core/audits/deprecations.js
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#12298 tests: retry some jest tests on failure
  .github/scripts/jest-retry.sh
  .github/workflows/ci.yml
  package.json
  yarn.lock
Labels: cla: yes, waiting4committer

#12267 report: tweak summary marker styles
  lighthouse-core/report/html/report-styles.css
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12358 misc: fix path check for roll devtools script
  lighthouse-core/scripts/roll-to-devtools.sh
Labels: cla: yes, waiting4reviewer

#12342 misc(treemap): tweak styles for logo spacing and text colors
  lighthouse-treemap/app/index.html
  lighthouse-treemap/app/src/main.js
  lighthouse-treemap/app/styles/treemap.css
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12145 misc: puppeteer script to test a page from devtools
  lighthouse-core/scripts/pptr-run-devtools.js
  lighthouse-core/test/chromium-web-tests/test-page-devtools.sh
  package.json
Labels: cla: yes, land-when-ci-is-green

#12347 core(fetcher): disable auto-attaching for injected iframe
  lighthouse-core/gather/fetcher.js
Labels: cla: yes, land-when-ci-is-green

#12359 tests: remove flaky Chrome launch from unit-cli
  .github/workflows/ci.yml
  lighthouse-cli/test/cli/run-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#12356 docs(readme): add Alertdesk to the list of integrations
  readme.md
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12368 docs(architecture): augment gathering & artifacts a bit
  docs/architecture.md
Labels: cla: yes, waiting4reviewer

#12367 core(fr): filter out manual-only categories
  lighthouse-core/fraggle-rock/config/filters.js
  lighthouse-core/test/fraggle-rock/config/filters-test.js
Labels: cla: yes, waiting4reviewer

#12376 misc(ci): increase yarn network timeout
  .github/workflows/ci.yml
Labels: cla: yes, waiting4reviewer

#12375 core(fr): prepare emulation utilities for shared use
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/gather/gatherers/full-page-screenshot.js
  lighthouse-core/lib/emulation.js
  lighthouse-core/test/gather/fake-driver.js
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/gather/gatherers/full-page-screenshot-test.js
  lighthouse-core/test/test-utils.js
Labels: cla: yes, waiting4reviewer

#12381 core(driver): move evaluateOnNewDocument to executionContext
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/driver/execution-context.js
  lighthouse-core/gather/driver/wait-for-condition.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js
  lighthouse-core/lib/page-functions.js
  lighthouse-core/test/gather/driver/execution-context-test.js
  lighthouse-core/test/gather/fake-driver.js
  lighthouse-core/test/gather/gather-runner-test.js
  types/externs.d.ts
Labels: cla: yes, waiting4reviewer

#12377 core(unsized-images): pass with explicit aspect-ratio
  lighthouse-cli/test/fixtures/launcher-icon-100x100.png
  lighthouse-cli/test/fixtures/perf/unsized-images.html
  lighthouse-cli/test/smokehouse/test-definitions/perf-diagnostics/expectations.js
  lighthouse-core/audits/unsized-images.js
  lighthouse-core/gather/gatherers/image-elements.js
  lighthouse-core/test/audits/unsized-images-test.js
  types/artifacts.d.ts
Labels: cla: yes, land-when-ci-is-green

#12360 misc(treemap): root node selector
  lighthouse-treemap/app/index.html
  lighthouse-treemap/app/src/main.js
  lighthouse-treemap/app/styles/treemap.css
  lighthouse-treemap/types/treemap.d.ts
  types/treemap.d.ts
Labels: cla: yes, waiting4reviewer

#12199 core(fetcher): fetch over protocol
  lighthouse-cli/test/smokehouse/test-definitions/source-maps/expectations.js
  lighthouse-core/gather/fetcher.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/gather/gatherers/source-maps.js
  lighthouse-core/lib/network-request.js
  lighthouse-core/test/gather/driver-test.js
  lighthouse-core/test/gather/fake-driver.js
  lighthouse-core/test/gather/fetcher-test.js
  lighthouse-core/test/gather/gatherers/source-maps-test.js
  package.json
  yarn.lock
Labels: cla: yes, next-release, waiting4reviewer

#12413 v7.4.0
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes, land-when-ci-is-green

#12414 core(responsive-images): ignore images larger than viewport
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-core/audits/image-size-responsive.js
  lighthouse-core/test/audits/image-size-responsive-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4reviewer

#12419 core(fr): add fetcher to transitional driver
  lighthouse-core/fraggle-rock/gather/driver.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/fetcher.js
  lighthouse-core/test/fraggle-rock/gather/driver-test.js
  lighthouse-core/test/gather/fetcher-test.js
  types/gatherer.d.ts
Labels: cla: yes, waiting4committer

#12418 tests: add organic TTI savings case to byte efficieny audit
  lighthouse-core/test/audits/byte-efficiency/__snapshots__/byte-efficiency-audit-test.js.snap
  lighthouse-core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
Labels: cla: yes, waiting4reviewer

#12391 tests(smoke): verify CSP violations caused by lighthouse
  lighthouse-cli/test/fixtures/csp.html
  lighthouse-cli/test/fixtures/static-server.js
  lighthouse-cli/test/smokehouse/test-definitions/core-tests.js
  lighthouse-cli/test/smokehouse/test-definitions/csp/csp-config.js
  lighthouse-cli/test/smokehouse/test-definitions/csp/csp-expectations.js
Labels: cla: yes, waiting4reviewer

#12392 report: add treemap button, refactor icon styles
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/report/html/templates.html
  lighthouse-core/test/report/html/renderer/report-ui-features-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/lighthouse-result.proto
Labels: cla: yes, waiting4reviewer

#12422 tests: split CI into unit and smoke workflows
  .github/workflows/ci.yml
  .github/workflows/devtools.yml
  .github/workflows/smoke.yml
  readme.md
Labels: cla: yes, waiting4reviewer

#12363 misc(treemap): add data table
  build/build-treemap.js
  lighthouse-treemap/app/index.html
  lighthouse-treemap/app/src/main.js
  lighthouse-treemap/app/styles/treemap.css
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12370 core(fr): separate phase from gatherMode
  lighthouse-core/fraggle-rock/config/validation.js
  lighthouse-core/fraggle-rock/gather/base-gatherer.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/fraggle-rock/gather/runner-helpers.js
  lighthouse-core/fraggle-rock/gather/snapshot-runner.js
  lighthouse-core/fraggle-rock/gather/timespan-runner.js
  lighthouse-core/gather/gatherers/accessibility.js
  lighthouse-core/gather/gatherers/cache-contents.js
  lighthouse-core/gather/gatherers/console-messages.js
  lighthouse-core/gather/gatherers/devtools-log-compat.js
  lighthouse-core/gather/gatherers/devtools-log.js
  lighthouse-core/gather/gatherers/dobetterweb/appcache.js
  lighthouse-core/gather/gatherers/dobetterweb/doctype.js
  lighthouse-core/gather/gatherers/dobetterweb/domstats.js
  lighthouse-core/gather/gatherers/dobetterweb/password-inputs-with-prevented-paste.js
  lighthouse-core/gather/gatherers/form-elements.js
  lighthouse-core/gather/gatherers/global-listeners.js
  lighthouse-core/gather/gatherers/iframe-elements.js
  lighthouse-core/gather/gatherers/installability-errors.js
  lighthouse-core/gather/gatherers/meta-elements.js
  lighthouse-core/gather/gatherers/network-user-agent.js
  lighthouse-core/gather/gatherers/seo/embedded-content.js
  lighthouse-core/gather/gatherers/seo/font-size.js
  lighthouse-core/gather/gatherers/seo/robots-txt.js
  lighthouse-core/gather/gatherers/seo/tap-targets.js
  lighthouse-core/gather/gatherers/trace-compat.js
  lighthouse-core/gather/gatherers/trace.js
  lighthouse-core/gather/gatherers/viewport-dimensions.js
  lighthouse-core/gather/gatherers/web-app-manifest.js
  lighthouse-core/test/fraggle-rock/config/config-test.js
  lighthouse-core/test/fraggle-rock/config/validation-test.js
  lighthouse-core/test/fraggle-rock/gather/base-gatherer-test.js
  lighthouse-core/test/fraggle-rock/gather/mock-driver.js
  lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
  lighthouse-core/test/fraggle-rock/gather/runner-helpers-test.js
  lighthouse-core/test/fraggle-rock/gather/snapshot-runner-test.js
  lighthouse-core/test/fraggle-rock/gather/timespan-runner-test.js
  types/gatherer.d.ts
Labels: cla: yes, waiting4reviewer
