Repository GoogleChrome/lighthouse, pull requests merged in 2021-10, with the labels that each got.

#13160 misc: ensure psi.espanol sample-report es en espanol
  build/build-sample-reports.js
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13099 docs: correct the Node.js version base
  package.json
  readme.md
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13168 Remove console logging noise when auditing various profiles
  lighthouse-core/lib/network-records-from-trace.js
Labels: cla: yes, waiting4reviewer

#13163 misc(scripts): fix run-devtools sniffing, add error checking
  lighthouse-core/scripts/pptr-run-devtools.js
Labels: cla: yes, waiting4reviewer

#13162 misc: set predictable order for sample json timing entries
  lighthouse-core/runner.js
  lighthouse-core/scripts/cleanup-LHR-for-diff.js
  lighthouse-core/test/results/sample_v2.json
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13161 core(fr): add `supportedModes` filter to categories
  flow-report/src/summary/category.tsx
  flow-report/test/summary/category-test.tsx
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/config/default-config.js
  lighthouse-core/fraggle-rock/config/filters.js
  lighthouse-core/scripts/update-flow-fixtures.js
  lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  lighthouse-core/test/fraggle-rock/config/filters-test.js
  lighthouse-core/test/fraggle-rock/scenarios/api-test-pptr.js
  lighthouse-core/test/results/sample_v2.json
  proto/lighthouse-result.proto
  types/config.d.ts
Labels: waiting4committer, cla: yes

#13171 report(flow): elide step name
  flow-report/assets/styles.css
  flow-report/src/summary/summary.tsx
  flow-report/test/summary/summary-test.tsx
Labels: waiting4committer, cla: yes

#13179 tests: update deprecations smoke for M96
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
Labels: cla: yes, waiting4reviewer

#13281 report(flow): puppeteer test
  flow-report/test/flow-report-pptr-test.ts
Labels: cla: yes, waiting4reviewer

#13265 core(image-elements): remove mimeType from artifact
  lighthouse-core/audits/image-aspect-ratio.js
  lighthouse-core/audits/image-size-responsive.js
  lighthouse-core/audits/unsized-images.js
  lighthouse-core/computed/image-records.js
  lighthouse-core/gather/gatherers/image-elements.js
  lighthouse-core/test/audits/image-aspect-ratio-test.js
  lighthouse-core/test/audits/image-size-responsive-test.js
  lighthouse-core/test/audits/unsized-images-test.js
  lighthouse-core/test/computed/image-records-test.js
  lighthouse-core/test/gather/gatherers/image-elements-test.js
  types/artifacts.d.ts
Labels: cla: yes, waiting4reviewer

#13285 tests: ignore .tmp directory in jest modules
  jest.config.js
Labels: cla: yes, waiting4reviewer

#13286 core(errors-in-console): remove url property from items
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb/dbw-expectations.js
  lighthouse-core/audits/errors-in-console.js
  lighthouse-core/test/audits/errors-in-console-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, waiting4reviewer

#13289 misc: revert missing bundle tests
  package.json
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer
