Repository GoogleChrome/lighthouse, pull requests merged in 2021-05, with the labels that each got.

#12415 misc: do not publish lighthouse-cli/test except smokehouse
  .npmignore
  lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js
  lighthouse-core/scripts/release/test.sh
Labels: cla: yes, waiting4committer

#12435 core(computed-artifact): remove settings and options from context
  lighthouse-core/audits/metrics.js
  lighthouse-core/audits/performance-budget.js
  lighthouse-core/audits/resource-summary.js
  lighthouse-core/audits/timing-budget.js
  lighthouse-core/computed/computed-artifact.js
  lighthouse-core/computed/critical-request-chains.js
  lighthouse-core/computed/layout-shift-variants.js
  lighthouse-core/computed/load-simulator.js
  lighthouse-core/computed/main-resource.js
  lighthouse-core/computed/main-thread-tasks.js
  lighthouse-core/computed/metrics/cumulative-layout-shift-all-frames.js
  lighthouse-core/computed/metrics/cumulative-layout-shift.js
  lighthouse-core/computed/metrics/estimated-input-latency.js
  lighthouse-core/computed/metrics/first-contentful-paint.js
  lighthouse-core/computed/metrics/first-cpu-idle.js
  lighthouse-core/computed/metrics/first-meaningful-paint.js
  lighthouse-core/computed/metrics/interactive.js
  lighthouse-core/computed/metrics/lantern-estimated-input-latency.js
  lighthouse-core/computed/metrics/lantern-first-cpu-idle.js
  lighthouse-core/computed/metrics/lantern-first-meaningful-paint.js
  lighthouse-core/computed/metrics/lantern-interactive.js
  lighthouse-core/computed/metrics/lantern-largest-contentful-paint.js
  lighthouse-core/computed/metrics/lantern-max-potential-fid.js
  lighthouse-core/computed/metrics/lantern-metric.js
  lighthouse-core/computed/metrics/lantern-speed-index.js
  lighthouse-core/computed/metrics/lantern-total-blocking-time.js
  lighthouse-core/computed/metrics/largest-contentful-paint.js
  lighthouse-core/computed/metrics/max-potential-fid.js
  lighthouse-core/computed/metrics/metric.js
  lighthouse-core/computed/metrics/speed-index.js
  lighthouse-core/computed/metrics/timing-summary.js
  lighthouse-core/computed/metrics/total-blocking-time.js
  lighthouse-core/computed/module-duplication.js
  lighthouse-core/computed/network-analysis.js
  lighthouse-core/computed/page-dependency-graph.js
  lighthouse-core/computed/resource-summary.js
  lighthouse-core/computed/speedline.js
  lighthouse-core/computed/unused-css.js
  lighthouse-core/computed/user-timings.js
  lighthouse-core/test/computed/metrics/timing-summary-test.js
  lighthouse-core/test/computed/resource-summary-test.js
  types/artifacts.d.ts
Labels: cla: yes, waiting4committer

#12436 docs: add python requests install to webtests
  lighthouse-core/test/chromium-web-tests/README.md
Labels: cla: yes, land-when-ci-is-green

#12423 core(robots): use new fetcher to get robots.txt
  lighthouse-cli/test/smokehouse/test-definitions/csp/csp-expectations.js
  lighthouse-core/gather/fetcher.js
  lighthouse-core/gather/gatherers/seo/robots-txt.js
  lighthouse-core/gather/gatherers/source-maps.js
  lighthouse-core/test/gather/fetcher-test.js
  lighthouse-core/test/gather/gatherers/source-maps-test.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes, waiting4committer

#12421 core(driver): extract gotoURL to navigation module
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/driver/navigation.js
  lighthouse-core/gather/driver/network-monitor.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/test/fraggle-rock/gather/mock-driver.js
  lighthouse-core/test/gather/driver-test.js
  lighthouse-core/test/gather/driver/navigation-test.js
  lighthouse-core/test/gather/driver/network-monitor-test.js
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/gather/mock-commands.js
  lighthouse-core/test/runner-test.js
  lighthouse-core/test/test-utils.js
Labels: cla: yes, waiting4reviewer

#12390 docs: remove AMP Plugin example
  docs/plugins.md
Labels: cla: yes, land-when-ci-is-green

#12431 core(fr): split out DOM utilities from legacy driver
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/driver/dom.js
  lighthouse-core/gather/gatherers/anchor-elements.js
  lighthouse-core/gather/gatherers/trace-elements.js
  lighthouse-core/lib/lh-element.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/gather/driver-test.js
  lighthouse-core/test/gather/driver/dom-test.js
  lighthouse-core/test/lib/lh-element-test.js
  types/artifacts.d.ts
Labels: cla: yes, waiting4committer

#12440 deps: update marky to latest
  lighthouse-logger/package.json
  lighthouse-logger/yarn.lock
  yarn.lock
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12424 misc(treemap): duplicate-modules view mode
  lighthouse-treemap/app/debug.json
  lighthouse-treemap/app/src/main.js
  lighthouse-treemap/app/styles/treemap.css
  types/treemap.d.ts
Labels: cla: yes, waiting4reviewer

#12442 core(fr): convert trace-elements gatherer
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/gather/gatherers/trace-elements.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/gather/gatherers/trace-elements-test.js
  types/artifacts.d.ts
Labels: cla: yes, waiting4committer

#12450 core(fr): convert js-usage gatherer
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/gather/gatherers/js-usage.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/gather/gatherers/js-usage-test.js
  types/artifacts.d.ts
Labels: cla: yes, waiting4committer

#12446 tests: add smokehouse to bin for downstream use
  .npmignore
  lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js
  lighthouse-cli/test/smokehouse/lighthouse-runners/cli.js
  lighthouse-cli/test/smokehouse/readme.md
  lighthouse-cli/test/smokehouse/report-assert.js
  lighthouse-cli/test/smokehouse/smokehouse.js
  lighthouse-core/scripts/release/test.sh
  package.json
  types/smokehouse.d.ts
  yarn.lock
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12452 core(script-treemap-data): include unmapped bytes
  lighthouse-core/audits/script-treemap-data.js
  lighthouse-core/computed/unused-javascript-summary.js
  lighthouse-core/test/audits/__snapshots__/script-treemap-data-test.js.snap
  lighthouse-core/test/audits/script-treemap-data-test.js
  lighthouse-treemap/app/debug.json
Labels: cla: yes, waiting4reviewer

#12462 misc(treemap): fix colors
  lighthouse-treemap/app/debug.json
  lighthouse-treemap/app/src/main.js
  lighthouse-treemap/app/src/util.js
  lighthouse-treemap/test/util-test.js
  types/treemap.d.ts
Labels: cla: yes, waiting4committer

#12467 core(fr): convert source-maps gatherer
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/gather/gatherers/source-maps.js
  lighthouse-core/test/gather/gatherers/source-maps-test.js
  types/artifacts.d.ts
Labels: cla: yes, waiting4committer

#12466 deps: update transitive dependencies
  package.json
  yarn.lock
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12461 core(fr): extract navigation errors from gather-runner
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/lib/navigation-error.js
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/lib/navigation-error-test.js
Labels: cla: yes, waiting4reviewer

#12427 core(fr): add computed cache to pass context
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/fraggle-rock/gather/base-gatherer.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/fraggle-rock/gather/runner-helpers.js
  lighthouse-core/fraggle-rock/gather/snapshot-runner.js
  lighthouse-core/fraggle-rock/gather/timespan-runner.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/gather/gatherers/link-elements.js
  lighthouse-core/index.js
  lighthouse-core/runner.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/fraggle-rock/gather/base-gatherer-test.js
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/gather/gatherers/css-usage-test.js
  lighthouse-core/test/gather/gatherers/link-elements-test.js
  lighthouse-core/test/runner-test.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
  types/artifacts.d.ts
  types/gatherer.d.ts
Labels: cla: yes, land-when-ci-is-green

#12398 misc(cli): destructure args in import
  lighthouse-cli/bin.js
Labels: cla: yes

#12470 core(fr): convert main-document-content gatherer
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/driver/network.js
  lighthouse-core/gather/gatherers/main-document-content.js
  lighthouse-core/test/fraggle-rock/gather/mock-driver.js
  lighthouse-core/test/gather/gatherers/main-document-content-test.js
  types/artifacts.d.ts
Labels: cla: yes, waiting4committer

#12476 core: add new CLS (all frames) to hidden metrics audit
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-core/audits/metrics.js
  lighthouse-core/computed/layout-shift-variants.js
  lighthouse-core/computed/metrics/timing-summary.js
  lighthouse-core/test/audits/__snapshots__/metrics-test.js.snap
  lighthouse-core/test/audits/metrics-test.js
  lighthouse-core/test/computed/layout-shift-variants-test.js
  lighthouse-core/test/computed/metrics/timing-summary-test.js
  lighthouse-core/test/create-test-trace.js
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#12441 misc(treemap): i18n
  build/build-treemap.js
  build/gh-pages-app.js
  lighthouse-core/lib/i18n/locales.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/report/html/renderer/i18n.js
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/scripts/i18n/bake-ctc-to-lhl.js
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/test/report/html/renderer/report-ui-features-test.js
  lighthouse-treemap/app/index.html
  lighthouse-treemap/app/src/main.js
  lighthouse-treemap/app/src/util.js
  lighthouse-treemap/test/util-test.js
  lighthouse-treemap/types/treemap.d.ts
Labels: cla: yes, waiting4reviewer

#12482 misc: move predictive-perf off renderer i18n
  lighthouse-core/audits/predictive-perf.js
  lighthouse-core/report/html/renderer/i18n.js
  lighthouse-core/test/audits/predictive-perf-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12481 misc(treemap): add GA snippet for new property
  lighthouse-treemap/app/index.html
Labels: cla: yes, waiting4committer

#12484 misc(treemap): remove byte size from title
  lighthouse-treemap/app/index.html
  lighthouse-treemap/app/src/main.js
Labels: cla: yes, waiting4committer

#12487 tests(i18n): only accept IcuMessages in toBeDisplayString
  lighthouse-core/test/audits/installable-manifest-test.js
  lighthouse-core/test/audits/is-on-https-test.js
  lighthouse-core/test/index-test.js
  lighthouse-core/test/runner-test.js
  lighthouse-core/test/test-utils.js
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12469 core(fr): extract warnings from gather-runner
  lighthouse-core/gather/driver/environment.js
  lighthouse-core/gather/driver/navigation.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
  lighthouse-core/test/gather/driver/environment-test.js
  lighthouse-core/test/gather/driver/navigation-test.js
  lighthouse-core/test/gather/fake-driver.js
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/runner-test.js
  lighthouse-core/test/test-utils.js
Labels: cla: yes, waiting4committer

#12474 core(fr): convert image-elements gatherer
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/gather/gatherers/image-elements.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/fraggle-rock/config/config-test.js
  lighthouse-core/test/gather/gatherers/image-elements-test.js
  types/artifacts.d.ts
Labels: cla: yes, waiting4committer

#12485 misc(treemap): use 0.1 for default granularity
  lighthouse-core/report/html/renderer/i18n.js
Labels: cla: yes, waiting4reviewer

#12488 misc(treemap): upgrade to 3.2.0 for keyboard navigation
  package.json
  yarn.lock
Labels: cla: yes, waiting4committer

#11732 report: map metrics to audits
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/config/default-config.js
  lighthouse-core/config/metrics-to-audits.js
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/test/config/default-config-test.js
  lighthouse-core/test/results/sample_v2.json
  proto/lighthouse-result.proto
  types/config.d.ts
  types/lhr.d.ts
Labels: P1, cla: yes, land-when-ci-is-green, waiting4reviewer

#12364 tests: update chromium installable source path
  third-party/chromium-synchronization/installability-errors-test.js
Labels: cla: yes, land-when-ci-is-green, waiting4committer

#12477 report: metric filter refactor to JS and adornments
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/report/html/renderer/category-renderer.js
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/report/html/renderer/util.js
  lighthouse-core/report/html/report-styles.css
  lighthouse-core/test/results/sample_v2.json
  proto/lighthouse-result.proto
  types/html-renderer.d.ts
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12483 misc(treemap): highlight treemap node on mouse hover table row
  lighthouse-treemap/app/src/main.js
  types/treemap.d.ts
Labels: cla: yes, waiting4reviewer

#12493 misc(treemap): tweak styles for mobile
  lighthouse-treemap/app/index.html
  lighthouse-treemap/app/src/main.js
  lighthouse-treemap/app/styles/treemap.css
Labels: cla: yes, waiting4reviewer

#12491 core(fr): convert optimized-images gatherer
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js
  lighthouse-core/test/gather/gatherers/dobetterweb/optimized-images-test.js
  types/artifacts.d.ts
Labels: cla: yes, waiting4reviewer

#12495 misc(treemap): set focus-visible styles for view mode buttons
  lighthouse-treemap/app/src/main.js
  lighthouse-treemap/app/styles/treemap.css
Labels: cla: yes, waiting4reviewer

#12492 i18n: import new strings
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
Labels: cla: yes, land-when-ci-is-green, rls-blocker, waiting4committer

#12496 misc(treemap): update colors on enter keypress
  lighthouse-treemap/app/src/main.js
Labels: cla: yes, waiting4reviewer

#12486 misc(treemap): shade background for unused bytes
  lighthouse-treemap/app/src/main.js
  lighthouse-treemap/app/styles/treemap.css
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12497 misc(treemap): remove too similar color hues
  lighthouse-treemap/app/src/util.js
Labels: cla: yes, waiting4reviewer

#12498 misc(treemap): esc to zoom out
  lighthouse-treemap/app/src/main.js
  lighthouse-treemap/types/treemap.d.ts
Labels: cla: yes, waiting4committer

#12494 core(script-treemap-data): default config
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/audits/script-treemap-data.js
  lighthouse-core/config/default-config.js
  lighthouse-core/config/experimental-config.js
  lighthouse-core/report/html/renderer/details-renderer.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/report-template.html
  lighthouse-core/test/audits/script-treemap-data-test.js
  lighthouse-core/test/report/html/renderer/report-ui-features-test.js
  lighthouse-core/test/results/sample_v2.json
  lighthouse-treemap/app/debug.json
  lighthouse-treemap/app/src/main.js
  lighthouse-treemap/app/src/util.js
  lighthouse-treemap/types/treemap.d.ts
  types/audit-details.d.ts
  types/audit.d.ts
  types/treemap.d.ts
Labels: cla: yes, rls-blocker, waiting4committer

#12500 v7.5.0
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/config/default-config.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/test/results/sample_v2.json
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run-expected.txt
Labels: cla: yes, waiting4reviewer

#12478 core(fr): align navigation-runner with legacy gather-runner
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/fraggle-rock/gather/runner-helpers.js
  lighthouse-core/fraggle-rock/gather/snapshot-runner.js
  lighthouse-core/fraggle-rock/gather/timespan-runner.js
  lighthouse-core/test/fraggle-rock/gather/mock-driver.js
  lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
  lighthouse-core/test/fraggle-rock/gather/runner-helpers-test.js
  lighthouse-core/test/network-records-to-devtools-log.js
  types/artifacts.d.ts
  types/externs.d.ts
Labels: cla: yes, waiting4committer

#12507 deps: update chrome-launcher to latest
  package.json
  yarn.lock
Labels: 8.0, cla: yes, land-when-ci-is-green, waiting4reviewer

#12508 core(fr): convert response-compression gatherer
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/gather/gatherers/dobetterweb/response-compression.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/fraggle-rock/gather/mock-driver.js
  lighthouse-core/test/gather/gatherers/dobetterweb/response-compression-test.js
  types/artifacts.d.ts
Labels: cla: yes, waiting4reviewer

#12505 report(viewer): fix gist icon
  lighthouse-core/report/html/templates.html
  lighthouse-viewer/app/src/viewer-ui-features.js
  lighthouse-viewer/app/styles/viewer.css
Labels: cla: yes, waiting4committer

#12515 i18n: import
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
Labels: cla: yes, waiting4reviewer

#12516 report: add buttons to .lh-buttons flex container
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/report-styles.css
Labels: cla: yes, waiting4reviewer

#12513 tests(ci): run unit tests on all active node versions
  .github/workflows/ci.yml
  .github/workflows/unit.yml
  lighthouse-core/test/lib/i18n/locales-test.js
  readme.md
Labels: cla: yes, waiting4reviewer

#12527 core(fr): convert tags-blocking-first-paint gatherer
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js
  lighthouse-core/test/gather/gatherers/dobetterweb/tags-blocking-first-paint-test.js
  types/artifacts.d.ts
Labels: cla: yes, waiting4reviewer

#12511 misc(treemap): add placeholder, gist and file upload features
  build/build-treemap.js
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/scripts/i18n/count-translated.js
  lighthouse-treemap/app/images/lighthouse-logo.svg
  lighthouse-treemap/app/index.html
  lighthouse-treemap/app/src/main.js
  lighthouse-treemap/app/styles/treemap.css
  lighthouse-treemap/test/treemap-test-pptr.js
  lighthouse-treemap/types/treemap.d.ts
  lighthouse-viewer/app/src/drag-and-drop.js
  lighthouse-viewer/app/src/lighthouse-report-viewer.js
  lighthouse-viewer/app/styles/viewer.css
  lighthouse-viewer/test/drag-and-drop-test.js
  package.json
  yarn.lock
Labels: cla: yes, waiting4committer

#12284 deps(puppeteer): upgrade to 9.1.1
  clients/test/extension/popup-test.js
  lighthouse-core/fraggle-rock/gather/session.js
  lighthouse-core/scripts/pptr-run-devtools.js
  lighthouse-core/test/fraggle-rock/gather/session-test.js
  lighthouse-treemap/test/treemap-test-pptr.js
  lighthouse-viewer/test/viewer-test-pptr.js
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#12514 core(csp-xss): move to default config
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/audits/csp-xss.js
  lighthouse-core/config/default-config.js
  lighthouse-core/config/experimental-config.js
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/test/results/sample_v2.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: cla: yes, waiting4reviewer

#12530 core(fr): convert inspector-issues gatherer
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/gather/gatherers/inspector-issues.js
  lighthouse-core/test/fraggle-rock/api-test-pptr.js
  lighthouse-core/test/gather/gatherers/inspector-issues-test.js
  types/artifacts.d.ts
Labels: cla: yes, waiting4committer

#12555 misc(treemap): reduce debug.json
  lighthouse-treemap/app/debug.json
Labels: cla: yes, waiting4reviewer

#12556 core: update FCP score curve
  lighthouse-core/audits/metrics/first-contentful-paint-3g.js
  lighthouse-core/audits/metrics/first-contentful-paint.js
  lighthouse-core/test/audits/metrics/first-contentful-paint-3g-test.js
  lighthouse-core/test/audits/metrics/first-contentful-paint-test.js
  lighthouse-core/test/report/report-generator-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, land-when-ci-is-green, waiting4reviewer

#12533 core: fix main session OOPIF checks for devtools
  lighthouse-core/lib/network-recorder.js
Labels: cla: yes, waiting4reviewer

#12554 core: update cumulative-layout-shift
  lighthouse-cli/test/smokehouse/test-definitions/perf/expectations.js
  lighthouse-core/audits/metrics.js
  lighthouse-core/audits/metrics/cumulative-layout-shift.js
  lighthouse-core/computed/layout-shift-variants.js
  lighthouse-core/computed/metrics/cumulative-layout-shift-all-frames.js
  lighthouse-core/computed/metrics/cumulative-layout-shift.js
  lighthouse-core/computed/metrics/timing-summary.js
  lighthouse-core/test/audits/__snapshots__/metrics-test.js.snap
  lighthouse-core/test/audits/metrics-test.js
  lighthouse-core/test/audits/metrics/cumulative-layout-shift-test.js
  lighthouse-core/test/computed/layout-shift-variants-test.js
  lighthouse-core/test/computed/metrics/cumulative-layout-shift-all-frames-test.js
  lighthouse-core/test/computed/metrics/cumulative-layout-shift-test.js
  lighthouse-core/test/computed/metrics/timing-summary-test.js
  lighthouse-core/test/results/artifacts/defaultPass.trace.json
  lighthouse-core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: 8.0, breaking, cla: yes, land-when-ci-is-green, waiting4reviewer

#12552 report: make metric filter tab accessible
  lighthouse-core/report/html/renderer/performance-category-renderer.js
  lighthouse-core/report/html/report-styles.css
Labels: cla: yes, waiting4reviewer

#12545 core(navigate): only observe longtasks in PerfObserver
  lighthouse-core/gather/driver/wait-for-condition.js
Labels: cla: yes, waiting4reviewer

#12551 core(csp-xss): add severity text column to report
  lighthouse-core/audits/csp-xss.js
  lighthouse-core/audits/dobetterweb/no-vulnerable-libraries.js
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/lib/i18n/locales/ar-XB.json
  lighthouse-core/lib/i18n/locales/ar.json
  lighthouse-core/lib/i18n/locales/bg.json
  lighthouse-core/lib/i18n/locales/ca.json
  lighthouse-core/lib/i18n/locales/cs.json
  lighthouse-core/lib/i18n/locales/da.json
  lighthouse-core/lib/i18n/locales/de.json
  lighthouse-core/lib/i18n/locales/el.json
  lighthouse-core/lib/i18n/locales/en-GB.json
  lighthouse-core/lib/i18n/locales/en-US.json
  lighthouse-core/lib/i18n/locales/en-XA.json
  lighthouse-core/lib/i18n/locales/en-XL.json
  lighthouse-core/lib/i18n/locales/es-419.json
  lighthouse-core/lib/i18n/locales/es.json
  lighthouse-core/lib/i18n/locales/fi.json
  lighthouse-core/lib/i18n/locales/fil.json
  lighthouse-core/lib/i18n/locales/fr.json
  lighthouse-core/lib/i18n/locales/he.json
  lighthouse-core/lib/i18n/locales/hi.json
  lighthouse-core/lib/i18n/locales/hr.json
  lighthouse-core/lib/i18n/locales/hu.json
  lighthouse-core/lib/i18n/locales/id.json
  lighthouse-core/lib/i18n/locales/it.json
  lighthouse-core/lib/i18n/locales/ja.json
  lighthouse-core/lib/i18n/locales/ko.json
  lighthouse-core/lib/i18n/locales/lt.json
  lighthouse-core/lib/i18n/locales/lv.json
  lighthouse-core/lib/i18n/locales/nl.json
  lighthouse-core/lib/i18n/locales/no.json
  lighthouse-core/lib/i18n/locales/pl.json
  lighthouse-core/lib/i18n/locales/pt-PT.json
  lighthouse-core/lib/i18n/locales/pt.json
  lighthouse-core/lib/i18n/locales/ro.json
  lighthouse-core/lib/i18n/locales/ru.json
  lighthouse-core/lib/i18n/locales/sk.json
  lighthouse-core/lib/i18n/locales/sl.json
  lighthouse-core/lib/i18n/locales/sr-Latn.json
  lighthouse-core/lib/i18n/locales/sr.json
  lighthouse-core/lib/i18n/locales/sv.json
  lighthouse-core/lib/i18n/locales/ta.json
  lighthouse-core/lib/i18n/locales/te.json
  lighthouse-core/lib/i18n/locales/th.json
  lighthouse-core/lib/i18n/locales/tr.json
  lighthouse-core/lib/i18n/locales/uk.json
  lighthouse-core/lib/i18n/locales/vi.json
  lighthouse-core/lib/i18n/locales/zh-HK.json
  lighthouse-core/lib/i18n/locales/zh-TW.json
  lighthouse-core/lib/i18n/locales/zh.json
  lighthouse-core/test/audits/csp-xss-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: cla: yes, land-when-ci-is-green

#12426 deps: remove intl polyfill
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/test/config/config-helpers-test.js
  lighthouse-core/test/config/config-test.js
  lighthouse-core/test/lib/i18n/i18n-test.js
  lighthouse-core/test/lib/i18n/swap-locale-test.js
  lighthouse-core/test/report/html/renderer/i18n-test.js
  package.json
  readme.md
  yarn.lock
Labels: 8.0, breaking, cla: yes, i18n, land-when-ci-is-green, waiting4reviewer

#12565 core(fr): fix usage of distributed conditional type
  lighthouse-core/fraggle-rock/gather/runner-helpers.js
  types/gatherer.d.ts
Labels: cla: yes, land-when-ci-is-green

#12566 misc(proto): backport proto formatting fixes
  proto/lighthouse-result.proto
Labels: cla: yes, waiting4reviewer

#12569 core(script-treemap-data): do not create nodes with blank names
  lighthouse-core/audits/script-treemap-data.js
  lighthouse-core/test/audits/__snapshots__/script-treemap-data-test.js.snap
  lighthouse-core/test/audits/script-treemap-data-test.js
  lighthouse-treemap/app/debug.json
  lighthouse-treemap/app/src/main.js
Labels: 8.0, cla: yes, land-when-ci-is-green, waiting4reviewer

#12570 clients(psi): render treemap button
  lighthouse-core/report/html/renderer/psi.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/test/report/html/renderer/psi-test.js
Labels: 8.0, cla: yes, waiting4committer

#12575 deps(axe-core): upgrade to 4.2.1
  lighthouse-cli/test/fixtures/a11y/a11y_tester.html
  lighthouse-cli/test/smokehouse/test-definitions/a11y/expectations.js
  lighthouse-core/gather/gatherers/accessibility.js
  lighthouse-core/test/report/html/renderer/report-renderer-test.js
  package.json
  yarn.lock
Labels: 8.0, cla: yes, land-when-ci-is-green

#12519 report: gzip treemap data
  build/build-treemap.js
  lighthouse-core/report/html/html-report-assets.js
  lighthouse-core/report/html/renderer/psi.js
  lighthouse-core/report/html/renderer/report-ui-features.js
  lighthouse-core/report/html/renderer/text-encoding.js
  lighthouse-core/test/report/html/renderer/text-encoding-test.js
  lighthouse-treemap/app/src/main.js
  lighthouse-treemap/test/treemap-test-pptr.js
  lighthouse-treemap/types/treemap.d.ts
  package.json
  types/html-renderer.d.ts
  yarn.lock
Labels: 8.0, cla: yes, waiting4committer

#12578 tests(devtools): sync webtests
  .github/workflows/devtools.yml
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-flags-run.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run.js
Labels: cla: yes, waiting4reviewer
