Repository GoogleChrome/lighthouse, pull requests merged in 2022-06, with the labels that each got.

#14017 docs(architecture): update to reflect FR changes
  docs/architecture.md
Labels: waiting4reviewer

#14074 core(driver): fix legacy runner hanging oopifs in some cases
  lighthouse-core/gather/driver.js
Labels: waiting4reviewer

#14092 tests: disable `perf-diagnostics-third-party` for FR
  .github/workflows/package-test.yml
  .github/workflows/smoke.yml
Labels: waiting4reviewer

#14031 misc(build): fix lightrider report generator bundle
  build/build-lightrider-bundles.js
Labels: waiting4reviewer

#14063 core(cdp): update HTTP method for /json/new call
  lighthouse-core/gather/connections/cri.js
Labels: land-when-ci-is-green, waiting4reviewer

#14087 core(fr): do not monkey patch puppeteer session.emit
  lighthouse-core/fraggle-rock/gather/session.js
  lighthouse-core/test/fraggle-rock/gather/session-test.js
Labels: land-when-ci-is-green, waiting4reviewer

#14062 clients(psi): expose the swapLocale types
  build/build-report.js
Labels: land-when-ci-is-green, waiting4reviewer

#14104 tests(smoke): use major milestone
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb.js
  lighthouse-cli/test/smokehouse/test-definitions/screenshot.js
Labels: land-when-ci-is-green, waiting4reviewer

#14079 core(driver): do not use target manager in legacy mode
  lighthouse-core/gather/driver/network-monitor.js
Labels: waiting4reviewer

#14086 core(driver): guard verbose logic behind log.isVerbose check
  lighthouse-core/gather/driver/wait-for-condition.js
  types/lighthouse-logger/index.d.ts
Labels: land-when-ci-is-green, waiting4reviewer

#14075 clients(lr): run benchmark repeatedly given special query parameter
  lighthouse-core/config/config.js
  lighthouse-core/fraggle-rock/config/filters.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/runner.js
  types/artifacts.d.ts
  types/lhr/lhr.d.ts
Labels: land-when-ci-is-green, waiting4reviewer

#14101 core(devtoolslog): include Target and Runtime domains
  lighthouse-core/gather/gatherers/devtools-log.js
Labels: land-when-ci-is-green, waiting4reviewer

#14097 core(fr): minor renames… cdpSession, defaultSession, requestfinished
  lighthouse-core/fraggle-rock/gather/driver.js
  lighthouse-core/fraggle-rock/gather/session.js
  lighthouse-core/gather/driver/network-monitor.js
  lighthouse-core/gather/driver/wait-for-condition.js
  lighthouse-core/lib/network-recorder.js
  lighthouse-core/test/fraggle-rock/gather/driver-test.js
  lighthouse-core/test/gather/driver/network-monitor-test.js
Labels: waiting4reviewer

#14004 misc: remove `createCommonjsRefs`
  build/build-bundle.js
  build/build-treemap.js
  build/build-viewer.js
  build/test/plugins/inline-fs-test.js
  esm-utils.mjs
  lighthouse-core/scripts/cleanup-vuln-snapshot.js
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/test/config/config-helpers-test.js
  lighthouse-core/test/config/config-plugin-test.js
  lighthouse-core/test/config/config-test.js
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/lib/asset-saver-test.js
  lighthouse-core/test/lib/i18n/i18n-test.js
  lighthouse-core/test/lib/minification-estimator-test.js
  lighthouse-core/test/runner-test.js
  lighthouse-core/test/test-utils.js
  tsconfig.json
Labels: land-when-ci-is-green, waiting4reviewer

#14106 core: handle sessions inside target-manager
  lighthouse-core/fraggle-rock/gather/driver.js
  lighthouse-core/fraggle-rock/gather/session.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/driver/network-monitor.js
  lighthouse-core/gather/driver/target-manager.js
  lighthouse-core/test/fraggle-rock/gather/mock-driver.js
  lighthouse-core/test/fraggle-rock/gather/session-test.js
  lighthouse-core/test/gather/driver/target-manager-test.js
  types/gatherer.d.ts
Labels: waiting4reviewer

#14109 i18n: replace placeholder using replacer callback
  lighthouse-core/scripts/i18n/bake-ctc-to-lhl.js
Labels: waiting4reviewer

#14080 core(devtools-log): consolidate implementation into gatherer
  lighthouse-core/gather/devtools-log.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/gatherers/devtools-log.js
  lighthouse-core/test/gather/gatherers/devtools-log-test.js
  tsconfig.json
Labels: waiting4reviewer

#13975 misc: use top-level await
  build/build-bundle.js
  build/build-dt-report-resources.js
  build/build-extension.js
  build/build-lightrider-bundles.js
  build/build-report-components.js
  build/build-report.js
  build/build-sample-reports.js
  build/build-smokehouse-bundle.js
  build/build-treemap.js
  build/build-viewer.js
  lighthouse-cli/index.js
  lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js
  lighthouse-core/scripts/benchmark-plus-extras.js
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/scripts/lantern/collect/collect.js
  lighthouse-core/scripts/lantern/run-once.js
  lighthouse-core/scripts/legacy-javascript/run.js
  lighthouse-core/scripts/update-flow-fixtures.js
  tsconfig-base.json
Labels: waiting4reviewer

#14111 deps: update typescript-eslint for tsc 4.7
  package.json
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer

#14120 core(scripts): narrow to only listen to parsed events
  lighthouse-core/gather/gatherers/scripts.js
Labels: land-when-ci-is-green, waiting4reviewer

#14021 docs(user-flows): refactor document
  assets/flows/navigation.png
  assets/flows/navigation.svg
  assets/flows/snapshot.png
  assets/flows/snapshot.svg
  assets/flows/timespan.png
  assets/flows/timespan.svg
  docs/user-flows.md
Labels: land-when-ci-is-green

#13966 core(user-flow): start/end navigation functions
  docs/user-flows.md
  lighthouse-core/fraggle-rock/user-flow.js
  lighthouse-core/test/fraggle-rock/scenarios/start-end-navigation-test-pptr.js
  lighthouse-core/test/fraggle-rock/user-flow-test.js
Labels: land-when-ci-is-green, waiting4reviewer

#14130 misc: fix broken links in changelog
  build/changelog-generator/templates/header.hbs
  changelog.md
Labels: waiting4reviewer

#14138 tests(smoke): add tests for report-assert.js
  lighthouse-cli/test/smokehouse/__snapshots__/report-assert-test.js.snap
  lighthouse-cli/test/smokehouse/report-assert-test.js
  lighthouse-cli/test/smokehouse/report-assert.js
Labels: waiting4reviewer

#14141 tests(smoke): print multiple differences
  lighthouse-cli/test/smokehouse/__snapshots__/report-assert-test.js.snap
  lighthouse-cli/test/smokehouse/report-assert-test.js
  lighthouse-cli/test/smokehouse/report-assert.js
Labels: waiting4reviewer

#14100 tests(smoke): make oopif-requests assertions more specific
  lighthouse-cli/test/smokehouse/test-definitions/oopif-requests.js
Labels: waiting4reviewer

#14145 misc: only run scheduled publish job if there are new commits
  .github/workflows/publish.yml
Labels: waiting4reviewer

#14140 tests(asset-saver): use .tmp instead of pwd for temp file
  lighthouse-core/test/lib/asset-saver-test.js
Labels: waiting4reviewer

#14148 tests(smoke): disable `oopif-requests`
  .github/workflows/package-test.yml
  .github/workflows/smoke.yml
Labels: land-when-ci-is-green

#14011 core(index): update api helpers to use FR
  lighthouse-cli/bin.js
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/cli/index-test.js
  lighthouse-core/config/config-helpers.js
  lighthouse-core/fraggle-rock/config/config.js
  lighthouse-core/index.js
  lighthouse-core/test/fraggle-rock/config/config-test.js
Labels: land-when-ci-is-green

#13994 tests(fr): snapshot audit id lists in api test
  lighthouse-core/test/fraggle-rock/scenarios/__snapshots__/api-test-pptr.js.snap
  lighthouse-core/test/fraggle-rock/scenarios/api-test-pptr.js
Labels: waiting4reviewer

#14150 tests(smoke): disable `oopif-scripts` in FR
  .github/workflows/package-test.yml
  .github/workflows/smoke.yml
Labels: waiting4reviewer

#14152 core: move network recorder and monitor to EventEmitter
  lighthouse-core/fraggle-rock/gather/session.js
  lighthouse-core/gather/driver/network-monitor.js
  lighthouse-core/gather/driver/target-manager.js
  lighthouse-core/lib/network-recorder.js
  types/protocol.d.ts
Labels: waiting4reviewer

#14024 clients(lr): expose listenForStatus
  clients/devtools/devtools-entry.js
  clients/lightrider/lightrider-entry.js
Labels: land-when-ci-is-green

#14155 core(preload-lcp-image): enrich debugData
  lighthouse-cli/test/smokehouse/test-definitions/perf-trace-elements.js
  lighthouse-core/audits/preload-lcp-image.js
  lighthouse-core/lib/dependency-graph/network-node.js
  lighthouse-core/test/audits/preload-lcp-image-test.js
  lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
Labels: waiting4reviewer

#14156 docs(releasing): dependencies that should always be up to date
  docs/releasing.md
Labels: waiting4reviewer

#12351 core: return result for xhtml, but with warning
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/lib/navigation-error.js
  lighthouse-core/test/lib/navigation-error-test.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: waiting4committer, cla: yes

#13853 core(uses-responsive-images): higher threshold with breakpoints
  lighthouse-core/audits/byte-efficiency/uses-responsive-images.js
  lighthouse-core/test/audits/byte-efficiency/uses-responsive-images-test.js
Labels: waiting4reviewer

#13921 core(plugins): allow `supportedModes` in category
  lighthouse-core/config/config-plugin.js
  lighthouse-core/test/config/__snapshots__/config-plugin-test.js.snap
  lighthouse-core/test/config/config-plugin-test.js
Labels: rls-blocker, waiting4reviewer, 10.0

#14174 misc: include used files in flow-report tsconfig
  flow-report/test/common-test.tsx
  flow-report/test/setup/env-setup.ts
  flow-report/tsconfig.json
Labels: land-when-ci-is-green, waiting4reviewer

#14172 misc: rename eslint config files to .cjs
  .eslintignore
  .eslintrc.cjs
  .npmignore
  CONTRIBUTING.md
  clients/.eslintrc.cjs
  docs/recipes/auth/.eslintrc.cjs
  eslint-local-rules.cjs
  flow-report/.eslintrc.cjs
  report/generator/.eslintrc.cjs
  report/test/generator/.eslintrc.cjs
  tsconfig.json
Labels: land-when-ci-is-green

#14181 clients: convert extension to ES modules
  build/build-extension.js
  clients/extension/scripts/popup.js
  clients/extension/scripts/settings-controller.js
  clients/package.json
  clients/test/extension/popup-test-pptr.js
  clients/test/extension/settings-controller-test.js
  clients/test/lightrider/package.json
Labels: waiting4reviewer

#14173 misc: rename LHError to LighthouseError
  clients/lightrider/lightrider-entry.js
  clients/test/lightrider/lightrider-entry-test.js
  lighthouse-cli/run.js
  lighthouse-core/audits/final-screenshot.js
  lighthouse-core/audits/screenshot-thumbnails.js
  lighthouse-core/audits/work-during-interaction.js
  lighthouse-core/computed/metrics/cumulative-layout-shift.js
  lighthouse-core/computed/metrics/first-meaningful-paint.js
  lighthouse-core/computed/metrics/interactive.js
  lighthouse-core/computed/metrics/lantern-first-meaningful-paint.js
  lighthouse-core/computed/metrics/lantern-largest-contentful-paint.js
  lighthouse-core/computed/metrics/largest-contentful-paint-all-frames.js
  lighthouse-core/computed/metrics/largest-contentful-paint.js
  lighthouse-core/computed/speedline.js
  lighthouse-core/fraggle-rock/gather/session.js
  lighthouse-core/gather/connections/connection.js
  lighthouse-core/gather/driver.js
  lighthouse-core/gather/driver/wait-for-condition.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/lib/asset-saver.js
  lighthouse-core/lib/lh-error.js
  lighthouse-core/lib/lh-trace-processor.js
  lighthouse-core/lib/navigation-error.js
  lighthouse-core/lib/sentry.js
  lighthouse-core/lib/url-shim.js
  lighthouse-core/runner.js
  lighthouse-core/test/gather/gather-runner-test.js
  lighthouse-core/test/lib/asset-saver-test.js
  lighthouse-core/test/runner-test.js
  shared/localization/format.js
  types/global-lh.d.ts
Labels: waiting4reviewer
