Repository GoogleChrome/lighthouse, pull requests merged in 2022-03, with the labels that each got.

#13707 tests(smoke): add _excludes and _runner
  lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js
  lighthouse-cli/test/smokehouse/readme.md
  lighthouse-cli/test/smokehouse/report-assert.js
  lighthouse-cli/test/smokehouse/smokehouse.js
  types/smokehouse.d.ts
Labels: waiting4reviewer

#13695 deps(lodash): replace `lodash` per-method packages with full `lodash`
  lighthouse-cli/test/smokehouse/frontends/lib.js
  lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js
  lighthouse-cli/test/smokehouse/report-assert.js
  lighthouse-core/config/config-helpers.js
  lighthouse-core/fraggle-rock/gather/base-artifacts.js
  lighthouse-core/lib/arbitrary-equality-map.js
  lighthouse-core/runner.js
  package.json
  shared/localization/swap-locale.js
  yarn.lock
Labels: waiting4reviewer

#13624 tests(smoke): enable more devtools smoke tests
  .github/workflows/devtools.yml
Labels: land-when-ci-is-green, waiting4reviewer

#13705 tests: add more cases for oopif smoke test
  lighthouse-cli/test/fixtures/oopif-requests.html
  lighthouse-cli/test/fixtures/oopif-scripts.html
  lighthouse-cli/test/fixtures/oopif-simple-page.html
  lighthouse-cli/test/fixtures/oopif.html
  lighthouse-cli/test/fixtures/simple-script.js
  lighthouse-cli/test/fixtures/simple-worker.js
  lighthouse-cli/test/fixtures/simple-worker.mjs
  lighthouse-cli/test/smokehouse/core-tests.js
  lighthouse-cli/test/smokehouse/test-definitions/oopif-requests.js
  lighthouse-cli/test/smokehouse/test-definitions/oopif-scripts.js
Labels: land-when-ci-is-green, waiting4reviewer

#13623 core(fr): separate audit phase for flows
  lighthouse-core/fraggle-rock/api.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/fraggle-rock/gather/snapshot-runner.js
  lighthouse-core/fraggle-rock/gather/timespan-runner.js
  lighthouse-core/fraggle-rock/user-flow.js
  lighthouse-core/scripts/update-flow-fixtures.js
  lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
  lighthouse-core/test/fraggle-rock/gather/snapshot-runner-test.js
  lighthouse-core/test/fraggle-rock/gather/timespan-runner-test.js
  lighthouse-core/test/fraggle-rock/user-flow-test.js
  types/gatherer.d.ts
Labels: waiting4reviewer

#13716 core(script-treemap-data): correct value for size
  lighthouse-core/audits/script-treemap-data.js
  lighthouse-core/test/audits/__snapshots__/script-treemap-data-test.js.snap
  lighthouse-core/test/audits/script-treemap-data-test.js
  lighthouse-core/test/results/sample_v2.json
Labels: waiting4reviewer

#13717 tests(devtools): add yarn install timeout
  .github/workflows/devtools.yml
Labels: land-when-ci-is-green, waiting4reviewer

#13722 clients: convert devtools and lightrider entries to ES modules
  clients/devtools/devtools-entry.js
  clients/devtools/package.json
  clients/lightrider/lightrider-entry.js
  clients/lightrider/package.json
  clients/test/lightrider/lightrider-entry-test.js
  clients/test/lightrider/package.json
  package.json
Labels: waiting4reviewer

#13720 core(lighthouse-logger): convert to ES modules
  build/build-bundle.js
  lighthouse-logger/index.js
  lighthouse-logger/package.json
Labels: waiting4reviewer

#13643 core(full-page-screenshot): leave emulated width unchanged
  lighthouse-core/gather/gatherers/full-page-screenshot.js
  lighthouse-core/test/gather/gatherers/full-page-screenshot-test.js
Labels: waiting4reviewer

#13625 misc: support --chrome-flags in run devtools script
  .github/workflows/devtools.yml
  lighthouse-cli/test/smokehouse/lighthouse-runners/devtools.js
  lighthouse-core/scripts/pptr-run-devtools.js
Labels: land-when-ci-is-green, waiting4reviewer

#13732 report: fix timespan/snapshot sticky header
  build/build-sample-reports.js
  lighthouse-core/scripts/update-snapshot-sample.js
  lighthouse-core/test/fixtures/fraggle-rock/reports/sample-snapshot-lhr.json
  package.json
  report/assets/templates.html
  report/renderer/components.js
  report/renderer/topbar-features.js
Labels: waiting4reviewer

#13733 v9.5.0
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-navigation-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: waiting4reviewer

#13704 core(scripts): use scriptId as identifier for scripts
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/smokehouse/lighthouse-runners/cli.js
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency.js
  lighthouse-cli/test/smokehouse/test-definitions/oopif-requests.js
  lighthouse-cli/test/smokehouse/test-definitions/oopif-scripts.js
  lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
  lighthouse-core/audits/byte-efficiency/duplicated-javascript.js
  lighthouse-core/audits/byte-efficiency/legacy-javascript.js
  lighthouse-core/audits/byte-efficiency/unminified-javascript.js
  lighthouse-core/audits/byte-efficiency/unused-javascript.js
  lighthouse-core/audits/deprecations.js
  lighthouse-core/audits/dobetterweb/geolocation-on-start.js
  lighthouse-core/audits/dobetterweb/no-document-write.js
  lighthouse-core/audits/dobetterweb/notification-on-start.js
  lighthouse-core/audits/dobetterweb/uses-passive-event-listeners.js
  lighthouse-core/audits/errors-in-console.js
  lighthouse-core/audits/no-unload-listeners.js
  lighthouse-core/audits/script-elements-test-audit.js
  lighthouse-core/audits/script-treemap-data.js
  lighthouse-core/audits/valid-source-maps.js
  lighthouse-core/audits/violation-audit.js
  lighthouse-core/computed/js-bundles.js
  lighthouse-core/computed/module-duplication.js
  lighthouse-core/computed/unused-javascript-summary.js
  lighthouse-core/config/default-config.js
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/gather/gatherers/console-messages.js
  lighthouse-core/gather/gatherers/js-usage.js
  lighthouse-core/gather/gatherers/script-elements.js
  lighthouse-core/gather/gatherers/scripts.js
  lighthouse-core/gather/gatherers/source-maps.js
  lighthouse-core/scripts/legacy-javascript/create-polyfill-size-estimation.js
  lighthouse-core/scripts/legacy-javascript/examine-latest-run.js
  lighthouse-core/scripts/legacy-javascript/run.js
  lighthouse-core/scripts/update-report-fixtures.js
  lighthouse-core/test/audits/__snapshots__/script-treemap-data-test.js.snap
  lighthouse-core/test/audits/byte-efficiency/duplicated-javascript-test.js
  lighthouse-core/test/audits/byte-efficiency/legacy-javascript-test.js
  lighthouse-core/test/audits/byte-efficiency/unminified-javascript-test.js
  lighthouse-core/test/audits/byte-efficiency/unused-javascript-test.js
  lighthouse-core/test/audits/deprecations-test.js
  lighthouse-core/test/audits/dobetterweb/geolocation-on-start-test.js
  lighthouse-core/test/audits/dobetterweb/no-document-write-test.js
  lighthouse-core/test/audits/dobetterweb/notification-on-start-test.js
  lighthouse-core/test/audits/dobetterweb/uses-passive-event-listeners-test.js
  lighthouse-core/test/audits/errors-in-console-test.js
  lighthouse-core/test/audits/no-unload-listeners-test.js
  lighthouse-core/test/audits/script-treemap-data-test.js
  lighthouse-core/test/audits/valid-source-maps-test.js
  lighthouse-core/test/computed/js-bundles-test.js
  lighthouse-core/test/computed/module-duplication-test.js
  lighthouse-core/test/gather/gatherers/js-usage-test.js
  lighthouse-core/test/gather/gatherers/script-elements-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  lighthouse-core/test/test-utils.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
  types/artifacts.d.ts
Labels: waiting4reviewer

#13755 tests(devtools): bump cache
  .github/workflows/devtools.yml
Labels: waiting4reviewer

#13751 core: resolve redirected script records
  .github/workflows/devtools.yml
  lighthouse-cli/test/fixtures/redirects-scripts.html
  lighthouse-cli/test/fixtures/unused-javascript.js
  lighthouse-cli/test/smokehouse/core-tests.js
  lighthouse-cli/test/smokehouse/lighthouse-runners/cli.js
  lighthouse-cli/test/smokehouse/test-definitions/redirects-scripts.js
  lighthouse-core/audits/byte-efficiency/duplicated-javascript.js
  lighthouse-core/audits/byte-efficiency/legacy-javascript.js
  lighthouse-core/audits/byte-efficiency/unminified-javascript.js
  lighthouse-core/audits/byte-efficiency/unused-javascript.js
  lighthouse-core/lib/script-helpers.js
Labels: waiting4reviewer

#13753 core(js-usage): remove debugger domain
  lighthouse-core/gather/gatherers/js-usage.js
  lighthouse-core/test/gather/gatherers/js-usage-test.js
Labels: waiting4reviewer

#13758 tests: clean devtools repo in CI
  lighthouse-core/test/chromium-web-tests/download-devtools.sh
Labels: land-when-ci-is-green, waiting4reviewer

#13558 core: refactor csv output
  report/generator/report-generator.js
  report/test/generator/report-generator-test.js
Labels: waiting4reviewer, 10.0

#13622 core(installable-manifest): always run `InstallabilityErrors` in legacy mode
  .github/workflows/smoke.yml
  lighthouse-cli/test/smokehouse/test-definitions/offline-online-only.js
  lighthouse-cli/test/smokehouse/test-definitions/pwa-chromestatus.js
  lighthouse-core/audits/installable-manifest.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/test/audits/installable-manifest-test.js
  lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: waiting4reviewer

#13782 tests: upgrade devtools web tests deps, use python3
  .github/workflows/devtools.yml
  lighthouse-core/test/chromium-web-tests/README.md
  lighthouse-core/test/chromium-web-tests/blink-tools.patch
  lighthouse-core/test/chromium-web-tests/download-blink-tools.sh
  lighthouse-core/test/chromium-web-tests/web-test-server.sh
Labels: land-when-ci-is-green, waiting4reviewer

#13746 core(legacy-javascript): key on script id, not url
  lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js
  lighthouse-core/audits/byte-efficiency/duplicated-javascript.js
  lighthouse-core/audits/byte-efficiency/legacy-javascript.js
  lighthouse-core/audits/byte-efficiency/render-blocking-resources.js
Labels: land-when-ci-is-green, waiting4reviewer

#13792 tests: increase smoke shards from 2 to 3
  .github/workflows/devtools.yml
  .github/workflows/smoke.yml
Labels: waiting4reviewer

#13790 core(network-monitor): resolve server redirects
  lighthouse-core/gather/driver/network-monitor.js
  lighthouse-core/test/fixtures/fraggle-rock/navigation-basic/links-to-index.html
  lighthouse-core/test/fraggle-rock/scenarios/api-test-pptr.js
  lighthouse-core/test/gather/driver/network-monitor-test.js
Labels: waiting4reviewer

#13791 report: avoid really slow regexes for data urls
  lighthouse-core/util-commonjs.js
  report/renderer/util.js
Labels: waiting4reviewer

#13771 core(preload-lcp-image): be specific about when to do this
  lighthouse-core/audits/preload-lcp-image.js
  lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  lighthouse-core/test/results/sample_v2.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: waiting4reviewer
