Repository GoogleChrome/lighthouse, pull requests merged in 2022-12, with the labels that each got.

#14571 core(lantern): add network timings to debug traces
  core/lib/dependency-graph/simulator/simulator-timing-map.js
  core/lib/dependency-graph/simulator/simulator.js
  core/lib/dependency-graph/simulator/tcp-connection.js
  core/lib/lantern-trace-saver.js
  core/test/lib/dependency-graph/simulator/tcp-connection-test.js
Labels: land-when-ci-is-green, waiting4reviewer

#14546 deps: upgrade third-party-web to 0.20.2
  package.json
  yarn.lock
Labels: waiting4reviewer

#14577 tests(devtools): sync e2e
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
  third-party/devtools-tests/e2e/lighthouse/snapshot_test.ts
  third-party/devtools-tests/e2e/lighthouse/timespan_test.ts
Labels: land-when-ci-is-green, waiting4reviewer

#14580 tests(ci): force color output in CI
  .github/workflows/ci.yml
  .github/workflows/devtools.yml
  .github/workflows/package-test.yml
  .github/workflows/smoke.yml
  .github/workflows/unit.yml
Labels: land-when-ci-is-green, waiting4reviewer

#14582 clients(lr): expose computeBenchmarkIndex
  clients/lightrider/lightrider-entry.js
Labels: waiting4reviewer

#14338 docs(readme): drop dead and unmaintained services/projects
  readme.md
Labels: land-when-ci-is-green, waiting4reviewer

#14593 docs(changelog): add 9.6.x release notes
  changelog.md
Labels: land-when-ci-is-green

#14588 misc: update vercel deployment config
  now.json
  vercel.json
Labels: waiting4reviewer

#14589 core: internalize resolved configs
  core/index.js
Labels: waiting4reviewer

#14587 report: fix wording when screenEmulation disabled
  core/util.cjs
  flow-report/test/sidebar/sidebar-test.tsx
  report/renderer/util.js
  report/test/renderer/util-test.js
Labels: land-when-ci-is-green, waiting4reviewer

#14590 core: remove trace-of-tab references
  core/computed/metrics/timing-summary.js
  core/lib/tracehouse/trace-processor.js
  core/test/computed/metrics/timing-summary-test.js
  core/test/lib/tracehouse/trace-processor-test.js
Labels: waiting4reviewer

#14604 docs: update user-flow.md to reflect current release
  docs/user-flows.md
Labels: waiting4reviewer

#14606 deps: update to latest chrome-devtools-frontend
  core/lib/bfcache-strings.js
  core/lib/cdt/generated/SourceMap.js
  core/lib/deprecations-strings.js
  package.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer

#13071 tests: add computed/metrics/interactive-test.js to tsconfig
  core/test/computed/metrics/interactive-test.js
  core/test/test-utils.js
  tsconfig.json
Labels: cla: yes, waiting4reviewer

#14608 core(use-landmarks): fix missing markdown in description
  core/audits/accessibility/manual/use-landmarks.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
Labels: waiting4reviewer

#14576 core(doctype): check for limited quirks mode
  core/audits/dobetterweb/doctype.js
  core/test/audits/dobetterweb/doctype-test.js
  core/test/results/artifacts/artifacts.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: land-when-ci-is-green, waiting4reviewer

#14595 tests: rewrite fake timer usage to reduce isolation
  core/test/gather/driver/execution-context-test.js
  core/test/gather/driver/navigation-test.js
  core/test/gather/driver/prepare-test.js
  core/test/gather/driver/service-workers-test.js
  core/test/gather/driver/wait-for-condition-test.js
  core/test/gather/gatherers/css-usage-test.js
  core/test/gather/gatherers/image-elements-test.js
  core/test/gather/gatherers/inspector-issues-test.js
  core/test/gather/gatherers/js-usage-test.js
  core/test/gather/gatherers/main-document-content-test.js
  core/test/gather/gatherers/source-maps-test.js
  core/test/gather/gatherers/trace-elements-test.js
  core/test/gather/gatherers/trace-test.js
  core/test/gather/session-test.js
  core/test/legacy/gather/driver-test.js
  core/test/scripts/run-mocha-tests.js
  core/test/test-env/mocha-setup.js
  flow-report/test/common-test.tsx
Labels: land-when-ci-is-green, waiting4reviewer

#13952 core(js-usage): ignore __puppeteer_evaluation_script__
  core/gather/gatherers/js-usage.js
Labels: land-when-ci-is-green, waiting4reviewer
