Repository GoogleChrome/lighthouse, pull requests merged in 2022-01, with the labels that each got.

#13537 misc: add web.dev and other option to bug template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: land-when-ci-is-green

#13538 deps: update transitive deps to quiet vulnerability alerts
  package.json
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer

#13456 tests: run most smoke tests on devtools
  .github/workflows/devtools.yml
  .gitignore
  clients/devtools-entry.js
  lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js
  lighthouse-cli/test/smokehouse/lighthouse-runners/devtools.js
  lighthouse-cli/test/smokehouse/readme.md
  lighthouse-core/scripts/download-chrome.sh
  lighthouse-core/scripts/pptr-run-devtools.js
  lighthouse-core/test/chromium-web-tests/roll-devtools.sh
Labels: cla: yes, waiting4reviewer

#13540 tests: more targeted caching for devtools build
  .github/scripts/generate-devtools-hash.sh
  .github/workflows/devtools.yml
Labels: land-when-ci-is-green, waiting4reviewer

#13545 clients: use minimal 'url' polyfil instead of url-shim
  build/build-bundle.js
  package.json
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer

#13519 core(runner): asset manager helper
  lighthouse-cli/run.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/fraggle-rock/gather/snapshot-runner.js
  lighthouse-core/fraggle-rock/gather/timespan-runner.js
  lighthouse-core/index.js
  lighthouse-core/lib/url-shim.js
  lighthouse-core/runner.js
  lighthouse-core/test/fraggle-rock/gather/mock-driver.js
  lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
  lighthouse-core/test/fraggle-rock/gather/snapshot-runner-test.js
  lighthouse-core/test/fraggle-rock/gather/timespan-runner-test.js
  lighthouse-core/test/lib/url-shim-test.js
  lighthouse-core/test/runner-test.js
Labels: waiting4reviewer

#13546 tests: split devtools ci into build, web-tests and smoke jobs
  .github/workflows/devtools.yml
  lighthouse-core/test/chromium-web-tests/download-devtools.sh
  lighthouse-core/test/chromium-web-tests/run-web-tests.sh
  lighthouse-core/test/chromium-web-tests/test-locally.sh
Labels: waiting4reviewer

#13549 tests: dedupe some CI job names
  .github/workflows/devtools.yml
  .github/workflows/smoke.yml
  .github/workflows/unit.yml
Labels: waiting4reviewer

#13459 misc(build): set correct exit code when build scripts fail
  build/build-bundle.js
  build/build-dt-report-resources.js
  build/build-extension.js
  build/build-lightrider-bundles.js
  build/build-report-components.js
  build/build-report.js
  build/build-smokehouse-bundle.js
  build/build-viewer.js
  lighthouse-cli/test/smokehouse/smokehouse.js
  package.json
  yarn.lock
Labels: cla: yes, waiting4reviewer

#13462 core(inspector-issues): collect all issue types
  lighthouse-cli/test/smokehouse/test-definitions/csp-allow-all.js
  lighthouse-cli/test/smokehouse/test-definitions/csp-block-all.js
  lighthouse-cli/test/smokehouse/test-definitions/issues-mixed-content.js
  lighthouse-core/audits/deprecations.js
  lighthouse-core/audits/dobetterweb/inspector-issues.js
  lighthouse-core/audits/is-on-https.js
  lighthouse-core/gather/gatherers/inspector-issues.js
  lighthouse-core/test/audits/deprecations-test.js
  lighthouse-core/test/audits/dobetterweb/inspector-issues-test.js
  lighthouse-core/test/audits/is-on-https-test.js
  lighthouse-core/test/gather/gatherers/inspector-issues-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/artifacts/defaultPass.devtoolslog.json
  lighthouse-core/test/results/artifacts/offlinePass.devtoolslog.json
  lighthouse-core/test/results/artifacts/redirectPass.devtoolslog.json
  package.json
  types/artifacts.d.ts
  yarn.lock
Labels: cla: yes, waiting4reviewer

#13554 deps: update robots-parser to latest
  build/build-bundle.js
  lighthouse-core/audits/seo/is-crawlable.js
  package.json
  types/robots-parser/index.d.ts
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer

#13559 core: ensure good and average scores start exactly at control points
  lighthouse-core/audits/audit.js
  lighthouse-core/test/audits/audit-test.js
  lighthouse-core/test/audits/mainthread-work-breakdown-test.js
  lighthouse-core/test/audits/metrics/first-contentful-paint-test.js
  lighthouse-core/test/results/sample_v2.json
  report/test/generator/report-generator-test.js
Labels: waiting4reviewer

#13566 cli(asset-saver): end devtoolsLog with a newline
  lighthouse-core/lib/asset-saver.js
  lighthouse-core/scripts/update-report-fixtures.js
  lighthouse-core/test/lib/asset-saver-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/artifacts/defaultPass.devtoolslog.json
  lighthouse-core/test/results/artifacts/offlinePass.devtoolslog.json
  lighthouse-core/test/results/artifacts/redirectPass.devtoolslog.json
Labels: waiting4reviewer

#13579 tests(devtools): ensure WebSQL table is populated
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-clear-data-warning.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/resources/lighthouse-storage.html
Labels: waiting4reviewer

#13595 core(inspector-issue): remove wasmCrossOriginModuleSharingIssue
  lighthouse-core/gather/gatherers/inspector-issues.js
  lighthouse-core/test/audits/dobetterweb/inspector-issues-test.js
  lighthouse-core/test/gather/gatherers/inspector-issues-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  package.json
  third-party/chromium-synchronization/inspector-issueAdded-types-test.js
  types/artifacts.d.ts
  yarn.lock
Labels: waiting4reviewer

#13504 docs: update devtools panel throttling details
  docs/throttling.md
Labels: land-when-ci-is-green, waiting4reviewer

#13593 clients(devtools): add FR runners to DevTools entry
  clients/devtools-entry.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: land-when-ci-is-green, waiting4reviewer

#13596 tests: add snapshot tests for cli-flags.js
  lighthouse-cli/test/cli/__snapshots__/cli-flags-test.js.snap
  lighthouse-cli/test/cli/cli-flags-test.js
Labels: waiting4reviewer

#13588 cli: remove update-notifier
  lighthouse-cli/bin.js
  lighthouse-cli/test/cli/bin-test.js
  package.json
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer

#13590 deps(yargs): upgrade to 17.3.1
  lighthouse-cli/cli-flags.js
  lighthouse-cli/test/cli/__snapshots__/cli-flags-test.js.snap
  lighthouse-cli/test/cli/cli-flags-test.js
  lighthouse-cli/test/fixtures/cli-flags-path-inline-budgets.json
  lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js
  lighthouse-core/runner.js
  lighthouse-core/scripts/compare-runs.js
  lighthouse-core/scripts/pptr-run-devtools.js
  package.json
  yarn.lock
Labels: waiting4reviewer

#13597 deps(yargs-parser): upgrade to 21.0.0
  package.json
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer

#13599 core(preload-lcp-image): enable audit
  lighthouse-core/audits/preload-fonts.js
  lighthouse-core/audits/preload-lcp-image.js
  lighthouse-core/audits/uses-rel-preload.js
  lighthouse-core/test/audits/preload-lcp-image-test.js
  lighthouse-core/test/results/sample_v2.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: waiting4reviewer

#13601 misc(build): remove empty devtools report resources
  build/build-dt-report-resources.js
Labels: waiting4reviewer

#13603 core(inspector-issues): add federatedAuthRequestIssue
  lighthouse-core/gather/gatherers/inspector-issues.js
  lighthouse-core/test/audits/dobetterweb/inspector-issues-test.js
  lighthouse-core/test/gather/gatherers/inspector-issues-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  package.json
  third-party/chromium-synchronization/inspector-issueAdded-types-test.js
  types/artifacts.d.ts
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer

#13602 i18n: import
  shared/localization/locales/ar-XB.json
  shared/localization/locales/ar.json
  shared/localization/locales/bg.json
  shared/localization/locales/ca.json
  shared/localization/locales/cs.json
  shared/localization/locales/da.json
  shared/localization/locales/de.json
  shared/localization/locales/el.json
  shared/localization/locales/en-GB.json
  shared/localization/locales/en-XA.json
  shared/localization/locales/es-419.json
  shared/localization/locales/es.json
  shared/localization/locales/fi.json
  shared/localization/locales/fil.json
  shared/localization/locales/fr.json
  shared/localization/locales/he.json
  shared/localization/locales/hi.json
  shared/localization/locales/hr.json
  shared/localization/locales/hu.json
  shared/localization/locales/id.json
  shared/localization/locales/it.json
  shared/localization/locales/ja.json
  shared/localization/locales/ko.json
  shared/localization/locales/lt.json
  shared/localization/locales/lv.json
  shared/localization/locales/nl.json
  shared/localization/locales/no.json
  shared/localization/locales/pl.json
  shared/localization/locales/pt-PT.json
  shared/localization/locales/pt.json
  shared/localization/locales/ro.json
  shared/localization/locales/ru.json
  shared/localization/locales/sk.json
  shared/localization/locales/sl.json
  shared/localization/locales/sr-Latn.json
  shared/localization/locales/sr.json
  shared/localization/locales/sv.json
  shared/localization/locales/ta.json
  shared/localization/locales/te.json
  shared/localization/locales/th.json
  shared/localization/locales/tr.json
  shared/localization/locales/uk.json
  shared/localization/locales/vi.json
  shared/localization/locales/zh-HK.json
  shared/localization/locales/zh-TW.json
  shared/localization/locales/zh.json
Labels: waiting4reviewer

#13604 deps(lighthouse-stack-packs): upgrade to 1.7.0
  lighthouse-core/lib/stack-packs.js
  lighthouse-core/test/lib/stack-packs-test.js
  lighthouse-core/test/results/sample_v2.json
  package.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  yarn.lock
Labels: waiting4reviewer

#13605 v9.3.0
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: waiting4reviewer

#13610 report: disable fireworks with flag
  report/renderer/report-ui-features.js
Labels: waiting4reviewer

#13611 v9.3.1
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: waiting4reviewer
