Repository GoogleChrome/lighthouse, pull requests merged in 2022-11, with the labels that each got.

#14479 core(dom-size): display metric values as integers
  cli/test/smokehouse/test-definitions/dobetterweb.js
  core/audits/dobetterweb/dom-size.js
  core/test/audits/dobetterweb/dom-size-test.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
Labels: waiting4reviewer

#14497 report: use `focus-visible` for the three-dot menu
  report/assets/styles.css
  report/renderer/components.js
Labels: waiting4reviewer

#14490 core(csp-xss): prevent meta warning if header CSPs are secure
  core/audits/csp-xss.js
  core/test/audits/csp-xss-test.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: land-when-ci-is-green, waiting4reviewer

#14499 core(fps): limit height at max webp size
  cli/test/fixtures/max-texture-size.html
  cli/test/smokehouse/core-tests.js
  cli/test/smokehouse/test-definitions/fps-max.js
  core/gather/gatherers/full-page-screenshot.js
  core/lib/page-functions.js
  core/test/gather/gatherers/full-page-screenshot-test.js
Labels: land-when-ci-is-green, waiting4reviewer

#14531 core: merge `api.js` into `index.js`, new report generator api
  clients/devtools/devtools-entry.js
  core/api.js
  core/index.js
  core/scripts/update-flow-fixtures.js
  core/test/scenarios/api-test-pptr.js
  core/test/scenarios/cross-origin-test-pptr.js
  core/test/scenarios/disconnect-test-pptr.js
  core/test/scenarios/start-end-navigation-test-pptr.js
  report/generator/report-generator.js
  report/test/generator/report-generator-test.js
Labels: waiting4reviewer

#14534 tests: fix node version in weekly cron
  .github/workflows/cron-weekly.yml
Labels: land-when-ci-is-green, waiting4reviewer

#14533 docs(user-flows): use new api location
  docs/user-flows.md
Labels: waiting4reviewer

#14468 tests: dynamically import all modules when using mocks
  core/test/gather/driver/navigation-test.js
  core/test/gather/driver/prepare-test.js
  core/test/gather/gatherers/dobetterweb/response-compression-test.js
  core/test/gather/gatherers/link-elements-test.js
  core/test/gather/gatherers/script-elements-test.js
  core/test/gather/gatherers/service-worker-test.js
  core/test/gather/navigation-runner-test.js
  core/test/gather/snapshot-runner-test.js
  core/test/gather/timespan-runner-test.js
  core/test/legacy/gather/gather-runner-test.js
  core/test/runner-test.js
  core/test/user-flow-test.js
  docs/hacking-tips.md
Labels: land-when-ci-is-green, waiting4reviewer

#14536 misc(build): remove non-functional package.json shim
  build/build-bundle.js
Labels: land-when-ci-is-green, waiting4reviewer

#14537 core: remove globals from `externs.d.ts`
  cli/cli-flags.js
  cli/printer.js
  cli/test/smokehouse/frontends/smokehouse-bin.js
  core/audits/byte-efficiency/render-blocking-resources.js
  core/audits/metrics/first-contentful-paint-3g.js
  core/audits/performance-budget.js
  core/audits/timing-budget.js
  core/computed/computed-artifact.js
  core/computed/load-simulator.js
  core/computed/metrics/responsiveness.js
  core/computed/metrics/timing-summary.js
  core/computed/network-analysis.js
  core/computed/resource-summary.js
  core/config/budget.js
  core/config/config-helpers.js
  core/gather/gatherers/full-page-screenshot.js
  core/lib/lantern-trace-saver.js
  core/lib/network-request.js
  core/scripts/compare-runs.js
  core/test/gather/mock-commands.js
  core/test/scripts/run-mocha-tests.js
  core/test/test-utils.js
  types/artifacts.d.ts
  types/audit.d.ts
  types/externs.d.ts
  types/global-lh.d.ts
  types/node.d.ts
  types/utility-types.d.ts
Labels: waiting4reviewer

#14541 tests(dbw): ignore `webkitStorageInfo` deprecation in m110
  cli/test/smokehouse/test-definitions/dobetterweb.js
Labels: waiting4reviewer

#14544 tests(devtools): sync e2e
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
Labels: land-when-ci-is-green, waiting4reviewer

#14543 core: expose default and desktop configs on `index.js`
  core/index.js
Labels: waiting4reviewer

#14515 report: screen emulation and dpr in meta tooltip
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  core/util.cjs
  flow-report/src/sidebar/sidebar.tsx
  flow-report/test/sidebar/sidebar-test.tsx
  proto/lighthouse-result.proto
  report/renderer/report-renderer.js
  report/renderer/util.js
  report/test/renderer/report-renderer-test.js
  report/test/renderer/util-test.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: waiting4reviewer

#14557 tests: upgrade protobuf test to use python 3
  .github/workflows/unit.yml
  package.json
Labels: waiting4reviewer

#14556 core: use LCP specific message for NO_LCP
  core/lib/lh-error.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: land-when-ci-is-green, waiting4reviewer

#14558 docs(proto): update protobuf installation guidance
  proto/README.md
Labels: waiting4reviewer

#14563 docs(readme): update devtools screenshot, better alt
  readme.md
Labels: land-when-ci-is-green, waiting4reviewer

#14564 core(lantern): divide throughput only on network node count
  core/lib/dependency-graph/simulator/simulator.js
  core/test/audits/__snapshots__/metrics-test.js.snap
  core/test/audits/__snapshots__/predictive-perf-test.js.snap
  core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
  core/test/audits/dobetterweb/uses-http2-test.js
  core/test/audits/metrics/__snapshots__/first-meaningful-paint-test.js.snap
  core/test/audits/predictive-perf-test.js
  core/test/computed/metrics/__snapshots__/first-meaningful-paint-test.js.snap
  core/test/computed/metrics/__snapshots__/interactive-test.js.snap
  core/test/computed/metrics/__snapshots__/lantern-first-meaningful-paint-test.js.snap
  core/test/computed/metrics/__snapshots__/lantern-interactive-test.js.snap
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/fixtures/lantern-baseline-accuracy.json
  core/test/fixtures/lantern-baseline-computed-values.json
Labels: land-when-ci-is-green, waiting4reviewer

#14202 tests: fix mocha test runner and mocks on windows
  .github/workflows/unit.yml
  build/test/plugins/inline-fs-test.js
  cli/test/cli/bin-test.js
  core/config/config-helpers.js
  core/test/gather/mock-driver.js
  core/test/test-utils.js
  package.json
  yarn.lock
Labels: waiting4reviewer

#13501 core(font-size): use order from protocol as implicit specificity
  core/gather/gatherers/seo/font-size.js
  core/test/gather/gatherers/seo/font-size-test.js
Labels: land-when-ci-is-green, waiting4reviewer, 10.0

#14567 core(network-request): use ms instead of seconds
  core/audits/byte-efficiency/offscreen-images.js
  core/audits/byte-efficiency/render-blocking-resources.js
  core/audits/critical-request-chains.js
  core/audits/font-display.js
  core/audits/network-requests.js
  core/audits/redirects.js
  core/audits/uses-rel-preconnect.js
  core/lib/dependency-graph/network-node.js
  core/lib/dependency-graph/simulator/network-analyzer.js
  core/lib/network-request.js
  core/test/audits/byte-efficiency/offscreen-images-test.js
  core/test/audits/critical-request-chains-test.js
  core/test/audits/font-display-test.js
  core/test/audits/network-requests-test.js
  core/test/audits/redirects-test.js
  core/test/audits/uses-rel-preconnect-test.js
  core/test/audits/uses-rel-preload-test.js
  core/test/computed/metrics/lantern-first-contentful-paint-test.js
  core/test/computed/page-dependency-graph-test.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/lib/dependency-graph/simulator/network-analyzer-test.js
  core/test/lib/network-request-test.js
  core/test/network-records-to-devtools-log.js
  core/test/results/sample_v2.json
Labels: waiting4reviewer

#14538 misc(build): remove lighthouse shim no longer necessary for plugins
  build/build-bundle.js
Labels: land-when-ci-is-green, waiting4reviewer

#14425 clients(lr): export primary api, presets from lr bundle
  clients/lightrider/lightrider-entry.js
Labels: land-when-ci-is-green

#14493 report: reuse numberFormatters for ~50% performance gains
  report/renderer/i18n.js
Labels: waiting4reviewer

#14492 misc: change default build folder for devtools gn
  cli/test/smokehouse/lighthouse-runners/devtools.js
  core/scripts/build-devtools.sh
  core/scripts/open-devtools.sh
  core/scripts/pptr-run-devtools.js
  core/test/devtools-tests/download-devtools.sh
  core/test/devtools-tests/roll-devtools.sh
  core/test/devtools-tests/setup.sh
Labels: waiting4reviewer

#14485 core: add `BFCacheFailures` artifact
  core/config/default-config.js
  core/gather/driver.js
  core/gather/driver/target-manager.js
  core/gather/gatherers/bf-cache-failures.js
  core/legacy/config/legacy-default-config.js
  core/test/gather/gatherers/bf-cache-failures-test.js
  types/artifacts.d.ts
Labels: waiting4reviewer

#14568 core(lantern): add comment to about node times being in microseconds
  core/lib/dependency-graph/base-node.js
  core/lib/dependency-graph/network-node.js
Labels: land-when-ci-is-green

#14353 misc: remove some unwanted TODOs
  core/config/config-helpers.js
  core/gather/base-gatherer.js
  core/lib/asset-saver.js
  core/runner.js
  core/scripts/lantern/constants.js
  core/test/legacy/config/config-test.js
  core/test/legacy/gather/fake-driver.js
Labels: land-when-ci-is-green, waiting4reviewer
