Repository GoogleChrome/lighthouse, pull requests merged in 2022-08, with the labels that each got.

#14252 core: use trace time origin for main-thread-task time origin
  core/computed/main-thread-tasks.js
  core/lib/tracehouse/main-thread-tasks.js
  core/test/computed/main-thread-tasks-test.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/lib/tracehouse/main-thread-tasks-test.js
  core/test/results/sample_v2.json
Labels: land-when-ci-is-green

#14244 deps(puppeteer): upgrade to 16.1.0
  core/scripts/benchmark-plus-extras.js
  package.json
  viewer/test/viewer-test-pptr.js
  yarn.lock
Labels: waiting4reviewer

#14146 core(replay): @puppeteer/replay stringify extension
  .github/workflows/unit.yml
  cli/test/fixtures/flow/index.html
  cli/test/fixtures/flow/next.html
  core/fraggle-rock/replay/stringify-extension.js
  core/test/fixtures/fraggle-rock/replay/desktop-test-flow.json
  core/test/fixtures/fraggle-rock/replay/mobile-test-flow.json
  core/test/fraggle-rock/replay/__snapshots__/stringify-extension-test.js.snap
  core/test/fraggle-rock/replay/stringify-extension-test.js
  core/test/fraggle-rock/scenarios/__snapshots__/stringified-replay-test-pptr.js.snap
  core/test/fraggle-rock/scenarios/pptr-test-utils.js
  core/test/fraggle-rock/scenarios/stringified-replay-test-pptr.js
  package.json
  yarn.lock
Labels: waiting4reviewer

#14297 core(replay): fix stringify extension
  core/fraggle-rock/replay/stringify-extension.js
  core/test/fraggle-rock/replay/__snapshots__/stringify-extension-test.js.snap
  core/test/fraggle-rock/scenarios/__snapshots__/stringified-replay-test-pptr.js.snap
Labels: land-when-ci-is-green

#14289 tests(smoke): remove external domains from perf-preload
  cli/test/fixtures/perf/preload_style_ranchers.css
  cli/test/fixtures/perf/preload_tester.js
  cli/test/fixtures/perf/ranchers.woff2
  cli/test/fixtures/preload.html
  cli/test/fixtures/static-server-test.js
  cli/test/fixtures/static-server.js
  cli/test/smokehouse/frontends/smokehouse-bin.js
  cli/test/smokehouse/test-definitions/perf-preload.js
  core/scripts/update-report-fixtures.js
  core/test/fraggle-rock/scenarios/pptr-test-utils.js
  treemap/test/treemap-test-pptr.js
  viewer/test/viewer-test-pptr.js
Labels: land-when-ci-is-green

#14227 misc: document where network timings come from
  core/lib/network-request.js
  docs/Network-Timings.svg
Labels: land-when-ci-is-green, waiting4reviewer

#14308 misc: use a unique local port for the treemap
  docs/releasing.md
  package.json
  report/renderer/open-tab.js
  treemap/README.md
  viewer/README.md
Labels: waiting4reviewer

#13901 clients(lr): add FR navigation support
  clients/lightrider/lightrider-entry.js
Labels: waiting4reviewer, 10.0

#14278 docs(budgets): add example using config
  docs/performance-budgets.md
Labels: waiting4reviewer

#14307 tests: static-server can continue if already running
  cli/test/fixtures/static-server.js
Labels: land-when-ci-is-green, waiting4reviewer

#13976 docs(readme): add Auditzy and Lighthouse Metrics to services list
  readme.md
Labels: land-when-ci-is-green, waiting4reviewer

#14320 tests(smoke): check lhr.environment exists in version check
  cli/test/smokehouse/report-assert.js
Labels: waiting4reviewer

#14321 docs(config): update to reflect changes in FR
  core/config/default-config.js
  docs/configuration.md
Labels: land-when-ci-is-green, waiting4reviewer

#14323 docs(config): revert #14321
  core/config/default-config.js
  docs/configuration.md
Labels: land-when-ci-is-green, waiting4reviewer

#14325 clients(psi): expose hasLocale in bundle types
  build/build-report.js
  report/test-assets/faux-psi-template.html
  report/test-assets/faux-psi.js
  shared/localization/format.js
Labels: land-when-ci-is-green, waiting4reviewer

#14329 report: prevent breaking words in opportunity text
  report/assets/styles.css
  report/renderer/components.js
Labels: land-when-ci-is-green, waiting4reviewer
