Repository GoogleChrome/lighthouse, pull requests merged in 2022-04, with the labels that each got.

#13804 deps: update to third-party-web 0.15.0
  lighthouse-core/test/audits/third-party-summary-test.js
  lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  package.json
  yarn.lock
Labels: waiting4reviewer

#13814 deps(axe-core): upgrade to 4.4.1
  package.json
  report/test/renderer/__snapshots__/report-renderer-axe-test.js.snap
  yarn.lock
Labels: waiting4reviewer

#13793 core: use `mainDocumentUrl` instead of `finalUrl`
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency.js
  lighthouse-core/audits/byte-efficiency/render-blocking-resources.js
  lighthouse-core/audits/byte-efficiency/unminified-css.js
  lighthouse-core/audits/byte-efficiency/unminified-javascript.js
  lighthouse-core/audits/byte-efficiency/unused-css-rules.js
  lighthouse-core/audits/script-treemap-data.js
  lighthouse-core/audits/seo/link-text.js
  lighthouse-core/audits/service-worker.js
  lighthouse-core/computed/main-resource.js
  lighthouse-core/computed/resource-summary.js
  lighthouse-core/computed/unused-css.js
  lighthouse-core/config/budget.js
  lighthouse-core/lib/script-helpers.js
  lighthouse-core/test/audits/byte-efficiency/unminified-javascript-test.js
  lighthouse-core/test/audits/diagnostics-test.js
  lighthouse-core/test/audits/dobetterweb/charset-test.js
  lighthouse-core/test/audits/performance-budget-test.js
  lighthouse-core/test/audits/resource-summary-test.js
  lighthouse-core/test/audits/seo/canonical-test.js
  lighthouse-core/test/audits/seo/http-status-code-test.js
  lighthouse-core/test/audits/seo/is-crawlable-test.js
  lighthouse-core/test/audits/server-response-time-test.js
  lighthouse-core/test/audits/service-worker-test.js
  lighthouse-core/test/audits/third-party-facades-test.js
  lighthouse-core/test/computed/main-resource-test.js
  lighthouse-core/test/computed/resource-summary-test.js
  lighthouse-core/test/computed/unused-css-test.js
  lighthouse-core/test/fraggle-rock/gather/mock-driver.js
Labels: waiting4reviewer

#13816 core: make `requestedUrl` optional
  lighthouse-core/computed/page-dependency-graph.js
  lighthouse-core/fraggle-rock/gather/base-artifacts.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/fraggle-rock/gather/snapshot-runner.js
  lighthouse-core/fraggle-rock/gather/timespan-runner.js
  lighthouse-core/runner.js
  lighthouse-core/scripts/compare-runs.js
  lighthouse-core/test/fraggle-rock/gather/base-artifacts-test.js
  lighthouse-core/test/fraggle-rock/gather/mock-driver.js
  lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
  lighthouse-core/test/fraggle-rock/gather/snapshot-runner-test.js
  lighthouse-core/test/fraggle-rock/gather/timespan-runner-test.js
  lighthouse-core/test/fraggle-rock/scenarios/api-test-pptr.js
  lighthouse-core/test/fraggle-rock/user-flow-test.js
  report/generator/report-generator.js
  report/renderer/open-tab.js
  treemap/app/debug.json
  treemap/app/src/main.js
  treemap/test/treemap-test-pptr.js
  types/artifacts.d.ts
  types/lhr/lhr.d.ts
  types/lhr/treemap.d.ts
Labels: waiting4reviewer

#13826 docs(user-flows): update api usage
  docs/user-flows.md
Labels: waiting4reviewer

#13838 misc: add brendan back to triage rotation
  .github/workflows/issue-assigner.yml
Labels: land-when-ci-is-green, waiting4reviewer

#13846 core(installability-errors): add url scheme error
  lighthouse-core/audits/installable-manifest.js
  lighthouse-core/test/audits/installable-manifest-test.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  third-party/chromium-synchronization/installability-errors-test.js
Labels: land-when-ci-is-green, waiting4reviewer

#13848 core(trace-processor): ignore `navigationStart` with falsy document url
  lighthouse-core/lib/tracehouse/trace-processor.js
  lighthouse-core/test/create-test-trace.js
Labels: land-when-ci-is-green, waiting4reviewer

#13844 tests: fix smoke shard total in CI
  .github/workflows/devtools.yml
  .github/workflows/smoke.yml
Labels: land-when-ci-is-green, waiting4reviewer

#13841 tests: fix invalid artifact name for devtools smoke failures
  .github/workflows/devtools.yml
Labels: land-when-ci-is-green, waiting4reviewer

#13783 core(fr): make FR navigations the default in node
  .github/workflows/ci.yml
  .github/workflows/package-test.yml
  .github/workflows/smoke.yml
  .github/workflows/unit.yml
  build/build-bundle.js
  clients/devtools/devtools-entry.js
  clients/lightrider/lightrider-entry.js
  clients/test/extension/popup-test-pptr.js
  docs/recipes/custom-gatherer-puppeteer/custom-gatherer.js
  lighthouse-cli/run.js
  lighthouse-cli/test/smokehouse/lighthouse-runners/bundle.js
  lighthouse-cli/test/smokehouse/report-assert.js
  lighthouse-cli/test/smokehouse/smokehouse.js
  lighthouse-core/fraggle-rock/api.js
  lighthouse-core/fraggle-rock/gather/driver.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/fraggle-rock/gather/session.js
  lighthouse-core/fraggle-rock/gather/snapshot-runner.js
  lighthouse-core/fraggle-rock/gather/timespan-runner.js
  lighthouse-core/index.js
  lighthouse-core/scripts/benchmark-plus-extras.js
  lighthouse-core/scripts/pptr-run-devtools.js
  lighthouse-core/scripts/release/package-test.sh
  lighthouse-core/scripts/update-flow-fixtures.js
  lighthouse-core/scripts/update-snapshot-sample.js
  lighthouse-core/test/fraggle-rock/gather/driver-test.js
  lighthouse-core/test/fraggle-rock/gather/mock-driver.js
  lighthouse-core/test/fraggle-rock/gather/session-test.js
  lighthouse-core/test/fraggle-rock/gather/snapshot-runner-test.js
  lighthouse-core/test/fraggle-rock/gather/timespan-runner-test.js
  lighthouse-core/test/fraggle-rock/scenarios/pptr-test-utils.js
  lighthouse-core/test/index-test.js
  package.json
  types/global-lh.d.ts
  yarn.lock
Labels: waiting4reviewer

#13859 tests: temporarily disable oopif-scripts smoke for devtools
  .github/workflows/devtools.yml
Labels: land-when-ci-is-green

#13855 tests: fix flaky isPositionFixed check in oopif-scripts
  lighthouse-cli/test/fixtures/oopif-scripts.html
Labels: land-when-ci-is-green, waiting4reviewer

#13864 report: remove eslint --fix step in report generation
  build/build-report-components.js
  package.json
  report/renderer/components.js
Labels: waiting4reviewer

#13862 deps(lighthouse-stack-packs): upgrade to 1.8.1
  lighthouse-core/lib/stack-packs.js
  lighthouse-core/scripts/i18n/collect-strings.js
  lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  lighthouse-core/test/lib/stack-packs-test.js
  package.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer

#13809 tests(lantern): correctly clear old trace data
  lighthouse-core/scripts/lantern/download-traces.sh
Labels: waiting4reviewer

#13828 core(full-page-screenshot): use webp instead of jpeg
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb.js
  lighthouse-cli/test/smokehouse/test-definitions/screenshot.js
  lighthouse-core/gather/gatherers/full-page-screenshot.js
  lighthouse-core/test/gather/gatherers/full-page-screenshot-test.js
Labels: waiting4reviewer

#13856 report: set minimum width of element screenshot preview
  report/assets/styles.css
  report/assets/templates.html
  report/renderer/components.js
  report/renderer/element-screenshot-renderer.js
  report/test/renderer/element-screenshot-renderer-test.js
Labels: waiting4reviewer

#13865 core: fix build-sample-reports
  build/build-sample-reports.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/index.js
  types/config.d.ts
Labels: waiting4reviewer

#13872 docs: fix some broken links
  docs/architecture.md
  docs/new-audits.md
  docs/understanding-results.md
  docs/v8-perf-faq.md
  lighthouse-core/audits/byte-efficiency/legacy-javascript.js
  lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  lighthouse-core/test/results/sample_v2.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: land-when-ci-is-green, waiting4reviewer

#13830 i18n: localize units in report formatter
  flow-report/src/summary/category.tsx
  lighthouse-core/util-commonjs.js
  report/renderer/i18n.js
  report/renderer/util.js
  report/test/renderer/i18n-test.js
  report/test/renderer/util-test.js
  treemap/app/src/util.js
Labels: waiting4reviewer

#13873 deps: upgrade third-party-web
  package.json
  yarn.lock
Labels: waiting4reviewer

#13878 tests(devtools): extend yarn timeout
  .github/workflows/devtools.yml
Labels: land-when-ci-is-green, waiting4reviewer

#13877 report: avoid css issue with border when hoisting meta block
  report/assets/styles.css
  report/renderer/components.js
  report/test-assets/faux-psi.js
Labels: land-when-ci-is-green, waiting4reviewer

#13876 core(accessibility): link audits directly to axe docs
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/audits/accessibility/accesskeys.js
  lighthouse-core/audits/accessibility/aria-allowed-attr.js
  lighthouse-core/audits/accessibility/aria-command-name.js
  lighthouse-core/audits/accessibility/aria-hidden-body.js
  lighthouse-core/audits/accessibility/aria-hidden-focus.js
  lighthouse-core/audits/accessibility/aria-input-field-name.js
  lighthouse-core/audits/accessibility/aria-meter-name.js
  lighthouse-core/audits/accessibility/aria-progressbar-name.js
  lighthouse-core/audits/accessibility/aria-required-attr.js
  lighthouse-core/audits/accessibility/aria-required-children.js
  lighthouse-core/audits/accessibility/aria-required-parent.js
  lighthouse-core/audits/accessibility/aria-roles.js
  lighthouse-core/audits/accessibility/aria-toggle-field-name.js
  lighthouse-core/audits/accessibility/aria-tooltip-name.js
  lighthouse-core/audits/accessibility/aria-treeitem-name.js
  lighthouse-core/audits/accessibility/aria-valid-attr-value.js
  lighthouse-core/audits/accessibility/aria-valid-attr.js
  lighthouse-core/audits/accessibility/button-name.js
  lighthouse-core/audits/accessibility/bypass.js
  lighthouse-core/audits/accessibility/color-contrast.js
  lighthouse-core/audits/accessibility/definition-list.js
  lighthouse-core/audits/accessibility/dlitem.js
  lighthouse-core/audits/accessibility/document-title.js
  lighthouse-core/audits/accessibility/duplicate-id-active.js
  lighthouse-core/audits/accessibility/duplicate-id-aria.js
  lighthouse-core/audits/accessibility/form-field-multiple-labels.js
  lighthouse-core/audits/accessibility/frame-title.js
  lighthouse-core/audits/accessibility/heading-order.js
  lighthouse-core/audits/accessibility/html-has-lang.js
  lighthouse-core/audits/accessibility/html-lang-valid.js
  lighthouse-core/audits/accessibility/image-alt.js
  lighthouse-core/audits/accessibility/input-image-alt.js
  lighthouse-core/audits/accessibility/label.js
  lighthouse-core/audits/accessibility/link-name.js
  lighthouse-core/audits/accessibility/list.js
  lighthouse-core/audits/accessibility/listitem.js
  lighthouse-core/audits/accessibility/meta-refresh.js
  lighthouse-core/audits/accessibility/meta-viewport.js
  lighthouse-core/audits/accessibility/object-alt.js
  lighthouse-core/audits/accessibility/tabindex.js
  lighthouse-core/audits/accessibility/td-headers-attr.js
  lighthouse-core/audits/accessibility/th-has-data-cells.js
  lighthouse-core/audits/accessibility/valid-lang.js
  lighthouse-core/audits/accessibility/video-caption.js
  lighthouse-core/config/default-config.js
  lighthouse-core/test/audits/accessibility/axe-audit-test.js
  lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  lighthouse-core/test/results/sample_v2.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: land-when-ci-is-green

#13896 tests(smoke): support full chrome version for pruning
  lighthouse-cli/test/smokehouse/readme.md
  lighthouse-cli/test/smokehouse/report-assert.js
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency.js
  lighthouse-cli/test/smokehouse/test-definitions/csp-block-all.js
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb.js
  lighthouse-cli/test/smokehouse/test-definitions/issues-mixed-content.js
  lighthouse-cli/test/smokehouse/test-definitions/offline-sw-broken.js
  lighthouse-cli/test/smokehouse/test-definitions/perf-diagnostics-animations.js
  lighthouse-cli/test/smokehouse/test-definitions/perf-frame-metrics.js
  lighthouse-cli/test/smokehouse/test-definitions/perf-trace-elements.js
  lighthouse-cli/test/smokehouse/version-check-test.js
  lighthouse-cli/test/smokehouse/version-check.js
  lighthouse-core/audits/deprecations.js
  types/smokehouse.d.ts
Labels: waiting4reviewer

#13888 core(doctype): fix mistaken text saying name must be lowercase
  lighthouse-core/audits/dobetterweb/doctype.js
  lighthouse-core/test/audits/dobetterweb/doctype-test.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: land-when-ci-is-green, waiting4reviewer

#10880 report: handle non-numeric numericValues in calc link
  report/test/renderer/performance-category-renderer-test.js
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#12699 tests: assert what axe checks matches our a11y audits
  lighthouse-core/gather/gatherers/accessibility.js
  lighthouse-core/test/gather/gatherers/accessibility-test.js
  types/artifacts.d.ts
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13902 deps(devtools-protocol): upgrade to 0.0.995287
  lighthouse-core/audits/deprecations.js
  lighthouse-core/test/gather/gatherers/inspector-issues-test.js
  package.json
  yarn.lock
Labels: waiting4reviewer

#13911 misc(links): remove git.io shortlinks
  lighthouse-cli/cli-flags.js
  readme.md
Labels: waiting4reviewer

#12978 core(doctype): check document.compatMode for quirks mode
  lighthouse-core/audits/dobetterweb/doctype.js
  lighthouse-core/gather/gatherers/dobetterweb/doctype.js
  lighthouse-core/test/audits/dobetterweb/doctype-test.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  types/artifacts.d.ts
Labels: cla: yes, waiting4reviewer

#13913 core(trace): use tracing-started event for frame tree info
  lighthouse-core/lib/tracehouse/trace-processor.js
  lighthouse-core/test/computed/metrics/cumulative-layout-shift-test.js
  lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  lighthouse-core/test/lib/tracehouse/trace-processor-test.js
  types/artifacts.d.ts
Labels: land-when-ci-is-green, waiting4reviewer

#13912 tests: default to chrome-launcher path
  .github/workflows/ci.yml
  .github/workflows/unit.yml
  clients/test/extension/popup-test-pptr.js
  lighthouse-core/scripts/benchmark-plus-extras.js
  lighthouse-core/scripts/pptr-run-devtools.js
  lighthouse-core/scripts/update-flow-fixtures.js
  lighthouse-core/scripts/update-snapshot-sample.js
  lighthouse-core/test/fraggle-rock/scenarios/pptr-test-utils.js
Labels: land-when-ci-is-green, waiting4reviewer

#13903 tests(smoke): remove old chrome version checks
  lighthouse-cli/test/smokehouse/test-definitions/byte-efficiency.js
  lighthouse-cli/test/smokehouse/test-definitions/csp-block-all.js
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb.js
  lighthouse-cli/test/smokehouse/test-definitions/issues-mixed-content.js
  lighthouse-cli/test/smokehouse/test-definitions/offline-sw-broken.js
  lighthouse-cli/test/smokehouse/test-definitions/perf-diagnostics-animations.js
  lighthouse-cli/test/smokehouse/test-definitions/perf-frame-metrics.js
  lighthouse-cli/test/smokehouse/test-definitions/perf-trace-elements.js
Labels: waiting4reviewer

#13930 tests: add temp fix for failing deprecations smoke test
  lighthouse-cli/test/smokehouse/test-definitions/dobetterweb.js
Labels: land-when-ci-is-green, waiting4reviewer

#13910 tests(crq): call setExtrasFn before using the urls
  lighthouse-core/test/computed/critical-request-chains-test.js
Labels: waiting4reviewer

#13922 tests: replace $0 in cli-flag snapshots
  lighthouse-cli/test/cli/__snapshots__/cli-flags-test.js.snap
  lighthouse-cli/test/cli/cli-flags-test.js
Labels: land-when-ci-is-green, waiting4reviewer

#13893 core(deprecations): drop compat for ConsoleMessages
  lighthouse-core/audits/deprecations.js
  lighthouse-core/test/audits/deprecations-test.js
Labels: land-when-ci-is-green, waiting4reviewer

#13914 deps(lodash): use individual lodash modules to reduce bundle size
  lighthouse-cli/test/smokehouse/frontends/lib.js
  lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js
  lighthouse-cli/test/smokehouse/report-assert.js
  lighthouse-core/config/config-helpers.js
  lighthouse-core/fraggle-rock/gather/base-artifacts.js
  lighthouse-core/lib/arbitrary-equality-map.js
  lighthouse-core/runner.js
  shared/localization/swap-locale.js
Labels: land-when-ci-is-green, waiting4reviewer

#13839 i18n: remove default granularity values from formatter
  docs/new-audits.md
  lighthouse-core/util-commonjs.js
  report/renderer/details-renderer.js
  report/renderer/i18n.js
  report/renderer/util.js
  report/test/renderer/details-renderer-test.js
  report/test/renderer/i18n-test.js
Labels: waiting4reviewer

#13932 clients(viewer): ga event for flow-report
  viewer/app/src/lighthouse-report-viewer.js
Labels: waiting4reviewer

#13917 new_audit: add responsiveness metric for timespans
  lighthouse-core/audits/metrics/experimental-interaction-to-next-paint.js
  lighthouse-core/computed/metrics/responsiveness.js
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/lib/i18n/i18n.js
  lighthouse-core/lib/minify-trace.js
  lighthouse-core/test/audits/metrics/experimental-interaction-to-next-paint-test.js
  lighthouse-core/test/computed/metrics/responsiveness-test.js
  lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  lighthouse-core/test/fixtures/traces/timespan-responsiveness-m103.trace.json
  lighthouse-core/test/fraggle-rock/scenarios/api-test-pptr.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-navigation-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
  types/artifacts.d.ts
Labels: land-when-ci-is-green, waiting4reviewer

#13942 tests: update create-test-trace utility
  lighthouse-core/test/audits/redirects-test.js
  lighthouse-core/test/computed/metrics/cumulative-layout-shift-test.js
  lighthouse-core/test/create-test-trace.js
  lighthouse-core/test/lib/tracehouse/trace-processor-test.js
Labels: land-when-ci-is-green, waiting4reviewer
