Repository GoogleChrome/lighthouse, pull requests merged in 2022-09, with the labels that each got.

#14332 core(smoke): replace --invert-match cli option with --ignore-exclusions
  cli/test/smokehouse/frontends/smokehouse-bin.js
Labels: waiting4reviewer

#14348 misc: remove transitionary ES module package.json files
  build/package.json
  cli/package.json
  clients/devtools/package.json
  clients/package.json
  core/package.json
  core/scripts/package.json
  core/test/fixtures/config/lighthouse-plugin-config-helper/plugin-config-helper.js
  core/test/package.json
  esm-utils.js
  flow-report/package.json
  report/package.json
  treemap/package.json
  viewer/package.json
Labels: waiting4reviewer

#13940 docs(recipes): update custom-gatherer-puppeteer to use FR
  docs/recipes/custom-gatherer-puppeteer/custom-config.js
  docs/recipes/custom-gatherer-puppeteer/custom-gatherer.js
  docs/recipes/custom-gatherer-puppeteer/test.sh
Labels: waiting4reviewer, 10.0

#14365 tests(devtools): sync e2e tests
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
Labels: land-when-ci-is-green

#14360 core: rename url-shim to url-utils, stop extending global URL
  cli/run.js
  core/audits/byte-efficiency/modern-image-formats.js
  core/audits/byte-efficiency/offscreen-images.js
  core/audits/byte-efficiency/uses-long-cache-ttl.js
  core/audits/byte-efficiency/uses-optimized-images.js
  core/audits/byte-efficiency/uses-responsive-images-snapshot.js
  core/audits/byte-efficiency/uses-responsive-images.js
  core/audits/byte-efficiency/uses-text-compression.js
  core/audits/dobetterweb/uses-http2.js
  core/audits/font-display.js
  core/audits/image-aspect-ratio.js
  core/audits/image-size-responsive.js
  core/audits/is-on-https.js
  core/audits/network-requests.js
  core/audits/seo/canonical.js
  core/audits/seo/is-crawlable.js
  core/audits/seo/link-text.js
  core/audits/seo/plugins.js
  core/audits/seo/robots-txt.js
  core/audits/service-worker.js
  core/audits/unsized-images.js
  core/audits/uses-rel-preconnect.js
  core/audits/uses-rel-preload.js
  core/computed/image-records.js
  core/computed/resource-summary.js
  core/fraggle-rock/gather/navigation-runner.js
  core/gather/driver/navigation.js
  core/gather/driver/network-monitor.js
  core/gather/gather-runner.js
  core/gather/gatherers/dobetterweb/optimized-images.js
  core/gather/gatherers/dobetterweb/response-compression.js
  core/gather/gatherers/link-elements.js
  core/gather/gatherers/source-maps.js
  core/index.js
  core/lib/dependency-graph/simulator/network-analyzer.js
  core/lib/icons.js
  core/lib/manifest-parser.js
  core/lib/network-request.js
  core/lib/sd-validation/json-expander.js
  core/lib/url-utils.js
  core/test/audits/service-worker-test.js
  core/test/lib/url-utils-test.js
  report/test/renderer/performance-category-renderer-test.js
  report/test/renderer/report-renderer-test.js
  tsconfig.json
Labels: waiting4reviewer

#14343 tests(smoke): check runner result is sensible before using
  cli/test/smokehouse/report-assert.js
  cli/test/smokehouse/smokehouse.js
Labels: land-when-ci-is-green, waiting4reviewer

#14330 core: remove replay stringify extension
  core/fraggle-rock/replay/stringify-extension.js
  core/test/fraggle-rock/replay/__snapshots__/stringify-extension-test.js.snap
  core/test/fraggle-rock/replay/stringify-extension-test.js
  core/test/fraggle-rock/scenarios/__snapshots__/stringified-replay-test-pptr.js.snap
  core/test/fraggle-rock/scenarios/stringified-replay-test-pptr.js
  package.json
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer

#14347 misc(build): use git-describe for build bundle version header
  build/build-bundle.js
Labels: waiting4reviewer

#14373 tests(devtools): sync e2e tests
  third-party/devtools-tests/e2e/lighthouse/BUILD.gn
  third-party/devtools-tests/e2e/lighthouse/generate-report_test.ts
  third-party/devtools-tests/e2e/lighthouse/indexeddb-warning_test.ts
  third-party/devtools-tests/e2e/lighthouse/start-view_test.ts
Labels: waiting4reviewer

#14241 misc: re-enable pubads after esm migration
  build/build-bundle.js
  cli/test/smokehouse/core-tests.js
  clients/devtools/devtools-entry.js
  core/scripts/release/package-test.sh
  package.json
  yarn.lock
Labels: waiting4reviewer

#14341 core(legacy): create legacy directory under core
  CONTRIBUTING.md
  build/build-bundle.js
  cli/test/smokehouse/lighthouse-runners/bundle.js
  clients/devtools/devtools-entry.js
  clients/lightrider/lightrider-entry.js
  core/gather/gatherers/seo/font-size.js
  core/index.js
  core/legacy/config/config.js
  core/legacy/config/legacy-default-config.js
  core/legacy/gather/connections/connection.js
  core/legacy/gather/connections/cri.js
  core/legacy/gather/connections/raw.js
  core/legacy/gather/driver.js
  core/legacy/gather/gather-runner.js
  core/runner.js
  core/test/gather/fetcher-test.js
  core/test/gather/gatherers/global-listeners-test.js
  core/test/gather/gatherers/js-usage-test.js
  core/test/gather/gatherers/source-maps-test.js
  core/test/gather/gatherers/trace-elements-test.js
  core/test/legacy/config/config-test.js
  core/test/legacy/gather/driver-test.js
  core/test/legacy/gather/fake-driver.js
  core/test/legacy/gather/gather-runner-test.js
  core/test/lib/emulation-test.js
  core/test/runner-test.js
  core/test/scripts/run-mocha-tests.js
  tsconfig.json
  types/gatherer.d.ts
Labels: waiting4reviewer, 10.0

#14374 core(page-functions): remove all `*String` exports
  core/gather/driver/execution-context.js
  core/gather/gatherers/accessibility.js
  core/gather/gatherers/anchor-elements.js
  core/gather/gatherers/dobetterweb/domstats.js
  core/gather/gatherers/dobetterweb/password-inputs-with-prevented-paste.js
  core/gather/gatherers/full-page-screenshot.js
  core/gather/gatherers/iframe-elements.js
  core/gather/gatherers/image-elements.js
  core/gather/gatherers/inputs.js
  core/gather/gatherers/link-elements.js
  core/gather/gatherers/meta-elements.js
  core/gather/gatherers/script-elements.js
  core/gather/gatherers/seo/embedded-content.js
  core/gather/gatherers/seo/tap-targets.js
  core/gather/gatherers/trace-elements.js
  core/lib/page-functions.js
  core/test/gather/gatherers/accessibility-test.js
Labels: waiting4reviewer

#14389 tests(devtools): sync e2e
  third-party/devtools-tests/e2e/lighthouse/BUILD.gn
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
  third-party/devtools-tests/e2e/lighthouse/snapshot_test.ts
  third-party/devtools-tests/e2e/resources/lighthouse/hello.html
Labels: waiting4reviewer

#14391 core: remove sd-validation audit files
  .npmignore
  core/lib/sd-validation/assets/jsonldcontext.json
  core/lib/sd-validation/assets/schema-tree.json
  core/lib/sd-validation/helpers/walk-object.js
  core/lib/sd-validation/json-expander.js
  core/lib/sd-validation/json-linter.js
  core/lib/sd-validation/jsonld-keyword-validator.js
  core/lib/sd-validation/line-number-from-jsonld-path.js
  core/lib/sd-validation/schema-validator.js
  core/lib/sd-validation/scripts/download-jsonldcontext.js
  core/lib/sd-validation/scripts/generate-schema-tree.js
  core/lib/sd-validation/sd-validation.js
  core/test/lib/line-number-from-jsonld-path-test.js
  core/test/lib/sd-validation-test.js
  package.json
  tsconfig.json
  types/global-lh.d.ts
  types/jsonld/index.d.ts
  types/structured-data.d.ts
Labels: waiting4reviewer

#14392 core(fr): always run NetworkUserAgent gatherer
  cli/test/cli/__snapshots__/index-test.js.snap
  core/fraggle-rock/config/filters.js
Labels: waiting4reviewer

#13874 tests(ci): add node 18 to test matrix
  .github/workflows/unit.yml
Labels: waiting4reviewer

#14409 core: finalize master => main branch rename
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/scripts/git-get-shared-history.sh
  .github/workflows/ci.yml
  .github/workflows/devtools.yml
  .github/workflows/package-test.yml
  .github/workflows/smoke.yml
  .github/workflows/unit.yml
  CONTRIBUTING.md
  build/readme.md
  changelog.md
  cli/cli-flags.js
  cli/sentry-prompt.js
  cli/test/smokehouse/readme.md
  core/config/validation.js
  core/gather/driver/environment.js
  core/legacy/config/config.js
  core/lib/cdt/Platform.js
  core/lib/i18n/i18n.js
  core/lib/network-request.js
  core/scripts/dogfood-lhci.sh
  core/scripts/gcp-collection/README.md
  core/scripts/gcp-collection/run.sh
  core/scripts/lantern/collect/gcp-run.sh
  core/scripts/release/prepare-commit.sh
  core/scripts/release/prepare-pristine.sh
  core/scripts/test-lantern.sh
  core/scripts/test-legacy-javascript.sh
  core/user-flow.js
  docs/authenticated-pages.md
  docs/configuration.md
  docs/headless-chrome.md
  docs/new-audits.md
  docs/puppeteer.md
  docs/readme.md
  docs/recipes/auth/README.md
  docs/recipes/custom-audit/readme.md
  docs/recipes/lighthouse-plugin-example/readme.md
  docs/scoring.md
  docs/throttling.md
  docs/understanding-results.md
  docs/variability.md
  flow-report/.eslintrc.cjs
  proto/lighthouse-result.proto
  readme.md
  report/README.md
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: waiting4reviewer

#14385 core(target-manager): only listen to LH sessions
  clients/lightrider/lightrider-entry.js
  core/gather/driver/target-manager.js
  core/test/gather/driver/target-manager-test.js
  core/test/gather/session-test.js
  package.json
  viewer/test/viewer-test-pptr.js
  yarn.lock
Labels: waiting4reviewer
