Repository GoogleChrome/lighthouse, pull requests merged in 2022-05, with the labels that each got.

#13931 report: hide disclaimer text in timespan
  report/renderer/performance-category-renderer.js
  report/test/renderer/performance-category-renderer-test.js
Labels: waiting4reviewer

#13937 misc: generate snapshot/timespan reports from sample flow result
  build/build-sample-reports.js
  lighthouse-core/scripts/update-snapshot-sample.js
  lighthouse-core/test/fixtures/fraggle-rock/reports/sample-snapshot-lhr.json
  package.json
Labels: land-when-ci-is-green, waiting4reviewer

#13860 cli: use fraggle rock runner by default, deprecate legacy navigation runner
  docs/recipes/custom-gatherer-puppeteer/test.sh
  lighthouse-cli/cli-flags.js
  lighthouse-cli/run.js
  lighthouse-cli/test/cli/__snapshots__/cli-flags-test.js.snap
  lighthouse-cli/test/cli/bin-test.js
  lighthouse-cli/test/smokehouse/lighthouse-runners/cli.js
  lighthouse-core/index.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  types/externs.d.ts
Labels: waiting4reviewer

#9801 core(crc): exclude non network nodes from being a leaf
  lighthouse-core/computed/critical-request-chains.js
  lighthouse-core/test/computed/critical-request-chains-test.js
Labels: cla: yes, waiting4reviewer

#13927 core(listitem): mention li can be contained by a menu
  lighthouse-core/audits/accessibility/listitem.js
  lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  lighthouse-core/test/results/sample_v2.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-navigation-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: waiting4reviewer

#13941 tests(docs): clear problematic cache
  docs/recipes/package.json
Labels: waiting4reviewer

#13657 deps(puppeteer): upgrade to 13.7.0
  lighthouse-core/fraggle-rock/gather/session.js
  package.json
  report/test/renderer/__snapshots__/report-renderer-axe-test.js.snap
  report/test/renderer/report-renderer-axe-test.js
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer, 10.0

#13885 report(psi): stub out locale swapping
  build/build-report.js
  report/clients/bundle.js
  report/test-assets/faux-psi-template.html
  report/test-assets/faux-psi.js
Labels: report, waiting4reviewer

#13959 tests: fix unconverted test
  lighthouse-core/test/audits/metrics/experimental-interaction-to-next-paint-test.js
  lighthouse-core/test/computed/metrics/responsiveness-test.js
Labels: land-when-ci-is-green, waiting4reviewer

#13963 tests: rebaseline webtests
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-block-url-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-clear-data-warning-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-flags-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-i18n-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-limited-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-prevent-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-navigation-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run-expected.txt
Labels: land-when-ci-is-green, waiting4reviewer

#13950 core(trace): add PrePaint event, renamed from UpdateLayerTree
  lighthouse-core/lib/tracehouse/task-groups.js
Labels: waiting4reviewer

#13947 tests(smoke): run bundle smokes in a worker
  lighthouse-cli/test/smokehouse/lighthouse-runners/bundle.js
  package.json
Labels: waiting4reviewer

#13969 deps(js-library-detector): upgrade to 6.5.0
  lighthouse-core/lib/stack-packs.js
  lighthouse-core/test/lib/stack-packs-test.js
  package.json
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer

#13970 core(responsiveness): use raw trace event
  lighthouse-core/audits/metrics/experimental-interaction-to-next-paint.js
  lighthouse-core/computed/metrics/responsiveness.js
  lighthouse-core/test/computed/metrics/responsiveness-test.js
  types/artifacts.d.ts
Labels: land-when-ci-is-green, waiting4reviewer

#13971 core: extract BootupTime task summary methods
  lighthouse-core/audits/bootup-time.js
  lighthouse-core/audits/long-tasks.js
  lighthouse-core/audits/third-party-summary.js
  lighthouse-core/lib/tracehouse/task-summary.js
  lighthouse-core/test/lib/tracehouse/task-summary-test.js
  tsconfig.json
Labels: land-when-ci-is-green, waiting4reviewer

#13936 misc: also update flow json in update:sample-json script
  package.json
Labels: land-when-ci-is-green, waiting4reviewer

#13967 misc(build): convert to ES modules
  build/.eslintrc.cjs
  build/build-bundle.js
  build/build-cdt-lib.js
  build/build-dt-report-resources.js
  build/build-extension.js
  build/build-lightrider-bundles.js
  build/build-report-components.js
  build/build-report.js
  build/build-sample-reports.js
  build/build-smokehouse-bundle.js
  build/build-treemap.js
  build/build-viewer.js
  build/changelog-generator/index.cjs
  build/gh-pages-app.js
  build/package.json
  build/plugins/browserify-inline-fs.js
  build/plugins/inline-fs.js
  build/plugins/rollup-plugin-inline-fs.js
  build/rollup-plugins.js
  build/test/plugins/inline-fs-test.js
  lighthouse-core/lib/cdt/generated/SourceMap.js
  package.json
  treemap/app/src/main.js
  treemap/app/src/util.js
  treemap/types/treemap.d.ts
  tsconfig.json
Labels: waiting4reviewer

#13887 core(css-usage): fetch stylesheet contents immediately after discovery
  lighthouse-core/gather/gatherers/css-usage.js
  lighthouse-core/test/fixtures/fraggle-rock/css-change/end.css
  lighthouse-core/test/fixtures/fraggle-rock/css-change/end.html
  lighthouse-core/test/fixtures/fraggle-rock/css-change/start.css
  lighthouse-core/test/fixtures/fraggle-rock/css-change/start.html
  lighthouse-core/test/fraggle-rock/scenarios/cross-origin-test-pptr.js
  lighthouse-core/test/fraggle-rock/scenarios/pptr-test-utils.js
  lighthouse-core/test/gather/gatherers/css-usage-test.js
Labels: waiting4reviewer

#13979 core(responsiveness): use new EventTiming trace event format
  lighthouse-core/audits/metrics/experimental-interaction-to-next-paint.js
  lighthouse-core/computed/metrics/responsiveness.js
  lighthouse-core/test/audits/metrics/experimental-interaction-to-next-paint-test.js
  lighthouse-core/test/computed/metrics/responsiveness-test.js
  lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  lighthouse-core/test/fixtures/traces/timespan-responsiveness-m103.trace.json
  types/artifacts.d.ts
Labels: land-when-ci-is-green, waiting4reviewer

#13981 report: render notApplicable metrics with double dash
  report/renderer/performance-category-renderer.js
  report/test/renderer/performance-category-renderer-test.js
Labels: waiting4reviewer

#13982 new_audit: add work-during-interaction diagnostic
  lighthouse-core/audits/work-during-interaction.js
  lighthouse-core/config/metrics-to-audits.js
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/test/audits/work-during-interaction-test.js
  lighthouse-core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  lighthouse-core/test/fraggle-rock/scenarios/api-test-pptr.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-navigation-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: land-when-ci-is-green, waiting4reviewer

#13989 core(fps): run at the end of timespan/snapshot
  lighthouse-core/fraggle-rock/config/default-config.js
Labels: waiting4reviewer

#13984 core(responsiveness): add element screenshot to INP diagnostic
  lighthouse-core/audits/work-during-interaction.js
  lighthouse-core/gather/gatherers/trace-elements.js
  lighthouse-core/test/audits/work-during-interaction-test.js
  report/assets/styles.css
  report/renderer/components.js
  report/renderer/details-renderer.js
  report/test/renderer/details-renderer-test.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-navigation-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
  types/artifacts.d.ts
  types/lhr/audit-details.d.ts
Labels: land-when-ci-is-green, waiting4reviewer

#13997 tests: move webtest expectations to platform/generic
  lighthouse-core/scripts/roll-to-devtools.sh
  lighthouse-core/test/chromium-web-tests/web-test-server.sh
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-block-url.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-clear-data-warning.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-i18n-run.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-limited-run.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-prevent-run.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-view-trace-run.js
  third-party/chromium-webtests/webtests/platform/generic/http/tests/devtools/lighthouse/lighthouse-block-url-expected.txt
  third-party/chromium-webtests/webtests/platform/generic/http/tests/devtools/lighthouse/lighthouse-clear-data-warning-expected.txt
  third-party/chromium-webtests/webtests/platform/generic/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/platform/generic/http/tests/devtools/lighthouse/lighthouse-export-run-expected.txt
  third-party/chromium-webtests/webtests/platform/generic/http/tests/devtools/lighthouse/lighthouse-flags-run-expected.txt
  third-party/chromium-webtests/webtests/platform/generic/http/tests/devtools/lighthouse/lighthouse-i18n-run-expected.txt
  third-party/chromium-webtests/webtests/platform/generic/http/tests/devtools/lighthouse/lighthouse-limited-run-expected.txt
  third-party/chromium-webtests/webtests/platform/generic/http/tests/devtools/lighthouse/lighthouse-prevent-run-expected.txt
  third-party/chromium-webtests/webtests/platform/generic/http/tests/devtools/lighthouse/lighthouse-successful-navigation-expected.txt
  third-party/chromium-webtests/webtests/platform/generic/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
  third-party/chromium-webtests/webtests/platform/generic/http/tests/devtools/lighthouse/lighthouse-view-trace-run-expected.txt
Labels: land-when-ci-is-green, waiting4reviewer

#13999 misc(inp): switch proccessing "delay" to "time"
  lighthouse-core/audits/work-during-interaction.js
  lighthouse-core/test/audits/work-during-interaction-test.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: land-when-ci-is-green, waiting4reviewer

#13995 misc: replace appendChild with append
  clients/extension/scripts/popup.js
  flow-report/src/util.ts
  lighthouse-cli/test/fixtures/byte-efficiency/tester.html
  lighthouse-cli/test/fixtures/delayed-fcp.html
  lighthouse-cli/test/fixtures/delayed-lcp.html
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
  lighthouse-cli/test/fixtures/perf/level-3.js
  lighthouse-cli/test/fixtures/perf/preload_tester.js
  lighthouse-core/test/fixtures/fraggle-rock/snapshot-basic/onclick.html
  lighthouse-core/test/lib/page-functions-test.js
  report/renderer/category-renderer.js
  report/renderer/crc-details-renderer.js
  report/renderer/details-renderer.js
  report/renderer/dom.js
  report/renderer/element-screenshot-renderer.js
  report/renderer/performance-category-renderer.js
  report/renderer/pwa-category-renderer.js
  report/renderer/report-renderer.js
  report/renderer/snippet-renderer.js
  treemap/app/src/util.js
  viewer/app/src/lighthouse-report-viewer.js
Labels: waiting4reviewer

#13968 tests(ci): shard all smoke tests
  .github/workflows/smoke.yml
Labels: waiting4reviewer

#14022 tests(smoke): increase windows retries
  .github/workflows/smoke.yml
Labels: land-when-ci-is-green

#14010 core: log `requestedUrl` with unexpected value
  lighthouse-core/gather/driver/navigation.js
Labels: land-when-ci-is-green

#14002 core: save native getBoundingClientRect to avoid overrides
  lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
  lighthouse-core/gather/driver/execution-context.js
  lighthouse-core/gather/gatherers/iframe-elements.js
  lighthouse-core/lib/page-functions.js
  lighthouse-core/test/lib/page-functions-test.js
  types/externs.d.ts
Labels: waiting4reviewer

#14036 tests(config-helpers): restore process.cwd after mocking
  lighthouse-core/test/config/config-helpers-test.js
Labels: waiting4reviewer

#14009 docs(user-flows): add instructions for DevTools
  docs/user-flows.md
Labels: land-when-ci-is-green

#14057 tests(topbar): replace module mock with dependency injection
  flow-report/src/topbar.tsx
  flow-report/test/topbar-test.tsx
Labels: waiting4reviewer

#14060 core(source-maps): throw explicit error when map is missing required fields
  lighthouse-core/gather/gatherers/source-maps.js
Labels: land-when-ci-is-green, waiting4reviewer
