Repository GoogleChrome/lighthouse, pull requests merged in 2022-02, with the labels that each got.

#13587 core(runner): store gather timing on artifacts
  lighthouse-core/runner.js
  lighthouse-core/scripts/update-report-fixtures.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
Labels: waiting4reviewer

#13615 tests(devtools): update report resource names
  build/build-dt-report-resources.js
Labels: waiting4reviewer

#13614 tests: timing smoke test
  lighthouse-cli/test/fixtures/simple-page.html
  lighthouse-cli/test/smokehouse/core-tests.js
  lighthouse-cli/test/smokehouse/report-assert.js
  lighthouse-cli/test/smokehouse/test-definitions/timing.js
  lighthouse-core/runner.js
  types/smokehouse.d.ts
Labels: waiting4reviewer

#13619 tests(smoke): test array `_includes` and `lhr.timing`
  lighthouse-cli/test/smokehouse/readme.md
  lighthouse-cli/test/smokehouse/report-assert.js
  types/smokehouse.d.ts
Labels: waiting4reviewer

#13569 core(runner): independent gather and audit functions
  clients/test/lightrider-entry-test.js
  lighthouse-cli/test/fixtures/simple-page.html
  lighthouse-cli/test/smokehouse/core-tests.js
  lighthouse-cli/test/smokehouse/test-definitions/timing.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/fraggle-rock/gather/snapshot-runner.js
  lighthouse-core/fraggle-rock/gather/timespan-runner.js
  lighthouse-core/index.js
  lighthouse-core/runner.js
  lighthouse-core/scripts/update-flow-fixtures.js
  lighthouse-core/scripts/update-report-fixtures.js
  lighthouse-core/test/fraggle-rock/gather/mock-driver.js
  lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
  lighthouse-core/test/fraggle-rock/gather/snapshot-runner-test.js
  lighthouse-core/test/fraggle-rock/gather/timespan-runner-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  lighthouse-core/test/results/sample_v2.json
  lighthouse-core/test/runner-test.js
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: waiting4reviewer

#13618 misc: temporarily remove brendan from triage rotation
  .github/workflows/issue-assigner.yml
Labels: waiting4reviewer

#13626 tests: fix single node a11y tests
  lighthouse-core/test/audits/accessibility/aria-allowed-attr-test.js
  lighthouse-core/test/audits/accessibility/aria-required-attr-test.js
  lighthouse-core/test/audits/accessibility/aria-required-children-test.js
  lighthouse-core/test/audits/accessibility/aria-required-parent-test.js
  lighthouse-core/test/audits/accessibility/aria-roles-test.js
  lighthouse-core/test/audits/accessibility/aria-valid-attr-test.js
  lighthouse-core/test/audits/accessibility/aria-valid-attr-value-test.js
  lighthouse-core/test/audits/accessibility/button-name-test.js
  lighthouse-core/test/audits/accessibility/bypass-test.js
  lighthouse-core/test/audits/accessibility/color-contrast-test.js
  lighthouse-core/test/audits/accessibility/definition-list-test.js
  lighthouse-core/test/audits/accessibility/dlitem-test.js
  lighthouse-core/test/audits/accessibility/document-title-test.js
  lighthouse-core/test/audits/accessibility/frame-title-test.js
  lighthouse-core/test/audits/accessibility/html-has-lang-test.js
  lighthouse-core/test/audits/accessibility/html-lang-valid-test.js
  lighthouse-core/test/audits/accessibility/image-alt-test.js
  lighthouse-core/test/audits/accessibility/input-image-alt-test.js
  lighthouse-core/test/audits/accessibility/label-test.js
  lighthouse-core/test/audits/accessibility/link-name-test.js
  lighthouse-core/test/audits/accessibility/list-test.js
  lighthouse-core/test/audits/accessibility/listitem-test.js
  lighthouse-core/test/audits/accessibility/meta-refresh-test.js
  lighthouse-core/test/audits/accessibility/meta-viewport-test.js
  lighthouse-core/test/audits/accessibility/object-alt-test.js
  lighthouse-core/test/audits/accessibility/tabindex-test.js
  lighthouse-core/test/audits/accessibility/td-headers-attr-test.js
  lighthouse-core/test/audits/accessibility/th-has-data-cells-test.js
  lighthouse-core/test/audits/accessibility/valid-lang-test.js
  lighthouse-core/test/audits/accessibility/video-caption-test.js
Labels: waiting4reviewer

#13385 core(hreflang): remove eval, import axe valid-langs.js directly
  .npmignore
  docs/recipes/integration-test/example-lh-auth.test.js
  lighthouse-core/audits/seo/hreflang.js
  readme.md
  third-party/axe/LICENSE
  third-party/axe/README.md
  third-party/axe/valid-langs.js
  tsconfig.json
Labels: cla: yes, waiting4reviewer

#13636 core(page-functions): set style in getOuterHTMLSnippet without violating CSP
  lighthouse-cli/test/fixtures/csp.html
  lighthouse-cli/test/smokehouse/core-tests.js
  lighthouse-cli/test/smokehouse/test-definitions/csp-block-all-m91.js
  lighthouse-cli/test/smokehouse/test-definitions/csp-block-all.js
  lighthouse-core/lib/page-functions.js
Labels: waiting4reviewer

#13635 report: fix fireworks
  report/assets/templates.html
  report/renderer/components.js
Labels: waiting4reviewer

#13496 core(fr): user triggered navigations
  docs/user-flows.md
  lighthouse-cli/run.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/fraggle-rock/user-flow.js
  lighthouse-core/gather/driver/navigation.js
  lighthouse-core/gather/driver/network-monitor.js
  lighthouse-core/gather/driver/prepare.js
  lighthouse-core/gather/gather-runner.js
  lighthouse-core/test/fixtures/fraggle-rock/navigation-basic/links-to-index.html
  lighthouse-core/test/fraggle-rock/gather/navigation-runner-test.js
  lighthouse-core/test/fraggle-rock/scenarios/api-test-pptr.js
  lighthouse-core/test/fraggle-rock/user-flow-test.js
  lighthouse-core/test/gather/driver/navigation-test.js
  lighthouse-core/test/gather/driver/network-monitor-test.js
  lighthouse-core/test/gather/driver/prepare-test.js
  types/global-lh.d.ts
Labels: waiting4reviewer

#13528 report: add onViewTrace to renderer options
  lighthouse-core/test/results/sample_v2.json
  lighthouse-core/util-commonjs.js
  proto/lighthouse-result.proto
  report/renderer/report-ui-features.js
  report/renderer/util.js
  report/types/report-renderer.d.ts
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: waiting4reviewer

#13658 tests: use simpler assertion in report-renderer-axe-test.js
  report/test/renderer/__snapshots__/report-renderer-axe-test.js.snap
  report/test/renderer/report-renderer-axe-test.js
Labels: waiting4reviewer

#13662 core(inputs): refactor form-elements gatherer
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-cli/test/fixtures/form.html
  lighthouse-cli/test/smokehouse/core-tests.js
  lighthouse-cli/test/smokehouse/test-definitions/forms-autocomplete.js
  lighthouse-core/audits/autocomplete.js
  lighthouse-core/config/default-config.js
  lighthouse-core/fraggle-rock/config/default-config.js
  lighthouse-core/gather/gatherers/form-elements.js
  lighthouse-core/gather/gatherers/inputs.js
  lighthouse-core/test/audits/autocomplete-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  types/artifacts.d.ts
Labels: waiting4reviewer

#13663 core(full-page-screenshot): wait for doubleraf, network quiet
  lighthouse-core/gather/driver/wait-for-condition.js
  lighthouse-core/gather/gatherers/full-page-screenshot.js
  lighthouse-core/test/gather/gatherers/full-page-screenshot-test.js
Labels: waiting4reviewer

#13671 core(inputs): fix typo in artifact
  lighthouse-cli/test/smokehouse/test-definitions/forms-autocomplete.js
  lighthouse-core/gather/gatherers/inputs.js
  lighthouse-core/scripts/legacy-javascript/create-polyfill-size-estimation.js
  lighthouse-core/test/results/artifacts/artifacts.json
  types/artifacts.d.ts
Labels: waiting4reviewer

#13649 report: add options disableFireworks and disableDarkMode
  flow-report/src/wrappers/report.tsx
  report/renderer/report-ui-features.js
  report/test-assets/faux-psi.js
  report/types/report-renderer.d.ts
Labels: waiting4reviewer

#13529 report: add options onPrintOverride and onSaveFileOverride
  flow-report/src/topbar.tsx
  flow-report/test/topbar-test.tsx
  report/renderer/dom.js
  report/renderer/report-ui-features.js
  report/renderer/topbar-features.js
  report/types/report-renderer.d.ts
Labels: waiting4reviewer

#13612 core(uses-long-cache-ttl): ignore `stale-while-revalidate`
  lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js
  types/parse-cache-control/index.d.ts
Labels: waiting4reviewer

#13638 core(a11y): change link in category description to web.dev
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  lighthouse-core/config/default-config.js
  lighthouse-core/test/results/sample_v2.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: land-when-ci-is-green, waiting4reviewer

#9325 deps(sentry): move from raven to @sentry/node
  build/build-bundle.js
  lighthouse-cli/bin.js
  lighthouse-core/lib/sentry.js
  lighthouse-core/runner.js
  lighthouse-core/test/lib/sentry-test.js
  package.json
  yarn.lock
Labels: land-when-ci-is-green, cla: yes, waiting4reviewer

#13672 v9.4.0
  changelog.md
  docs/plugins.md
  docs/recipes/custom-audit/package.json
  docs/recipes/gulp/package.json
  docs/recipes/lighthouse-plugin-example/package.json
  lighthouse-core/test/results/sample_v2.json
  package.json
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-emulate-run-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-run-expected.txt
Labels: waiting4reviewer

#13673 tests(devtools): navigation web test
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-navigation-expected.txt
  third-party/chromium-webtests/webtests/http/tests/devtools/lighthouse/lighthouse-successful-navigation.js
Labels: waiting4reviewer

#13693 tests(devtools): update Lighthouse sniffer for smokes
  lighthouse-core/scripts/pptr-run-devtools.js
Labels: waiting4reviewer

#13681 core(fr): add `logLevel` to config context
  lighthouse-cli/run.js
  lighthouse-core/fraggle-rock/config/config.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/fraggle-rock/gather/snapshot-runner.js
  lighthouse-core/fraggle-rock/gather/timespan-runner.js
  types/config.d.ts
Labels: waiting4reviewer

#13699 core(fr): use frame url in gather context
  lighthouse-cli/test/fixtures/redirects-self.html
  lighthouse-cli/test/smokehouse/core-tests.js
  lighthouse-cli/test/smokehouse/test-definitions/redirects-self.js
  lighthouse-core/fraggle-rock/gather/navigation-runner.js
  lighthouse-core/fraggle-rock/gather/runner-helpers.js
  lighthouse-core/fraggle-rock/gather/snapshot-runner.js
  lighthouse-core/fraggle-rock/gather/timespan-runner.js
  lighthouse-core/test/fraggle-rock/gather/mock-driver.js
  lighthouse-core/test/fraggle-rock/gather/runner-helpers-test.js
  lighthouse-core/test/fraggle-rock/gather/snapshot-runner-test.js
  lighthouse-core/test/fraggle-rock/gather/timespan-runner-test.js
Labels: land-when-ci-is-green, waiting4reviewer

#13708 core(inspector-issues): update sameSiteCookie to cookie
  lighthouse-core/audits/dobetterweb/inspector-issues.js
  lighthouse-core/gather/gatherers/inspector-issues.js
  lighthouse-core/test/audits/dobetterweb/inspector-issues-test.js
  lighthouse-core/test/gather/gatherers/inspector-issues-test.js
  lighthouse-core/test/results/artifacts/artifacts.json
  package.json
  third-party/chromium-synchronization/inspector-issueAdded-types-test.js
  types/artifacts.d.ts
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer
