Repository GoogleChrome/lighthouse, pull requests merged in 2023-03, with the labels that each got.

#14790 tests: reenable `metrics-tricky-tti` on ToT
  cli/test/smokehouse/test-definitions/metrics-tricky-tti.js
Labels: land-when-ci-is-green, waiting4reviewer

#14838 core(redirects): use requestId instead of URL to find requests
  cli/test/smokehouse/test-definitions/redirects-client-paint-server.js
  cli/test/smokehouse/test-definitions/redirects-history-push-state.js
  cli/test/smokehouse/test-definitions/redirects-multiple-server.js
  cli/test/smokehouse/test-definitions/redirects-scripts.js
  cli/test/smokehouse/test-definitions/redirects-single-client.js
  cli/test/smokehouse/test-definitions/redirects-single-server.js
  core/audits/redirects.js
  core/test/audits/redirects-test.js
  types/artifacts.d.ts
Labels: land-when-ci-is-green, waiting4reviewer

#14800 core(tracing): handle FrameCommittedInBrowser with processPseudoId
  core/lib/tracehouse/trace-processor.js
  core/test/lib/tracehouse/trace-processor-test.js
Labels: waiting4reviewer

#14840 v10.0.2
  changelog.md
  core/scripts/release/bump-versions.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  docs/plugins.md
  docs/recipes/lighthouse-plugin-example/package.json
  package.json
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
Labels: waiting4reviewer

#14209 docs: fix various typos
  docs/configuration.md
  docs/new-audits.md
  docs/performance-budgets.md
  docs/throttling.md
Labels: waiting4reviewer

#14842 report: consistently use our monospace font stack
  report/assets/styles.css
  report/renderer/components.js
Labels: waiting4reviewer

#14855 core(audit): update link for source maps to chrome developer docs
  core/audits/valid-source-maps.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  report/test-assets/lhr-8.5.0.json
  shared/localization/locales/ar-XB.json
  shared/localization/locales/ar.json
  shared/localization/locales/bg.json
  shared/localization/locales/ca.json
  shared/localization/locales/cs.json
  shared/localization/locales/da.json
  shared/localization/locales/de.json
  shared/localization/locales/el.json
  shared/localization/locales/en-GB.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XA.json
  shared/localization/locales/en-XL.json
  shared/localization/locales/es-419.json
  shared/localization/locales/es.json
  shared/localization/locales/fi.json
  shared/localization/locales/fil.json
  shared/localization/locales/fr.json
  shared/localization/locales/he.json
  shared/localization/locales/hi.json
  shared/localization/locales/hr.json
  shared/localization/locales/hu.json
  shared/localization/locales/id.json
  shared/localization/locales/it.json
  shared/localization/locales/ja.json
  shared/localization/locales/ko.json
  shared/localization/locales/lt.json
  shared/localization/locales/lv.json
  shared/localization/locales/nl.json
  shared/localization/locales/no.json
  shared/localization/locales/pl.json
  shared/localization/locales/pt-PT.json
  shared/localization/locales/pt.json
  shared/localization/locales/ro.json
  shared/localization/locales/ru.json
  shared/localization/locales/sk.json
  shared/localization/locales/sl.json
  shared/localization/locales/sr-Latn.json
  shared/localization/locales/sr.json
  shared/localization/locales/sv.json
  shared/localization/locales/ta.json
  shared/localization/locales/te.json
  shared/localization/locales/th.json
  shared/localization/locales/tr.json
  shared/localization/locales/uk.json
  shared/localization/locales/vi.json
  shared/localization/locales/zh-HK.json
  shared/localization/locales/zh-TW.json
  shared/localization/locales/zh.json
  treemap/app/debug.json
Labels: land-when-ci-is-green, waiting4reviewer

#14851 clients(viewer): rework landing with link to lhci diff tool
  viewer/app/index.html
  viewer/app/src/lighthouse-report-viewer.js
  viewer/app/styles/viewer.css
Labels: land-when-ci-is-green, waiting4reviewer

#14863 deps(testdouble): update, move off forked quibble
  package.json
  yarn.lock
Labels: waiting4reviewer

#14655 report: group third-party entities
  core/audits/audit.js
  core/audits/bootup-time.js
  core/audits/byte-efficiency/byte-efficiency-audit.js
  core/audits/byte-efficiency/total-byte-weight.js
  core/audits/byte-efficiency/uses-long-cache-ttl.js
  core/audits/long-tasks.js
  core/audits/mainthread-work-breakdown.js
  core/audits/network-rtt.js
  core/audits/network-server-latency.js
  core/audits/performance-budget.js
  core/audits/prioritize-lcp-image.js
  core/audits/third-party-summary.js
  core/audits/timing-budget.js
  core/audits/uses-rel-preconnect.js
  core/audits/uses-rel-preload.js
  core/audits/work-during-interaction.js
  core/lib/lighthouse-compatibility.js
  core/runner.js
  core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
  core/test/audits/byte-efficiency/total-byte-weight-test.js
  core/test/audits/byte-efficiency/uses-long-cache-ttl-test.js
  core/test/audits/work-during-interaction-test.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/lib/lighthouse-compatibility-test.js
  core/test/results/sample_v2.json
  proto/lighthouse-result.proto
  report/assets/styles.css
  report/renderer/components.js
  report/renderer/details-renderer.js
  report/renderer/report-renderer.js
  report/renderer/report-ui-features.js
  report/renderer/report-utils.js
  report/test/renderer/details-renderer-test.js
  report/test/renderer/report-ui-features-test.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  types/lhr/audit-details.d.ts
Labels: waiting4reviewer, 10.1

#14862 tests(devtools): reenable `issues-mixed-content`
  cli/test/smokehouse/config/exclusions.js
Labels: waiting4reviewer

#14865 clients(viewer): link to diff tool's new URL
  viewer/app/index.html
Labels: waiting4reviewer

#14869 core(tap-targets): update audit description
  core/audits/seo/tap-targets.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: waiting4reviewer

#14873 report: update table hover shades
  report/assets/styles.css
  report/renderer/components.js
Labels: waiting4reviewer

#14874 clients(bundled): include soft navigation plugin
  build/build-bundle.js
  package.json
  yarn.lock
Labels: waiting4reviewer

#14877 misc: fix typos of overridden
  cli/bin.js
  cli/test/fixtures/dobetterweb/dbw_tester.html
  core/audits/audit.js
  core/lib/i18n/i18n.js
  core/lib/network-request.js
  core/scripts/pptr-run-devtools.js
  core/scripts/roll-to-devtools.sh
  core/test/legacy/gather/gather-runner-test.js
  report/test/renderer/details-renderer-test.js
  types/artifacts.d.ts
Labels: waiting4reviewer

#14866 tests: fix seo-tap-targets in high DPI
  cli/test/fixtures/seo/seo-tap-targets.html
Labels: land-when-ci-is-green, waiting4reviewer

#14883 deps: upgrade soft navigation plugin
  package.json
  yarn.lock
Labels: waiting4reviewer

#14751 misc: replace deprecated command with environment file
  .github/workflows/publish.yml
Labels: waiting4reviewer

#14827 core(legacy-javascript): add focus-visible polyfill
  core/audits/byte-efficiency/legacy-javascript.js
  core/audits/byte-efficiency/polyfill-graph-data.json
  core/scripts/legacy-javascript/create-polyfill-size-estimation.js
  core/scripts/legacy-javascript/run.js
  core/test/audits/byte-efficiency/legacy-javascript-test.js
Labels: waiting4reviewer

#14901 core(trace-processor): support single process trace
  core/lib/tracehouse/trace-processor.js
  core/test/lib/tracehouse/trace-processor-test.js
Labels: waiting4reviewer

#14890 core(uses-responsive-images-snapshot): ignore CSS images
  core/audits/byte-efficiency/uses-responsive-images-snapshot.js
Labels: waiting4reviewer

#14910 clients(lr): remove FCP 3G from config
  core/config/lr-mobile-config.js
Labels: waiting4reviewer

#14889 deps: upgrade `http-link-header` and node polyfills
  cli/test/smokehouse/lighthouse-runners/bundle.js
  core/lib/asset-saver.js
  package.json
  yarn.lock
Labels: waiting4reviewer

#14918 core(doctype): handle optional trace correctly
  core/audits/dobetterweb/doctype.js
  core/test/audits/dobetterweb/doctype-test.js
Labels: land-when-ci-is-green, waiting4reviewer

#14911 core: correctly truncate unicode strings
  cli/test/smokehouse/test-definitions/byte-efficiency.js
  core/audits/audit.js
  core/audits/byte-efficiency/unminified-javascript.js
  core/computed/unused-css.js
  core/gather/driver/prepare.js
  core/lib/page-functions.js
  core/lib/url-utils.js
  core/test/computed/unused-css-test.js
  shared/test/util-test.js
  shared/tsconfig.json
  shared/util.js
Labels: waiting4reviewer

#14402 core(cls): ignore `had_recent_input` by timing window
  core/computed/metrics/cumulative-layout-shift.js
  core/lib/tracehouse/trace-processor.js
  core/test/computed/metrics/cumulative-layout-shift-test.js
  types/artifacts.d.ts
Labels: waiting4reviewer

#14921 core: cap byte-efficiency-audit scores to a max of 1
  core/audits/byte-efficiency/byte-efficiency-audit.js
  core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
Labels: land-when-ci-is-green, waiting4reviewer

#14924 cli: fix `--channel` flag
  cli/run.js
Labels: waiting4reviewer

#14923 v10.1.0
  changelog.md
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  docs/plugins.md
  docs/recipes/lighthouse-plugin-example/package.json
  package.json
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
Labels: waiting4reviewer

#14925 core: collect fetchpriority for images and link rel preload
  cli/test/fixtures/dobetterweb/dbw_tester.html
  cli/test/fixtures/preload.html
  cli/test/smokehouse/test-definitions/dobetterweb.js
  cli/test/smokehouse/test-definitions/perf-preload.js
  core/gather/gatherers/image-elements.js
  core/gather/gatherers/link-elements.js
  core/test/results/artifacts/artifacts.json
  types/artifacts.d.ts
  types/internal/node.d.ts
Labels: land-when-ci-is-green

#14931 tests(devtools): sync e2e
  third-party/devtools-tests/e2e/lighthouse/devtools-settings_test.ts
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
  third-party/devtools-tests/e2e/lighthouse/snapshot_test.ts
  third-party/devtools-tests/e2e/lighthouse/start-view_test.ts
  third-party/devtools-tests/e2e/lighthouse/timespan_test.ts
Labels: land-when-ci-is-green, waiting4reviewer

#14936 core(link-elements): gracefully handle header parser error
  core/gather/gatherers/link-elements.js
  core/test/gather/gatherers/link-elements-test.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: waiting4reviewer
