Repository GoogleChrome/lighthouse, pull requests merged in 2023-10, with the labels that each got.

#15445 report: sort performance audits based on impact
  cli/test/smokehouse/__snapshots__/report-assert-test.js.snap
  core/audits/audit.js
  core/audits/byte-efficiency/uses-long-cache-ttl.js
  core/audits/metrics/cumulative-layout-shift.js
  core/audits/metrics/first-contentful-paint.js
  core/audits/metrics/largest-contentful-paint.js
  core/audits/metrics/speed-index.js
  core/audits/metrics/total-blocking-time.js
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  proto/lighthouse-result.proto
  report/assets/styles.css
  report/assets/templates.html
  report/renderer/components.js
  report/renderer/performance-category-renderer.js
  report/test/renderer/performance-category-renderer-test.js
  shared/statistics.js
  shared/test/statistics-test.js
  shared/util.js
  types/audit.d.ts
  types/lhr/audit-result.d.ts
Labels: waiting4reviewer

#15197 core(long-tasks): compute TBT impact
  core/audits/long-tasks.js
  core/test/audits/long-tasks-test.js
Labels: waiting4reviewer

#15518 tests(devtools): remove usage of frontend globals
  core/scripts/pptr-run-devtools.js
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
Labels: land-when-ci-is-green

#15521 misc: tweak dependabot ecosystem value
  .github/dependabot.yml
Labels: waiting4reviewer

#14915 misc(bot): delete stale git bot rules
  core/scripts/git3po-rules/cannot-attach-to-this-target.yaml
  core/scripts/git3po-rules/failed-document-request.yaml
  core/scripts/git3po-rules/failed-to-construct-url.yaml
  core/scripts/git3po-rules/invalid-url.yaml
  core/scripts/git3po-rules/lock-resolved.yaml
  core/scripts/git3po-rules/multiple-tabs.yaml
  core/scripts/git3po-rules/no-fcp.yaml
  core/scripts/git3po-rules/no-tabid-set-for-sendcommand.yaml
  core/scripts/git3po-rules/page-hung.yaml
  core/scripts/git3po-rules/parsing-problem.yaml
  core/scripts/git3po-rules/read-failed.yaml
  core/scripts/git3po-rules/resolve-current-tab.yaml
  core/scripts/git3po-rules/tracing-start-wasnt-found.yaml
  core/scripts/git3po-rules/tracing.yaml
  core/scripts/git3po-rules/url-runner.yaml
Labels: land-when-ci-is-green, waiting4reviewer

#15395 docs(readme): edit description of the PageVitals tool
  readme.md
Labels: land-when-ci-is-green, waiting4reviewer

#15524 v11.2.0
  changelog.md
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  docs/plugins.md
  docs/recipes/lighthouse-plugin-example/package.json
  package.json
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
Labels: waiting4reviewer

#15534 misc: update web.dev URLs
  cli/test/smokehouse/__snapshots__/report-assert-test.js.snap
  core/audits/byte-efficiency/legacy-javascript.js
  core/audits/image-size-responsive.js
  core/audits/layout-shift-elements.js
  core/audits/lcp-lazy-loaded.js
  core/audits/long-tasks.js
  core/audits/metrics/cumulative-layout-shift.js
  core/audits/metrics/interaction-to-next-paint.js
  core/audits/metrics/largest-contentful-paint.js
  core/audits/no-unload-listeners.js
  core/audits/preload-fonts.js
  core/audits/prioritize-lcp-image.js
  core/audits/unsized-images.js
  core/audits/work-during-interaction.js
  core/config/default-config.js
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  docs/performance-budgets.md
  docs/user-flows.md
  docs/v8-perf-faq.md
  report/test/generator/report-generator-test.js
  report/test/renderer/dom-test.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: waiting4reviewer

#15543 core(accessibility): hide experimental axe rules
  core/config/default-config.js
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  report/test/generator/report-generator-test.js
  report/test/renderer/category-renderer-test.js
Labels: waiting4reviewer

#15397 core: remove config navigations
  core/config/config.js
  core/config/constants.js
  core/config/filters.js
  core/config/validation.js
  core/gather/base-artifacts.js
  core/gather/driver/navigation.js
  core/gather/driver/prepare.js
  core/gather/navigation-runner.js
  core/lib/navigation-error.js
  core/test/config/config-test.js
  core/test/config/filters-test.js
  core/test/config/validation-test.js
  core/test/fixtures/user-flows/artifacts/step0/artifacts.json
  core/test/fixtures/user-flows/artifacts/step1/artifacts.json
  core/test/fixtures/user-flows/artifacts/step2/artifacts.json
  core/test/fixtures/user-flows/artifacts/step3/artifacts.json
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/gather/base-artifacts-test.js
  core/test/gather/driver/prepare-test.js
  core/test/gather/navigation-runner-test.js
  core/test/lib/navigation-error-test.js
  core/test/results/artifacts/artifacts.json
  core/test/results/sample_v2.json
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
  types/config.d.ts
Labels: waiting4reviewer

#14419 tests: use --headless=new for all smoketests
  .github/workflows/devtools.yml
  .github/workflows/smoke.yml
  cli/test/smokehouse/frontends/smokehouse-bin.js
  cli/test/smokehouse/lighthouse-runners/bundle.js
  cli/test/smokehouse/lighthouse-runners/cli.js
  cli/test/smokehouse/lighthouse-runners/devtools.js
  cli/test/smokehouse/smokehouse.js
  docs/headless-chrome.md
  types/internal/smokehouse.d.ts
Labels: waiting4reviewer

#15550 tests(devtools): sync e2e
  third-party/devtools-tests/e2e/lighthouse/devtools-settings_test.ts
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
  third-party/devtools-tests/e2e/lighthouse/snapshot_test.ts
  third-party/devtools-tests/e2e/lighthouse/start-view_test.ts
  third-party/devtools-tests/e2e/lighthouse/timespan_test.ts
Labels: waiting4reviewer

#15553 core(inspector-issues): add cookie deprecation issue
  core/gather/gatherers/inspector-issues.js
  core/test/audits/dobetterweb/inspector-issues-test.js
  core/test/gather/gatherers/inspector-issues-test.js
  package.json
  third-party/chromium-synchronization/inspector-issueAdded-types-test.js
  third-party/devtools-tests/e2e/lighthouse/devtools-settings_test.ts
  types/artifacts.d.ts
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer

#15554 report: use normal gauge if performance score is null
  report/renderer/performance-category-renderer.js
Labels: waiting4reviewer

#15555 tests(devtools): extend protocol timeout for load
  core/scripts/pptr-run-devtools.js
Labels: land-when-ci-is-green, waiting4reviewer

#15557 deps: upgrade puppeteer to 21.4.0
  build/build-bundle.js
  package.json
  types/internal/rxjs.d.ts
  yarn.lock
Labels: waiting4reviewer

#15494 core: create flag to prevent fatal error on bad status code
  cli/cli-flags.js
  core/config/constants.js
  core/gather/navigation-runner.js
  core/lib/navigation-error.js
  core/scripts/i18n/collect-strings.js
  core/test/fixtures/user-flows/artifacts/step0/artifacts.json
  core/test/fixtures/user-flows/artifacts/step1/artifacts.json
  core/test/fixtures/user-flows/artifacts/step2/artifacts.json
  core/test/fixtures/user-flows/artifacts/step3/artifacts.json
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/lib/navigation-error-test.js
  core/test/results/artifacts/artifacts.json
  core/test/results/sample_v2.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  types/lhr/settings.d.ts
Labels: waiting4reviewer

#15508 core: add `clearStorageTypes` option
  core/config/constants.js
  core/gather/driver/prepare.js
  core/gather/driver/storage.js
  core/gather/navigation-runner.js
  core/test/fixtures/user-flows/artifacts/step0/artifacts.json
  core/test/fixtures/user-flows/artifacts/step1/artifacts.json
  core/test/fixtures/user-flows/artifacts/step2/artifacts.json
  core/test/fixtures/user-flows/artifacts/step3/artifacts.json
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/gather/driver/prepare-test.js
  core/test/gather/driver/storage-test.js
  core/test/gather/navigation-runner-test.js
  core/test/results/artifacts/artifacts.json
  core/test/results/sample_v2.json
  report/test-assets/lhr-3.0.0.json
  report/test-assets/lhr-4.3.0.json
  report/test-assets/lhr-5.0.0.json
  report/test-assets/lhr-6.0.0.json
  report/test-assets/lhr-8.5.0.json
  treemap/app/debug.json
  types/lhr/settings.d.ts
Labels: waiting4reviewer

#15566 deps: upgrade `lighthouse-stack-packs` to 1.12.1
  package.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  yarn.lock
Labels: waiting4reviewer
