Repository GoogleChrome/lighthouse, pull requests merged in 2023-06, with the labels that each got.

#15108 docs(readme): add unit test tips
  readme.md
Labels: waiting4reviewer

#15144 core(inspector-issues): add `stylesheetLoadingIssue`
  core/gather/gatherers/inspector-issues.js
  core/lib/tracehouse/trace-processor.js
  core/test/gather/gatherers/inspector-issues-test.js
  package.json
  third-party/chromium-synchronization/inspector-issueAdded-types-test.js
  types/artifacts.d.ts
  yarn.lock
Labels: waiting4reviewer

#15149 core(inspector-issues): add `federatedAuthUserInfoRequestIssue`
  core/gather/gatherers/inspector-issues.js
  core/test/gather/gatherers/inspector-issues-test.js
  package.json
  third-party/chromium-synchronization/inspector-issueAdded-types-test.js
  types/artifacts.d.ts
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer

#15121 deps(es-main): update to 1.2.0
  package.json
  types/internal/es-main.d.ts
  yarn.lock
Labels: waiting4reviewer

#15126 core(time-to-first-byte): use receiveHeadersStart
  core/computed/metrics/time-to-first-byte.js
  core/lib/network-request.js
  core/test/computed/metrics/time-to-first-byte-test.js
  core/test/lib/network-request-test.js
Labels: land-when-ci-is-green, waiting4reviewer

#15122 core(cumulative-layout-shift): remove totalCumulativeLayoutShift
  cli/test/smokehouse/__snapshots__/report-assert-test.js.snap
  cli/test/smokehouse/test-definitions/perf-frame-metrics.js
  core/audits/metrics.js
  core/computed/metrics/cumulative-layout-shift.js
  core/computed/metrics/timing-summary.js
  core/test/audits/__snapshots__/metrics-test.js.snap
  core/test/audits/metrics-test.js
  core/test/audits/metrics/cumulative-layout-shift-test.js
  core/test/computed/metrics/cumulative-layout-shift-test.js
  core/test/computed/metrics/timing-summary-test.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: waiting4reviewer

#15100 core(network-analyzer): include 0 start times in rtt estimate
  core/lib/dependency-graph/simulator/network-analyzer.js
  core/test/fixtures/lantern-baseline-computed-values.json
  core/test/lib/dependency-graph/simulator/network-analyzer-test.js
Labels: waiting4reviewer

#15137 deps: update to latest chrome-devtools-frontend
  build/build-cdt-lib.js
  build/build-cdt-strings.js
  core/audits/deprecations.js
  core/lib/bf-cache-strings.js
  core/lib/cdt/generated/SourceMap.js
  core/lib/deprecation-description.js
  core/lib/deprecations-strings.js
  core/scripts/i18n/collect-strings.js
  core/test/audits/deprecations-test.js
  package.json
  shared/localization/locales/ar-XB.json
  shared/localization/locales/ar.json
  shared/localization/locales/bg.json
  shared/localization/locales/ca.json
  shared/localization/locales/cs.json
  shared/localization/locales/da.json
  shared/localization/locales/de.json
  shared/localization/locales/el.json
  shared/localization/locales/en-GB.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XA.json
  shared/localization/locales/en-XL.json
  shared/localization/locales/es-419.json
  shared/localization/locales/es.json
  shared/localization/locales/fi.json
  shared/localization/locales/fil.json
  shared/localization/locales/fr.json
  shared/localization/locales/he.json
  shared/localization/locales/hi.json
  shared/localization/locales/hr.json
  shared/localization/locales/hu.json
  shared/localization/locales/id.json
  shared/localization/locales/it.json
  shared/localization/locales/ja.json
  shared/localization/locales/ko.json
  shared/localization/locales/lt.json
  shared/localization/locales/lv.json
  shared/localization/locales/nl.json
  shared/localization/locales/no.json
  shared/localization/locales/pl.json
  shared/localization/locales/pt-PT.json
  shared/localization/locales/pt.json
  shared/localization/locales/ro.json
  shared/localization/locales/ru.json
  shared/localization/locales/sk.json
  shared/localization/locales/sl.json
  shared/localization/locales/sr-Latn.json
  shared/localization/locales/sr.json
  shared/localization/locales/sv.json
  shared/localization/locales/ta.json
  shared/localization/locales/te.json
  shared/localization/locales/th.json
  shared/localization/locales/tr.json
  shared/localization/locales/uk.json
  shared/localization/locales/vi.json
  shared/localization/locales/zh-HK.json
  shared/localization/locales/zh-TW.json
  shared/localization/locales/zh.json
  yarn.lock
Labels: waiting4reviewer

#15165 deps: upgrade axe-core to 4.7.2
  package.json
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer

#15164 deps: upgrade puppeteer to 20.7.1
  package.json
  yarn.lock
Labels: land-when-ci-is-green

#15166 deps: upgrade third-party-web to 0.23.0
  package.json
  yarn.lock
Labels: land-when-ci-is-green

#15157 core(uses-rel-preconnect): handle 0 connect start timings
  core/audits/uses-rel-preconnect.js
Labels: land-when-ci-is-green, waiting4reviewer

#15158 core(network-analyzer): estimate from lrStatistics
  core/lib/dependency-graph/simulator/network-analyzer.js
  core/lib/network-request.js
  core/test/lib/dependency-graph/simulator/network-analyzer-test.js
Labels: waiting4reviewer

#15156 core(server-response-time): fix for lightrider
  core/audits/server-response-time.js
  core/test/audits/server-response-time-test.js
Labels: land-when-ci-is-green, waiting4reviewer

#15168 i18n: import
  shared/localization/locales/ar-XB.json
  shared/localization/locales/ar.json
  shared/localization/locales/bg.json
  shared/localization/locales/ca.json
  shared/localization/locales/cs.json
  shared/localization/locales/da.json
  shared/localization/locales/de.json
  shared/localization/locales/el.json
  shared/localization/locales/en-GB.json
  shared/localization/locales/en-XA.json
  shared/localization/locales/es-419.json
  shared/localization/locales/es.json
  shared/localization/locales/fi.json
  shared/localization/locales/fil.json
  shared/localization/locales/fr.json
  shared/localization/locales/he.json
  shared/localization/locales/hi.json
  shared/localization/locales/hr.json
  shared/localization/locales/hu.json
  shared/localization/locales/id.json
  shared/localization/locales/it.json
  shared/localization/locales/ja.json
  shared/localization/locales/ko.json
  shared/localization/locales/lt.json
  shared/localization/locales/lv.json
  shared/localization/locales/nl.json
  shared/localization/locales/no.json
  shared/localization/locales/pl.json
  shared/localization/locales/pt-PT.json
  shared/localization/locales/pt.json
  shared/localization/locales/ro.json
  shared/localization/locales/ru.json
  shared/localization/locales/sk.json
  shared/localization/locales/sl.json
  shared/localization/locales/sr-Latn.json
  shared/localization/locales/sr.json
  shared/localization/locales/sv.json
  shared/localization/locales/ta.json
  shared/localization/locales/te.json
  shared/localization/locales/th.json
  shared/localization/locales/tr.json
  shared/localization/locales/uk.json
  shared/localization/locales/vi.json
  shared/localization/locales/zh-HK.json
  shared/localization/locales/zh-TW.json
  shared/localization/locales/zh.json
Labels: land-when-ci-is-green, waiting4reviewer

#15169 v10.3.0
  changelog.md
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  docs/plugins.md
  docs/recipes/lighthouse-plugin-example/package.json
  package.json
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
Labels: waiting4reviewer

#15171 core(stacks): add wix
  core/lib/stack-packs.js
  core/test/lib/stack-packs-test.js
  package.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  yarn.lock
Labels: land-when-ci-is-green

#15099 core(non-composited-animations): add CLS savings as always 0
  core/audits/non-composited-animations.js
  core/test/audits/non-composited-animations-test.js
Labels: waiting4reviewer

#15177 tests(ci): skip puppeteer Chrome download
  .github/workflows/ci.yml
  .github/workflows/devtools.yml
  .github/workflows/package-test.yml
  .github/workflows/smoke.yml
  .github/workflows/unit.yml
  core/test/gather/gatherers/accessibility-test.js
  docs/recipes/integration-test/example-lh-auth.test.js
  flow-report/test/flow-report-pptr-test.ts
  report/test/renderer/report-renderer-axe-test.js
  treemap/test/treemap-test-pptr.js
  viewer/test/viewer-test-pptr.js
Labels: waiting4reviewer

#15176 core(work-during-interaction): add INP savings
  core/audits/work-during-interaction.js
  core/test/audits/work-during-interaction-test.js
Labels: land-when-ci-is-green, waiting4reviewer

#15071 core(viewport): add INP savings
  core/audits/viewport.js
  core/test/audits/viewport-test.js
Labels: waiting4reviewer

#15159 new_audit: aria-dialog-name, aria-text, link-in-text-block, select-name
  cli/test/fixtures/a11y/a11y_tester.html
  cli/test/smokehouse/test-definitions/a11y.js
  core/audits/accessibility/aria-dialog-name.js
  core/audits/accessibility/aria-text.js
  core/audits/accessibility/link-in-text-block.js
  core/audits/accessibility/select-name.js
  core/config/default-config.js
  core/gather/gatherers/accessibility.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  core/test/scenarios/__snapshots__/api-test-pptr.js.snap
  report/test/generator/report-generator-test.js
  report/test/renderer/category-renderer-test.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
  third-party/devtools-tests/e2e/lighthouse/snapshot_test.ts
Labels: waiting4reviewer

#15181 report: use fixed position for hidden radios
  report/assets/styles.css
  report/renderer/components.js
Labels: land-when-ci-is-green, waiting4reviewer

#15189 core: support ts targets before es2022
  core/lib/lh-error.js
  docs/recipes/type-checking/package.json
Labels: land-when-ci-is-green, waiting4reviewer

#15188 tests(smoke): expect server-response-time to be greater than 0
  cli/test/smokehouse/test-definitions/perf-preload.js
Labels: waiting4reviewer

#15152 core(link-text): add tamil keywords to blocklist
  core/audits/seo/link-text.js
Labels: waiting4reviewer
