Repository GoogleChrome/lighthouse, pull requests merged in 2023-05, with the labels that each got.

#15028 core(predictive-perf): add URL as requiredArtifact
  core/audits/predictive-perf.js
Labels: waiting4reviewer

#15006 core: use target type instead of session for oopif
  cli/test/fixtures/oopif-scripts-timespan.html
  cli/test/fixtures/oopif-simple-page.html
  core/audits/network-requests.js
  core/gather/driver/target-manager.js
  core/gather/gatherers/dobetterweb/optimized-images.js
  core/gather/gatherers/dobetterweb/response-compression.js
  core/gather/gatherers/script-elements.js
  core/gather/gatherers/scripts.js
  core/legacy/gather/connections/connection.js
  core/lib/network-recorder.js
  core/lib/network-request.js
  core/test/fixtures/fraggle-rock/artifacts/step0/defaultPass.devtoolslog.json
  core/test/fixtures/fraggle-rock/artifacts/step1/defaultPass.devtoolslog.json
  core/test/fixtures/fraggle-rock/artifacts/step3/defaultPass.devtoolslog.json
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/gather/driver/target-manager-test.js
  core/test/gather/gatherers/bf-cache-failures-test.js
  core/test/gather/gatherers/dobetterweb/optimized-images-test.js
  core/test/gather/gatherers/dobetterweb/response-compression-test.js
  core/test/gather/gatherers/dobetterweb/tags-blocking-first-paint-test.js
  core/test/gather/gatherers/script-elements-test.js
  core/test/lib/network-recorder-test.js
  core/test/network-records-to-devtools-log.js
  core/test/results/artifacts/defaultPass.devtoolslog.json
  core/test/results/sample_v2.json
  core/test/scenarios/api-test-pptr.js
  core/test/scenarios/pptr-test-utils.js
  types/protocol.d.ts
Labels: waiting4reviewer

#15033 deps(axe-core): upgrade to 4.7.0
  cli/test/smokehouse/test-definitions/a11y.js
  core/audits/accessibility/accesskeys.js
  core/audits/accessibility/aria-allowed-attr.js
  core/audits/accessibility/aria-command-name.js
  core/audits/accessibility/aria-hidden-body.js
  core/audits/accessibility/aria-hidden-focus.js
  core/audits/accessibility/aria-input-field-name.js
  core/audits/accessibility/aria-meter-name.js
  core/audits/accessibility/aria-progressbar-name.js
  core/audits/accessibility/aria-required-attr.js
  core/audits/accessibility/aria-required-children.js
  core/audits/accessibility/aria-required-parent.js
  core/audits/accessibility/aria-roles.js
  core/audits/accessibility/aria-toggle-field-name.js
  core/audits/accessibility/aria-tooltip-name.js
  core/audits/accessibility/aria-treeitem-name.js
  core/audits/accessibility/aria-valid-attr-value.js
  core/audits/accessibility/aria-valid-attr.js
  core/audits/accessibility/button-name.js
  core/audits/accessibility/bypass.js
  core/audits/accessibility/color-contrast.js
  core/audits/accessibility/definition-list.js
  core/audits/accessibility/dlitem.js
  core/audits/accessibility/document-title.js
  core/audits/accessibility/duplicate-id-active.js
  core/audits/accessibility/duplicate-id-aria.js
  core/audits/accessibility/form-field-multiple-labels.js
  core/audits/accessibility/frame-title.js
  core/audits/accessibility/heading-order.js
  core/audits/accessibility/html-has-lang.js
  core/audits/accessibility/html-lang-valid.js
  core/audits/accessibility/image-alt.js
  core/audits/accessibility/input-image-alt.js
  core/audits/accessibility/label.js
  core/audits/accessibility/link-name.js
  core/audits/accessibility/list.js
  core/audits/accessibility/listitem.js
  core/audits/accessibility/meta-refresh.js
  core/audits/accessibility/meta-viewport.js
  core/audits/accessibility/object-alt.js
  core/audits/accessibility/tabindex.js
  core/audits/accessibility/td-headers-attr.js
  core/audits/accessibility/th-has-data-cells.js
  core/audits/accessibility/valid-lang.js
  core/audits/accessibility/video-caption.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  package.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  yarn.lock
Labels: waiting4reviewer

#15037 deps(puppeteer): upgrade to 20.1.0
  package.json
  yarn.lock
Labels: waiting4reviewer

#15039 core(stack-packs): sort packs in order we defined them
  core/lib/stack-packs.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/lib/stack-packs-test.js
Labels: land-when-ci-is-green

#14891 core(largest-contentful-paint-element): add phases table
  cli/test/smokehouse/test-definitions/perf-frame-metrics.js
  cli/test/smokehouse/test-definitions/perf-trace-elements.js
  core/audits/largest-contentful-paint-element.js
  core/test/audits/largest-contentful-paint-element-test.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: land-when-ci-is-green, waiting4reviewer

#15038 deps(lighthouse-stack-packs): upgrade to 1.10.0
  core/lib/stack-packs.js
  core/scripts/i18n/collect-strings.js
  core/test/lib/stack-packs-test.js
  package.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  yarn.lock
Labels: waiting4reviewer

#14963 core(driver): warn about remaining inflight requests urls
  core/gather/driver/wait-for-condition.js
  core/test/gather/driver/wait-for-condition-test.js
Labels: waiting4reviewer

#15041 i18n: import
  shared/localization/locales/ar-XB.json
  shared/localization/locales/ar.json
  shared/localization/locales/bg.json
  shared/localization/locales/ca.json
  shared/localization/locales/cs.json
  shared/localization/locales/da.json
  shared/localization/locales/de.json
  shared/localization/locales/el.json
  shared/localization/locales/en-GB.json
  shared/localization/locales/en-XA.json
  shared/localization/locales/es-419.json
  shared/localization/locales/es.json
  shared/localization/locales/fi.json
  shared/localization/locales/fil.json
  shared/localization/locales/fr.json
  shared/localization/locales/he.json
  shared/localization/locales/hi.json
  shared/localization/locales/hr.json
  shared/localization/locales/hu.json
  shared/localization/locales/id.json
  shared/localization/locales/it.json
  shared/localization/locales/ja.json
  shared/localization/locales/ko.json
  shared/localization/locales/lt.json
  shared/localization/locales/lv.json
  shared/localization/locales/nl.json
  shared/localization/locales/no.json
  shared/localization/locales/pl.json
  shared/localization/locales/pt-PT.json
  shared/localization/locales/pt.json
  shared/localization/locales/ro.json
  shared/localization/locales/ru.json
  shared/localization/locales/sk.json
  shared/localization/locales/sl.json
  shared/localization/locales/sr-Latn.json
  shared/localization/locales/sr.json
  shared/localization/locales/sv.json
  shared/localization/locales/ta.json
  shared/localization/locales/te.json
  shared/localization/locales/th.json
  shared/localization/locales/tr.json
  shared/localization/locales/uk.json
  shared/localization/locales/vi.json
  shared/localization/locales/zh-HK.json
  shared/localization/locales/zh-TW.json
  shared/localization/locales/zh.json
Labels: waiting4reviewer

#15045 core: add flow methods to cjs entry
  cli/test/smokehouse/test-definitions/dobetterweb.js
  core/index.cjs
  package.json
Labels: land-when-ci-is-green, waiting4reviewer

#15046 v10.2.0
  changelog.md
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  core/test/scenarios/api-test-pptr.js
  docs/plugins.md
  docs/recipes/lighthouse-plugin-example/package.json
  package.json
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
Labels: waiting4reviewer

#15050 tests: rebaseline inspector issue detail types
  core/gather/gatherers/inspector-issues.js
  core/test/audits/dobetterweb/inspector-issues-test.js
  core/test/fixtures/fraggle-rock/artifacts/step0/artifacts.json
  core/test/fixtures/fraggle-rock/artifacts/step1/artifacts.json
  core/test/fixtures/fraggle-rock/artifacts/step3/artifacts.json
  core/test/gather/gatherers/inspector-issues-test.js
  core/test/results/artifacts/artifacts.json
  third-party/chromium-synchronization/inspector-issueAdded-types-test.js
  types/artifacts.d.ts
Labels: land-when-ci-is-green, waiting4reviewer

#15057 tests: remove most usages of `afterPass`
  core/test/gather/gatherers/accessibility-test.js
  core/test/gather/gatherers/cache-contents-test.js
  core/test/gather/gatherers/console-messages-test.js
  core/test/gather/gatherers/dobetterweb/optimized-images-test.js
  core/test/gather/gatherers/dobetterweb/tags-blocking-first-paint-test.js
  core/test/gather/gatherers/global-listeners-test.js
  core/test/gather/gatherers/link-elements-test.js
  core/test/gather/gatherers/seo/font-size-test.js
  core/test/gather/gatherers/viewport-dimensions-test.js
  core/test/network-records-to-devtools-log.js
Labels: land-when-ci-is-green, waiting4reviewer

#15059 report: update keyframes for confetti animation
  report/assets/templates.html
  report/renderer/components.js
Labels: waiting4reviewer

#14997 core: add metric savings to audit result
  core/audits/server-response-time.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  types/lhr/audit-details.d.ts
  types/lhr/audit-result.d.ts
Labels: waiting4reviewer

#15066 misc(compare-runs): allow for multiple args to lighthouse
  core/scripts/compare-runs.js
  docs/readme.md
Labels: land-when-ci-is-green, waiting4reviewer

#15067 core(trace-elements): use CLS metric event filtering
  core/computed/metrics/cumulative-layout-shift.js
  core/gather/gatherers/trace-elements.js
  core/test/gather/gatherers/trace-elements-test.js
  types/artifacts.d.ts
Labels: waiting4reviewer

#15069 misc(lantern-collect): rebaseline to include new ttfb metric
  core/scripts/lantern/assert-baseline-lantern-values-unchanged.js
  core/scripts/lantern/constants.js
  core/scripts/lantern/print-correlations.js
  core/scripts/lantern/update-baseline-lantern-values.js
  core/test/fixtures/lantern-baseline-computed-values.json
Labels: waiting4reviewer

#15051 new_audit: td-has-header
  cli/test/smokehouse/test-definitions/a11y.js
  core/audits/accessibility/td-has-header.js
  core/config/default-config.js
  core/gather/gatherers/accessibility.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  core/test/scenarios/__snapshots__/api-test-pptr.js.snap
  report/test/generator/report-generator-test.js
  report/test/renderer/category-renderer-test.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
  third-party/devtools-tests/e2e/lighthouse/snapshot_test.ts
Labels: waiting4reviewer

#15017 core(entity-classification): classify chrome extensions into separate entities
  core/computed/entity-classification.js
  core/lib/url-utils.js
  core/test/computed/entity-classification-test.js
  report/test/renderer/details-renderer-test.js
  shared/util.js
Labels: waiting4reviewer

#15089 misc: support node 10 in lighthouse-logger
  lighthouse-logger/package.json
Labels: land-when-ci-is-green

#15077 misc(lantern-collect): add median lhr to golden zip
  core/scripts/lantern/collect/golden.js
  core/scripts/lantern/download-traces.sh
Labels: waiting4reviewer

#15074 core: move metric savings to audit product
  core/audits/server-response-time.js
  core/test/audits/server-response-time-test.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  types/audit.d.ts
  types/lhr/audit-details.d.ts
  types/lhr/audit-result.d.ts
Labels: waiting4reviewer

#15011 docs(readme): add `laravel-lighthouse` to project list
  readme.md
Labels: waiting4reviewer

#15054 core(global-listeners): iterate all execution contexts
  core/gather/driver/target-manager.js
  core/gather/gatherers/global-listeners.js
  core/legacy/gather/driver.js
  core/test/gather/driver-test.js
  core/test/gather/driver/network-monitor-test.js
  core/test/gather/driver/target-manager-test.js
  core/test/scenarios/api-test-pptr.js
  types/gatherer.d.ts
Labels: waiting4reviewer

#15092 report: update error icons
  flow-report/test/wrappers/category-score-test.tsx
  report/assets/styles.css
  report/renderer/category-renderer.js
  report/renderer/components.js
  report/test/renderer/pwa-category-renderer-test.js
Labels: waiting4reviewer

#15097 deps: upgrade third-party-web to 0.22.0
  package.json
  yarn.lock
Labels: waiting4reviewer

#15094 report: append utm query params to stack pack links
  report/renderer/category-renderer.js
  report/renderer/dom.js
  report/test/renderer/dom-test.js
Labels: waiting4reviewer

#15107 core(network-request): simplify recomputeTimesWithResourceTiming
  core/lib/network-request.js
  core/scripts/test-lantern.sh
Labels: waiting4reviewer

#15072 misc(lantern-collect): drop sampling
  core/scripts/lantern/collect/README.md
  core/scripts/lantern/collect/collect.js
  core/scripts/lantern/collect/common.js
  core/scripts/lantern/collect/golden.js
  core/scripts/lantern/run-on-all-assets.js
Labels: land-when-ci-is-green, waiting4reviewer

#15112 tests(smoke): add expectation for lcp-element
  cli/test/smokehouse/test-definitions/dobetterweb.js
Labels: waiting4reviewer

#15111 tests(smoke): remove external resource from dbw
  cli/test/fixtures/dobetterweb/dbw_tester.html
  cli/test/smokehouse/test-definitions/dobetterweb.js
Labels: waiting4reviewer
