Repository GoogleChrome/lighthouse, pull requests merged in 2023-07, with the labels that each got.

#15196 core(unsized-images): add CLS savings as always 0
  core/audits/unsized-images.js
  core/test/audits/unsized-images-test.js
Labels: waiting4reviewer

#15104 core(byte-efficiency): compute FCP & LCP savings
  core/audits/audit.js
  core/audits/byte-efficiency/byte-efficiency-audit.js
  core/lib/dependency-graph/simulator/simulator.js
  core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
Labels: waiting4reviewer

#15047 tests(runner): drop usages of legacy runner
  core/test/runner-test.js
Labels: waiting4reviewer

#15198 core(long-tasks): add more task information to debugData
  core/audits/long-tasks.js
  core/test/audits/long-tasks-test.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
Labels: waiting4reviewer

#15241 tests(issues-mixed-content): use new site for testing
  cli/test/smokehouse/test-definitions/issues-mixed-content.js
Labels: waiting4reviewer

#15243 i18n: import
  shared/localization/locales/ar-XB.json
  shared/localization/locales/ar.json
  shared/localization/locales/bg.json
  shared/localization/locales/ca.json
  shared/localization/locales/cs.json
  shared/localization/locales/da.json
  shared/localization/locales/de.json
  shared/localization/locales/el.json
  shared/localization/locales/en-GB.json
  shared/localization/locales/en-XA.json
  shared/localization/locales/es-419.json
  shared/localization/locales/es.json
  shared/localization/locales/fi.json
  shared/localization/locales/fil.json
  shared/localization/locales/fr.json
  shared/localization/locales/he.json
  shared/localization/locales/hi.json
  shared/localization/locales/hr.json
  shared/localization/locales/hu.json
  shared/localization/locales/id.json
  shared/localization/locales/it.json
  shared/localization/locales/ja.json
  shared/localization/locales/ko.json
  shared/localization/locales/lt.json
  shared/localization/locales/lv.json
  shared/localization/locales/nl.json
  shared/localization/locales/no.json
  shared/localization/locales/pl.json
  shared/localization/locales/pt-PT.json
  shared/localization/locales/pt.json
  shared/localization/locales/ro.json
  shared/localization/locales/ru.json
  shared/localization/locales/sk.json
  shared/localization/locales/sl.json
  shared/localization/locales/sr-Latn.json
  shared/localization/locales/sr.json
  shared/localization/locales/sv.json
  shared/localization/locales/ta.json
  shared/localization/locales/te.json
  shared/localization/locales/th.json
  shared/localization/locales/tr.json
  shared/localization/locales/uk.json
  shared/localization/locales/vi.json
  shared/localization/locales/zh-HK.json
  shared/localization/locales/zh-TW.json
  shared/localization/locales/zh.json
Labels: waiting4reviewer

#15244 v10.4.0
  changelog.md
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  docs/plugins.md
  docs/recipes/lighthouse-plugin-example/package.json
  package.json
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
Labels: waiting4reviewer

#15250 tests(devtools): sync e2e
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
  third-party/devtools-tests/e2e/lighthouse/snapshot_test.ts
  third-party/devtools-tests/e2e/lighthouse/timespan_test.ts
Labels: waiting4reviewer

#15238 core(render-blocking-resources): add FCP and LCP savings
  core/audits/byte-efficiency/render-blocking-resources.js
  core/test/audits/byte-efficiency/render-blocking-resources-test.js
Labels: waiting4reviewer

#15249 tests(smoke): drop legacy support
  .github/workflows/package-test.yml
  .github/workflows/smoke.yml
  cli/test/smokehouse/frontends/smokehouse-bin.js
  cli/test/smokehouse/lighthouse-runners/bundle.js
  cli/test/smokehouse/lighthouse-runners/cli.js
  cli/test/smokehouse/lighthouse-runners/devtools.js
  cli/test/smokehouse/readme.md
  cli/test/smokehouse/report-assert.js
  cli/test/smokehouse/smokehouse.js
  cli/test/smokehouse/test-definitions/errors-expired-ssl.js
  cli/test/smokehouse/test-definitions/errors-infinite-loop.js
  cli/test/smokehouse/test-definitions/oopif-scripts.js
  clients/devtools/devtools-entry.js
  core/scripts/pptr-run-devtools.js
  types/internal/smokehouse.d.ts
Labels: waiting4reviewer

#15252 core: remove `first-contentful-paint-3g` audit
  core/audits/metrics/first-contentful-paint-3g.js
  core/test/audits/metrics/first-contentful-paint-3g-test.js
Labels: waiting4reviewer, breaking

#15253 core: remove legacy runner
  build/build-bundle.js
  cli/cli-flags.js
  cli/run.js
  cli/test/cli/__snapshots__/cli-flags-test.js.snap
  cli/test/cli/bin-test.js
  clients/devtools/devtools-entry.js
  clients/lightrider/lightrider-entry.js
  clients/test/lightrider/lightrider-entry-test.js
  core/config/config-helpers.js
  core/config/config.js
  core/config/constants.js
  core/config/validation.js
  core/gather/base-gatherer.js
  core/gather/gatherers/bf-cache-failures.js
  core/gather/gatherers/css-usage.js
  core/gather/gatherers/dobetterweb/optimized-images.js
  core/gather/gatherers/dobetterweb/response-compression.js
  core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js
  core/gather/gatherers/gatherer.js
  core/gather/gatherers/inspector-issues.js
  core/gather/gatherers/link-elements.js
  core/gather/gatherers/main-document-content.js
  core/gather/gatherers/script-elements.js
  core/gather/gatherers/service-worker.js
  core/gather/gatherers/trace-elements.js
  core/index.cjs
  core/index.js
  core/legacy/config/config.js
  core/legacy/config/legacy-default-config.js
  core/legacy/gather/connections/connection.js
  core/legacy/gather/connections/cri.js
  core/legacy/gather/connections/raw.js
  core/legacy/gather/driver.js
  core/legacy/gather/gather-runner.js
  core/runner.js
  core/test/config/config-helpers-test.js
  core/test/config/config-test.js
  core/test/config/validation-test.js
  core/test/gather/base-gatherer-test.js
  core/test/gather/gatherers/bf-cache-failures-test.js
  core/test/gather/gatherers/dobetterweb/response-compression-test.js
  core/test/gather/gatherers/gatherer-test.js
  core/test/gather/gatherers/image-elements-test.js
  core/test/gather/gatherers/inspector-issues-test.js
  core/test/gather/gatherers/main-document-content-test.js
  core/test/gather/gatherers/trace-elements-test.js
  core/test/gather/mock-driver.js
  core/test/gather/navigation-runner-test.js
  core/test/index-test.js
  core/test/legacy/config/config-test.js
  core/test/legacy/gather/driver-test.js
  core/test/legacy/gather/fake-driver.js
  core/test/legacy/gather/gather-runner-test.js
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
  types/config.d.ts
  types/externs.d.ts
  types/gatherer.d.ts
Labels: waiting4reviewer, breaking

#15264 docs(plugins): fix syntax typos
  docs/plugins.md
Labels: waiting4reviewer

#15273 core: remove legacy artifacts types
  build/build-sample-reports.js
  core/config/filters.js
  core/gather/base-artifacts.js
  core/gather/navigation-runner.js
  core/gather/runner-helpers.js
  core/lib/asset-saver.js
  core/runner.js
  core/test/gather/base-artifacts-test.js
  core/test/gather/mock-driver.js
  core/test/gather/navigation-runner-test.js
  core/test/gather/runner-helpers-test.js
  types/artifacts.d.ts
  types/gatherer.d.ts
  types/lh.d.ts
Labels: waiting4reviewer

#15279 misc(logger): add types, remove cjs
  lighthouse-logger/index.js
  lighthouse-logger/package.json
Labels: waiting4reviewer

#15284 misc: add main path to logger
  lighthouse-logger/package.json
Labels: waiting4reviewer

#15174 cli(sentry): mention --enable-error-reporting flag in prompt
  cli/sentry-prompt.js
Labels: land-when-ci-is-green, waiting4reviewer

#15281 core(uses-rel-preconnect): add FCP and LCP savings
  core/audits/uses-rel-preconnect.js
  core/test/audits/uses-rel-preconnect-test.js
  core/test/create-test-trace.js
Labels: land-when-ci-is-green, waiting4reviewer

#15288 docs(readme): add PageVitals to the list of integrations
  readme.md
Labels: waiting4reviewer

#15219 clients(extension): update to manifest v3
  clients/extension/manifest.json
Labels: land-when-ci-is-green, waiting4reviewer, 11.0

#15287 deps: upgrade `chrome-launcher` to 1.0.0
  cli/test/smokehouse/lighthouse-runners/bundle.js
  package.json
  yarn.lock
Labels: waiting4reviewer

#15120 misc: fix typo
  core/config/constants.js
Labels: land-when-ci-is-green, waiting4reviewer

#15282 deps: upgrade `lighthouse-logger` to 2.0.1
  package.json
  types/internal/lighthouse-logger.d.ts
  yarn.lock
Labels: waiting4reviewer

#15293 core(source-maps): use `Scripts` as a dependency
  core/gather/gatherers/scripts.js
  core/gather/gatherers/source-maps.js
  core/test/gather/gatherers/source-maps-test.js
Labels: waiting4reviewer

#15292 misc: remove residual references to legacy
  cli/test/fixtures/dobetterweb/dbw_tester.js
  cli/test/smokehouse/test-definitions/dobetterweb.js
  core/config/validation.js
  core/gather/driver/network-monitor.js
  core/test/config/config-test.js
  core/test/config/filters-test.js
  core/test/config/validation-test.js
  core/test/fixtures/user-flows/navigation-basic/index.html
  core/test/fixtures/user-flows/navigation-basic/links-to-index.html
  core/test/fixtures/user-flows/snapshot-basic/onclick.html
  core/test/gather/driver/target-manager-test.js
  core/test/gather/gatherers/css-usage-test.js
  core/test/gather/mock-commands.js
  core/test/gather/mock-driver.js
  core/test/scenarios/__snapshots__/api-test-pptr.js.snap
  core/test/scenarios/api-test-pptr.js
  core/test/scripts/run-mocha-tests.js
  tsconfig.json
  types/gatherer.d.ts
  types/lhr/settings.d.ts
Labels: waiting4reviewer

#15285 core: make INP non-experimental
  core/audits/metrics/interaction-to-next-paint.js
  core/audits/work-during-interaction.js
  core/config/default-config.js
  core/test/audits/metrics/interaction-to-next-paint-test.js
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/scenarios/__snapshots__/api-test-pptr.js.snap
  shared/localization/locales/ar-XB.json
  shared/localization/locales/ar.json
  shared/localization/locales/bg.json
  shared/localization/locales/ca.json
  shared/localization/locales/cs.json
  shared/localization/locales/da.json
  shared/localization/locales/de.json
  shared/localization/locales/el.json
  shared/localization/locales/en-GB.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XA.json
  shared/localization/locales/en-XL.json
  shared/localization/locales/es-419.json
  shared/localization/locales/es.json
  shared/localization/locales/fi.json
  shared/localization/locales/fil.json
  shared/localization/locales/fr.json
  shared/localization/locales/he.json
  shared/localization/locales/hi.json
  shared/localization/locales/hr.json
  shared/localization/locales/hu.json
  shared/localization/locales/id.json
  shared/localization/locales/it.json
  shared/localization/locales/ja.json
  shared/localization/locales/ko.json
  shared/localization/locales/lt.json
  shared/localization/locales/lv.json
  shared/localization/locales/nl.json
  shared/localization/locales/no.json
  shared/localization/locales/pl.json
  shared/localization/locales/pt-PT.json
  shared/localization/locales/pt.json
  shared/localization/locales/ro.json
  shared/localization/locales/ru.json
  shared/localization/locales/sk.json
  shared/localization/locales/sl.json
  shared/localization/locales/sr-Latn.json
  shared/localization/locales/sr.json
  shared/localization/locales/sv.json
  shared/localization/locales/ta.json
  shared/localization/locales/te.json
  shared/localization/locales/th.json
  shared/localization/locales/tr.json
  shared/localization/locales/uk.json
  shared/localization/locales/vi.json
  shared/localization/locales/zh-HK.json
  shared/localization/locales/zh-TW.json
  shared/localization/locales/zh.json
  third-party/devtools-tests/e2e/lighthouse/timespan_test.ts
  viewer/test/viewer-test-pptr.js
Labels: waiting4reviewer

#15290 misc: drop node 16 support
  .github/workflows/ci.yml
  .github/workflows/cron-weekly.yml
  .github/workflows/devtools.yml
  .github/workflows/package-test.yml
  .github/workflows/publish.yml
  .github/workflows/smoke.yml
  .github/workflows/unit.yml
  cli/test/cli/index-test.js
  cli/test/fixtures/static-server.js
  cli/test/smokehouse/lighthouse-runners/bundle.js
  core/scripts/gcp-collection/gcp-setup.sh
  core/scripts/lantern/collect/gcp-setup.sh
  core/test/config/config-helpers-test.js
  core/test/gather/gatherers/source-maps-test.js
  docs/headless-chrome.md
  package.json
  readme.md
  yarn.lock
Labels: waiting4reviewer

#15314 core(stack-packs): add NitroPack detection
  core/lib/stack-packs.js
  core/test/lib/stack-packs-test.js
  package.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  yarn.lock
Labels: waiting4reviewer

#15315 report: move "View Original Trace" to the topbar dropdown
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  proto/lighthouse-result.proto
  report/assets/templates.html
  report/renderer/components.js
  report/renderer/report-ui-features.js
  report/renderer/report-utils.js
  report/renderer/topbar-features.js
  report/test/renderer/report-ui-features-test.js
  shared/localization/locales/ar-XB.json
  shared/localization/locales/ar.json
  shared/localization/locales/bg.json
  shared/localization/locales/ca.json
  shared/localization/locales/cs.json
  shared/localization/locales/da.json
  shared/localization/locales/de.json
  shared/localization/locales/el.json
  shared/localization/locales/en-GB.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XA.json
  shared/localization/locales/en-XL.json
  shared/localization/locales/es-419.json
  shared/localization/locales/es.json
  shared/localization/locales/fi.json
  shared/localization/locales/fil.json
  shared/localization/locales/fr.json
  shared/localization/locales/he.json
  shared/localization/locales/hi.json
  shared/localization/locales/hr.json
  shared/localization/locales/hu.json
  shared/localization/locales/id.json
  shared/localization/locales/it.json
  shared/localization/locales/ja.json
  shared/localization/locales/ko.json
  shared/localization/locales/lt.json
  shared/localization/locales/lv.json
  shared/localization/locales/nl.json
  shared/localization/locales/no.json
  shared/localization/locales/pl.json
  shared/localization/locales/pt-PT.json
  shared/localization/locales/pt.json
  shared/localization/locales/ro.json
  shared/localization/locales/ru.json
  shared/localization/locales/sk.json
  shared/localization/locales/sl.json
  shared/localization/locales/sr-Latn.json
  shared/localization/locales/sr.json
  shared/localization/locales/sv.json
  shared/localization/locales/ta.json
  shared/localization/locales/te.json
  shared/localization/locales/th.json
  shared/localization/locales/tr.json
  shared/localization/locales/uk.json
  shared/localization/locales/vi.json
  shared/localization/locales/zh-HK.json
  shared/localization/locales/zh-TW.json
  shared/localization/locales/zh.json
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
Labels: waiting4reviewer

#15310 report: re-order manual audits and expand when audits pass
  core/config/default-config.js
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  report/renderer/category-renderer.js
  report/renderer/pwa-category-renderer.js
  report/test/renderer/category-renderer-test.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: waiting4reviewer

#15318 docs: remove references to `devtoolsLogs` and `traces`
  CONTRIBUTING.md
  docs/plugins.md
  docs/readme.md
Labels: waiting4reviewer
