Repository GoogleChrome/lighthouse, pull requests merged in 2023-01, with the labels that each got.

#14625 misc: fix gcp-collection scripts
  core/scripts/gcp-collection/README.md
  core/scripts/gcp-collection/fleet-create.sh
  core/scripts/gcp-collection/gcp-run.sh
  core/scripts/gcp-collection/gcp-setup.sh
  core/scripts/gcp-collection/run.sh
  core/test/devtools-tests/download-devtools.sh
Labels: waiting4reviewer

#14476 core: warn when clear storage times out
  core/gather/driver/prepare.js
  core/gather/driver/storage.js
  core/test/gather/driver/prepare-test.js
  core/test/gather/driver/storage-test.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: waiting4reviewer

#14645 docs(config): add plugins property
  docs/configuration.md
Labels: land-when-ci-is-green, waiting4reviewer

#14600 core: use `resolvedConfig` to name every resolved config
  clients/test/lightrider/lightrider-entry-test.js
  core/config/config.js
  core/config/filters.js
  core/config/validation.js
  core/gather/base-artifacts.js
  core/gather/navigation-runner.js
  core/gather/snapshot-runner.js
  core/gather/timespan-runner.js
  core/index.js
  core/legacy/config/config.js
  core/runner.js
  core/scripts/print-a11y-scoring.js
  core/test/config/config-test.js
  core/test/config/filters-test.js
  core/test/gather/base-artifacts-test.js
  core/test/gather/navigation-runner-test.js
  core/test/gather/snapshot-runner-test.js
  core/test/gather/timespan-runner-test.js
  core/test/lib/stack-packs-test.js
  core/test/runner-test.js
  core/test/user-flow-test.js
  core/user-flow.js
  types/gatherer.d.ts
Labels: land-when-ci-is-green, waiting4reviewer

#14647 core: rename resolved config types
  core/config/config.js
  core/config/filters.js
  core/config/validation.js
  core/gather/base-artifacts.js
  core/gather/navigation-runner.js
  core/index.js
  core/legacy/config/config.js
  core/runner.js
  core/test/config/filters-test.js
  core/test/gather/navigation-runner-test.js
  core/test/legacy/config/config-test.js
  core/test/legacy/gather/gather-runner-test.js
  core/test/runner-test.js
  types/config.d.ts
  types/gatherer.d.ts
Labels: waiting4reviewer

#14663 core: replace `Page.getResourceTree` with `Page.getFrameTree`
  core/gather/driver/execution-context.js
  core/gather/driver/network-monitor.js
  core/test/gather/driver/execution-context-test.js
  core/test/gather/driver/navigation-test.js
  core/test/gather/driver/network-monitor-test.js
Labels: waiting4reviewer

#14550 core(is-crawlable): only warn if some bots are blocked
  core/audits/seo/is-crawlable.js
  core/test/audits/seo/is-crawlable-test.js
  core/test/computed/main-thread-tasks-test.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
Labels: waiting4reviewer

#14668 core(no-unload-listeners): move to best practices
  core/config/default-config.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  report/test/generator/report-generator-test.js
Labels: waiting4reviewer, 10.0

#14649 core: use `config` to name every config json
  cli/bin.js
  cli/test/smokehouse/lighthouse-runners/bundle.js
  cli/test/smokehouse/lighthouse-runners/cli.js
  cli/test/smokehouse/lighthouse-runners/devtools.js
  cli/test/smokehouse/smokehouse.js
  core/config/config-helpers.js
  core/config/config-plugin.js
  core/config/config.js
  core/config/validation.js
  core/index.js
  core/legacy/config/config.js
  core/test/config/config-helpers-test.js
  core/test/config/config-test.js
  core/test/legacy/config/config-test.js
  core/test/runner-test.js
  core/user-flow.js
  types/smokehouse.d.ts
Labels: waiting4reviewer

#14672 report(devtools): fix wrong emulation string in meta block
  core/util.cjs
  report/renderer/util.js
  report/test/renderer/util-test.js
Labels: land-when-ci-is-green

#14660 core(fr): preserve scroll position in gatherers
  core/gather/gatherers/accessibility.js
  core/gather/gatherers/seo/tap-targets.js
  core/legacy/gather/driver.js
  core/legacy/gather/gather-runner.js
  core/test/legacy/gather/fake-driver.js
  core/test/legacy/gather/gather-runner-test.js
Labels: waiting4reviewer

#14657 core(full-page-screenshot): remove audit, move to top-level
  cli/cli-flags.js
  cli/test/smokehouse/report-assert.js
  cli/test/smokehouse/test-definitions/dobetterweb.js
  cli/test/smokehouse/test-definitions/fps-max.js
  cli/test/smokehouse/test-definitions/fps-scaled.js
  cli/test/smokehouse/test-definitions/screenshot.js
  core/audits/full-page-screenshot.js
  core/config/constants.js
  core/config/default-config.js
  core/config/filters.js
  core/gather/gatherers/full-page-screenshot.js
  core/legacy/config/config.js
  core/runner.js
  core/test/config/filters-test.js
  core/test/fixtures/fraggle-rock/artifacts/step0/artifacts.json
  core/test/fixtures/fraggle-rock/artifacts/step1/artifacts.json
  core/test/fixtures/fraggle-rock/artifacts/step2/artifacts.json
  core/test/fixtures/fraggle-rock/artifacts/step3/artifacts.json
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/legacy/config/config-test.js
  core/test/results/artifacts/artifacts.json
  core/test/results/sample_v2.json
  core/test/scenarios/__snapshots__/api-test-pptr.js.snap
  core/util.cjs
  flow-report/src/common.tsx
  flow-report/src/util.ts
  flow-report/test/common-test.tsx
  proto/lighthouse-result.proto
  readme.md
  report/renderer/details-renderer.js
  report/renderer/element-screenshot-renderer.js
  report/renderer/report-renderer.js
  report/renderer/report-ui-features.js
  report/renderer/util.js
  report/test-assets/faux-psi.js
  report/test/renderer/util-test.js
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
  third-party/devtools-tests/e2e/lighthouse/snapshot_test.ts
  third-party/devtools-tests/e2e/lighthouse/timespan_test.ts
  types/artifacts.d.ts
  types/lhr/audit-details.d.ts
  types/lhr/lhr.d.ts
  types/lhr/settings.d.ts
  types/smokehouse.d.ts
Labels: waiting4reviewer, 10.0

#14680 core(legacy): convert some base artifacts to regular gatherers
  build/build-sample-reports.js
  core/gather/base-artifacts.js
  core/gather/gatherers/installability-errors.js
  core/gather/gatherers/stacks.js
  core/gather/gatherers/web-app-manifest.js
  core/legacy/config/config.js
  core/legacy/config/legacy-default-config.js
  core/legacy/gather/gather-runner.js
  core/lib/stack-packs.js
  core/test/legacy/config/config-test.js
  core/test/test-utils.js
  types/artifacts.d.ts
Labels: waiting4reviewer

#14688 misc: exclude core/util.cjs from code coverage
  .codecov.yml
Labels: waiting4reviewer

#14667 core(scoring): rebalance perf metric weightings for v10
  core/config/default-config.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  report/renderer/performance-category-renderer.js
  report/test/generator/report-generator-test.js
  report/test/renderer/performance-category-renderer-test.js
Labels: waiting4reviewer, 10.0

#14692 core(scoring): update expected perf score for flow fixtures
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
Labels: land-when-ci-is-green, waiting4reviewer

#14693 core(processed-navigation): computed directly from trace
  core/audits/byte-efficiency/render-blocking-resources.js
  core/audits/uses-rel-preconnect.js
  core/computed/metrics/lantern-metric.js
  core/computed/metrics/metric.js
  core/computed/metrics/timing-summary.js
  core/computed/processed-navigation.js
  core/gather/gatherers/trace-elements.js
  core/test/computed/processed-navigation-test.js
Labels: waiting4reviewer

#14685 core: use `performance.now` in isolation
  core/gather/driver/execution-context.js
  core/gather/driver/wait-for-condition.js
Labels: waiting4reviewer

#14679 report(thumbnails): increase res and display, reduce number
  core/audits/screenshot-thumbnails.js
  core/test/audits/screenshot-thumbnails-test.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  report/assets/styles.css
  report/renderer/components.js
Labels: waiting4reviewer

#14664 core(viewport): support interactive-widget
  core/test/computed/viewport-meta-test.js
  package.json
  yarn.lock
Labels: waiting4reviewer

#14699 core(bf-cache): link to chrome developer docs
  core/audits/bf-cache.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: waiting4reviewer

#13933 report: rename i18n to i18n-formatter, move strings to Util
  core/util.cjs
  flow-report/src/i18n/i18n.tsx
  flow-report/src/sidebar/sidebar.tsx
  flow-report/src/summary/category.tsx
  report/renderer/category-renderer.js
  report/renderer/crc-details-renderer.js
  report/renderer/i18n-formatter.js
  report/renderer/performance-category-renderer.js
  report/renderer/report-renderer.js
  report/renderer/report-ui-features.js
  report/renderer/snippet-renderer.js
  report/renderer/util.js
  report/test/renderer/category-renderer-test.js
  report/test/renderer/crc-details-renderer-test.js
  report/test/renderer/details-renderer-test.js
  report/test/renderer/dom-test.js
  report/test/renderer/element-screenshot-renderer-test.js
  report/test/renderer/i18n-formatter-test.js
  report/test/renderer/performance-category-renderer-test.js
  report/test/renderer/pwa-category-renderer-test.js
  report/test/renderer/snippet-renderer-test.js
  report/test/renderer/util-test.js
  treemap/app/src/main.js
  treemap/app/src/util.js
Labels: waiting4reviewer

#14700 core(trace-processing): add backport for pubads
  cli/test/smokehouse/test-definitions/pubads.js
  core/computed/processed-navigation.js
  core/test/computed/processed-navigation-test.js
Labels: waiting4reviewer

#14702 rename entityClassification to entities in LHR.
  core/runner.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  proto/lighthouse-result.proto
  types/lhr/lhr.d.ts
Labels: waiting4reviewer

#14704 report: specify in tooltip that cpu/memory power is unthrottled
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  core/util.cjs
  report/renderer/util.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: land-when-ci-is-green, waiting4reviewer

#14622 core: add entity classification of origins to the LHR
  core/audits/byte-efficiency/legacy-javascript.js
  core/audits/dobetterweb/uses-http2.js
  core/audits/third-party-facades.js
  core/audits/third-party-summary.js
  core/audits/valid-source-maps.js
  core/computed/entity-classification.js
  core/computed/resource-summary.js
  core/runner.js
  core/test/audits/third-party-facades-test.js
  core/test/audits/third-party-summary-test.js
  core/test/audits/valid-source-maps-test.js
  core/test/computed/entity-classification-test.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  core/test/runner-test.js
  proto/lighthouse-result.proto
  types/artifacts.d.ts
  types/lhr/lhr.d.ts
Labels: 10.0, third-party

#14706 deps: upgrade puppeteer to 19.6.0
  core/scripts/benchmark-plus-extras.js
  core/scripts/pptr-run-devtools.js
  core/scripts/update-flow-fixtures.js
  core/test/scenarios/pptr-test-utils.js
  package.json
  yarn.lock
Labels: waiting4reviewer

#14709 core: delete util.cjs
  core/computed/entity-classification.js
  core/util.cjs
  tsconfig.json
Labels: land-when-ci-is-green, waiting4reviewer

#14690 deps: upgrade `axe-core` to 4.6.3
  cli/test/fixtures/a11y/a11y_tester.html
  cli/test/smokehouse/test-definitions/a11y.js
  core/audits/accessibility/accesskeys.js
  core/audits/accessibility/aria-allowed-attr.js
  core/audits/accessibility/aria-command-name.js
  core/audits/accessibility/aria-hidden-body.js
  core/audits/accessibility/aria-hidden-focus.js
  core/audits/accessibility/aria-input-field-name.js
  core/audits/accessibility/aria-meter-name.js
  core/audits/accessibility/aria-progressbar-name.js
  core/audits/accessibility/aria-required-attr.js
  core/audits/accessibility/aria-required-children.js
  core/audits/accessibility/aria-required-parent.js
  core/audits/accessibility/aria-roles.js
  core/audits/accessibility/aria-toggle-field-name.js
  core/audits/accessibility/aria-tooltip-name.js
  core/audits/accessibility/aria-treeitem-name.js
  core/audits/accessibility/aria-valid-attr-value.js
  core/audits/accessibility/aria-valid-attr.js
  core/audits/accessibility/button-name.js
  core/audits/accessibility/bypass.js
  core/audits/accessibility/color-contrast.js
  core/audits/accessibility/definition-list.js
  core/audits/accessibility/dlitem.js
  core/audits/accessibility/document-title.js
  core/audits/accessibility/duplicate-id-active.js
  core/audits/accessibility/duplicate-id-aria.js
  core/audits/accessibility/form-field-multiple-labels.js
  core/audits/accessibility/frame-title.js
  core/audits/accessibility/heading-order.js
  core/audits/accessibility/html-has-lang.js
  core/audits/accessibility/html-lang-valid.js
  core/audits/accessibility/image-alt.js
  core/audits/accessibility/input-image-alt.js
  core/audits/accessibility/label.js
  core/audits/accessibility/link-name.js
  core/audits/accessibility/list.js
  core/audits/accessibility/listitem.js
  core/audits/accessibility/meta-refresh.js
  core/audits/accessibility/meta-viewport.js
  core/audits/accessibility/object-alt.js
  core/audits/accessibility/tabindex.js
  core/audits/accessibility/td-headers-attr.js
  core/audits/accessibility/th-has-data-cells.js
  core/audits/accessibility/valid-lang.js
  core/audits/accessibility/video-caption.js
  core/gather/gatherers/accessibility.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  package.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  yarn.lock
Labels: waiting4reviewer

#14713 deps(lighthouse-stack-packs): upgrade to 1.9.0
  core/lib/stack-packs.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/lib/stack-packs-test.js
  core/test/results/sample_v2.json
  package.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer

#14711 core(network-request): add rendererStartTime
  core/audits/network-requests.js
  core/lib/network-request.js
  core/test/audits/network-requests-test.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/lib/network-request-test.js
  core/test/network-records-to-devtools-log.js
  core/test/results/sample_v2.json
Labels: land-when-ci-is-green, waiting4reviewer, 10.0

#14287 core(trace-processor): refactor processEvents and frameEvents
  core/computed/metrics/responsiveness.js
  core/computed/page-dependency-graph.js
  core/lib/minify-trace.js
  core/lib/tracehouse/trace-processor.js
  core/lib/traces/metric-trace-events.js
  core/scripts/lantern/minify-trace.js
  core/test/computed/page-dependency-graph-test.js
  core/test/computed/processed-trace-test.js
  core/test/create-test-trace.js
  core/test/fixtures/artifacts/perflog/defaultPass.trace.json
  core/test/fixtures/traces/airhorner_no_fcp.json
  core/test/fixtures/traces/animation.json
  core/test/fixtures/traces/backgrounded-tab-missing-paints.json
  core/test/fixtures/traces/iframe-m79.trace.json
  core/test/fixtures/traces/lcp-m78.json
  core/test/fixtures/traces/no_fmp_event.json
  core/test/fixtures/traces/no_navstart_event.json
  core/test/fixtures/traces/pid-change.json
  core/test/fixtures/traces/preactjs.com_ts_of_undefined.json
  core/test/fixtures/traces/speedindex-1ms-layout-m84.trace.json
  core/test/fixtures/traces/threeframes-blank_content_more.json
  core/test/fixtures/traces/trace-user-timings.json
  core/test/fixtures/traces/video-embeds-m84.json
  core/test/gather/gatherers/trace-elements-test.js
  core/test/lib/asset-saver-test.js
  core/test/lib/minify-trace-test.js
  core/test/lib/tracehouse/main-thread-tasks-test.js
  core/test/lib/tracehouse/trace-processor-test.js
  package.json
  tsconfig.json
  types/artifacts.d.ts
Labels: waiting4reviewer, 10.0

#14384 core(emulation): bump chrome UA to m109 and drop LH identifier
  core/config/constants.js
  core/test/fixtures/fraggle-rock/artifacts/step0/artifacts.json
  core/test/fixtures/fraggle-rock/artifacts/step1/artifacts.json
  core/test/fixtures/fraggle-rock/artifacts/step2/artifacts.json
  core/test/fixtures/fraggle-rock/artifacts/step3/artifacts.json
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/legacy/config/config-test.js
  core/test/results/artifacts/artifacts.json
  core/test/results/sample_v2.json
Labels: land-when-ci-is-green, waiting4reviewer, 10.0

#14714 tests: better times for generated network requests
  core/test/audits/network-requests-test.js
  core/test/audits/preload-lcp-image-test.js
  core/test/computed/metrics/lantern-first-contentful-paint-test.js
  core/test/gather/gatherers/inspector-issues-test.js
  core/test/lib/network-request-test.js
  core/test/network-records-to-devtools-log-test.js
  core/test/network-records-to-devtools-log.js
Labels: land-when-ci-is-green, waiting4reviewer

#14619 report: prevent opportunity savings from wrapping
  report/assets/styles.css
  report/renderer/components.js
Labels: waiting4reviewer

#14720 docs: fix outdated code and command line in hacking tips
  docs/hacking-tips.md
Labels: waiting4reviewer

#14697 report: use entity classification to filter third-parties
  report/renderer/details-renderer.js
  report/renderer/report-ui-features.js
  report/renderer/report-utils.js
  report/test/renderer/report-ui-features-test.js
  report/test/renderer/report-utils-test.js
Labels: waiting4reviewer, 10.0

#14724 report: filter `lcp-lazy-loaded` with LCP audits
  core/config/metrics-to-audits.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
Labels: land-when-ci-is-green

#14732 misc: mark dependencies of entity classification computed artifact
  core/computed/entity-classification.js
  core/computed/resource-summary.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
Labels: waiting4reviewer

#14740 misc: fix issues found in some strings from localizers
  core/audits/dobetterweb/doctype.js
  core/lib/bf-cache-strings.js
  core/scripts/i18n/collect-strings.js
  core/test/audits/dobetterweb/doctype-test.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: waiting4reviewer

#14723 report: use narrow formatting for opportunity units
  report/assets/styles.css
  report/renderer/components.js
  report/renderer/i18n-formatter.js
Labels: waiting4reviewer
