Repository GoogleChrome/lighthouse, pull requests merged in 2023-09, with the labels that each got.

#15432 tests(dbw): remove upper bound for LCP load start/end
  cli/test/smokehouse/test-definitions/dobetterweb.js
Labels: waiting4reviewer

#15428 docs(readme): fix chrome-launcher import example
  docs/readme.md
Labels: waiting4reviewer

#15431 core: add TBT savings to `bootup-time`
  core/audits/bootup-time.js
  core/test/audits/bootup-time-test.js
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
Labels: waiting4reviewer

#15403 deps: upgrade puppeteer to 21.1.1
  cli/test/smokehouse/test-definitions/dobetterweb.js
  package.json
  yarn.lock
Labels: waiting4reviewer

#14520 core(main-resource): fix protocol error when page is reloaded
  cli/test/fixtures/sw-reloaded.html
  cli/test/smokehouse/core-tests.js
  cli/test/smokehouse/test-definitions/service-worker-reloaded.js
  core/computed/main-resource.js
  core/computed/page-dependency-graph.js
  core/lib/dependency-graph/simulator/network-analyzer.js
  core/test/computed/main-resource-test.js
Labels: waiting4reviewer

#10511 docs: add a guide to running Lighthouse at scale
  docs/running-at-scale.md
Labels: waiting4committer, cla: yes, waiting4reviewer

#15414 docs: update explainer for devtools build
  build/readme.md
Labels: land-when-ci-is-green, waiting4reviewer

#15381 misc(build): do not minify browser extension
  build/build-extension.js
Labels: waiting4reviewer

#15354 deps: upgrade `third-party-web` to 0.24.0
  package.json
  yarn.lock
Labels: waiting4reviewer

#15443 i18n: import
  shared/localization/locales/ar-XB.json
  shared/localization/locales/ar.json
  shared/localization/locales/bg.json
  shared/localization/locales/ca.json
  shared/localization/locales/cs.json
  shared/localization/locales/da.json
  shared/localization/locales/de.json
  shared/localization/locales/el.json
  shared/localization/locales/en-GB.json
  shared/localization/locales/en-XA.json
  shared/localization/locales/es-419.json
  shared/localization/locales/es.json
  shared/localization/locales/fi.json
  shared/localization/locales/fil.json
  shared/localization/locales/fr.json
  shared/localization/locales/he.json
  shared/localization/locales/hi.json
  shared/localization/locales/hr.json
  shared/localization/locales/hu.json
  shared/localization/locales/id.json
  shared/localization/locales/it.json
  shared/localization/locales/ja.json
  shared/localization/locales/ko.json
  shared/localization/locales/lt.json
  shared/localization/locales/lv.json
  shared/localization/locales/nl.json
  shared/localization/locales/no.json
  shared/localization/locales/pl.json
  shared/localization/locales/pt-PT.json
  shared/localization/locales/pt.json
  shared/localization/locales/ro.json
  shared/localization/locales/ru.json
  shared/localization/locales/sk.json
  shared/localization/locales/sl.json
  shared/localization/locales/sr-Latn.json
  shared/localization/locales/sr.json
  shared/localization/locales/sv.json
  shared/localization/locales/ta.json
  shared/localization/locales/te.json
  shared/localization/locales/th.json
  shared/localization/locales/tr.json
  shared/localization/locales/uk.json
  shared/localization/locales/vi.json
  shared/localization/locales/zh-HK.json
  shared/localization/locales/zh-TW.json
  shared/localization/locales/zh.json
Labels: waiting4reviewer

#15442 v11.1.0
  changelog.md
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  docs/plugins.md
  docs/recipes/lighthouse-plugin-example/package.json
  package.json
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
Labels: waiting4reviewer

#15444 tests(devtools): sync e2e
  third-party/devtools-tests/e2e/lighthouse/devtools-settings_test.ts
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
  third-party/devtools-tests/e2e/lighthouse/snapshot_test.ts
  third-party/devtools-tests/e2e/lighthouse/timespan_test.ts
  third-party/devtools-tests/e2e/resources/lighthouse/hello.html
Labels: waiting4reviewer

#15446 deps: upgrade `axe-core` to 4.8.1
  cli/test/smokehouse/test-definitions/a11y.js
  package.json
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer

#15449 docs(plugins): minor corrections
  docs/plugins.md
  docs/recipes/lighthouse-plugin-example/readme.md
Labels: land-when-ci-is-green, waiting4reviewer

#15458 deps: pin puppeteer version
  package.json
  yarn.lock
Labels: waiting4reviewer

#15454 tests(devtools): fix viewport in smoke tests
  core/scripts/pptr-run-devtools.js
Labels: land-when-ci-is-green, waiting4reviewer

#15451 core(asset-saver): fix handling of undefined trace
  core/lib/asset-saver.js
  core/test/lib/asset-saver-test.js
Labels: land-when-ci-is-green, waiting4reviewer

#15459 tests(devtools): ensure Lighthouse starts in smoke tests
  .github/workflows/devtools.yml
  cli/test/smokehouse/smokehouse.js
  core/scripts/pptr-run-devtools.js
Labels: waiting4reviewer

#15486 report: redefine gauge percentage positioning
  report/assets/styles.css
  report/assets/templates.html
  report/renderer/components.js
Labels: waiting4reviewer

#15485 cli(sentry): set useful tags from resolved config
  cli/bin.js
  core/lib/sentry.js
  core/test/lib/sentry-test.js
Labels: waiting4reviewer

#15201 core(mainthread-work-breakdown): add TBT savings
  core/audits/mainthread-work-breakdown.js
  core/test/audits/mainthread-work-breakdown-test.js
  core/test/fixtures/artifacts/animation/devtoolslog.json
  core/test/fixtures/artifacts/animation/regenerate.js
  core/test/fixtures/artifacts/animation/trace.json
  core/test/fixtures/artifacts/update-test-fixture.js
Labels: waiting4reviewer

#15489 core(tags-blocking-first-paint): ignore malformed link tags
  cli/test/fixtures/dobetterweb/dbw_tester.html
  cli/test/smokehouse/test-definitions/dobetterweb.js
  core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js
Labels: waiting4reviewer

#15491 core(inspector-issues): add `propertyRuleIssue`
  core/gather/gatherers/inspector-issues.js
  core/test/gather/gatherers/inspector-issues-test.js
  package.json
  third-party/chromium-synchronization/inspector-issueAdded-types-test.js
  types/artifacts.d.ts
  yarn.lock
Labels: waiting4reviewer

#15374 tests: use new headless for puppeteer tests
  core/test/gather/gatherers/accessibility-test.js
  core/test/scenarios/pptr-test-utils.js
  flow-report/test/flow-report-pptr-test.ts
  report/test/renderer/report-renderer-axe-test.js
  treemap/test/treemap-test-pptr.js
  viewer/test/viewer-test-pptr.js
Labels: waiting4reviewer

#15493 misc(ci): use commit sha for markdown action
  .github/workflows/cron-weekly.yml
Labels: waiting4reviewer

#15496 misc: have dependabot check github actions deps
  .github/dependabot.yml
Labels: land-when-ci-is-green, waiting4reviewer
