Repository GoogleChrome/lighthouse, pull requests merged in 2023-04, with the labels that each got.

#14960 core(installability): deprecate scheme support warning
  core/audits/installable-manifest.js
  third-party/chromium-synchronization/installability-errors-test.js
Labels: waiting4reviewer

#14962 tests(devtools): fix config for testing
  core/scripts/pptr-run-devtools.js
Labels: waiting4reviewer

#14959 misc(proto): fix case in entities fields
  cli/test/fixtures/seo/seo-tap-targets.html
  proto/lighthouse-result.proto
Labels: land-when-ci-is-green, waiting4reviewer

#14974 deps: upgrade `devtools-protocol` & deprecate SW install error
  core/audits/installable-manifest.js
  core/gather/gatherers/inspector-issues.js
  core/test/gather/gatherers/inspector-issues-test.js
  package.json
  third-party/chromium-synchronization/inspector-issueAdded-types-test.js
  third-party/chromium-synchronization/installability-errors-test.js
  types/artifacts.d.ts
  yarn.lock
Labels: waiting4reviewer

#14975 v10.1.1
  changelog.md
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  docs/plugins.md
  docs/recipes/lighthouse-plugin-example/package.json
  package.json
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
Labels: waiting4reviewer

#14978 docs: update pptr options example
  docs/puppeteer.md
Labels: waiting4reviewer

#14981 core(runner): handle erroneous screenshot
  core/runner.js
  core/test/runner-test.js
Labels: waiting4reviewer

#14983 deps(chrome-launcher): update to 0.15.2
  package.json
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer

#14964 misc(logger): add warn level
  lighthouse-logger/index.js
  types/externs.d.ts
Labels: waiting4reviewer

#14993 docs: update throttling methods
  build/readme.md
  clients/extension/popup.html
  docs/authenticated-pages.md
  docs/throttling.md
  docs/variability.md
  report/README.md
Labels: waiting4reviewer

#14994 report: remove content-visibility from lh-category
  report/assets/styles.css
  report/renderer/components.js
Labels: waiting4reviewer

#14995 tests(devtools): sync e2e
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
  third-party/devtools-tests/e2e/lighthouse/start-view_test.ts
Labels: land-when-ci-is-green, waiting4reviewer

#14937 core: fix viewport when running over adb
  core/gather/navigation-runner.js
  docs/readme.md
Labels: waiting4reviewer

#15000 deps: upgrade puppeteer and puppeteer-core
  package.json
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer

#15009 core(entity-classification): classify unknown urls as "unattributable"
  core/computed/entity-classification.js
  core/test/computed/entity-classification-test.js
  report/test/renderer/details-renderer-test.js
Labels: waiting4reviewer

#14745 report: avoid really slow regexes for long urls
  shared/util.js
Labels: waiting4reviewer

#14941 core: add time-to-first-byte and lcp-breakdown
  cli/test/smokehouse/test-definitions/dobetterweb.js
  core/audits/predictive-perf.js
  core/audits/prioritize-lcp-image.js
  core/computed/document-urls.js
  core/computed/lcp-image-record.js
  core/computed/metrics/lcp-breakdown.js
  core/computed/metrics/metric.js
  core/computed/metrics/navigation-metric.js
  core/computed/metrics/time-to-first-byte.js
  core/computed/metrics/timing-summary.js
  core/computed/page-dependency-graph.js
  core/scripts/lantern/collect/README.md
  core/scripts/lantern/collect/collect.js
  core/scripts/lantern/collect/gcp-create-and-run.sh
  core/scripts/lantern/collect/gcp-run.sh
  core/scripts/lantern/collect/gcp-setup.sh
  core/scripts/lantern/collect/golden.js
  core/scripts/lantern/run-once.js
  core/test/audits/__snapshots__/metrics-test.js.snap
  core/test/audits/__snapshots__/predictive-perf-test.js.snap
  core/test/audits/metrics-test.js
  core/test/audits/predictive-perf-test.js
  core/test/computed/document-urls-test.js
  core/test/computed/lcp-image-record-test.js
  core/test/computed/metrics/lcp-breakdown-test.js
  core/test/computed/metrics/time-to-first-byte-test.js
  core/test/computed/metrics/timing-summary-test.js
  core/test/computed/page-dependency-graph-test.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/fixtures/lantern-baseline-accuracy.json
  core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: land-when-ci-is-green, cla: no, waiting4reviewer

#15022 core: classify extension urls as non-network
  core/lib/url-utils.js
  core/test/lib/url-utils-test.js
Labels: waiting4reviewer

#15023 deps: update to typescript 5.0.4
  build/build-cdt-lib.js
  core/legacy/gather/gather-runner.js
  package.json
  types/internal/test.d.ts
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer

#15024 core: create timing entries for `getArtifact`
  core/gather/runner-helpers.js
  core/test/fixtures/fraggle-rock/artifacts/step0/artifacts.json
  core/test/fixtures/fraggle-rock/artifacts/step1/artifacts.json
  core/test/fixtures/fraggle-rock/artifacts/step2/artifacts.json
  core/test/fixtures/fraggle-rock/artifacts/step3/artifacts.json
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/artifacts/artifacts.json
  core/test/results/sample_v2.json
Labels: land-when-ci-is-green, waiting4reviewer
