Repository GoogleChrome/lighthouse, pull requests merged in 2023-02, with the labels that each got.

#14701 misc: split lhr compat code to lib/lighthouse-compatibility.js
  core/lib/lighthouse-compatibility.js
  core/test/lib/lighthouse-compatibility-test.js
  report/renderer/report-utils.js
  report/test/renderer/report-utils-test.js
  report/tsconfig.json
  tsconfig.json
Labels: waiting4reviewer

#14721 core(network-request): switch to improved timing names
  core/audits/byte-efficiency/offscreen-images.js
  core/audits/critical-request-chains.js
  core/audits/font-display.js
  core/audits/network-requests.js
  core/audits/redirects.js
  core/audits/uses-rel-preconnect.js
  core/gather/driver/network-monitor.js
  core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js
  core/lib/dependency-graph/network-node.js
  core/lib/dependency-graph/simulator/network-analyzer.js
  core/lib/navigation-error.js
  core/lib/network-recorder.js
  core/lib/network-request.js
  core/test/audits/byte-efficiency/offscreen-images-test.js
  core/test/audits/byte-efficiency/total-byte-weight-test.js
  core/test/audits/byte-efficiency/uses-responsive-images-test.js
  core/test/audits/critical-request-chains-test.js
  core/test/audits/font-display-test.js
  core/test/audits/network-requests-test.js
  core/test/audits/preload-lcp-image-test.js
  core/test/audits/redirects-test.js
  core/test/audits/uses-rel-preconnect-test.js
  core/test/audits/uses-rel-preload-test.js
  core/test/computed/critical-request-chains-test.js
  core/test/computed/metrics/interactive-test.js
  core/test/computed/metrics/lantern-first-contentful-paint-test.js
  core/test/computed/page-dependency-graph-test.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/gather/driver/network-monitor-test.js
  core/test/gather/gatherers/dobetterweb/tags-blocking-first-paint-test.js
  core/test/lib/dependency-graph/simulator/network-analyzer-test.js
  core/test/lib/dependency-graph/simulator/simulator-test.js
  core/test/lib/network-recorder-test.js
  core/test/lib/network-request-test.js
  core/test/network-records-to-devtools-log-test.js
  core/test/network-records-to-devtools-log.js
  core/test/results/sample_v2.json
Labels: land-when-ci-is-green, waiting4reviewer

#14744 core: refactor out entity-classification lookup tables
  core/runner.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  proto/lighthouse-result.proto
  report/renderer/report-ui-features.js
  report/renderer/report-utils.js
  report/test/renderer/report-ui-features-test.js
  types/lhr/lhr.d.ts
Labels: waiting4reviewer

#14716 core: fix protocol errors from late frame navigation
  cli/test/fixtures/dobetterweb/dbw_tester.html
  cli/test/smokehouse/test-definitions/dobetterweb.js
  core/gather/driver/prepare.js
  core/gather/navigation-runner.js
  core/gather/timespan-runner.js
  core/legacy/gather/driver.js
  core/legacy/gather/gather-runner.js
  core/test/gather/driver/prepare-test.js
  core/test/gather/mock-driver.js
  core/test/test-utils.js
  third-party/devtools-tests/e2e/lighthouse/snapshot_test.ts
  third-party/devtools-tests/e2e/lighthouse/timespan_test.ts
Labels: land-when-ci-is-green, waiting4reviewer

#14674 core(emulation): retire moto g4, use moto g power
  cli/test/fixtures/dobetterweb/dbw_tester.css
  cli/test/fixtures/dobetterweb/dbw_tester.html
  cli/test/fixtures/dobetterweb/lighthouse-1024x680.jpg
  cli/test/smokehouse/test-definitions/byte-efficiency.js
  cli/test/smokehouse/test-definitions/dobetterweb.js
  cli/test/smokehouse/test-definitions/fps-max-passive.js
  cli/test/smokehouse/test-definitions/fps-max.js
  cli/test/smokehouse/test-definitions/fps-scaled.js
  cli/test/smokehouse/test-definitions/perf-frame-metrics.js
  cli/test/smokehouse/test-definitions/perf-trace-elements.js
  core/config/constants.js
  core/lib/emulation.js
  core/test/fixtures/fraggle-rock/artifacts/step0/artifacts.json
  core/test/fixtures/fraggle-rock/artifacts/step0/defaultPass.devtoolslog.json
  core/test/fixtures/fraggle-rock/artifacts/step1/artifacts.json
  core/test/fixtures/fraggle-rock/artifacts/step1/defaultPass.devtoolslog.json
  core/test/fixtures/fraggle-rock/artifacts/step2/artifacts.json
  core/test/fixtures/fraggle-rock/artifacts/step3/artifacts.json
  core/test/fixtures/fraggle-rock/artifacts/step3/defaultPass.devtoolslog.json
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/legacy/config/config-test.js
  core/test/results/artifacts/artifacts.json
  core/test/results/artifacts/defaultPass.devtoolslog.json
  core/test/results/sample_v2.json
  flow-report/test/sidebar/sidebar-test.tsx
  report/renderer/report-utils.js
  report/test/generator/report-generator-test.js
  report/test/renderer/performance-category-renderer-test.js
  report/test/renderer/report-renderer-test.js
  report/test/renderer/report-utils-test.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  third-party/devtools-tests/e2e/lighthouse/devtools-settings_test.ts
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
  third-party/devtools-tests/e2e/lighthouse/snapshot_test.ts
Labels: land-when-ci-is-green, waiting4reviewer, 10.0

#14749 core(third-party-summary): change item.entity from link to text
  core/audits/third-party-summary.js
  core/test/audits/third-party-summary-test.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
Labels: land-when-ci-is-green, 10.0

#14748 report(flow): disable sticky table header
  report/assets/styles.css
  report/renderer/components.js
Labels: waiting4reviewer

#14741 core: add initiatorRequest from async stacks and preloads
  core/lib/network-recorder.js
  core/scripts/test-lantern.sh
  core/test/fixtures/lantern-baseline-accuracy.json
  core/test/fixtures/lantern-baseline-computed-values.json
  core/test/lib/network-recorder-test.js
Labels: waiting4reviewer

#14758 core(valid-source-maps): validate url in first-party check
  core/audits/valid-source-maps.js
Labels: waiting4reviewer

#14762 tests(metrics-tricky-tti): disable for M112
  cli/test/smokehouse/test-definitions/metrics-tricky-tti.js
Labels: waiting4reviewer

#14757 misc(lint): enable no-conditional-assignment rule
  .eslintrc.cjs
  core/lib/page-functions.js
Labels: P3, waiting4reviewer

#14763 core(full-page-screenshot): get screenshot, nodes concurrently
  core/gather/gatherers/full-page-screenshot.js
Labels: waiting4reviewer

#14760 core: use main-frame LCP trace element
  cli/test/smokehouse/test-definitions/perf-frame-metrics.js
  core/audits/preload-lcp-image.js
  core/gather/gatherers/trace-elements.js
Labels: waiting4reviewer, 10.0

#14766 report: fix sticky table header in DevTools
  report/assets/styles.css
  report/renderer/components.js
Labels: waiting4reviewer

#14761 core: rename preload-lcp-image to prioritize-lcp-image
  cli/test/smokehouse/test-definitions/dobetterweb.js
  cli/test/smokehouse/test-definitions/perf-trace-elements.js
  core/audits/prioritize-lcp-image.js
  core/config/default-config.js
  core/config/metrics-to-audits.js
  core/test/audits/prioritize-lcp-image-test.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/lib/stack-packs-test.js
  core/test/results/sample_v2.json
  core/test/scenarios/__snapshots__/api-test-pptr.js.snap
  package.json
  shared/localization/locales/ar-XB.json
  shared/localization/locales/ar.json
  shared/localization/locales/bg.json
  shared/localization/locales/ca.json
  shared/localization/locales/cs.json
  shared/localization/locales/da.json
  shared/localization/locales/de.json
  shared/localization/locales/el.json
  shared/localization/locales/en-GB.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XA.json
  shared/localization/locales/en-XL.json
  shared/localization/locales/es-419.json
  shared/localization/locales/es.json
  shared/localization/locales/fi.json
  shared/localization/locales/fil.json
  shared/localization/locales/fr.json
  shared/localization/locales/he.json
  shared/localization/locales/hi.json
  shared/localization/locales/hr.json
  shared/localization/locales/hu.json
  shared/localization/locales/id.json
  shared/localization/locales/it.json
  shared/localization/locales/ja.json
  shared/localization/locales/ko.json
  shared/localization/locales/lt.json
  shared/localization/locales/lv.json
  shared/localization/locales/nl.json
  shared/localization/locales/no.json
  shared/localization/locales/pl.json
  shared/localization/locales/pt-PT.json
  shared/localization/locales/pt.json
  shared/localization/locales/ro.json
  shared/localization/locales/ru.json
  shared/localization/locales/sk.json
  shared/localization/locales/sl.json
  shared/localization/locales/sr-Latn.json
  shared/localization/locales/sr.json
  shared/localization/locales/sv.json
  shared/localization/locales/ta.json
  shared/localization/locales/te.json
  shared/localization/locales/th.json
  shared/localization/locales/tr.json
  shared/localization/locales/uk.json
  shared/localization/locales/vi.json
  shared/localization/locales/zh-HK.json
  shared/localization/locales/zh-TW.json
  shared/localization/locales/zh.json
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer, 10.0

#14756 core(config): prevent custom gatherer interference
  core/config/config.js
  core/legacy/config/config.js
  core/test/config/config-test.js
  core/test/legacy/config/config-test.js
Labels: waiting4reviewer, 10.0

#14768 i18n: import strings
  shared/localization/locales/ar-XB.json
  shared/localization/locales/ar.json
  shared/localization/locales/bg.json
  shared/localization/locales/ca.json
  shared/localization/locales/cs.json
  shared/localization/locales/da.json
  shared/localization/locales/de.json
  shared/localization/locales/el.json
  shared/localization/locales/en-GB.json
  shared/localization/locales/en-XA.json
  shared/localization/locales/es-419.json
  shared/localization/locales/es.json
  shared/localization/locales/fi.json
  shared/localization/locales/fil.json
  shared/localization/locales/fr.json
  shared/localization/locales/he.json
  shared/localization/locales/hi.json
  shared/localization/locales/hr.json
  shared/localization/locales/hu.json
  shared/localization/locales/id.json
  shared/localization/locales/it.json
  shared/localization/locales/ja.json
  shared/localization/locales/ko.json
  shared/localization/locales/lt.json
  shared/localization/locales/lv.json
  shared/localization/locales/nl.json
  shared/localization/locales/no.json
  shared/localization/locales/pl.json
  shared/localization/locales/pt-PT.json
  shared/localization/locales/pt.json
  shared/localization/locales/ro.json
  shared/localization/locales/ru.json
  shared/localization/locales/sk.json
  shared/localization/locales/sl.json
  shared/localization/locales/sr-Latn.json
  shared/localization/locales/sr.json
  shared/localization/locales/sv.json
  shared/localization/locales/ta.json
  shared/localization/locales/te.json
  shared/localization/locales/th.json
  shared/localization/locales/tr.json
  shared/localization/locales/uk.json
  shared/localization/locales/vi.json
  shared/localization/locales/zh-HK.json
  shared/localization/locales/zh-TW.json
  shared/localization/locales/zh.json
Labels: waiting4reviewer, 10.0

#14770 core: disconnect Puppeteer when started by Lighthouse
  core/gather/navigation-runner.js
Labels: waiting4reviewer

#14772 tests(e2e): seek translated view trace button
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
Labels: waiting4reviewer

#14773 misc(build): shim unneeded deps in lr report generator
  build/build-lightrider-bundles.js
Labels: waiting4reviewer, 10.0

#14774 core(lr): disable bf-cache
  core/config/lr-desktop-config.js
  core/config/lr-mobile-config.js
Labels: waiting4reviewer

#14594 v10.0.0
  changelog.md
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  docs/plugins.md
  docs/recipes/lighthouse-plugin-example/package.json
  package.json
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
Labels: waiting4reviewer, 10.0

#14778 docs: split changelog at 10.0
  changelog-pre10.md
  changelog.md
Labels: waiting4reviewer

#14777 docs(changelog): minor v10 edits
  changelog.md
Labels: land-when-ci-is-green, waiting4reviewer

#14779 misc: update .npmignore
  .npmignore
Labels: waiting4reviewer, 10.0.1

#14782 core: reduce DevTools flakiness
  core/gather/driver/network-monitor.js
  core/gather/gatherers/bf-cache-failures.js
  core/test/gather/driver/navigation-test.js
  core/test/gather/driver/network-monitor-test.js
Labels: waiting4reviewer, 10.0.1

#14794 core(paste-preventing-inputs): rephrase description
  core/audits/dobetterweb/paste-preventing-inputs.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: waiting4reviewer

#14796 v10.0.1
  changelog.md
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  docs/plugins.md
  docs/recipes/lighthouse-plugin-example/package.json
  package.json
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
Labels: waiting4reviewer

#14801 tests(devtools): sync e2e
  third-party/devtools-tests/e2e/lighthouse/devtools-settings_test.ts
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
Labels: land-when-ci-is-green, waiting4reviewer

#14807 core(prioritize-lcp-image): use request initiators for load path
  cli/test/smokehouse/test-definitions/dobetterweb.js
  cli/test/smokehouse/test-definitions/perf-trace-elements.js
  core/audits/prioritize-lcp-image.js
  core/test/audits/prioritize-lcp-image-test.js
  core/test/fixtures/fraggle-rock/reports/sample-flow-result.json
  core/test/results/sample_v2.json
Labels: waiting4reviewer

#14809 misc(proto): add screenEmulation to configSettings
  core/lib/proto-preprocessor.js
  core/test/lib/proto-preprocessor-test.js
  proto/lighthouse-result.proto
Labels: land-when-ci-is-green, waiting4reviewer

#14799 clients(lr): accept multiple channel naming conventions
  clients/lightrider/lightrider-entry.js
Labels: waiting4reviewer

#14815 core(types): fix error when using module resolution "node"
  docs/recipes/type-checking/package.json
  types/artifacts.d.ts
Labels: waiting4reviewer

#14818 core: change error message if no artifacts are defined
  core/gather/navigation-runner.js
Labels: waiting4reviewer

#14819 core: don't use failed network requests as potential initiators
  core/lib/network-recorder.js
  core/test/lib/network-recorder-test.js
  core/test/network-records-to-devtools-log-test.js
  core/test/network-records-to-devtools-log.js
Labels: land-when-ci-is-green, waiting4reviewer

#14823 core(bf-cache): count failures based on affected frames
  core/audits/bf-cache.js
  core/test/audits/bf-cache-test.js
Labels: waiting4reviewer

#14826 misc(proto): bump next id
  proto/lighthouse-result.proto
Labels: land-when-ci-is-green, waiting4reviewer

#14806 docs(user-flows): add desktop config examples
  docs/user-flows.md
Labels: land-when-ci-is-green, waiting4reviewer

#14828 core(legacy-javascript): update polyfill size graph
  core/audits/byte-efficiency/polyfill-graph-data.json
  core/scripts/test-legacy-javascript.sh
  core/test/audits/byte-efficiency/legacy-javascript-test.js
  core/test/results/sample_v2.json
Labels: waiting4reviewer

#14839 tests(devtools): use new `primaryPageTarget` function
  cli/test/smokehouse/config/exclusions.js
  core/scripts/pptr-run-devtools.js
Labels: land-when-ci-is-green, waiting4reviewer
