Repository GoogleChrome/lighthouse, pull requests merged in 2023-08, with the labels that each got.

#15311 core: add `DevtoolsLogError` and `TraceError` artifacts
  cli/test/smokehouse/test-definitions/errors-expired-ssl.js
  cli/test/smokehouse/test-definitions/errors-iframe-expired-ssl.js
  cli/test/smokehouse/test-definitions/errors-infinite-loop.js
  core/config/constants.js
  core/gather/navigation-runner.js
  core/lib/asset-saver.js
  core/runner.js
  core/test/config/config-test.js
  core/test/gather/navigation-runner-test.js
  types/artifacts.d.ts
Labels: waiting4reviewer

#15321 core: re-weight best practices
  core/config/default-config.js
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  report/test/generator/report-generator-test.js
Labels: waiting4reviewer

#15329 core(lcp-element): gracefully handle error in phase table
  core/audits/largest-contentful-paint-element.js
  core/test/audits/largest-contentful-paint-element-test.js
Labels: waiting4reviewer

#15334 i18n: import
  shared/localization/locales/ar-XB.json
  shared/localization/locales/ar.json
  shared/localization/locales/bg.json
  shared/localization/locales/ca.json
  shared/localization/locales/cs.json
  shared/localization/locales/da.json
  shared/localization/locales/de.json
  shared/localization/locales/el.json
  shared/localization/locales/en-GB.json
  shared/localization/locales/en-XA.json
  shared/localization/locales/es-419.json
  shared/localization/locales/es.json
  shared/localization/locales/fi.json
  shared/localization/locales/fil.json
  shared/localization/locales/fr.json
  shared/localization/locales/he.json
  shared/localization/locales/hi.json
  shared/localization/locales/hr.json
  shared/localization/locales/hu.json
  shared/localization/locales/id.json
  shared/localization/locales/it.json
  shared/localization/locales/ja.json
  shared/localization/locales/ko.json
  shared/localization/locales/lt.json
  shared/localization/locales/lv.json
  shared/localization/locales/nl.json
  shared/localization/locales/no.json
  shared/localization/locales/pl.json
  shared/localization/locales/pt-PT.json
  shared/localization/locales/pt.json
  shared/localization/locales/ro.json
  shared/localization/locales/ru.json
  shared/localization/locales/sk.json
  shared/localization/locales/sl.json
  shared/localization/locales/sr-Latn.json
  shared/localization/locales/sr.json
  shared/localization/locales/sv.json
  shared/localization/locales/ta.json
  shared/localization/locales/te.json
  shared/localization/locales/th.json
  shared/localization/locales/tr.json
  shared/localization/locales/uk.json
  shared/localization/locales/vi.json
  shared/localization/locales/zh-HK.json
  shared/localization/locales/zh-TW.json
  shared/localization/locales/zh.json
Labels: waiting4reviewer

#15340 docs: remove legacy navigation
  docs/configuration.md
  docs/readme.md
  docs/recipes/custom-audit/readme.md
Labels: waiting4reviewer

#15342 v11.0.0
  changelog.md
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  docs/plugins.md
  docs/recipes/lighthouse-plugin-example/package.json
  package.json
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
Labels: waiting4reviewer

#15256 docs(readme): add Lighthouse Metrics China to services list
  readme.md
Labels: waiting4reviewer

#15341 misc: add dependabot.yml
  core/scripts/legacy-javascript/package.json
  dependabot.yml
Labels: waiting4reviewer

#15363 tests: do not allow hashes in mock dt log
  core/test/network-records-to-devtools-log.js
Labels: waiting4reviewer

#15345 core(asset-saver): use new `DevtoolsLog` and `Trace` artifacts
  core/lib/asset-saver.js
  core/runner.js
  core/test/lib/asset-saver-test.js
Labels: waiting4reviewer

#15378 tests(unit): retry failures and upload failure artifacts
  .github/workflows/unit.yml
  core/test/scenarios/api-test-pptr.js
  core/test/scenarios/pptr-test-utils.js
  core/test/scenarios/start-end-navigation-test-pptr.js
  core/test/scripts/run-mocha-tests.js
  package.json
Labels: waiting4reviewer

#15064 core(lcp-lazy-loaded): add LCP savings estimate
  core/audits/lcp-lazy-loaded.js
  core/test/audits/lcp-lazy-loaded-test.js
Labels: waiting4reviewer

#15178 core(largest-contentful-paint-element): add LCP savings
  core/audits/largest-contentful-paint-element.js
  core/test/audits/largest-contentful-paint-element-test.js
Labels: waiting4reviewer

#15307 core(dom-size): add TBT savings
  core/audits/dobetterweb/dom-size.js
  core/test/audits/dobetterweb/dom-size-test.js
  core/test/create-test-trace.js
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
Labels: waiting4reviewer

#15388 core(installable-manifest): update available installability errors
  core/audits/installable-manifest.js
  core/test/audits/installable-manifest-test.js
  shared/localization/locales/ar-XB.json
  shared/localization/locales/ar.json
  shared/localization/locales/bg.json
  shared/localization/locales/ca.json
  shared/localization/locales/cs.json
  shared/localization/locales/da.json
  shared/localization/locales/de.json
  shared/localization/locales/el.json
  shared/localization/locales/en-GB.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XA.json
  shared/localization/locales/en-XL.json
  shared/localization/locales/es-419.json
  shared/localization/locales/es.json
  shared/localization/locales/fi.json
  shared/localization/locales/fil.json
  shared/localization/locales/fr.json
  shared/localization/locales/he.json
  shared/localization/locales/hi.json
  shared/localization/locales/hr.json
  shared/localization/locales/hu.json
  shared/localization/locales/id.json
  shared/localization/locales/it.json
  shared/localization/locales/ja.json
  shared/localization/locales/ko.json
  shared/localization/locales/lt.json
  shared/localization/locales/lv.json
  shared/localization/locales/nl.json
  shared/localization/locales/no.json
  shared/localization/locales/pl.json
  shared/localization/locales/pt-PT.json
  shared/localization/locales/pt.json
  shared/localization/locales/ro.json
  shared/localization/locales/ru.json
  shared/localization/locales/sk.json
  shared/localization/locales/sl.json
  shared/localization/locales/sr-Latn.json
  shared/localization/locales/sr.json
  shared/localization/locales/sv.json
  shared/localization/locales/ta.json
  shared/localization/locales/te.json
  shared/localization/locales/th.json
  shared/localization/locales/tr.json
  shared/localization/locales/uk.json
  shared/localization/locales/vi.json
  shared/localization/locales/zh-HK.json
  shared/localization/locales/zh-TW.json
  shared/localization/locales/zh.json
  third-party/chromium-synchronization/installability-errors-test.js
Labels: land-when-ci-is-green, waiting4reviewer

#15387 core: fix `index.cjs` types
  core/index.cjs
Labels: land-when-ci-is-green

#15385 core: add TBT impact to third party audits
  core/audits/third-party-facades.js
  core/audits/third-party-summary.js
  core/computed/tbt-impact-tasks.js
  core/test/audits/third-party-facades-test.js
  core/test/audits/third-party-summary-test.js
  core/test/fixtures/artifacts/intercom-widget/devtoolslog.json
  core/test/fixtures/artifacts/intercom-widget/regenerate.js
  core/test/fixtures/artifacts/intercom-widget/trace.json
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  types/artifacts.d.ts
Labels: waiting4reviewer

#15389 tests(devtools): sync e2e
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
Labels: waiting4reviewer

#15353 docs(releasing): remove instructions covered by automated tests
  docs/releasing.md
Labels: waiting4reviewer

#15393 tests(dbw): increase threshold for LCP load start/end
  cli/test/smokehouse/test-definitions/dobetterweb.js
Labels: waiting4reviewer

#15392 docs(releasing): update cadence section
  docs/releasing.md
Labels: land-when-ci-is-green, waiting4reviewer

#15394 core(viewport-meta): include initial-scale value condition
  core/computed/viewport-meta.js
  core/test/computed/viewport-meta-test.js
Labels: waiting4reviewer

#15410 misc(readme): use note for Node version callout
  readme.md
Labels: waiting4reviewer

#15413 report: fix category highlight in DevTools
  report/assets/templates.html
  report/renderer/components.js
Labels: waiting4reviewer

#15415 misc(treemap): reduce granularity for byte values
  report/renderer/i18n-formatter.js
Labels: waiting4reviewer

#15407 core(timespan-runner): warn if a navigation is detected
  core/gather/timespan-runner.js
  core/test/gather/timespan-runner-test.js
  core/test/scenarios/api-test-pptr.js
  core/test/scenarios/pptr-test-utils.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
Labels: waiting4reviewer

#15417 misc: move dependabot.yml to correct folder
  .github/dependabot.yml
Labels: waiting4reviewer

#15418 misc: move esm-utils.js to shared/
  core/config/config-helpers.js
  core/config/config.js
  core/lib/i18n/i18n.js
  core/runner.js
  core/scripts/i18n/collect-strings.js
  core/test/config/config-helpers-test.js
  core/test/lib/asset-saver-test.js
  core/test/lib/i18n/i18n-test.js
  core/test/runner-test.js
  core/test/test-utils.js
  flow-report/tsconfig.json
  report/generator/flow-report-assets.js
  report/generator/report-assets.js
  report/generator/tsconfig.json
  root.js
  shared/esm-utils.js
  shared/localization/format.js
  shared/localization/locales.js
  shared/test/localization/format-test.js
  shared/tsconfig.json
  tsconfig.json
Labels: waiting4reviewer

#15422 tests(smoke): update installability icon error for ToT
  cli/test/smokehouse/test-definitions/offline-ready.js
  cli/test/smokehouse/test-definitions/offline-sw-broken.js
Labels: land-when-ci-is-green, waiting4reviewer

#15025 core: add guidance level to performance audits
  core/audits/bf-cache.js
  core/audits/bootup-time.js
  core/audits/byte-efficiency/duplicated-javascript.js
  core/audits/byte-efficiency/efficient-animated-content.js
  core/audits/byte-efficiency/legacy-javascript.js
  core/audits/byte-efficiency/modern-image-formats.js
  core/audits/byte-efficiency/offscreen-images.js
  core/audits/byte-efficiency/render-blocking-resources.js
  core/audits/byte-efficiency/total-byte-weight.js
  core/audits/byte-efficiency/unminified-css.js
  core/audits/byte-efficiency/unminified-javascript.js
  core/audits/byte-efficiency/unused-css-rules.js
  core/audits/byte-efficiency/unused-javascript.js
  core/audits/byte-efficiency/uses-long-cache-ttl.js
  core/audits/byte-efficiency/uses-optimized-images.js
  core/audits/byte-efficiency/uses-responsive-images-snapshot.js
  core/audits/byte-efficiency/uses-responsive-images.js
  core/audits/byte-efficiency/uses-text-compression.js
  core/audits/critical-request-chains.js
  core/audits/dobetterweb/dom-size.js
  core/audits/dobetterweb/no-document-write.js
  core/audits/dobetterweb/uses-http2.js
  core/audits/dobetterweb/uses-passive-event-listeners.js
  core/audits/font-display.js
  core/audits/largest-contentful-paint-element.js
  core/audits/layout-shift-elements.js
  core/audits/lcp-lazy-loaded.js
  core/audits/long-tasks.js
  core/audits/mainthread-work-breakdown.js
  core/audits/non-composited-animations.js
  core/audits/prioritize-lcp-image.js
  core/audits/redirects.js
  core/audits/server-response-time.js
  core/audits/third-party-facades.js
  core/audits/third-party-summary.js
  core/audits/unsized-images.js
  core/audits/user-timings.js
  core/audits/uses-rel-preconnect.js
  core/audits/uses-rel-preload.js
  core/audits/viewport.js
  core/audits/work-during-interaction.js
  types/audit.d.ts
Labels: waiting4reviewer
