Repository GoogleChrome/lighthouse, pull requests merged in 2024-02, with the labels that each got.

#15810 deps: upgrade trace_engine and drop manually written types
  core/audits/layout-shifts.js
  core/computed/metrics/cumulative-layout-shift.js
  core/computed/trace-engine-result.js
  core/gather/gatherers/root-causes.js
  core/gather/gatherers/trace-elements.js
  core/lib/trace-engine.js
  package.json
  types/artifacts.d.ts
  types/trace-engine.d.ts
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer

#15819 core(trace): disable JS samples
  core/gather/gatherers/trace.js
Labels: waiting4reviewer

#15821 i18n: import
  shared/localization/locales/ar-XB.json
  shared/localization/locales/ar.json
  shared/localization/locales/bg.json
  shared/localization/locales/ca.json
  shared/localization/locales/cs.json
  shared/localization/locales/da.json
  shared/localization/locales/de.json
  shared/localization/locales/el.json
  shared/localization/locales/en-GB.json
  shared/localization/locales/en-XA.json
  shared/localization/locales/es-419.json
  shared/localization/locales/es.json
  shared/localization/locales/fi.json
  shared/localization/locales/fil.json
  shared/localization/locales/fr.json
  shared/localization/locales/he.json
  shared/localization/locales/hi.json
  shared/localization/locales/hr.json
  shared/localization/locales/hu.json
  shared/localization/locales/id.json
  shared/localization/locales/it.json
  shared/localization/locales/ja.json
  shared/localization/locales/ko.json
  shared/localization/locales/lt.json
  shared/localization/locales/lv.json
  shared/localization/locales/nl.json
  shared/localization/locales/no.json
  shared/localization/locales/pl.json
  shared/localization/locales/pt-PT.json
  shared/localization/locales/pt.json
  shared/localization/locales/ro.json
  shared/localization/locales/ru.json
  shared/localization/locales/sk.json
  shared/localization/locales/sl.json
  shared/localization/locales/sr-Latn.json
  shared/localization/locales/sr.json
  shared/localization/locales/sv.json
  shared/localization/locales/ta.json
  shared/localization/locales/te.json
  shared/localization/locales/th.json
  shared/localization/locales/tr.json
  shared/localization/locales/uk.json
  shared/localization/locales/vi.json
  shared/localization/locales/zh-HK.json
  shared/localization/locales/zh-TW.json
  shared/localization/locales/zh.json
Labels: land-when-ci-is-green, waiting4reviewer

#15822 deps: upgrade puppeteer to 22.1.0
  package.json
  types/internal/rxjs.d.ts
  yarn.lock
Labels: land-when-ci-is-green

#15827 core(navigation-runner): only run `getArtifact` phase once
  core/gather/gatherers/devtools-log.js
  core/gather/gatherers/trace.js
  core/gather/navigation-runner.js
  core/test/gather/navigation-runner-test.js
Labels: waiting4reviewer

#15830 core(gather): gatherFn refactor
  core/gather/navigation-runner.js
  core/gather/snapshot-runner.js
  core/gather/timespan-runner.js
Labels: land-when-ci-is-green, waiting4reviewer

#15833 core(driver): don't await cleanup in PAGE_HUNG case
  core/gather/driver/wait-for-condition.js
Labels: waiting4reviewer

#15837 tests(devtools): sync e2e
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
  third-party/devtools-tests/e2e/lighthouse/snapshot_test.ts
  third-party/devtools-tests/e2e/lighthouse/start-view_test.ts
  third-party/devtools-tests/e2e/lighthouse/timespan_test.ts
Labels: waiting4reviewer
