Repository GoogleChrome/lighthouse, pull requests merged in 2024-01, with the labels that each got.

#15540 report(performance): use metric savings for metric filter
  flow-report/test/setup/env-setup.ts
  report/renderer/category-renderer.js
  report/renderer/performance-category-renderer.js
  report/renderer/pwa-category-renderer.js
  report/test/clients/bundle-test.js
  report/test/renderer/category-renderer-test.js
  report/test/renderer/performance-category-renderer-test.js
  report/test/renderer/pwa-category-renderer-test.js
  report/test/renderer/report-renderer-test.js
  types/config.d.ts
  types/lhr/audit-result.d.ts
  types/lhr/lhr.d.ts
Labels: waiting4reviewer

#15725 report: small renderAudit simplification
  report/renderer/category-renderer.js
Labels: land-when-ci-is-green, waiting4reviewer

#15726 core: create separate product savings type
  core/audits/audit.js
  core/audits/byte-efficiency/byte-efficiency-audit.js
  report/renderer/performance-category-renderer.js
  types/audit.d.ts
  types/config.d.ts
  types/lhr/audit-result.d.ts
  types/lhr/lhr.d.ts
Labels: land-when-ci-is-green, waiting4reviewer

#15727 core(viewport): include meta viewport string in debugDetails
  cli/test/fixtures/dobetterweb/dbw_tester.html
  cli/test/smokehouse/test-definitions/dobetterweb.js
  cli/test/smokehouse/test-definitions/seo-failing.js
  core/audits/viewport.js
  core/computed/viewport-meta.js
  core/test/computed/viewport-meta-test.js
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
Labels: land-when-ci-is-green, waiting4reviewer

#15729 tests(dbw): fix server latency flake
  cli/test/smokehouse/test-definitions/dobetterweb.js
Labels: land-when-ci-is-green, waiting4reviewer

#15733 misc(build): set line limit to 1000
  build/build-bundle.js
Labels: waiting4reviewer

#15722 docs: update deprecated link to shared flags
  docs/readme.md
Labels: waiting4reviewer

#15735 tests(mocha): fix snapshot expectations in retries
  core/test/scenarios/__snapshots__/api-test-pptr.js.snap
  core/test/test-env/mocha-setup.js
Labels: waiting4reviewer

#15718 core: lower guidance level of unused- audits
  core/audits/byte-efficiency/unused-css-rules.js
  core/audits/byte-efficiency/unused-javascript.js
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
Labels: waiting4reviewer

#15695 core: bump guidance level of top CWV recommendations
  core/audits/bf-cache.js
  core/audits/prioritize-lcp-image.js
  core/audits/unsized-images.js
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
Labels: waiting4reviewer

#15730 core(layout-shift-elements): hide audit
  core/config/default-config.js
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
Labels: land-when-ci-is-green

#15753 tests: fix ToT chrome install path
  .github/workflows/ci.yml
  .github/workflows/smoke.yml
  .github/workflows/unit.yml
  core/scripts/download-chrome.sh
Labels: land-when-ci-is-green, waiting4reviewer

#15765 tests(dbw): update expectations for unload handler removal
  cli/test/smokehouse/test-definitions/dobetterweb.js
Labels: land-when-ci-is-green, waiting4reviewer

#15764 clients(lr): include flag for ignoring bad page status code
  clients/lightrider/lightrider-entry.js
  clients/test/lightrider/lightrider-entry-test.js
  proto/lighthouse-result.proto
Labels: waiting4reviewer

#15740 core(target-manager): warn on errors while attaching to workers
  core/gather/driver/target-manager.js
  core/test/gather/driver/target-manager-test.js
Labels: waiting4reviewer

#15689 core: score of 1 for informative audits
  cli/test/smokehouse/test-definitions/a11y.js
  cli/test/smokehouse/test-definitions/dobetterweb.js
  cli/test/smokehouse/test-definitions/perf-budgets.js
  cli/test/smokehouse/test-definitions/perf-diagnostics-animations.js
  cli/test/smokehouse/test-definitions/perf-frame-metrics.js
  cli/test/smokehouse/test-definitions/perf-trace-elements.js
  core/audits/audit.js
  core/lib/lighthouse-compatibility.js
  core/test/audits/audit-test.js
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  report/renderer/performance-category-renderer.js
Labels: waiting4reviewer
