Repository GoogleChrome/lighthouse, pull requests merged in 2024-04, with the labels that each got.

#15902 core: deprecate `overallSavingsMs`
  cli/test/smokehouse/test-definitions/byte-efficiency.js
  core/audits/byte-efficiency/byte-efficiency-audit.js
  core/audits/byte-efficiency/offscreen-images.js
  core/audits/dobetterweb/uses-http2.js
  core/test/audits/byte-efficiency/byte-efficiency-audit-test.js
  core/test/audits/byte-efficiency/duplicated-javascript-test.js
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  flow-report/src/summary/category.tsx
  flow-report/test/summary/category-test.tsx
  types/lhr/audit-details.d.ts
Labels: waiting4reviewer

#15888 core(a11y): re-enable target-size hidden audit
  cli/test/smokehouse/test-definitions/a11y.js
  core/gather/gatherers/accessibility.js
  core/test/gather/gatherers/accessibility-test.js
Labels: land-when-ci-is-green, waiting4reviewer

#15900 core: remove `duplicate-id-active`
  cli/test/fixtures/a11y/a11y_tester.html
  cli/test/smokehouse/test-definitions/a11y.js
  core/audits/accessibility/duplicate-id-active.js
  core/config/default-config.js
  core/gather/gatherers/accessibility.js
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  core/test/scenarios/__snapshots__/api-test-pptr.js.snap
  shared/localization/locales/ar-XB.json
  shared/localization/locales/ar.json
  shared/localization/locales/bg.json
  shared/localization/locales/ca.json
  shared/localization/locales/cs.json
  shared/localization/locales/da.json
  shared/localization/locales/de.json
  shared/localization/locales/el.json
  shared/localization/locales/en-GB.json
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XA.json
  shared/localization/locales/en-XL.json
  shared/localization/locales/es-419.json
  shared/localization/locales/es.json
  shared/localization/locales/fi.json
  shared/localization/locales/fil.json
  shared/localization/locales/fr.json
  shared/localization/locales/he.json
  shared/localization/locales/hi.json
  shared/localization/locales/hr.json
  shared/localization/locales/hu.json
  shared/localization/locales/id.json
  shared/localization/locales/it.json
  shared/localization/locales/ja.json
  shared/localization/locales/ko.json
  shared/localization/locales/lt.json
  shared/localization/locales/lv.json
  shared/localization/locales/nl.json
  shared/localization/locales/no.json
  shared/localization/locales/pl.json
  shared/localization/locales/pt-PT.json
  shared/localization/locales/pt.json
  shared/localization/locales/ro.json
  shared/localization/locales/ru.json
  shared/localization/locales/sk.json
  shared/localization/locales/sl.json
  shared/localization/locales/sr-Latn.json
  shared/localization/locales/sr.json
  shared/localization/locales/sv.json
  shared/localization/locales/ta.json
  shared/localization/locales/te.json
  shared/localization/locales/th.json
  shared/localization/locales/tr.json
  shared/localization/locales/uk.json
  shared/localization/locales/vi.json
  shared/localization/locales/zh-HK.json
  shared/localization/locales/zh-TW.json
  shared/localization/locales/zh.json
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
  third-party/devtools-tests/e2e/lighthouse/snapshot_test.ts
Labels: waiting4reviewer

#15911 report: remove use of innerHTML to empty elements
  treemap/app/src/main.js
  viewer/app/src/lighthouse-report-viewer.js
Labels: land-when-ci-is-green, waiting4reviewer

#15910 core(target-size): use binary display mode
  cli/test/smokehouse/test-definitions/a11y.js
  core/audits/accessibility/target-size.js
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  report/test/generator/report-generator-test.js
  report/test/renderer/category-renderer-test.js
  third-party/devtools-tests/e2e/lighthouse/snapshot_test.ts
Labels: land-when-ci-is-green, waiting4reviewer

#15921 core(trace-processor): correct overlapping tasks
  core/lib/tracehouse/trace-processor.js
  core/test/audits/long-tasks-test.js
  core/test/audits/mainthread-work-breakdown-test.js
  core/test/lib/tracehouse/trace-processor-test.js
Labels: waiting4reviewer

#15924 misc: correct .npmignore for node >=18.20
  .npmignore
Labels: waiting4reviewer

#15915 core(trace-elements): add sentry debugging for `impactedNodes`
  core/audits/layout-shifts.js
  core/gather/gatherers/trace-elements.js
  core/test/gather/gatherers/trace-elements-test.js
Labels: waiting4reviewer

#15926 deps: upgrade `trace_engine` to 0.0.19
  cli/test/smokehouse/test-definitions/shift-attribution.js
  core/computed/metrics/cumulative-layout-shift.js
  core/computed/trace-engine-result.js
  package.json
  yarn.lock
Labels: waiting4reviewer

#15914 core(runner): use early return for readability
  core/runner.js
Labels: land-when-ci-is-green, waiting4reviewer

#13548 new_audit: bring back redirects-http with passive https check
  cli/test/smokehouse/config/exclusions.js
  cli/test/smokehouse/core-tests.js
  cli/test/smokehouse/test-definitions/offline-online-only.js
  cli/test/smokehouse/test-definitions/redirects-http.js
  core/audits/redirects-http.js
  core/config/default-config.js
  core/test/audits/redirects-http-test.js
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  core/test/scenarios/__snapshots__/api-test-pptr.js.snap
  lighthouse-cli/test/cli/__snapshots__/index-test.js.snap
  report/test/renderer/report-renderer-test.js
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
Labels: waiting4reviewer

#15913 core(driver): add sendCommandAndIgnore
  core/gather/driver.js
  core/gather/driver/target-manager.js
  core/gather/driver/wait-for-condition.js
  core/gather/session.js
  core/test/gather/mock-driver.js
  types/gatherer.d.ts
Labels: land-when-ci-is-green, waiting4reviewer

#15933 core(scoring): set is-crawlable weight high enough to fail SEO category
  core/config/default-config.js
  core/test/config/default-config-test.js
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  report/test/generator/report-generator-test.js
Labels: land-when-ci-is-green, waiting4reviewer

#15916 tests: update network target type expectations
  cli/test/smokehouse/test-definitions/oopif-scripts.js
  core/test/scenarios/api-test-pptr.js
Labels: waiting4reviewer

#15938 core(lantern): correct overlapping tasks in CPU nodes
  core/lib/lantern/cpu-node.js
  core/lib/lantern/metrics/interactive.js
  core/lib/lantern/page-dependency-graph.js
  core/lib/lantern/simulator/simulator.js
  core/test/lib/lantern/page-dependency-graph-test.js
Labels: waiting4reviewer

#15839 core(render-blocking): use trace engine as the source of truth
  cli/test/fixtures/dobetterweb/dbw_tester.html
  cli/test/smokehouse/test-definitions/dobetterweb.js
  core/audits/byte-efficiency/render-blocking-resources.js
  core/audits/layout-shifts.js
  core/computed/navigation-insights.js
  core/computed/trace-engine-result.js
  core/config/default-config.js
  core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js
  core/gather/gatherers/root-causes.js
  core/gather/gatherers/trace-elements.js
  core/test/audits/byte-efficiency/render-blocking-resources-test.js
  core/test/create-test-trace.js
  core/test/fixtures/artifacts/render-blocking/devtoolslog.json
  core/test/fixtures/artifacts/render-blocking/page/image.png
  core/test/fixtures/artifacts/render-blocking/page/render-blocking.html
  core/test/fixtures/artifacts/render-blocking/page/script.js
  core/test/fixtures/artifacts/render-blocking/page/style.css
  core/test/fixtures/artifacts/render-blocking/regenerate.js
  core/test/fixtures/artifacts/render-blocking/trace.json
  core/test/fixtures/artifacts/update-test-fixture.js
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/gather/gatherers/dobetterweb/tags-blocking-first-paint-test.js
  core/test/results/sample_v2.json
  tsconfig.json
  types/artifacts.d.ts
Labels: waiting4reviewer

#15940 misc: update public gatherer list
  core/lib/lh-error.js
  docs/plugins.md
  types/artifacts.d.ts
Labels: waiting4reviewer

#15941 misc: remove `BenchmarkIndexes` base artifact
  core/config/filters.js
  core/runner.js
  types/artifacts.d.ts
  types/lhr/lhr.d.ts
Labels: waiting4reviewer

#15942 core(service-worker): remove `service-worker` gatherer
  core/config/default-config.js
  core/gather/driver/service-workers.js
  core/gather/gatherers/service-worker.js
  core/test/audits/mainthread-work-breakdown-test.js
  core/test/gather/driver/service-workers-test.js
  core/test/gather/gatherers/service-worker-test.js
  core/test/results/artifacts/artifacts.json
  core/test/runner-test.js
  core/test/scripts/run-mocha-tests.js
  report/renderer/report-renderer.js
  report/test/renderer/report-renderer-test.js
  tsconfig.json
  types/artifacts.d.ts
Labels: land-when-ci-is-green, waiting4reviewer

#15949 core(seo): support Persian in link-text audit
  core/audits/seo/link-text.js
Labels: waiting4reviewer

#15951 deps: upgrade puppeteer to 22.6.5
  package.json
  yarn.lock
Labels: waiting4reviewer

#11840 core(gather): handle crash if CDP target crashes
  cli/test/smokehouse/config/exclusions.js
  cli/test/smokehouse/core-tests.js
  cli/test/smokehouse/test-definitions/crash.js
  core/gather/driver.js
  core/gather/driver/navigation.js
  core/gather/driver/prepare.js
  core/gather/driver/target-manager.js
  core/gather/navigation-runner.js
  core/gather/session.js
  core/lib/emulation.js
  core/lib/lh-error.js
  core/lib/navigation-error.js
  core/test/gather/mock-driver.js
  core/test/gather/session-test.js
  proto/lighthouse-result.proto
  shared/localization/locales/en-US.json
  shared/localization/locales/en-XL.json
  types/gatherer.d.ts
Labels: cla: yes, waiting4reviewer

#15952 core: split up `CSSUsage` artifact
  core/audits/byte-efficiency/render-blocking-resources.js
  core/audits/byte-efficiency/unminified-css.js
  core/audits/byte-efficiency/unused-css-rules.js
  core/audits/font-display.js
  core/computed/unused-css.js
  core/config/default-config.js
  core/gather/gatherers/css-usage.js
  core/gather/gatherers/stylesheets.js
  core/test/audits/byte-efficiency/unminified-css-test.js
  core/test/audits/byte-efficiency/unused-css-rules-test.js
  core/test/audits/font-display-test.js
  core/test/audits/preload-fonts-test.js
  core/test/fixtures/user-flows/artifacts/step0/artifacts.json
  core/test/fixtures/user-flows/artifacts/step1/artifacts.json
  core/test/fixtures/user-flows/artifacts/step3/artifacts.json
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/gather/gatherers/css-usage-test.js
  core/test/gather/gatherers/stylesheets-test.js
  core/test/results/artifacts/artifacts.json
  core/test/scenarios/__snapshots__/api-test-pptr.js.snap
  core/test/scenarios/stylesheet-tracking.js
  third-party/devtools-tests/e2e/lighthouse/timespan_test.ts
  types/artifacts.d.ts
Labels: waiting4reviewer

#15847 docs(readme): add DeploymentHawk to the list of integrations
  readme.md
Labels: waiting4reviewer

#15957 misc: merge changelog from branch-11
  changelog.md
Labels: waiting4reviewer

#15967 deps: upgrade `tldts-icann` to 6.1.16
  package.json
  yarn.lock
Labels: land-when-ci-is-green, waiting4reviewer

#15964 clients(viewer): stop using legacy DOM api
  viewer/app/src/lighthouse-report-viewer.js
Labels: land-when-ci-is-green, waiting4reviewer

#14383 docs(bug-report): require users to read FAQs
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: waiting4reviewer

#15970 v12.0.0
  changelog.md
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  docs/plugins.md
  docs/recipes/lighthouse-plugin-example/package.json
  package.json
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
Labels: waiting4reviewer
