Repository GoogleChrome/lighthouse, pull requests merged in 2024-11, with the labels that each got.

#16236 tests(smoke): fix devtools test runner & a11y errors
  cli/test/smokehouse/test-definitions/a11y.js
  core/scripts/pptr-run-devtools.js
  package.json
  yarn.lock
Labels: waiting4reviewer

#16219 deps: upgrade `third-party-web` to 0.26.1
  package.json
  yarn.lock
Labels: waiting4reviewer

#16221 core(target-manager): ignore target if type is unknown
  core/gather/driver/target-manager.js
  core/test/gather/driver/target-manager-test.js
Labels: land-when-ci-is-green, waiting4reviewer

#16235 docs(readme): add Guardius to services list
  readme.md
Labels: land-when-ci-is-green, cla: no, waiting4reviewer

#16239 docs(readme): add `lighthouse-matchers` to related projects
  readme.md
Labels: waiting4reviewer

#15990 cli: create writeFile destination if necessary
  cli/printer.js
  cli/test/cli/printer-test.js
Labels: waiting4reviewer

#16250 i18n: import
  shared/localization/locales/ar-XB.json
  shared/localization/locales/ar.json
  shared/localization/locales/bg.json
  shared/localization/locales/ca.json
  shared/localization/locales/cs.json
  shared/localization/locales/da.json
  shared/localization/locales/de.json
  shared/localization/locales/el.json
  shared/localization/locales/en-GB.json
  shared/localization/locales/en-XA.json
  shared/localization/locales/es-419.json
  shared/localization/locales/es.json
  shared/localization/locales/fi.json
  shared/localization/locales/fil.json
  shared/localization/locales/fr.json
  shared/localization/locales/he.json
  shared/localization/locales/hi.json
  shared/localization/locales/hr.json
  shared/localization/locales/hu.json
  shared/localization/locales/id.json
  shared/localization/locales/it.json
  shared/localization/locales/ja.json
  shared/localization/locales/ko.json
  shared/localization/locales/lt.json
  shared/localization/locales/lv.json
  shared/localization/locales/nl.json
  shared/localization/locales/no.json
  shared/localization/locales/pl.json
  shared/localization/locales/pt-PT.json
  shared/localization/locales/pt.json
  shared/localization/locales/ro.json
  shared/localization/locales/ru.json
  shared/localization/locales/sk.json
  shared/localization/locales/sl.json
  shared/localization/locales/sr-Latn.json
  shared/localization/locales/sr.json
  shared/localization/locales/sv.json
  shared/localization/locales/ta.json
  shared/localization/locales/te.json
  shared/localization/locales/th.json
  shared/localization/locales/tr.json
  shared/localization/locales/uk.json
  shared/localization/locales/vi.json
  shared/localization/locales/zh-HK.json
  shared/localization/locales/zh-TW.json
  shared/localization/locales/zh.json
Labels: waiting4reviewer

#16251 v12.2.2
  changelog.md
  core/test/fixtures/user-flows/reports/sample-flow-result.json
  core/test/results/sample_v2.json
  docs/plugins.md
  docs/recipes/lighthouse-plugin-example/package.json
  package.json
  third-party/devtools-tests/e2e/lighthouse/navigation_test.ts
Labels: waiting4reviewer
